### ISSUE TITLE
add 404 page picture api

### ISSUE THREAD

**Issue by manningpy** [SocialSisterYi/bilibili-API-collect#1]
https://www.bilibili.com/activity/web/view/data/1
https://www.bilibili.com/activity/web/view/data/666
why not add something like this,233

**Comment by SocialSisterYi** [comment]
okk

**Comment by SocialSisterYi** [comment]
404页漫画api🈚，but 404页漫画收集🈶 https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/web_widget/404_manga.md
