### ISSUE TITLE
https://api.live.bilibili.com/room/v1/Room/room_init这个api在浏览器是和接口测试工具都成功返回数据了，但在程序里不行

### ISSUE THREAD

**Issue by Yoimiya-993** [SocialSisterYi/bilibili-API-collect#1001]
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/52495231/f2cc8106-1f91-4d0b-a7d9-77f40d995364)
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/52495231/1a2c40c8-a0ea-46b6-b7cc-e3097626ab7e)
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/52495231/72c62a0c-51de-48bb-8adb-4f36e36919e0)

**Comment by wuziqian211** [comment]
手动设置 UA 为浏览器的试试？

**Comment by Yoimiya-993** [comment]
可以了，谢谢大佬
