### ISSUE TITLE
获取用户投稿接口只用wbi签名不能用了

### ISSUE THREAD

**Issue by ShaneLee-9** [SocialSisterYi/bilibili-API-collect#1009]
### 提交前请确认

- [ ] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### 详情描述

> 参考文档：[查询用户投稿视频明细](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/user/space.md#%E6%9F%A5%E8%AF%A2%E7%94%A8%E6%88%B7%E6%8A%95%E7%A8%BF%E8%A7%86%E9%A2%91%E6%98%8E%E7%BB%86)、[WBI签名JS版](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md#javascript)

以下是我修改过后的 `main` 函数，其余的代码和[WBI签名JS版](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md#javascript)一致：
```javascript
async function main() {
  const web_keys = await getWbiKeys()
  const params = {
    mid: "519045443"
  };
  const img_key = web_keys.img_key
  const sub_key = web_keys.sub_key
  const query = encWbi(params, img_key, sub_key)

  const res = await fetch(`https://api.bilibili.com/x/space/wbi/arc/search?${query}`)
  console.log(await res.json());
}
```
代码运行结果：
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/30720287/e188a2d9-1486-42a8-b5c2-afaa8d86e248)

**Comment by z0z0r4** [comment]
你完全没看已有 issue

https://github.com/SocialSisterYi/bilibili-API-collect/issues/868
