### ISSUE TITLE
退出登录API地址已修改

### ISSUE THREAD

**Issue by krishukr** [SocialSisterYi/bilibili-API-collect#101]
`https://passport.bilibili.com/login/exit/v2`
参数未变

**Comment by krishukr** [comment]
另外请确认[这部分](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_info.md#%E7%99%BB%E5%BD%95%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF%E4%BB%85%E9%83%A8%E5%88%86)API的有效性

**Comment by krishukr** [comment]
@xiaoyv404 来吃瓜啊（滑稽

**Comment by SocialSisterYi** [comment]
> 另外请确认[这部分](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_info.md#%E7%99%BB%E5%BD%95%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF%E4%BB%85%E9%83%A8%E5%88%86)API的有效性

这个api已经失效，下次更新进行折叠

**Comment by krishukr** [comment]
> > 另外请确认[这部分](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_info.md#%E7%99%BB%E5%BD%95%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF%E4%BB%85%E9%83%A8%E5%88%86)API的有效性
> 
> 这个api已经失效，下次更新进行折叠

感谢

**Comment by xiaoyv404** [comment]
来吃瓜了

**Comment by xiaoyv404** [comment]
> @xiaoyv404 来吃瓜啊（滑稽

来了

**Comment by krishukr** [comment]
另外的另外，[这部分](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_info.md#%E8%8E%B7%E5%8F%96%E7%A1%AC%E5%B8%81%E6%95%B0)中，cookies要多带一个DedeUserID，否则无法正常返回
返回`{
    "code": -101
}`
@SocialSisterYi

**Comment by SocialSisterYi** [comment]
收到，下次更新时修改

**Comment by SocialSisterYi** [comment]
已修改https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_info.md#获取硬币数
