### ISSUE TITLE
[新增/更新请求] <title>https://api.bilibili.com/x/space/wbi/arc/search风控水平提高？412

### ISSUE THREAD

**Issue by shouxindehai** [SocialSisterYi/bilibili-API-collect#1018]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/space/wbi/arc/search

### 详情描述

本人之前实现本api的爬取功能并挂机半个月有效，于昨日发现该api失效，更换云服务器（ip）和有效ua无效。怀疑产生了新的机制对本api进行风控？

**Comment by cxw620** [comment]
~~贴代码, 没代码谁知道你漏了什么东西.~~ 麻烦提供测试用例.

~~怎么个失效法? 不说让别人脑补?~~ 麻烦说清楚失效的详情, 例如返回的错误信息

**Comment by linyuye** [comment]
我也遇到过，懒加载api无需构造wbi签名的url偶尔会返回412，源代码我发到仓库里了

**Comment by linyuye** [comment]
原问题14：38出现，在23：18没有复现，疑似是短时间请求次数太多？

**Comment by z0z0r4** [comment]
by accident
