### ISSUE TITLE
获取用户基本信息返回-403访问权限不足怎么解决

### ISSUE THREAD

**Issue by Youyouovo** [SocialSisterYi/bilibili-API-collect#1024]
### 提交前请确认

- [x] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### 详情描述
按照文档写的测试，添加了wts和w_rid，cookie里也写了 SESSDATA和buvid3
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/129751927/d5771752-08bc-4e95-a1eb-c7f3389162ac)
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/129751927/1b755974-6103-4c37-83ec-a84671f3118e)

**Comment by z0z0r4** [comment]
bar foo 也是 query 参数

你在干什么…去学下 HTTP 基础

**Comment by Youyouovo** [comment]
sry....我是初学者，之前看到一个项目以为可以直接用，一路找到这里，但没有demo...



> bar foo 也是 query 参数
> 
> 你在干什么…去学下 HTTP 基础

**Comment by yxzlwz** [comment]
![image](https://github.com/user-attachments/assets/92902c56-d479-4ada-ba38-659d9b3f186f)

遇到这个问题怎么破呀

**Comment by yxzlwz** [comment]
测试过了，带上所有cookie就会变成权限不足发件人: stmtc233 ***@***.***>发送时间: 星期二, 九月 17, 2024 8:38:20 下午收件人: SocialSisterYi/bilibili-API-collect ***@***.***>抄送: 异想之旅王子 ***@***.***>; Comment ***@***.***>主题: Re: [SocialSisterYi/bilibili-API-collect] 获取用户基本信息返回-403访问权限不足怎么解决 (Issue #1024)


遇到这个问题怎么破呀

带上cookie应该能临时解决 风控这东西比较玄乎
