### ISSUE TITLE
关于错误码

### ISSUE THREAD

**Issue by kebufu** [SocialSisterYi/bilibili-API-collect#103]
1024是返回是"系统开小差了"，我感觉正数是警告，负数是错误，0是成功<br/>{"code":1024,"msg":"\u7cfb\u7edf\u5f00\u5c0f\u5dee\u4e86","message":"\u7cfb\u7edf\u5f00\u5c0f\u5dee\u4e86","data":{}}

**Comment by kebufu** [comment]
<a href="https://api.vc.bilibili.com/dynamic_like/v1/dynamic_like/like_detail?dynamic_id=460054846387493701">这个</a>返回的好像是1024

**Comment by kebufu** [comment]
<a href="http://api.bilibili.com/nav?jsonp=jsonp&callback=jsonp">这个</a>也是

**Comment by kebufu** [comment]
> [这个](http://api.bilibili.com/nav?jsonp=jsonp&callback=jsonp)也是



> [这个](https://api.vc.bilibili.com/dynamic_like/v1/dynamic_like/like_detail?dynamic_id=460054846387493701)返回的好像是1024

这两个都是返回的正数

**Comment by ProgramRipper** [comment]
> [这个](http://api.bilibili.com/nav?jsonp=jsonp&callback=jsonp)也是
这个http://api.bilibili.com/nav?jsonp=jsonp&callback=jsonp我获得的是:
{"code":40007,"msg":"refer  incorrect"}
设置了Referer: https://www.bilibili.com/后正常返回

**Comment by SocialSisterYi** [comment]
api.bilibili.com/nav不带任何url参数就可以

**Comment by kebufu** [comment]
> api.bilibili.com/nav不带任何url参数就可以



> > [这个](http://api.bilibili.com/nav?jsonp=jsonp&callback=jsonp)也是
> 
> 这个 http://api.bilibili.com/nav?jsonp=jsonp&callback=jsonp 我获得的是:
> {"code":40007,"msg":"refer incorrect"}
> 设置了Referer : https://www.bilibili.com/ 后正常返回

主要是我想要用jsonp跨域，但是不行

**Comment by kebufu** [comment]
然后我就把正数的错误码发出来了

**Comment by kebufu** [comment]
今天刷b站点赞评论的时候突然弹出了一个-500错误码，客户端是直接显示的错误码
