### ISSUE TITLE
[新增/更新请求] 21028 响应码

### ISSUE THREAD

**Issue by AnzhiZhang** [SocialSisterYi/bilibili-API-collect#1033]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.vc.bilibili.com/web_im/v1/web_im/send_msg

### 详情描述

发送私信时，发现这条响应，个人私信没有，仅限应援团，搜索了一下没有发现这个 code，留个记录

```text
{"code":21028,"message":"由于系统升级，暂无法发送，敬请谅解","ttl":1,"data":null}
```

可能相关：#14

**Comment by wuziqian211** [comment]
感谢反馈，在 #983 中将修复
