### ISSUE TITLE
cookie更新周期/更新条件

### ISSUE THREAD

**Issue by linyuye** [SocialSisterYi/bilibili-API-collect#1037]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### 详情描述

cookie更新周期/更新条件

**Comment by z0z0r4** [comment]
这个有什么好讨论的吗？相关接口都有吧
