### ISSUE TITLE
[更新请求]  https://api.bilibili.com/x/web-interface/newlist

### ISSUE THREAD

**Issue by SnowDream39** [SocialSisterYi/bilibili-API-collect#1039]
### 提交前请确认

- [x] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

 https://api.bilibili.com/x/web-interface/newlist

### 详情描述

原来的 https://api.bilibili.com/x/web-interface/dynamic/region 现在不知道返回的是什么内容，需要更新。
参数从原有的 rid、ps、pn 基础上新增一个 type ，意义不明。
相应与原来基本相同。

**Comment by SnowDream39** [comment]
type 的默认值是0。

**Comment by SessionHu** [comment]
原接口实测似乎没有变化, 在网络日志中仍正常工作, 作用及返回数据与给定接口相同.  
参数 `type` 是给定接口的, 且在网络日志中给定接口虽被请求但结果似乎并未在页面中呈现.
需要更多信息验证给定接口作用.
*(测试使用cURL及Firefox, 且是否登陆均进行)*
