### ISSUE TITLE
[更新请求] 视频基本信息接口返回的cc字幕链接变成空字符串了

### ISSUE THREAD

**Issue by clostou** [SocialSisterYi/bilibili-API-collect#1046]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/web-interface/view

### 详情描述

之前我下载cc字幕，一直用的是 https://api.bilibili.com/x/web-interface/view 接口（参考 [视频/基本信息](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/video/info.md) 小节），但最近发现无论是否登录，该接口响应的`subtitle_url`字段都为空字符串，下面是两个例子：

* 普通视频：https://api.bilibili.com/x/web-interface/view?aid=574480289&cid=1225067302
* 番剧：https://api.bilibili.com/x/web-interface/view?aid=300138897&cid=752139759

原因我不太清楚，但我发现如果只是下载字幕的话，完全可以用 https://api.bilibili.com/x/player/wbi/v2 替换之前的接口，不会出现空链接的问题，还是上面的两个例子（注意要新建标签页之后复制了看，不能直接点击跳转）：

* 普通视频：https://api.bilibili.com/x/player/wbi/v2?aid=574480289&cid=1225067302
* 番剧：https://api.bilibili.com/x/player/wbi/v2?aid=300138897&cid=752139759

另外，第二个接口有一个优点就是，在查询仅限港澳台地区的番剧时可以不开代理；而第一个接口不走代理直接访问会返回类似下面这种：

    {
        "code": -404,
        "message": "啥都木有",
        "ttl": 1
    }

**Comment by lovegaoshi** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/778
