### ISSUE TITLE
[新增/更新请求] <title> 已登录但无法获得1080P分辨率视频

### ISSUE THREAD

**Issue by JaceJu-frog** [SocialSisterYi/bilibili-API-collect#1052]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/player/wbi/playurl?bvid=BV1Zx3seHE33&cid=500001598666958&cookie=SESSDATA%3Dc745aba2%252C1736319870%252C4802a%252A71CjBAAoc6kSCqZNGa3E50Qi4mRWNbjVkrRzYjw3musR8PDDz6aWcJlZJrzsy21afXNLUSVjJlRExEd2dETExXYlcwR2ZZVFBscmg0ZDlOS21NdmRMMEVHbmotYklNX3dJb1NfMlNveDhxa0FNbTl6cFBGQllSdkd5REhYVnM4YzdIUGZHTkl2UXpBIIEC&qn=80&wts=1720780000&w_rid=3dfeccb269387ef73907b664e65d0ae5

### 详情描述

When I try to fetch this _video (BV1Zx3seHE33)  and (cid :500001598666958)_ by wbi ,I get json back ：
```json
{
    "code": 0,
    "message": "0",
    "ttl": 1,
    "data": {
        "from": "local",
        "result": "suee",
        "message": "",
        "quality": 16,
        "format": "mp4",
        "timelength": 1036309,
        "accept_format": "mp4,mp4",
        "accept_description": [
            "\u9ad8\u6e05 1080P",
            "\u6d41\u7545 360P"
        ],
        "accept_quality": [
            80,
            16
        ],
        "video_codecid": 7,
        "seek_param": "start",
        "seek_type": "second",
        "durl": [
            {
                "order": 1,
                "length": 1036309,
                "size": 56017329,
                "ahead": "",
                "vhead": "",
                "url": "https://upos-sz-mirror08c.bilivideo.com/upgcxcode/95/88/802388895/802388895-1-16.mp4?e=ig8euxZM2rNcNbRVhwdVhwdlhWdVhwdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1720788435&gen=playurlv2&os=08cbv&oi=2346972628&trid=a0b485bb0d064298a8ba7da295d011a1u&mid=0&platform=pc&og=hw&upsig=77422d48b6880337d07d987be7daa397&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&f=u_0_0&agrr=1&bw=54070&logo=80000000",
                "backup_url": [
                    "(backup_url1 ommited)",
                    "(backup_url2 ommited for readability)"
                ]
            }
        ],
        "support_formats": [
            {
                "quality": 80,
                "format": "mp4",
                "new_description": "1080P \u9ad8\u6e05",
                "display_desc": "1080P",
                "superscript": "",
                "codecs": null
            },
            {
                "quality": 16,
                "format": "mp4",
                "new_description": "360P \u6d41\u7545",
                "display_desc": "360P",
                "superscript": "",
                "codecs": null
            }
        ],
        "high_format": null,
        "last_play_time": 0,
        "last_play_cid": 0,
        "view_info": null
    }
}
```
And  **I Can only get 360P video** even by wbi path via cookies ,Even I know that 1080p is supported in this video
When I use bili desktop to store this video (in m4s format and use ffmpeg to combine),I can get 1080P format mp4 video (100M) 

BY the way ,I can login via 'https://api.bilibili.com/x/web-interface/nav' using "SESSDATA",So what causes this problem?

**Comment by JaceJu-frog** [comment]
I get json format response mentioned above by this function:
```python
    def get_video_url(self, cid):
        url = 'https://api.bilibili.com/x/player/wbi/playurl'
        params = {
            'cid': cid,
            'bvid': self.bvid,
            'qn': 80,
            'cookie': f"SESSDATA={self.sessdata}",
        }
        img_key, sub_key = getWbiKeys() # from utils
        signed_params=encWbi(params,img_key,sub_key)
        res = requests.get(url, params=signed_params, headers=self.headers)
        res.encoding = 'utf-8'
        video_url = res.json()['data']['durl'][0]['url']

        j = json.dumps(res.json(),indent=4)
        return j
```
If I request https://api.bilibili.com/x/player/wbi/playurl without cookie,I get this response too.So there is a probability that I misused the wbi sign,but I am not sure. Hope I can get some help.
![PixPin_2024-07-12_19-11-00](https://github.com/user-attachments/assets/e578e22b-a1fc-4e08-b682-e9695f2e2e75)

**Comment by grqz** [comment]
you might want to pass a `fnval` value like 4048(16|64|128|256|512|1024|2048). see [this table](https://github.com/SocialSisterYi/bilibili-API-collect/blob/8cdf355f7e963168f6237f4fd9a405f13ce036b6/docs/video/videostream_url.md#fnval%E8%A7%86%E9%A2%91%E6%B5%81%E6%A0%BC%E5%BC%8F%E6%A0%87%E8%AF%86)

**Comment by JaceJu-frog** [comment]
Thanks,With the params you provide,and adjusted the way of passing cookies,I was able to get full mp4 file at 1080P.
And size of the file is 100M,same as what I got from bili desktop.
there is only one flaw:video and audio are passed **separately** (**not encrypted**),so I have to use ffmpeg to combine them.But that's easy.

Attachment for the json format response I got ,Very long,full version of all resolution of videos and audios.
[video_url.json](https://github.com/user-attachments/files/16200424/video_url.json)

**Comment by z0z0r4** [comment]
Only low-quality videos such as 480P are in `flv` format, and other qualities are in `DASH` format

No way to avoid it. Detailed information about `DASH` in https://socialsisteryi.github.io/bilibili-API-collect/docs/video/videostream_url.html#%E8%A7%86%E9%A2%91%E5%8F%96%E6%B5%81%E8%AF%B4%E6%98%8E

**Comment by z0z0r4** [comment]
既然是中文标题为何不用中文正文...
