### ISSUE TITLE
86103回复

### ISSUE THREAD

**Issue by Linecom-lik** [SocialSisterYi/bilibili-API-collect#1057]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://passport.bilibili.com/x/passport-login/web/sms/send

### 详情描述

今天下午测试API的时候，出现
{"code":86103,"message":"请下载最新版本哔哩哔哩App完成注册或继续登录","ttl":1,"data":null}
返回，到提交本issue为止，尝试过切换网络环境、使用不同工具请求，发送验证码api均返回86103，无法正常使用。文档没有相关定义。

**Comment by xiao-rao** [comment]
经过一小波测试，发现可能跟buvid3这个参数有关，使用python requests库对https://www.bilibili.com/进行请求拿到set-cookie 
buvid3和b_nut的值，然后生成其他cookie参数  包括fp。请求下发短信 会返回86013   请下载最新版本哔哩哔哩App完成注册或继续登录的错误，然后直接复制浏览器上的buvid3 替换到模拟的cookie里 请求成功 测试多次页不会再出错。可能使用buvid3参数做了什么。还待继续研究
