### ISSUE TITLE
[更新请求] web端上报视频播放心跳接口变动

### ISSUE THREAD

**Issue by SessionHu** [SocialSisterYi/bilibili-API-collect#1062]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/click-interface/web/heartbeat

### 详情描述

[上报视频播放心跳（web端）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/video/report.md#%E4%B8%8A%E6%8A%A5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%BF%83%E8%B7%B3web%E7%AB%AF) 该接口正在今日一次之测试中, 发现并未按预期工作. 使用 Firefox 开发者工具抓包发现该接口请求参数大量变动. 该问题将在最新一次 PR 由本人解决<s>(如果不出意外的话)</s>.
![图片](https://github.com/user-attachments/assets/57bf571b-ff88-499a-8bd9-54b980a10c0a)
![图片](https://github.com/user-attachments/assets/7778e26a-91a8-4f63-8566-f0afe88a2b74)

**Comment by SessionHu** [comment]
label 好像标错了, 这是视频不是直播

**Comment by z0z0r4** [comment]
sorry，我下意识以为是直播的 heartbeat 了
