### ISSUE TITLE
[新增请求] 根据 v_voucher 生成 captcha 解除接口暂时风控

### ISSUE THREAD

**Issue by SessionHu** [SocialSisterYi/bilibili-API-collect#1067]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/gaia-vgate/v1/register

### 详情描述

下列请求均使用 Firefox, `User-Agent` 为 `curl/7.88.1` <s>(不然你说我是怎么触发风控的呢)</s>
- `POST` `https://api.bilibili.com/x/gaia-vgate/v1/register`
  - Request:
    - `application/x-www-form-urlencoded`: `csrf=xxx&v_voucher=voucher_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx`
  - Response: 
    - `application/json`: 与[申请captcha验证码](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/login_action/readme.md#申请captcha验证码)基本相同
- 中间如何验证没必要研究, 反正只要拿到 `validate` `seccode`
- `POST` `https://api.bilibili.com/x/gaia-vgate/v1/validate`
  - Request:
    - `application/x-www-form-urlencoded`: `challenge={challenge}&csrf=xxx&seccode={seccode}&token={token_in_first_step_resp}&validate={validate}`
  - Response:
    - `application/json`: `data` 中的 `grisk_id` 作为被风控接口的 `URL param` 的 `gaia_vtoken` 即可
> ~会不会在 PR 里解决我就不清楚了~

**Comment by z0z0r4** [comment]
按照现在的文档中的表述，我可以理解为无论是哪种风控，都能通过传入 gaia_vtoken 规避吗？

例如 wbi 参数有误？想了解下效用范围

**Comment by SessionHu** [comment]
对于无法申请到验证码的风控大概是无法解除的. 这一点通过在浏览器中通过插件删除 Cookie 中的 buvid3 等是可以注意到的. 这可能与 B 站的风控系统检查顺序有关.

**Comment by JiuChiYl** [comment]
所以validate和seccode怎么拿，在哪拿😭

**Comment by ZianTT** [comment]
> 所以validate和seccode怎么拿，在哪拿😭

这是极验(GeeTest)验证码成功的返回，要想获取请先人工或使用过码技术通过验证码。

**Comment by ZianTT** [comment]
另外注意到该风控在特定情况下（号很黑）可能会要求手机号验证码验证…遇到过
区分这种情况是在register后返回的type字段
