### ISSUE TITLE
[新增/更新请求] 收藏夹的API需登录的问题

### ISSUE THREAD

**Issue by jkhAIjava** [SocialSisterYi/bilibili-API-collect#1072]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/v3/fav/folder/created/list-all?up_mid=76090919

### 详情描述

请问，查询收藏夹的API必须提前登入获取Cookie（SESSDATA）才能执行成功，目前我是先在网站bilibili.com登入以下，F12 获取Cookie，有通过其他api获取SESSDATA的吗？希望全部走代码 完成 【查询目标用户收藏夹】的功能

**Comment by jkhAIjava** [comment]
另外我发现  网站【https://socialsisteryi.github.io/bilibili-API-collect/docs/】貌似和github上仓库的文档 不一致，前者不全。

**Comment by SessionHu** [comment]
> 另外我发现 网站【[https://socialsisteryi.github.io/bilibili-API-collect/docs/】貌似和github上仓库的文档](https://socialsisteryi.github.io/bilibili-API-collect/docs/%E3%80%91%E8%B2%8C%E4%BC%BC%E5%92%8Cgithub%E4%B8%8A%E4%BB%93%E5%BA%93%E7%9A%84%E6%96%87%E6%A1%A3) 不一致，前者好像故意隐藏了某些目录，但是可以直接猜目录结构 打开 github上的一些文档

最近的某次 PR 由于某两个元素未正确关闭导致 deploy failed, 因此出现网站与仓库内容不一致, 该问题将会在下一次 PR 解决.

**Comment by SessionHu** [comment]
查询某个用户的公开收藏夹并不需要登录 (即 Cookie 传 SESSDATA), 除非您所登录的账号能够访问该用户的私密收藏夹 (即所登陆账号与被获取收藏夹的用户为同一账号) 且您需要获取本用户的所有包括私密与公开收藏夹才需要传 SESSDATA. SESSDATA 等 Cookie 可以从 [登录接口](https://github.com/SocialSisterYi/bilibili-API-collect/tree/master/docs/login/login_action) 获取.
