### ISSUE TITLE
腾讯云部署手动执行actions时无法部署

### ISSUE THREAD

**Issue by 1258448151** [SocialSisterYi/bilibili-API-collect#1073]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### 详情描述

![Z2QT2E}MFYP{D Y~58ZNHN7](https://github.com/user-attachments/assets/7489f4e1-59eb-487c-b10a-bf2612727cdc)
求大佬解答

**Comment by z0z0r4** [comment]
what are you fucking saying
