### ISSUE TITLE
[新增/更新请求] 分享视频api接口的-403响应

### ISSUE THREAD

**Issue by qaqFei** [SocialSisterYi/bilibili-API-collect#1079]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/web-interface/share/add

### 详情描述

频繁请求时出现:
` {'code': -403, 'message': '账号异常,操作失败', 'ttl': 1}`

需经过1天左右恢复正常

**Comment by SessionHu** [comment]
可能与该接口新增了几个请求参数有关
![图片](https://github.com/user-attachments/assets/29432a8c-6d01-40ab-a523-8c3e9a898c1d)

**Comment by SessionHu** [comment]
Cookie 缺少 `buvid3` 有关, 参见 #840
