### ISSUE TITLE
[新增/更新请求] 装扮/收藏集搜索API及收藏集信息API

### ISSUE THREAD

**Issue by heartalborada-del** [SocialSisterYi/bilibili-API-collect#1080]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### 装扮/收藏集搜索API
`GET` https://api.bilibili.com/x/garb/v2/mall/home/search

请求参数:
| 字段 | 类型 | 内容  | 备注 |
|--|--|--|--|
| keyword | str | 关键词 | - |
| ps | int | 每页返回数据的最大值 | -|
| pn | int | 当前页数 |-|

返回值

根对象：
| 字段    | 类型 | 内容     | 备注 |
| ------- | ---- | -------- | --------------------------- |
| code    | num  | 返回值   | 0：成功 |
| message | str  | 错误信息 | 默认为0 |
| ttl | num  | 1 | - |
| data    | obj  | 返回数据 | - |

`data`字段：
| 字段 | 类型 | 内容 | 备注 |
|--|--|--|--|
| list | Array | 返回数据 | - |
| ps | int | 每页返回数据的最大值 | 默认为20 |
| pn | int | 当前页数 | 默认为1 |
| total | int | 查询到数据的总个数 | - |

`list`字段：
| 字段 | 类型 | 内容 | 备注 |
|--|--|--|--|
| item_id | int| 装扮对应的id | 收藏集均为`0`,需要在`properties`获取 |
| name| str | 装扮/收藏集名称 | - |
| group_id | int | ?分类的id | - |
| group_name | str | ?分类的名称 | - |
| part_id | int | 类型id | 装扮为`6` 收藏集为`0` |
| state | str | 当前状态| 默认为“active” |
| properties | Object | 见下方 | - |
| current_activity | Object | 见下方 | - |
| next_activity | int | ?下次活动的时间 | - |
| current_sources | int | ?活动开始时间 | - |
| finish_sources| int | ?活动结束时间 | - |
| sale_left_time | int | ?销售剩余时间 | - |
| sale_time_end | int | ?销售结束时间 | - |
| sale_surplus | int | 未知 | - |
| sale_count_desc| str| 销售量显示文本 | - |
| total_count_desc| str | 总量显示文本 | - |
| tag| str|当前状态标签 | - |
| jump_link| str| 跳转链接 | - |
| sales_mode| int | ?销售状态 | - |

`properties`字段：
- 共有字段
    | 字段 | 类型 | 内容 | 备注 |
    |--|--|--|--|
    |image_cover|str|图片封面|-|
    |sale_bp_forever_raw|str|价格|以0.01B币为单位|
    |type|str|类型|收藏集为`dlc_act`, 装扮为`ip`|
- 装扮特有：
    | 字段 | 类型 | 内容 | 备注 |
    |--|--|--|--|
    |desc|str|介绍文本|仅装扮|
    |fan_desc|str|装扮名称|仅装扮|
    |fan_item_ids|str|未知|仅装扮|
    |fan_mid|str|该up的uid|仅装扮|
    |fan_no_color|str|十六进制颜色|仅装扮|
    |fan_recommend_desc|str|装备说明|仅装扮|
    |fan_recommend_jump_type|str|跳转类型|仅装扮|
    |fan_recommend_jump_value|str|跳转值|仅装扮|
    |fan_share_image|str|分享时的背景图|仅装扮|
    |gray_rule|str|未知|仅装扮|
    |gray_rule_type|str|未知|仅装扮|
    |image_cover_color|str|?图片封面纯色背景|仅装扮|
    |is_hide|str|是否隐藏|仅装扮|
    |item_id_card|str|装扮背景卡片id|仅装扮|
    |item_id_emoji|str|装扮表情包id|仅装扮|
    |item_id_thumbup|str|装扮点赞动画id|仅装扮|
    |open_platform_vip_discount|str|是否有大会员减免|仅装扮|
    |owner_uid|str|UID|默认为[虚拟主播衍生品小货架](https://space.bilibili.com/18976141/), 仅装扮|
    |rank_investor_show|str|未知|仅装扮|
    |realname_auth|str|?是否需要实名认证|仅装扮|
    |sale_bp_pm_raw|str|该装扮`基础套餐`价格|以0.01B币为单位, 仅装扮|
    |sale_buy_num_limit|str|购买限额|仅装扮|
    |sale_quantity|str|该装扮`粉丝专属套餐`限额|仅装扮|
    |sale_quantity_limit|str|该装扮`粉丝专属套餐`是否限额|仅装扮|
    |sale_region_ip_limit|str|该装扮限制购买地区|仅装扮|
    |sale_reserve_switch|str|未知|仅装扮|
    |sale_time_begin|str|开始售卖时的时间戳|仅装扮|
    |sale_type|str|售卖类型|默认为`pay`, 仅装扮|
    |suit_card_type|str|仅装扮|
- 收藏集特有：
    | 字段 | 类型 | 内容 | 备注 |
    |--|--|--|--|
    |book_amount|str|购买总数|仅收藏集|
    |dlc_act_id|str|收藏集活动id|仅收藏集|
    |dlc_act_status|str|收藏集活动状态|仅收藏集|
    |dlc_is_free|str|收藏集抽奖是否免费|仅收藏集|
    |dlc_lottery_id|str|收藏集抽奖id|仅收藏集|
    |dlc_lottery_sale_quantity|str|购买总数|仅收藏集|
    |dlc_lottery_type|str|?抽奖类型|仅收藏集|
    |dlc_sale_end_time|str|收藏集抽奖结束时间|仅收藏集|
    |dlc_sale_mode|str|未知|仅收藏集|
    |dlc_sale_start_time|str|收藏集抽奖开始时间|仅收藏集|
    |dlc_surplus_stock|str|未知|仅收藏集|

- current_activity字段：
    | 字段 | 类型 | 内容 | 备注 |
    |--|--|--|--|
    |type|str|当前永久价格活动类型|装扮一般是`open_platform_vip_discount`, 收藏集一般是`first_draw_discount`|
    |time_limit|bool|是否存在时间限制|-|
    |time_left|int|剩余时间|-|
    |tag|str|显示标签|-|
    |price_bp_forever|int|永久价格|以0.01B币为单位|
    |price_bp_month|int|一个月的价格|以0.01B币为单位|
    |type_month|str|当前一个月的价格活动类型|仅装扮|
    |tag_month|str|显示标签|仅装扮|
    |time_limit_month|bool|是否存在时间限制|仅装扮|
    |time_left_month|int|剩余时间|仅装扮|

### 收藏集信息API
`GET` https://api.bilibili.com/x/vas/dlc_act/lottery_home_detail?act_id=111&lottery_id=15

请求参数:
| 字段 | 类型 | 内容  | 备注 |
|--|--|--|--|
| act_id | int | 收藏集活动id | - |
| lottery_id | int | 收藏集抽奖id | -|

返回值

根对象：
| 字段    | 类型 | 内容     | 备注 |
| ------- | ---- | -------- | --------------------------- |
| code    | num  | 返回值   | 0：成功 |
| message | str  | 错误信息 | 默认为0 |
| ttl | num  | 1 | - |
| data    | obj  | 返回数据 | - |

`data`字段：
| 字段 | 类型 | 内容  | 备注 |
|--|--|--|--|
|lottery_id|int|收藏集抽奖id|-|
|name|str|收藏集抽奖名称|-|
|item_list|Array|可抽出的物品列表|-|
|collect_list|Object|见下方|-|
|button_bubble|null|未知|-|
|guide_info|null|未知|-|
|is_booked|int|未知|-|
|total_book_cnt|int|未知|-|
|is_fission|int|未知|-|
|physical_exchange|int|未知|-|

`list`字段：
| 字段 | 类型 | 内容  | 备注 |
|--|--|--|--|
|item_type|int|物品类型|目前只拿到个`1`, 其他值未知|
|card_info|Object|见下方|-|

`card_info`字段：
| 字段 | 类型 | 内容  | 备注 |
|--|--|--|--|
|card_type_id|int|该卡片id|-|
|card_name|str|该卡片名称|-|
|card_img|str|该卡片图片|无水印|
|card_type|int|int|未知|-|
|video_list|Array|该卡片动态视频|无水印|
|is_physical_orientation|int|该卡片旋转方向|-|
|card_scarcity|int|该卡片稀有度|-|
|is_mute|int|该卡片是否静音|-|
|width|int|该卡片像素宽度|-|
|height|int|该卡片像素高度|-|
|card_ext_text|str|?该卡片文件名字符串|-|
|card_img_download|str|该卡片图片|有水印|
|video_list_download|Array|该卡片动态视频|有水印|
|subtitles_url|未知|-|
|play|null|未知|-|
|tag|null|未知|-|
|card_sub_type|int|未知|-|
|is_new_tag|int|未知|-|
|is_up_tag|int|未知|-|
|is_limited_card|int|未知|-|
|stock_info|null|未知|-|

`collect_list`字段：
| 字段 | 类型 | 内容  | 备注 |
|--|--|--|--|
|collect_infos|Array|见下方|-|
|collect_chain|null|未知|-|

`collect_infos`字段：
| 字段 | 类型 | 内容  | 备注 |
|--|--|--|--|
|collect_id|int|收集品id|-|
|start_time|int|开始时间|-|
|end_time|int|结束时间|-|
|redeem_text|str|兑换条件|-|
|redeem_item_type|int|兑换物类型|-|
|redeem_item_id|str|兑换物id|-|
|redeem_item_name|str|兑换物名称|-|
|redeem_item_image|str|兑换物预览图片|-|
|owned_item_amount|int|拥有的数量|-|
|require_item_amount|int|需要的数量|-|
|has_redeemed_cnt|int|兑换次数|-|
|effective_forever|int|是否永久有效|-|
|redeem_item_image_download|str|未知
|card_item|Object|见下方|-|
|jump_url|str|?跳转链接|-|
|redeem_cond_type|str|当前兑换状态|-|
|remain_stock|int|当前库存|-|
|total_stock|int|总库存|-|
|lottery_id|int|抽奖id|-|
|reward_tag|str|奖励显示标签|-|
|redeem_detail_image|str|兑换详情图片|-|
|redeem_detail_videos|null|未知|-|
|sort|int|排序|-|
|redeem_items_optional|null|未知|-|
|unlock_condition|Object|见下方|-|

`card_item`字段：
| 字段 | 类型 | 内容  | 备注 |
|--|--|--|--|
|card_type_info|null|-|-|
|card_asset_info|null|-|-|
|play|null|-|-|
|tag|null|-|-|

`unlock_condition`字段：
| 字段 | 类型 | 内容  | 备注 |
|--|--|--|--|
|unlocked|bool|是否解锁|-|
|lock_type|int|解锁类型|-|
|expire_at|int|过期与|-|
|unlocked_at|int|解锁于|-|
|unlock_threshold|int|?解锁起点|-|
|current_threshold|int|?当前起点|-|

**Comment by SessionHu** [comment]
Please close as #1066 has been merged. See [装扮/收藏集](https://github.com/SocialSisterYi/bilibili-API-collect/blob/60a0c5d1a2f44fe61335da04571305fa7727a968/docs/garb/lottery.md).

**Comment by hly1204** [comment]
请求参数那边应该是 `key_word`，所以才会没有返回。感谢提供。

**Comment by z0z0r4** [comment]
> 请求参数那边应该是 `key_word`，所以才会没有返回。感谢提供。

确定的话可以开个新 issue 吗？

**Comment by CloudyEagle** [comment]
看展示出来的备注，如果要用API去判断某个act_id是否存在，那还是需要lottery_id的，但lottery_id与act_id有什么逻辑，似乎很难推演

**Comment by heartalborada-del** [comment]
> 看展示出来的[内容](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/garb/lottery.md)，如果要用API去判断某个act_id是否存在，那还是需要lottery_id的，但lottery_id与act_id几乎没有关联度，若遇到DLC就不好推算 ![Image](https://github.com/user-attachments/assets/4889239e-9758-46a8-a12f-3bed44bc9559)
> 
> 此外API似乎没有网页访问的title，只有抽奖卡池的名称，个人担心的是存在重名的情况。 ![Image](https://github.com/user-attachments/assets/643deee5-a48b-403b-9014-0e948d619714)
> 
> 所以感觉用自动化脚本下载收藏集中的图片和视频还无法脱离浏览器

搜索的话可以看看我这个项目里面的api，当时没提交到BAC，理论上可以完全脱离网页进行下载的
https://github.com/heartalborada-del/Collection-Down/blob/main/pages/search.vue
https://github.com/heartalborada-del/Collection-Down/blob/main/pages/metadata.vue

**Comment by heartalborada-del** [comment]
> 看展示出来的[内容](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/garb/lottery.md)，如果要用API去判断某个act_id是否存在，那还是需要lottery_id的，但lottery_id与act_id几乎没有关联度，若遇到DLC就不好推算 ![Image](https://github.com/user-attachments/assets/4889239e-9758-46a8-a12f-3bed44bc9559)
> 
> 此外API似乎没有网页访问的title，只有抽奖卡池的名称，个人担心的是存在重名的情况。 ![Image](https://github.com/user-attachments/assets/643deee5-a48b-403b-9014-0e948d619714)
> 
> 所以感觉用自动化脚本下载收藏集中的图片和视频还无法脱离浏览器

比如说这个api `https://api.bilibili.com/x/vas/dlc_act/act/basic?act_id=${act_id}` 就可以获取网页title
这个 `
https://api.bilibili.com/x/garb/v2/user/suit/benefit?item_id=${emoji_package_id}&part=emoji_package` 就能获取表情包的数据

**Comment by CloudyEagle** [comment]
> 比如说这个api `https://api.bilibili.com/x/vas/dlc_act/act/basic?act_id=${act_id}` 里面就有网页title 这个 ` https://api.bilibili.com/x/garb/v2/user/suit/benefit?item_id=${emoji_package_id}&part=emoji_package` 就能获取表情包的数据

感谢提供API，我抽空去试试。
