### ISSUE TITLE
[新增/更新请求] 检测是否有新动态

### ISSUE THREAD

**Issue by SnhAenIgseAl** [SocialSisterYi/bilibili-API-collect#1082]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/all/update

### 详情描述

url: https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/all/update
method: GET
| 参数 | 含义 | 是否必要 |
|  ----  | ----  | ----  |
| type  | 动态类型 |
| update_baseline | 以当前第一条动态id为更新基线 | √ |
| web_location | 

response
```json
{
    "code": 0,
    "message": "0",
    "ttl": 1,
    "data": {
        "update_num": 0
    }
}  
```
data中的update_num为新动态数量

**Comment by SnhAenIgseAl** [comment]
需要sessdata

**Comment by SessionHu** [comment]
Please close. See [检测是否有新动态](https://github.com/SocialSisterYi/bilibili-API-collect/blob/60a0c5d1a2f44fe61335da04571305fa7727a968/docs/dynamic/all.md#%E6%A3%80%E6%B5%8B%E6%98%AF%E5%90%A6%E6%9C%89%E6%96%B0%E5%8A%A8%E6%80%81).
