### ISSUE TITLE
[新增/更新请求] 话题搜索API

### ISSUE THREAD

**Issue by JKLASDWD** [SocialSisterYi/bilibili-API-collect#1083]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/topic/pub/rcmd/search

### 详情描述

> https://api.bilibili.com/x/topic/pub/rcmd/search

*请求方式：GET*

**请求参数**：

| 参数名    | 类型 | 内容                     | 是否必要 | 备注                 |
| --------- | ---- | ------------------------ | -------- | -------------------- |
| keywords  | str  | 搜索关键词               | 非必要   | -                    |
| content   | ?    | (?)                      | 非必要   | -                    |
| upload_id | str  | (?)                      | 非必要   | UID_NUM1_NUM2        |
| page_size | num  | 单页最多显示搜索结果个数 | 非必要   | 默认为20，最大为1000 |
| page_num  | num  | 当前页面序号             | 非必要   | 默认为1              |
| offset    | num  | 搜索结果偏移量           | 非必要   | 默认为0              |

**响应正文:**

**JSON回复**

根对象：

| 字段    | 类型 | 内容     | 备注    |
| ------- | ---- | -------- | ------- |
| code    | num  | 返回值   | 0：成功 |
| message | str  | 错误信息 | 默认为0 |
| ttl     | num  | 1        | -       |
| data    | obj  | 返回数据 | -       |

`data`字段

| 字段                    | 类型  | 内容     | 备注            |
| ----------------------- | ----- | -------- | --------------- |
| has_create_jurisdiction | bool  | false    | ?               |
| new_topic               | obj   | 见下     | -               |
| page_info               | obj   | 见下     | -               |
| request_id              | str   |          | 随机生成的id号? |
| topic_items             | array | 搜索结果 | -               |

`new_topic`字段

| 字段 | 类型 | 内容       | 备注 |
| ---- | ---- | ---------- | ---- |
| name | str  | 搜索关键词 | -    |

`page_info`字段

| 字段     | 类型 | 内容         | 备注             |
| -------- | ---- | ------------ | ---------------- |
| has_more | bool | 是否还有页面 | -                |
| offset   | int  | 偏移量       | offset+page_size |

`topic_items`数组

| 项   | 类型 | 内容          | 备注 |
| ---- | ---- | ------------- | ---- |
| 0    | obj  | 第1个搜索结果 | -    |
| n    | obj  | 第n个搜索结果 | -    |
| ...  | obj  | ...           | -    |

`topic_items`数组中的项

| 字段               | 类型 | 内容               | 备注                          |
| ------------------ | ---- | ------------------ | ----------------------------- |
| description        | str  | 话题描述           | -                             |
| discuss            | int  | 讨论数             | 乘上10为stat_desc中显示的数字 |
| id                 | int  | 话题id             | -                             |
| name               | str  | 话题名称           | -                             |
| show_interact_data | bool | (?)                | -                             |
| stat_desc          | str  | 话题下方显示的状态 | -                             |
| view               | int  | 浏览数             | 乘上10为stat_desc中显示的数字 |

**响应示例:**

```json
{
    "code": 0,
    "message": "0",
    "ttl": 1,
    "data": {
        "new_topic": {
            "name": ""
        },
        "has_create_jurisdiction": false,
        "topic_items": [
            {
                "id": 1200265,
                "name": "巴黎最前线",
                "view": 641330561,
                "discuss": 885743,
                "stat_desc": "6.4亿浏览·88.6万讨论",
                "description": "巴黎体育盛会前线速递！",
                "show_interact_data": false
            }
        ],
        "request_id": "xxx",
        "page_info": {
            "offset": 20,
            "has_more": true
        }
    }
}
```

**Comment by JKLASDWD** [comment]
需要session data

**Comment by SessionHu** [comment]
您所说接口确实存在, 不过网页抓包显示该接口并没有返回实际内容, 但同时发现接口 `https://app.bilibili.com/x/topic/pub/search` 与所说的请求参数与响应相同

**Comment by SessionHu** [comment]
Please close. See [话题搜索](https://github.com/SocialSisterYi/bilibili-API-collect/blob/60a0c5d1a2f44fe61335da04571305fa7727a968/docs/dynamic/topic.md).
