### ISSUE TITLE
通过current_dynamic_id获取新动态数量与前20条新动态的详情

### ISSUE THREAD

**Issue by NGWORKS** [SocialSisterYi/bilibili-API-collect#109]
current_dynamic_id 某动态统类id之后[这个命名见上个issues关于dynamic_id](https://github.com/SocialSisterYi/bilibili-API-collect/issues/108)
url: https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?uid=<uid>&type_list=268435455&current_dynamic_id=<dynamic_id>
uid：uid
type_list：固定值
current_dynamic_id：起始的dynamic_id
需要 cookie
方法：get
返回的json中
data中有关于新动态的数量
data - cards是 从最新的动态向下20条的详情 最多20条 数据类型和[这个issues](https://github.com/SocialSisterYi/bilibili-API-collect/issues/108)基本一致  *开直播发出的动态不算

和这个伴生的api还有多个，我目前仅使用三个，
一个轮询 https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_cyclic_num?type_list=268435455&offset=<>
*offset 判断指定dynamic_id之上有没有新动态
一个新动态 本issue
一个历史动态https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_history?uid=<>&offset_dynamic_id=<>&type=268435455
*offset_dynamic_id :指定dynamic_id之下的20个动态

打开console应该很容易看到，不在这里赘述，希望能有帮助

**Comment by Sora233** [comment]
补充一个获取用户空间个人动态的，支持offset，不需要cookie
get https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?host_uid=2

**Comment by Misaka-0x447f** [comment]
该补充项目的参数列表示例：
https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?visitor_uid=7023714&host_uid=1472906636&offset_dynamic_id=546724340073763968&need_top=1&platform=web
