### ISSUE TITLE
这个接口 /x/v2/dm/seg.so是否是弹幕接口

### ISSUE THREAD

**Issue by dmankill** [SocialSisterYi/bilibili-API-collect#11]
我用fiddler看页面请求数据,有看到这个
https://api.bilibili.com/x/v2/dm/web/seg.so?type=1&oid=188218671&pid=668122988&segment_index=1 
这个接口有返回类似弹幕的数据

**Comment by SocialSisterYi** [comment]
这个是超长视频的流式弹幕接口（比如电影），以6min为一个分段，编码现在还不知道，回家以后再研究它

**Comment by SocialSisterYi** [comment]
可以参考一下这个https://www.zhihu.com/answer/1240725563

**Comment by dmankill** [comment]
原来是protobuf传输的,懂了,多谢
