### ISSUE TITLE
[新增/更新请求] up主包月充电开通时间

### ISSUE THREAD

**Issue by guanmengcheng** [SocialSisterYi/bilibili-API-collect#1127]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### 详情描述

当前关于包月充电可以获取到的数据没有up主包月充电开通的时间，能否获取该字段，精确到天。**科研需求**，如果有能解决该问题的大手子，欢迎留言，愿意付费，酬金好说，感谢！

**Comment by guanmengcheng** [comment]
> 您要获取的是，在同一个 UP 主下的粉丝给 UP 主包月充电的时间，还是您给 UP 主包月充电的时间？😂包月充电的文档是我写的

感谢大佬的回复，我需要的是up主开通包月充电这个功能的时间，比如食贫道在2023.12.1开通了包月充电的功能，后续才会有包月充电的粉丝。当然您说的同一个up主下的粉丝给up主开通包月充电的时间如果能获取也同样需要，目前在文档里我看到只能获取30个包月充电的粉丝。 如果方便的话可以email我 mcguanAThustDOTeduDOTcn

**Comment by wuziqian211** [comment]
> > 您要获取的是，在同一个 UP 主下的粉丝给 UP 主包月充电的时间，还是您给 UP 主包月充电的时间？😂包月充电的文档是我写的
> 
> 感谢大佬的回复，我需要的是up主开通包月充电这个功能的时间，比如食贫道在2023.12.1开通了包月充电的功能，后续才会有包月充电的粉丝。当然您说的同一个up主下的粉丝给up主开通包月充电的时间如果能获取也同样需要，目前在文档里我看到只能获取30个包月充电的粉丝。 如果方便的话可以email我 mcguanAThustDOTeduDOTcn

1. 关于UP主开通包月充电这个功能的时间，目前应该是没有办法能直接获取的；
2. 粉丝给UP主包月充电的时间，这个我过几天抓个包，如果可以获取到的话会联系您的，不过由于B站的反爬虫机制，**存在无法获取到包月充电具体时间的可能**。

**Comment by guanmengcheng** [comment]
> > > 您要获取的是，在同一个 UP 主下的粉丝给 UP 主包月充电的时间，还是您给 UP 主包月充电的时间？😂包月充电的文档是我写的
> > 
> > 
> > 感谢大佬的回复，我需要的是up主开通包月充电这个功能的时间，比如食贫道在2023.12.1开通了包月充电的功能，后续才会有包月充电的粉丝。当然您说的同一个up主下的粉丝给up主开通包月充电的时间如果能获取也同样需要，目前在文档里我看到只能获取30个包月充电的粉丝。 如果方便的话可以email我 mcguanAThustDOTeduDOTcn
> 
> 1. 关于UP主开通包月充电这个功能的时间，目前应该是没有办法能直接获取的；
> 2. 粉丝给UP主包月充电的时间，这个我过几天抓个包，如果可以获取到的话会联系您的，不过由于B站的反爬虫机制，**存在无法获取到包月充电具体时间的可能**。

太感谢了，如果为了解决反爬，需要服务器之类的资源支持可以联系我一块解决。-from HUST.

**Comment by wuziqian211** [comment]
您好，经过我的抓包，在我发现的接口中，B 站**的确没有在任何地方向前端返回粉丝的包月充电开通时间**。目前只有 UP 主以及给 UP 主包月充电的粉丝才能看到包月充电时间，其他用户是看不见的。很抱歉给您的工作带来了麻烦与不便。

**Comment by guanmengcheng** [comment]
> 您好，经过我的抓包，在我发现的接口中，B 站**的确没有在任何地方向前端返回粉丝的包月充电开通时间**。目前只有 UP 主以及给 UP 主包月充电的粉丝才能看到包月充电时间，其他用户是看不见的。
> 
> 如果您是因科研需求而需要获取这些数据，您可以直接联系 B 站的客服，不过 B 站可能会觉得这些数据属于隐私，而不提供这些数据。
> 
> 很抱歉给您的工作带来了麻烦与不便。

非常感谢您能抽时间check我的问题，辛苦了！ 我找下B站的客服试试，如果后续您这边有相关数据的更新，可以跟我说下，谢谢！
