### ISSUE TITLE
扫码登录（TV端）中的问题

### ISSUE THREAD

**Issue by zhongfly** [SocialSisterYi/bilibili-API-collect#113]
我个人实践发现，完成第2步后（以密钥作为参数进行POST），在未扫描二维码时，第一次会正确返回code：86039二维码尚未确认，等待2s后，再次请求会直接返回code：-3 API校验密匙错误。
根据提示应该是appkey错误，但这2次的appkey是相同的，不应该出现一次成功，一次失败的情况。

> 第一次请求的参数：{'appkey': '4409e2ce8ffd12b8', 'ts': '1607407916', 'sign': 'f745cae3586ad7a959b8fe2e885defb4'}
> 返回{'code': 86039, 'message': '二维码尚未确认', 'ttl': 1, 'data': None}
> 第二次请求的参数：{'appkey': '4409e2ce8ffd12b8', 'ts': '1607407918', 'sign': '37dc8bb8c632ff88534d369ee3effe4b'}
> 返回{'code': -3, 'message': 'API校验密匙错误', 'ttl': 1}

**Comment by zhongfly** [comment]
另外该文档有一处笔误[申请二维码URL及扫码密钥（TV端）](
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/QR.md#%E7%94%B3%E8%AF%B7%E4%BA%8C%E7%BB%B4%E7%A0%81url%E5%8F%8A%E6%89%AB%E7%A0%81%E5%AF%86%E9%92%A5tv%E7%AB%AF)：
json回复的data对象中字段`oauthKey`应为`auth_code`，响应示例是正确的。

**Comment by SocialSisterYi** [comment]
> 我个人实践发现，完成第2步后（以密钥作为参数进行POST），在未扫描二维码时，第一次会正确返回code：86039二维码尚未确认，等待2s后，再次请求会直接返回code：-3 API校验密匙错误。
> 根据提示应该是appkey错误，但这2次的appkey是相同的，不应该出现一次成功，一次失败的情况。
> 
> > 第一次请求的参数：{'appkey': '4409e2ce8ffd12b8', 'ts': '1607407916', 'sign': 'f745cae3586ad7a959b8fe2e885defb4'}
> > 返回{'code': 86039, 'message': '二维码尚未确认', 'ttl': 1, 'data': None}
> > 第二次请求的参数：{'appkey': '4409e2ce8ffd12b8', 'ts': '1607407918', 'sign': '37dc8bb8c632ff88534d369ee3effe4b'}
> > 返回{'code': -3, 'message': 'API校验密匙错误', 'ttl': 1}

这个应该是ts字段的值变化导致的，需要重新生成sign（带盐值的md5）

**Comment by zhongfly** [comment]
我重新生成了sign的……显而易见sign是不同的啊

社会易姐QwQ <notifications@github.com> 于 2020年12月8日周二 23:43写道：

**Comment by Chank616** [comment]
该如何获取二维码图片呢。。

**Comment by zhongfly** [comment]
> 该如何获取二维码图片呢。。

你应该问二维码的内容是什么
二维码的内容就是http://passport.bilibili.com/x/passport-tv-login/qrcode/auth_code 返回的data里的url

**Comment by zhongfly** [comment]
> 另外该文档有一处笔误[申请二维码URL及扫码密钥（TV端）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/QR.md#%E7%94%B3%E8%AF%B7%E4%BA%8C%E7%BB%B4%E7%A0%81url%E5%8F%8A%E6%89%AB%E7%A0%81%E5%AF%86%E9%92%A5tv%E7%AB%AF)：
> json回复的data对象中字段`oauthKey`应为`auth_code`，响应示例是正确的。

@SocialSisterYi  这个错误还没改呢

**Comment by Chank616** [comment]
> > 该如何获取二维码图片呢。。
> 
> 你应该问二维码的内容是什么
> 二维码的内容就是http://passport.bilibili.com/x/passport-tv-login/qrcode/auth_code返回的数据里的网址
已解决 谢谢拉
