### ISSUE TITLE
[新增/更新请求] 某些bv号视频，无法解析mp4直链，返回-404

### ISSUE THREAD

**Issue by byxiaobai** [SocialSisterYi/bilibili-API-collect#1145]
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### 详情描述

`package pers.byxiaobai.supervideo.media.support.bilibili;

import cn.hutool.http.HttpRequest;
import com.google.gson.internal.LinkedTreeMap;
import pers.byxiaobai.supervideo.media.support.bilibili.login.BilibiliCookie;
import pers.byxiaobai.supervideo.media.support.bilibili.login.BilibiliLogin;

import java.util.ArrayList;
import java.util.HashMap;

import static pers.byxiaobai.supervideo.media.support.bilibili.util.PacketUtil.toMap;

public class BilibiliVideoInfo {

    private HashMap<String,Object> infoMap;
    public String bvid;
    public int cid;
    public int qn=80;

    private BilibiliVideoInfo(String bvid){
        this.bvid=bvid;
    }

    public static BilibiliVideoInfo create(String bvid){
        BilibiliVideoInfo videoInfo=new BilibiliVideoInfo(bvid);
        videoInfo.init();
        return videoInfo;
    }

    public String getVideoDownloadUrl(){
        String streamUrl="https://api.bilibili.com/x/player/wbi/playurl";
        HashMap<String,Object> paramMap=new HashMap<>();
        paramMap.put("bvid",bvid);
        paramMap.put("cid",cid);
        paramMap.put("qn",qn);
        String jct = "";
        String sessData = "";

        if(BilibiliLogin.INSTANCE.hasCookie()){
            jct= BilibiliCookie.INSTANCE.getBili_jct();
            sessData=BilibiliCookie.INSTANCE.getSESSDATA();
        }

        String response= HttpRequest.get(streamUrl).form(paramMap)
                .header("Referer", "https://www.bilibili.com")
                .header("User-Agent","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36")
                .header("Cookie", "SESSDATA="+sessData+";bili_jct="+jct)
                .timeout(10 * 1000)
                .form(paramMap).execute().body();

        HashMap<String,Object> responseMap= toMap(response);
        System.out.println("normal response:"+response);
        LinkedTreeMap<String, Object> data=(LinkedTreeMap<String, Object>) responseMap.get("data");
        ArrayList durl=(ArrayList)data.get("durl");
        LinkedTreeMap<String, Object> urlMap=(LinkedTreeMap<String, Object>)durl.get(0);
        String url=(String)urlMap.get("url");
        return url;
    }

    private void initInfoMap(){
        String videoInfoUrl="https://api.bilibili.com/x/web-interface/view";
        HashMap<String,Object> paramMap=new HashMap<>();
        paramMap.put("bvid",bvid);

        String jct = "";
        String sessData = "";

        if(BilibiliLogin.INSTANCE.hasCookie()){
            jct= BilibiliCookie.INSTANCE.getBili_jct();
            sessData=BilibiliCookie.INSTANCE.getSESSDATA();
        }
        String response= HttpRequest.get(videoInfoUrl).form(paramMap).header("Referer", "https://www.bilibili.com")
                .header("Sec-Fetch-Mode", "no-cors")
                .header("User-Agent","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36")
                .header("Cookie", "SESSDATA="+sessData+";bili_jct="+jct)
                .execute().body();
        infoMap=toMap(response);
    }

    private void initCid(){
        LinkedTreeMap<String,Object> map= (LinkedTreeMap<String, Object>) infoMap.get("data");
        int cid=((Double)map.get("cid")).intValue();
        this.cid=cid;
    }

    private void init(){
        initInfoMap();
        initCid();
    }

    public static void main(String[] args){
        BilibiliVideoInfo videoInfo=new BilibiliVideoInfo("BV1Fw4m1Y7jo");
        videoInfo.init();
        videoInfo.getVideoDownloadUrl();

    }

}
`，代码如上。当bv号为BV1r1421o7of时，可以正常使用。当bv号为BV1qnxReMEfX时，返回-404。但是这个链接是可以访问的：https://www.bilibili.com/video/BV1qnxReMEfX

**Comment by wuziqian211** [comment]
我这边直接调用接口是正常的，您可以检查一下代码的精度问题，比如 `cid` 不应该使用 `int` 类型，而应该使用 `long`

附：

- `BV1r1421o7of`（`av1553050268`）cid：`1510799067`
- `BV1qnxReMEfX`（`av113245151040342`）cid：`26129861934`

**Comment by byxiaobai** [comment]
@wuziqian211 我又测试了一下，用我现在的代码还是报这个问题，-400。我自己用apifox测试也是-400
请问方便发一下调用接口的参数吗，我用apifox测试一下
![image](https://github.com/user-attachments/assets/f74f5f2d-c364-4fc8-9653-55ef32d46d17)

**Comment by wuziqian211** [comment]
https://api.bilibili.com/x/player/wbi/playurl？bvid=BV1qnxReMEfX&cid=26129861934&qn=80&web_location=1315877&w_webid=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzcG1faWQiOiIwLjAiLCJ1c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIzLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJiaWxpX3RpY2tldCI6ImZiMTdiZTYzMGNmYWQ3YjhhYzIzNzNkOGQ0ZDRlMzQwIiwiY3JlYXRlZF9hdCI6MTczMjU1ODUyOCwidHRsIjo4NjQwMCwidXJsIjoiLzQyNTUwMzkxMyIsInJlc3VsdCI6Im5vcm1hbCIsImlzcyI6ImdhaWEiLCJpYXQiOjE3MzI1NTg1Mjh9.Eh4Fa8eD4otdqUFGagEHac1vl0g1rqhODKq8qahFubrMe1bFxXq82fk-jwy7U5ev0xTyZWFb0hmWTYbcko8PNmLEWMSgXoNuK532Ug9zrp6W_YnrPxccAxwpnI3huMHYXcjg2MYNI0Af9qJVPxWRr0v6QOsgimNr7S96-SX3LGuStQBpEq-fil_u4A2HkujcUx1rVCeshTGGou1ZlZ9x4HPqVJLPXRvXNvr_4txhZy9dmf3eFrJHMw2Fe-3osdbqKUbDZnOKHTrQbr_OJ7yyr2EW2s1pphiHo6sfZWRBWckH865utYAUtbSAIlVLLwJDIr9iWo2T3W5BlKb6LqIygg&wts=1732558556&w_rid=ccd8191987a5230b40e3cdbe1a80c05d

**Comment by byxiaobai** [comment]
> 返回 `-400` 表示请求参数有问题，但我从您的截图中无法看到请求参数的值是什么😂
> 
> 调用此接口的正确 URL：https://api.bilibili.com/x/player/wbi/playurl?bvid=BV1qnxReMEfX&cid=26129861934&qn=80&web_location=1315877&w_webid=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzcG1faWQiOiIwLjAiLCJ1c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIzLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJiaWxpX3RpY2tldCI6ImZiMTdiZTYzMGNmYWQ3YjhhYzIzNzNkOGQ0ZDRlMzQwIiwiY3JlYXRlZF9hdCI6MTczMjU1ODUyOCwidHRsIjo4NjQwMCwidXJsIjoiLzQyNTUwMzkxMyIsInJlc3VsdCI6Im5vcm1hbCIsImlzcyI6ImdhaWEiLCJpYXQiOjE3MzI1NTg1Mjh9.Eh4Fa8eD4otdqUFGagEHac1vl0g1rqhODKq8qahFubrMe1bFxXq82fk-jwy7U5ev0xTyZWFb0hmWTYbcko8PNmLEWMSgXoNuK532Ug9zrp6W_YnrPxccAxwpnI3huMHYXcjg2MYNI0Af9qJVPxWRr0v6QOsgimNr7S96-SX3LGuStQBpEq-fil_u4A2HkujcUx1rVCeshTGGou1ZlZ9x4HPqVJLPXRvXNvr_4txhZy9dmf3eFrJHMw2Fe-3osdbqKUbDZnOKHTrQbr_OJ7yyr2EW2s1pphiHo6sfZWRBWckH865utYAUtbSAIlVLLwJDIr9iWo2T3W5BlKb6LqIygg&wts=1732558556&w_rid=ccd8191987a5230b40e3cdbe1a80c05d
> 
> 顺便提醒一下，要注意隐藏图片中的账号登录信息，如 SESSDATA

好的，发现确实是我搞错了，在apifox里的cid填错了，因为溢出了所以从idea里拿到的是错误的数据，检查的时候也忽略掉这个点了
