### ISSUE TITLE
获取用户对应的直播间状态返回请求被拦截

### ISSUE THREAD

**Issue by Sora233** [SocialSisterYi/bilibili-API-collect#118]
[获取用户对应的直播间状态](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/live/info.md#%E8%8E%B7%E5%8F%96%E6%88%BF%E9%97%B4%E9%A1%B5%E5%88%9D%E5%A7%8B%E5%8C%96%E4%BF%A1%E6%81%AF)

`{"code":-412,"message":"请求被拦截","ttl":1,"data":null}`

还有别的方式能直接从mid获取直播间状态吗？

**Comment by ProgramRipper** [comment]
尝试一下换个ua，我在iPad的Safari中是-412，但是在GitHub移动端内置的浏览器中是可以的。🤣

**Comment by ProgramRipper** [comment]
[test](http://api.live.bilibili.com/room/v1/Room/getRoomInfoOld?mid=2)

**Comment by ProgramRipper** [comment]
[test](https://httpbin.org/get)

**Comment by ProgramRipper** [comment]
[test](https://httpbin.org/get)

**Comment by SocialSisterYi** [comment]
> [获取用户对应的直播间状态](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/live/info.md#%E8%8E%B7%E5%8F%96%E6%88%BF%E9%97%B4%E9%A1%B5%E5%88%9D%E5%A7%8B%E5%8C%96%E4%BF%A1%E6%81%AF)
> 
> `{"code":-412,"message":"请求被拦截","ttl":1,"data":null}`
> 
> 还有别的方式能直接从mid获取直播间状态吗？

和referer与ua都没关系，需要cookie中DedeUserID字段存在且它的的值不为0，即正常情况下登录后有权限

**Comment by Sora233** [comment]
如果有人搜到这个issue，try this
`curl -G 'http://api.live.bilibili.com/room/v1/Room/getRoomInfoOld' --data-urlencode 'mid=2' -b 'DedeUserID=0'`
