### ISSUE TITLE
关于B站为什么不主动公开api的探讨

### ISSUE THREAD

**Issue by sunset1234321** [SocialSisterYi/bilibili-API-collect#122]
其实b站为什么不公开官方api文档
要用户自己不断琢磨.....

**Comment by ProgramRipper** [comment]
自从`api.bilibili.cn`被关闭后，就大概知道b站对于爪巴数据的人是什么态度了。`biliob.com`也能证明这点。
况且现在b站api也在往更难逆向的方向发展了，以前能用浏览器抓包，看个变量名就能懂个大概；现在protobuf，二进制数据，还要翻js源码才能序列化。😭

**Comment by SocialSisterYi** [comment]
> 其实b站为什么不公开官方api文档
> 要用户自己不断琢磨.....

公开了会助长黑产影响社区环境和商业利益，同时也会带来巨量的爬虫流量影响服务器的运行
再一种是会让大众从接口了解到平台的某种“操作办法”

**Comment by zhang-anzhi** [comment]
这样的讨论建议改个标题
另外B站的官方对数据统计一直做的不太好，但是明显不希望第三方来做数据统计，至少也应该是指定的组织来统计，公开这些接口的后果就是更巨大的服务器压力，甚至可能有人就会利用API的一些漏洞来查看仅仅从前端禁止查看的内容

**Comment by zhang-anzhi** [comment]
比如说完全可以通过暴力方式查找到一个人在B站发布过的所有评论

**Comment by batt1ebear** [comment]
搜索b站数据可以看到一个叫火烧云的网站  他们的数据十分完备  不知道和阿b有什么交易

**Comment by SocialSisterYi** [comment]
> 搜索b站数据可以看到一个叫火烧云的网站  他们的数据十分完备  不知道和阿b有什么交易

确实有交易，不然为什么B收拾biliob而不收拾火烧云😂😂

**Comment by lb-chc** [comment]
> 平台的某种“操作办法”

将这句话理解为“用户从底层操作平台的方法”，还是“平台实际操作信息的办法”呢
我觉得对于后者，拥有后台统计的人会对信息操作更有想象力，他们能看到一些很有趣的东西，获得对网络社会的独特认识......

**Comment by lb-chc** [comment]
目前b站有没有加密和混淆API的苗头？
对于“用户从底层操作平台的方法”这种理解，平台更多是怕用户发现平台的技术本质后突破限制，迫使平台使用更难拓展更消耗性能的业务逻辑吗......？

**Comment by zhang-anzhi** [comment]
> > 平台的某种“操作办法”
> 
> 将这句话理解为“用户从底层操作平台的方法”，还是“平台实际操作信息的办法”呢 我觉得对于后者，拥有后台统计的人会对信息操作更有想象力，他们能看到一些很有趣的东西，获得对网络社会的独特认识......

通过分析别人的API获取对网络的认识，对于非专业充满好奇还在学习的人来说，这是很危险的

**Comment by lb-chc** [comment]
> 将这句话理解为“用户从底层操作平台的方法”，还是“平台实际操作信息的办法”呢 我觉得对于后者，拥有后台统计的人会对信息操作更有想象力，他们能看到一些很有趣的东西，获得对网络社会的独特认识......

同时，对于这种取得独特认识的人（网站管理员），咱们使用者的各种讨论在他看来只是浅鱼塘里受控的的鱼翻了下身而已吧，他们理应是完全知道用户的小猫腻，只是受限于资源管不过来吧

**Comment by lb-chc** [comment]
> 通过分析别人的API获取对网络的认识，对于非专业充满好奇还在学习的人来说，这是很危险的

啊我指的是bilibili网站管理员......你指的危险是爬取不应该看到的内容、爬取过量影响网站性能、随意分享影响网站利益而被法律制裁的这种吗？

**Comment by lb-chc** [comment]
或者，你指，这行为不接触原理，却过度满足好奇心，容易沦为易语言外挂制作者那样的脚本小子？

**Comment by zhang-anzhi** [comment]
> > 通过分析别人的API获取对网络的认识，对于非专业充满好奇还在学习的人来说，这是很危险的
> 
> 啊我指的是bilibili网站管理员......你指的危险是爬取不应该看到的内容、爬取过量影响网站性能、随意分享影响网站利益而被法律制裁的这种吗？

我的危险指的是这可能让这些人失去网络活动的**边界感**，培养网络活动的法律意识是十分有必要的

**Comment by lb-chc** [comment]
> 我的危险指的是这可能让这些人失去网络活动的**边界感**，培养网络活动的法律意识是十分有必要的

(你在这里发言是不用顾及法律的是吧)这个法律意识是避免自己触犯法律给自己带来损失，还是一种互惠利他和公德心

你是不是隐含了一个判断：“无所顾忌的使用网络技术会造成很可怕的事”。你也在顾及这种事件的出现会造成先审后播一样的结果，使小心的技术使用者也失去伸展的空间，害了很多人？

**Comment by zhang-anzhi** [comment]
> > 我的危险指的是这可能让这些人失去网络活动的**边界感**，培养网络活动的法律意识是十分有必要的
> 
> (你在这里发言是不用顾及法律的是吧)这个法律意识是避免自己触犯法律给自己带来损失，还是一种互惠利他和公德心
> 
> 你是不是隐含了一个判断：“无所顾忌的使用网络技术会造成很可怕的事”。你也在顾及这种事件的出现会造成先审后播一样的结果，使小心的技术使用者也失去伸展的空间，害了很多人？

我之前提到了，是指对于非专业充满好奇还在学习的人来说，公开商业网站的API提供分析研究，获得对网络社会的独特认识，是很危险的

**Comment by lb-chc** [comment]
> > > 我的危险指的是这可能让这些人失去网络活动的**边界感**，培养网络活动的法律意识是十分有必要的
> > 
> > 
> > (你在这里发言是不用顾及法律的是吧)这个法律意识是避免自己触犯法律给自己带来损失，还是一种互惠利他和公德心
> > 你是不是隐含了一个判断：“无所顾忌的使用网络技术会造成很可怕的事”。你也在顾及这种事件的出现会造成先审后播一样的结果，使小心的技术使用者也失去伸展的空间，害了很多人？
> 
> 我之前提到了，是指对于非专业充满好奇还在学习的人来说，公开商业网站的API提供分析研究，获得对网络社会的独特认识，是很危险的

那你确实在和我说一件事了，你只说“通过分析别人的API获取对网络的认识”我以为你专指技术层面，我关心的就是对网络社会的独特认识。

我将你的话总结为：“对于非专业充满好奇还在学习的人，通过公开商业网站的API进行分析研究，获得对网络社会的独特认识，可能让这些人失去网络活动的边界感，这很危险，避免这种危险意味着培养网络活动的法律意识”

可对网络社会的独特认识从何处指向危险？不是传统的网站商业利益，但又和法律相关......是一种从表网发现深网的可能吗？

如果是这样，那因此，公开的大型网络社区分析项目止步于用户关系图、TAG/播放量/最高关注度制作组历时变化？因为真正取得对网络社会的独特认识的人发现他们不宜宣扬这种认识？

而危险来自非专业充满好奇还在学习的人不能很好的隐藏自己的痕迹和不给他人造成麻烦，并且他可能从这种特殊的深网环境中参与到普通现实社会的阴暗面？
