### ISSUE TITLE
获取用户所有视频的接口

### ISSUE THREAD

**Issue by AronWater** [SocialSisterYi/bilibili-API-collect#125]
space.bilibili.com/ajax/member/getSubmitVideos 这个已经下线了

请问有返回一个用户所有视频 的接口吗

**Comment by AronWater** [comment]
估计这个是
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/space.md#%E6%9F%A5%E8%AF%A2%E7%94%A8%E6%88%B7%E9%A2%91%E9%81%93%E4%B8%AD%E7%9A%84%E8%A7%86%E9%A2%91

**Comment by SocialSisterYi** [comment]
是查询用户投稿明细，而不是用户频道列表https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/space.md#%E6%9F%A5%E8%AF%A2%E7%94%A8%E6%88%B7%E6%8A%95%E7%A8%BF%E8%A7%86%E9%A2%91%E6%98%8E%E7%BB%86
