### ISSUE TITLE
什么时候要传入cookie SESSDATA

### ISSUE THREAD

**Issue by sunset1234321** [SocialSisterYi/bilibili-API-collect#126]
我想请教一下 
1. 这些接口 什么时候该传入 SESSDATA？
2. 一些本来不需要传也能获取数据的借口， 如果硬要传SESSDATA进去 会不会使quota增多？（  比如本来不传的话 每秒让你请求10次， 传了之后每秒可以请求100次等等）

**Comment by SocialSisterYi** [comment]
1.需要登录的接口，比如查看个人数据或者发送数据的，有些不强制登录的接口（比如评论区列表）登录之后会展示对于当前用户的特定信息（比如评论区排序以及点赞过哪条评论）
2.对，登录之后请求很多接口不容易被ban，但起作用的不是`SESSDATA`而是`sid`
