### ISSUE TITLE
发现少了一个重要的api

### ISSUE THREAD

**Issue by shoyu3** [SocialSisterYi/bilibili-API-collect#127]
https://api.bilibili.com/x/space/upstat?mid=UID
需要登录，可以获取到up主的视频总播放量，获赞数和阅读量，对统计很有用

**Comment by SocialSisterYi** [comment]
这个接口早都有了https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/status_number.md#UP%E4%B8%BB%E7%8A%B6%E6%80%81%E6%95%B0
