### ISSUE TITLE
？我提的issue选择性忽略？？

### ISSUE THREAD

**Issue by shoyu3** [SocialSisterYi/bilibili-API-collect#131]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/128

**Comment by SocialSisterYi** [comment]
本人高三，空闲时间太少，请理解

**Comment by ProgramRipper** [comment]
期末考大家都要考的啊，况且5天内连个周末都没等到，就算易姐没因为疫情被封学校里，也回答不了你啊。😓

**Comment by RigoLigoRLC** [comment]
李姐下，开源作者们都不容易。现在owner是高三。

**Comment by shoyu3** [comment]
那我没啥说的了，随你们便，反正我知道就行，谁管别人啊对吧

**Comment by TinyMaD** [comment]
我寻思这也不是收费项目，哪儿来的理直气壮？真把自己当个东西了
