### ISSUE TITLE
添加api

### ISSUE THREAD

**Issue by xiaowine** [SocialSisterYi/bilibili-API-collect#134]
不知道这里面有没有这个api
http://api.bilibili.com/x/web-show/res/loc?pf=0&id=34&_=1482805802383
主页推荐模块的

**Comment by SocialSisterYi** [comment]
收到，感谢提供！

**Comment by xiaowine** [comment]
> 收到，感谢提供！

这个api会添加到哪个分类

**Comment by SocialSisterYi** [comment]
> > 收到，感谢提供！
> 
> 这个api会添加到哪个分类

「web小组件」分类
