### ISSUE TITLE
live info中获取直播间主要信息的apifanhui-412并被拦截

### ISSUE THREAD

**Issue by LingkongSky** [SocialSisterYi/bilibili-API-collect#135]
curl -G 'http://api.live.bilibili.com/room/v1/Room/getRoomInfoOld' \
--data-urlencode 'mid=322892'
返回值
{"code":-412,"message":"请求被拦截","ttl":1,"data":null}

**Comment by SocialSisterYi** [comment]
> curl -G 'http://api.live.bilibili.com/room/v1/Room/getRoomInfoOld'
> --data-urlencode 'mid=322892'
> 返回值
> {"code":-412,"message":"请求被拦截","ttl":1,"data":null}

这个接口已经不常用，在【web端个人信息】接口中已经包含了这个接口返回的全部，如果必需用这个接口，就要保证cookie中DedeUserID字段存在且值不为0
