### ISSUE TITLE
视频选集api问题

### ISSUE THREAD

**Issue by AronWater** [SocialSisterYi/bilibili-API-collect#136]
例子： https://www.bilibili.com/video/BV1hs411C7wA

一个bvid 可能有很多集

请问怎么获取每个选集的信息？

**Comment by SocialSisterYi** [comment]
可以用查询视频分P信息api查询https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/info.md#%E6%9F%A5%E8%AF%A2%E8%A7%86%E9%A2%91%E5%88%86P%E5%88%97%E8%A1%A8
