### ISSUE TITLE
部分通过api获取到的直播源地址无法使用

### ISSUE THREAD

**Issue by LingkongSky** [SocialSisterYi/bilibili-API-collect#138]
据抓包方法得到的另一直播间的源地址:
https://cn-jxnc-cmcc-live-01.bilivideo.com/live-bvc/730840/live_1590370_4064847_1500.m3u8
(可用)
在另一正在直播的直播间中，在通过以下请求后，获取到返回json
curl -G -s 'http://api.live.bilibili.com/room/v1/Room/playUrl' \
--data-urlencode "cid=${cid}" \
--data-urlencode 'qn=10000' \
--data-urlencode 'platform=h5'
并从返回json中提取第一个durl的数值，得到
http://d1--cn-gotcha105.bilivideo.com/live-bvc/616763/live_14892034_6072323.m3u8?cdn=cn-gotcha05&expires=1611495037&len=0&oi=147989512&pt=h5&qn=10000&trid=b29ac4bcb69f4dd887b1ed626ab1cabe&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=8730a7a412c8d504b3acfc84d93e8c7c&ptype=0&src=4&sl=1&order=1
但该链接无法使用，返回为403
再次剔除多余信息
http://d1--cn-gotcha105.bilivideo.com/live-bvc/616763/live_14892034_6072323.m3u8
依旧无法使用，403
求为何据该api提取到的链接无法使用

**Comment by duzhaokun123** [comment]
可能是没有加ua

**Comment by LingkongSky** [comment]
但是似乎有一部分链接是有效的

**Comment by SocialSisterYi** [comment]
UA必须要有，Referer不确定
