### ISSUE TITLE
实测：粉丝列表最多获取前1000位

### ISSUE THREAD

**Issue by 1452206376** [SocialSisterYi/bilibili-API-collect#139]
![批注 2021-01-24 230536](https://user-images.githubusercontent.com/42541633/105634414-cea6a600-5e98-11eb-9b92-bc81beb392ea.jpg)
![批注 2021-01-24 230537](https://user-images.githubusercontent.com/42541633/105634416-cfd7d300-5e98-11eb-9b21-0fed6cb33e4d.jpg)
如上图
20*50=1000
再多就没了
也有可能是我调用次数过多被封了

**Comment by 1452206376** [comment]
问客服了，确实只能看前1000
![Uploading Screenshot_20210124-231658765.jpg…]()

**Comment by SocialSisterYi** [comment]
是的，别人的粉丝与关注限制最多拉取5页，默认每页20项，但最多只能50项

**Comment by 1452206376** [comment]
刚去问了问，确实只能看前1000
![Screenshot_20210124-231658765](https://user-images.githubusercontent.com/42541633/105634756-a9b33280-5e9a-11eb-965e-d2e4cc5aa292.jpg)

**Comment by 1452206376** [comment]
> 是的，别人的粉丝与关注限制最多拉取5页，默认每页20项，但最多只能50项

可以修改一下表格备注

**Comment by SocialSisterYi** [comment]
自己的粉丝也不能全部拉取，在第20页就会返回一个空列表，这是2年前为了防止爬虫爬用户关系网而特地设置的限制
比如何同学的粉丝墙，是直接向B站后台要的导出数据

**Comment by SocialSisterYi** [comment]
> > 是的，别人的粉丝与关注限制最多拉取5页，默认每页20项，但最多只能50项
> 
> 可以修改一下表格备注

好的
