### ISSUE TITLE
帐号密码登录 "message":"rsa解密失败","code":86000

### ISSUE THREAD

**Issue by ouuan** [SocialSisterYi/bilibili-API-collect#140]
我 [自己试图实现](https://github.com/ouuan/bilibili-login) [帐号密码登录](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/password.md) 的时候，每次返回的结果都是 `{"ts":1611653296,"message":"rsa解密失败","code":86000}` 这样的。

虽然不知道能不能在这问返回这个是哪搞错了，但文档里没有这个返回代码，所以还是在这开个 issue。

**Comment by mufeng233** [comment]
请问大佬解决了吗，我也遇到了相同的情况....
