### ISSUE TITLE
/x/space/acc/info 接口内容待补充

### ISSUE THREAD

**Issue by MineCreeper86** [SocialSisterYi/bilibili-API-collect#141]
[data.sys_notice](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/info.md#%E7%94%A8%E6%88%B7%E8%AF%A6%E7%BB%86%E4%BF%A1%E6%81%AF1-%E7%94%A8%E4%BA%8E%E7%A9%BA%E9%97%B4)对象缺少：
**notice_type icon text_color bg_color**字段说明

举例：
http://api.bilibili.com/x/space/acc/info?mid=212535360
的返回_（逝者安息）_为

sys_notice: {
id: 20
content: "请允许我们在此献上最后的告别，以此纪念其在哔哩哔哩留下的回忆与足迹。请点此查看纪念账号相关说明>"
url: "https://www.bilibili.com/blackboard/help.html#/?qid=fb37c62ca61f4f10b8d17f3dc9051603"
**notice_type**: 2
**icon**: "https://i0.hdslb.com/bfs/space/ca6d0ed2edae23cf348db19cd2c293f2121c1b59.png"
**text_color**: "#999999"
**bg_color**: "#e7e7e7"
}

**Comment by SocialSisterYi** [comment]
收到

**Comment by SocialSisterYi** [comment]
已添加`纪念账号`相关字段
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/info.md#%E7%94%A8%E6%88%B7%E8%AF%A6%E7%BB%86%E4%BF%A1%E6%81%AF1-%E7%94%A8%E4%BA%8E%E7%A9%BA%E9%97%B4
