### ISSUE TITLE
SESSIONID 如何获得

### ISSUE THREAD

**Issue by 838239178** [SocialSisterYi/bilibili-API-collect#144]
我在抓包过程中找不到带有SESSIONID的response，但是request上却带有SEESSIONID，和SESSDATA一样吗😓

**Comment by 838239178** [comment]
我抓的是 ios app 的包

**Comment by daofeng2015** [comment]
> 我抓的是 ios app 的包

在刚登录完成后给的cookie

**Comment by 838239178** [comment]
> > 我抓的是 ios app 的包
> 
> 在刚登录完成后给的cookie

登陆前就已经有sessionid了

**Comment by MineCreeper86** [comment]
> > 我抓的是 ios app 的包
> 
> 在刚登录完成后给的cookie

不一样吧

**Comment by MineCreeper86** [comment]
> > > 我抓的是 ios app 的包
> > 
> > 
> > 在刚登录完成后给的cookie
> 
> 登陆前就已经有sessionid了

sessdata是有一个格式的（十六进制数字），你看看sessionid格式和sessdata一样不

**Comment by 838239178** [comment]
> > > > 我抓的是 ios app 的包
> > > 
> > > 
> > > 在刚登录完成后给的cookie
> > 
> > 
> > 登陆前就已经有sessionid了
> 
> sessdata是有一个格式的（十六进制数字），你看看sessionid格式和sessdata一样不

两个是不同格式，sessdata是三个16段16进制，sessionid只有一段[图片](https://share.icloud.com/photos/0AnqGZY9Tgdh0It1IxOv8w9Hw)

**Comment by SocialSisterYi** [comment]
app端登录成功后会已json格式的形式返回app访问token `access_key`以及`SESSDATA`、`bili_jct`等等cookie字段内容
但web端登录后只会用set-cookie的方式添加cookie

**Comment by Blck4** [comment]
> Ow

大佬，小程序得ck是session很短，怎么转成sessdata啊。
