### ISSUE TITLE
protobuf弹幕python实例的注意事项

### ISSUE THREAD

**Issue by leiurayer** [SocialSisterYi/bilibili-API-collect#145]
protobuf弹幕的python例子中请求api没有添加header，得到的第0条弹幕是“我炮还能再战500年！！！我炮还能再战500年！！！我炮还能再战500年！！！我炮还能再战500年”。

在这个例子中，我测试发现不添加header请求api时，下载的proto文件大小是1150KB，第0条弹幕和python例子的结果相同；添加了referer和origin以后（均为"https://www.bilibili.com" ），下载的proto文件大小为1172KB，并且第0条弹幕为“世界第一电击公主殿下,遇到你是我一生最美好的风景!吾炮赛高,永生不离!唯我超电磁炮永世长存!”
从结果可知，获取完整的protobuf弹幕必须在请求api时添加header，否则会丢失一部分弹幕信息。

问题实例：https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/danmaku/danmaku_proto.md#%E5%AE%9E%E4%BE%8B
测试API为：http://api.bilibili.com/x/v2/dm/web/seg.so

**Comment by SocialSisterYi** [comment]
感谢提供

**Comment by SocialSisterYi** [comment]
该 feature 似乎已经不存在了，测试了不同的视频弹幕，加与不加`referer`、`origin`头部返回结果一致，但新增了几个新的字段`ps`、`pe`、`pull_mode`、`from_scene`，作用尚不明确

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/45892418/fcdb4b2c-ffde-447b-9dc3-0f1235d020b4)

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/45892418/5d0ddec4-1400-46ff-8dfa-401bb9964dee)
