### ISSUE TITLE
无法获取历史弹幕

### ISSUE THREAD

**Issue by HashLiver** [SocialSisterYi/bilibili-API-collect#147]
我按照[文档所述](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/danmaku/history.md#%E8%8E%B7%E5%8F%96%E5%8E%86%E5%8F%B2%E5%BC%B9%E5%B9%95)却无法获取历史弹幕。

例如：https://api.bilibili.com/x/v2/dm/history?type=1&oid=291407447&date=2020-02-02
返回结果：
```json
<i>
  <chatserver>chat.bilibili.com</chatserver>
  <chatid>291407447</chatid>
  <mission>0</mission>
  <maxlimit>8000</maxlimit>
  <state>2</state>
  <text>本视频弹幕功能已被关闭</text>
  <text_side>本视频弹幕功能已被关闭</text_side>
</i>
```
一致提示：**本视频弹幕功能已被关闭**

**Comment by SocialSisterYi** [comment]
现在历史弹幕的数据格式也改成protobuf了，原来的xml格式接口失效

**Comment by zjkwdy** [comment]
https://api.bilibili.com/x/v2/dm/web/history/seg.so?type=1&oid={cid}&date={date}
protobuf历史弹幕接口，是二进制数据需要自己解码，参考
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/danmaku/danmaku_proto.md

**Comment by HashLiver** [comment]
> [https://api.bilibili.com/x/v2/dm/web/history/seg.so?type=1&oid={cid}&date={date}](https://api.bilibili.com/x/v2/dm/web/history/seg.so?type=1&oid=%7Bcid%7D&date=%7Bdate%7D)

![unname01](https://user-images.githubusercontent.com/42889797/107842881-86c4d000-6e01-11eb-9c47-672a6448dc9c.png)

确实如此，貌似网络上也没个protobuf转ass工具。

**Comment by duzhaokun123** [comment]
@HashLiver 又不是什么标准格式，自己转

**Comment by SocialSisterYi** [comment]
protobuf历史弹幕接口已添加，数据结构同`protobuf实时弹幕`
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/danmaku/history.md#%E8%8E%B7%E5%8F%96%E5%8E%86%E5%8F%B2%E5%BC%B9%E5%B9%95protobuf%E6%8E%A5%E5%8F%A3
