### ISSUE TITLE
这是啥情况，TV端的登录

### ISSUE THREAD

**Issue by 1665169869** [SocialSisterYi/bilibili-API-collect#148]
![image](https://user-images.githubusercontent.com/50762038/107004862-d1ea3d80-6786-11eb-8671-e15f093374e1.png)
如图

**Comment by 1665169869** [comment]
搞定了，此贴终结
![image](https://user-images.githubusercontent.com/50762038/107017877-a459c000-6797-11eb-9a9a-651386029e2f.png)

**Comment by zhongfly** [comment]
> 搞定了，此贴终结
> ![image](https://user-images.githubusercontent.com/50762038/107017877-a459c000-6797-11eb-9a9a-651386029e2f.png)

问题解决了，选择Close Issue即可关闭issue。这里不是贴吧，需要说“此帖终结”
![Screenshot_20210212125715](https://user-images.githubusercontent.com/11155705/107731846-e5227d80-6d31-11eb-8f22-151f6b8b6554.png)

**Comment by 1665169869** [comment]
了解
