### ISSUE TITLE
视频撞车了

### ISSUE THREAD

**Issue by ASC8384** [SocialSisterYi/bilibili-API-collect#149]
视频 `BV1S4411x7Te`
显示视频撞车了，貌似 code 是 `-200`

**Comment by SocialSisterYi** [comment]
相关字段已添加
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/info.md#%E8%8E%B7%E5%8F%96%E8%A7%86%E9%A2%91%E8%AF%A6%E7%BB%86%E4%BF%A1%E6%81%AFweb%E7%AB%AF
