### ISSUE TITLE
收藏夹相关

### ISSUE THREAD

**Issue by AnzhiZhang** [SocialSisterYi/bilibili-API-collect#15]
收藏夹基本信息 <https://api.bilibili.com/x/v3/fav/folder/info?media_id=123>
收藏夹视频id列表 <https://api.bilibili.com/x/v3/fav/resource/ids?media_id=123>
收藏夹列表详细信息 <https://api.bilibili.com/x/v3/fav/resource/infos?resources=> （resources参数不明）

没有看到建好的文件夹或文件，就发了issue，能否提供一下以上内容应当放在哪个文件，我会将其写出来

**Comment by zhang-anzhi** [comment]
以上皆为视频收藏夹，没有看到专栏/相簿/课程收藏夹有可以展示的链接

**Comment by FlySelfLog** [comment]
补充几个收藏夹相关api：

创建的收藏夹：
https://api.bilibili.com/x/v3/fav/folder/created/list?pn=1&ps=10&up_mid=123
https://api.bilibili.com/x/v3/fav/folder/created/list-all?up_mid=123
收藏的收藏夹：
https://api.bilibili.com/x/v3/fav/folder/collected/list?pn=1&ps=20&up_mid=456

获取某一个收藏夹的内容：
其中，media_id为上述api获取的json中list中的id，pn为页码，ps为本次获取的视频数，keyword为搜索关键词，order为排序依据，type为视频分区id，tid不清楚
https://api.bilibili.com/x/v3/fav/resource/list?media_id=123&pn=1&ps=20&keyword=&order=mtime&type=0&tid=0

**Comment by CKylinMC** [comment]
> 收藏夹视频id列表 https://api.bilibili.com/x/v3/fav/resource/ids?media_id=123

实测这个API一次最多返回1000条数据，但是支持pn参数翻页。
