### ISSUE TITLE
是否观看过该视频

### ISSUE THREAD

**Issue by SwetyCore** [SocialSisterYi/bilibili-API-collect#151]
能找到判断是否观看过某一视频的Api嘛?

**Comment by duzhaokun123** [comment]
移动端API
`https://app.bilibili.com/x/v2/view`
移动端标准参数再加上`aid=$aid`或`bvid=$bvid`
`view.data.history != null`一定看过，但反之不一定

**Comment by SocialSisterYi** [comment]
现在gRPC的视频View API中也存在这个字段
