### ISSUE TITLE
关于gRPC接口

### ISSUE THREAD

**Issue by duzhaokun123** [SocialSisterYi/bilibili-API-collect#152]
里面的注释说是`app.bilibili.com`可我抓到的是`grpc.biliapi.net`

**Comment by SocialSisterYi** [comment]
那个是cname，其实两个都可以用的

**Comment by duzhaokun123** [comment]
此外方法定义的方法名应该都是大写开头
否则返回类似
```
grpc-status: 12
grpc-message: unknown method view for service bilibili.app.view.v1.View
```

**Comment by SocialSisterYi** [comment]
> 此外方法定义的方法名应该都是大写开头
> 否则返回类似
> ```
> grpc-status: 12
> grpc-message: unknown method view for service bilibili.app.view.v1.View
> ```

好的，下次更新时修改
