### ISSUE TITLE
为啥会显示-412

### ISSUE THREAD

**Issue by kebufu** [SocialSisterYi/bilibili-API-collect#153]
![QQ截图20210207131738](https://user-images.githubusercontent.com/31839741/107137385-ec6b1500-6946-11eb-9470-a1373e3040ca.png)

**Comment by kebufu** [comment]
找到了，要填入csrf才行

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/117543956-b1fe3a80-b051-11eb-97a8-3d8860cf65ad.png)

**Comment by Z-fly** [comment]
@kebufu 我最近一直校验失败，是什么原因
