### ISSUE TITLE
查询收藏夹的内容api

### ISSUE THREAD

**Issue by FlySelfLog** [SocialSisterYi/bilibili-API-collect#156]
我没看到收录了这个查询收藏夹内容的api，如果已经有了的话就关闭这个issue吧

https://api.bilibili.com/x/v3/fav/resource/ids?media_id=1114814240&platform=web

**Comment by SocialSisterYi** [comment]
确实没有，谢谢提供

**Comment by FlySelfLog** [comment]
再补充一个查询收藏夹内容的api，这个是在https://space.bilibili.com/{mid}/favlist网址下抓取到的
https://api.bilibili.com/x/v3/fav/resource/list?media_id={mediaId}&ps={number}&pn=1

另外还有，查询用户创建的收藏夹，这个api返回的信息比list-all那个更多一些
https://api.bilibili.com/x/v3/fav/folder/created/list?up_mid={mid}&ps={number}&pn=1

**Comment by SocialSisterYi** [comment]
这些已经有啦~
