### ISSUE TITLE
[视频基本信息]api的回复json中，data对象下有新的项"ugc_season"

### ISSUE THREAD

**Issue by HashLiver** [SocialSisterYi/bilibili-API-collect#157]
例子1：https://api.bilibili.com/x/web-interface/view?bvid=BV1Do4y1d7K7
例子2：https://api.bilibili.com/x/web-interface/view?bvid=BV1Uv4y1o7Ax

**Comment by SocialSisterYi** [comment]
谢谢提供，下次更新时添加
