### ISSUE TITLE
下载视频还有方式

### ISSUE THREAD

**Issue by xiaowine** [SocialSisterYi/bilibili-API-collect#163]
根据这个项目['https://github.com/Henryhaohao/Bilibili_video_download/blob/master/bilibili_video_download_v1.py'] 的第一个函数可以发现app端还有视频下载方式

**Comment by xiaowine** [comment]
这种方式不需要cookie

**Comment by HashLiver** [comment]
很早就有的app api了，甚至url都没有https。著名的youtube-dl里面下载B站视频的提取器[用的也是这个](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/bilibili.py#L171)。

例如：https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=300393758&otype=json&qn=80&sign=1f74ecb28236372987135fd6c945a826
<details>
<summary>cid300393758的响应Json：</summary>

```json
{
	"from": "local",
	"result": "suee",
	"quality": 80,
	"format": "flv",
	"timelength": 2457401,
	"accept_format": "flv_p60,flv720_p60,flv,flv480,mp4",
	"accept_description": [
		"高清 1080P60",
		"高清 720P60",
		"高清 1080P",
		"清晰 480P",
		"流畅 360P"
	],
	"accept_quality": [
		116,
		74,
		80,
		32,
		16
	],
	"video_codecid": 7,
	"video_project": true,
	"seek_param": "start",
	"seek_type": "offset",
	"durl": [
		{
			"order": 1,
			"length": 2457401,
			"size": 453091986,
			"url": "http://upos-sz-mirrorhw.bilivideo.com/upgcxcode/58/37/300393758/300393758-1-80.flv?e=ig8euxZM2rNcNbKjhwdVhoMM7bdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1613915196&gen=playurl&nbs=1&oi=1996394852&os=hwbv&platform=pc&trid=89ab152dae654ae8850f4b55b92aeadc&uipk=5&upsig=7da3380b97462085c001c4732feac21c&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0"
		}
	]
}
```
</details>

除了已知的`https://interface.bilibili.com/v2/playurl`，还有`https://app.bilibili.com/v2/playurlproj`，能下载原生mp4格式，似乎只能下载1080P。

例如：https://app.bilibili.com/v2/playurlproj?appkey=iVGUTjsxvpLeuDCf&cid=300393758&otype=json&qn=208&sign=2e3f230ace1d7000fd8f8a9bd7388017
<details>
<summary>cid300393758的响应Json：</summary>

```json
{
	"from": "local",
	"result": "suee",
	"quality": 208,
	"format": "mp4",
	"timelength": 2457323,
	"accept_format": "mp4",
	"accept_description": [
		"高清 1080P"
	],
	"accept_quality": [
		208
	],
	"video_codecid": 7,
	"video_project": false,
	"seek_param": "start",
	"seek_type": "second",
	"durl": [
		{
			"order": 1,
			"length": 2457323,
			"size": 452750740,
			"url": "http://upos-sz-mirrorcos.bilivideo.com/upgcxcode/58/37/300393758/300393758-1-208.mp4?e=ig8euxZM2rNcNbR37wdVhwdlhW4MhwdVhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&ua=tvproj&deadline=1613915203&gen=playurl&nbs=1&oi=1996394852&os=cosbv&trid=c12e79ff1ae04c45b6c8d82096ebe977&uipk=5&upsig=4f518faedabdb7f46ea80a54bc5dc351&uparams=e,ua,deadline,gen,nbs,oi,os,trid,uipk&mid=0"
		}
	]
}
```

</details>

**Comment by PdA1337** [comment]
> 很早就有的app api了，返回的url甚至都没有https。著名的youtube-dl里面下载B站视频的提取器[用的也是这个](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/bilibili.py#L171)。
> 
> 例如：https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=300393758&otype=json&qn=80&sign=1f74ecb28236372987135fd6c945a826
> 
> cid300393758的响应Json：
> 除了已知的`https://interface.bilibili.com/v2/playurl`，还有`https://app.bilibili.com/v2/playurlproj`，能下载原生mp4格式，似乎只能下载1080P。
> 
> 例如：https://app.bilibili.com/v2/playurlproj?appkey=iVGUTjsxvpLeuDCf&cid=300393758&otype=json&qn=208&sign=2e3f230ace1d7000fd8f8a9bd7388017
> 
> cid300393758的响应Json：

可以请教一下第一个接口的sign是如何计算的吗 按照文档中的方法计算出的sign值是错误的啊

万分感谢！
