### ISSUE TITLE
如何查询番剧是否付费/免费/限时免费

### ISSUE THREAD

**Issue by 1299172402** [SocialSisterYi/bilibili-API-collect#164]
仅仅番剧信息里的badge只能显示 限时免费/独家/会员抢先/会员专享 这几个

所以我想问下有没有哪里的信息可以显示 免费/限时免费/会员/付费观看 这类的信息（仅仅考虑已经完结的番剧）

**Comment by HashLiver** [comment]
可以从单个剧集看，`.result.episodes.status`的数值`2`就是免费，`13`就是会员。

**Comment by 1299172402** [comment]
感谢 @HashLiver
