### ISSUE TITLE
有个接口已被修改

### ISSUE THREAD

**Issue by 1665169869** [SocialSisterYi/bilibili-API-collect#167]
这个：https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_notice.md
![image](https://user-images.githubusercontent.com/50762038/110214893-c1da9080-7ee1-11eb-8133-d5ce58b2877d.png)

现在查询登录记录需要设置SESSDATA，否则如图

**Comment by SocialSisterYi** [comment]
收到

**Comment by SocialSisterYi** [comment]
已经修改https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_notice.md
