### ISSUE TITLE
风纪委众裁相关api

### ISSUE THREAD

**Issue by zhang-anzhi** [SocialSisterYi/bilibili-API-collect#17]
需要SESSDATA

发送投票(POST)
<https://api.bilibili.com/x/credit/jury/vote>
参数：
cid=案件id
vote=投票类型(1:封禁，2:否，3:弃权，4:删除)
attr=1     (没看懂, 疑似可选
csrf=csrf
apply_type=     (可选
origin_reason=   (可选
apply_reason=   (可选
以上三个疑似为理由
返回值：
code: 0
message: "0"
ttl: 1
![image](https://user-images.githubusercontent.com/37402126/87105780-7c9c8b00-c28e-11ea-90e2-6b33b026297f.png)

获取案件(POST)
<https://api.bilibili.com/x/credit/jury/caseObtain>
参数:
csrf=csrf
返回值:
code: 0,    25008(众裁处理完), 25014(今日数量已满)
data: {"id": 案件id}
message: "0"
ttl: 1
![image](https://user-images.githubusercontent.com/37402126/87105886-b9688200-c28e-11ea-85d2-f3b79822b83b.png)

我已成功用以上两个api众裁一个案件
![image](https://user-images.githubusercontent.com/37402126/87105717-5676eb00-c28e-11ea-9e9a-66aba6bb6ba1.png)

**Comment by zhang-anzhi** [comment]
能否告诉我这些内容应该写在哪个文件？我写好发PR

**Comment by zhang-anzhi** [comment]
我的案件列表(GET)
<https://api.bilibili.com/x/credit/jury/caseList>
参数pn, ps
ps最大30
pn不限（翻到你案件没了为止）

**Comment by zhang-anzhi** [comment]
历史每月统计（GET）
需要SESSDATA
<https://api.bilibili.com/x/credit/jury/kpi>
参数无

**Comment by zhang-anzhi** [comment]
风纪委基本数据(GET)
需要SESSDATA
<https://api.bilibili.com/x/credit/jury/jury>
无参数
返回值：
code, ttl, message
data: {
    "caseTotal": 案件总数,
    "face": "头像url",
    "restDays": 剩余天数,
    "rightRadio": 尚不明确,
    "status": 1,
    "uname": "昵称"
}

**Comment by zhang-anzhi** [comment]
#19

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/117543889-5469ee00-b051-11eb-98c0-4e044b693628.png)

**Comment by Z-fly** [comment]
最近一直提示我csrf校验失败
