### ISSUE TITLE
直播签到

### ISSUE THREAD

**Issue by xiaowine** [SocialSisterYi/bilibili-API-collect#170]
readme没有找到直播间的签到 API，是故意不加还是忘记了
api地址 https://api.live.bilibili.com/xlive/web-ucenter/v1/sign/DoSign'

**Comment by xiaowine** [comment]
不知道这个api有没有收集

**Comment by SocialSisterYi** [comment]
是忘了，主要还是没来得及怎么研究直播间相关的api，这个客户端和web端是一样的吗？

**Comment by xiaowine** [comment]
> 是忘了，主要还是没来得及怎么研究直播间相关的api，这个客户端和web端是一样的吗？

这是web的，客户端的不知道

**Comment by xiaowine** [comment]
https://api.live.bilibili.com/xlive/revenue/v1/wallet/silver2coin
同样的web端签到的api，bili换了，不过原来的还能用。
同样是post，参数只需csrf
