### ISSUE TITLE
No module named 'bilibili' 

### ISSUE THREAD

**Issue by Luffffffy** [SocialSisterYi/bilibili-API-collect#175]
你好，我想知道这是python代码示例吗？
我得到No module named 'bilibili' 的提示
我应该怎样安装它呢
![image](https://user-images.githubusercontent.com/49063302/113085355-3c14e100-9212-11eb-874e-84a0e3b35a5e.png)

**Comment by SocialSisterYi** [comment]
从/grpc_api那个目录里添加，需要编译protobuf

**Comment by lb-chc** [comment]
> 你好，我想 知道python代码示例吗？ ![图片](https://user-images.githubusercontent.com/49063302/113085355-3c14e100-9212-11eb-874e-84a0e3b35a5e.png)

#345 

你可以使用这个工具方便的获得这个文件
