### ISSUE TITLE
申请二维码URL及扫码密钥（web端），关于验证码的生成

### ISSUE THREAD

**Issue by ZY1000-7** [SocialSisterYi/bilibili-API-collect#178]
用户通过GET请求访问：`http://passport.bilibili.com/qrcode/getLoginUrl`
返回的data字段中的url，不是验证码图片地址。需要使用QRCode.js将url转换为base64的验证码图片进行验证
```
t.refer.makeCode(i.data.url)) : t.$nextTick(function() {
    t.refer = new QRCode(t.$refs.qrcode,{
        text: i.data.url,
        width: 140,
        height: 140
    })
}),
```
i为`http://passport.bilibili.com/qrcode/getLoginUrl`请求返回的对象。如下图。
![image](https://user-images.githubusercontent.com/52960278/114273139-9b14fa00-9a4b-11eb-9cce-ecb15530978f.png)

**Comment by FooderLeoYo** [comment]
题主好！我尝试密码登录的时候一直返回2400，不管我怎么改key的拼接方式。不知是否方便抽空稍加指点一下，不胜感激/(ㄒoㄒ)/。本人WX/QQ：1530092839

**Comment by leejoker** [comment]
@ZY1000-7 

原文里写的是
> 用申请到的data.url中的值生成二维码，等待手机客户端扫描，并将data.oauthKey保存等待使用

所以是没啥问题的~
