### ISSUE TITLE
大佬，获取到的 flv 视频url，如何绕过防盗链呢，具体有demo吗

### ISSUE THREAD

**Issue by 251205668** [SocialSisterYi/bilibili-API-collect#179]

**Comment by ProgramRipper** [comment]
> 需要验证请求Header中referer为 .bilibili.com域名下（防盗链）
且user-agent 不为空 （否则会403)

例如：
referer=`https://www.bilibili.com`
user-agent=`随便是什么都行`

**Comment by kebufu** [comment]
用cloudfare的worker吧

**Comment by RikaShiro** [comment]
> 

demo链接失效了 可以补一下吗？
