### ISSUE TITLE
官方似乎放出 gRPC 相关接口文档

### ISSUE THREAD

**Issue by duzhaokun123** [SocialSisterYi/bilibili-API-collect#189]
就在官方应用apk里包着`bilibili`下，还带文档和注释

**Comment by zjkwdy** [comment]
还真有，草了

**Comment by ProgramRipper** [comment]
草，不止bilibili自己的proto，在`test`中还有测试的用的，除此之外还有`github.com`、`google`的一些proto依赖。
我有充足理由怀疑他们把gitignore写错了😄

**Comment by SocialSisterYi** [comment]
就是V6.23.5版本的包里

**Comment by SocialSisterYi** [comment]
这个“漏洞”已经提交给了哔哩哔哩安全应急响应中心

**Comment by FlySelfLog** [comment]
今天去解包看了看，确实存在，B站发现这个漏洞后是否有可能全面修改protocol接口？

**Comment by ProgramRipper** [comment]
> 今天去解包看了看，确实存在，B站发现这个漏洞后是否有可能全面修改protocol接口？

不大可能，如果全面修改API，会涉及所有App端以及服务端的重构，工程量太大。况且，鉴于2019年的那一次后端源码泄露后，b站都没有改动API。所以这次，估计b站也不会有大动作。

**Comment by kebufu** [comment]
6.24.0已经没了

**Comment by SocialSisterYi** [comment]
> 6.24.0已经没了

对，现在的6.25同样没有
