### ISSUE TITLE
CSRF Token 校验问题

### ISSUE THREAD

**Issue by Z-fly** [SocialSisterYi/bilibili-API-collect#190]
现在模拟操作性接口时，提示CSRF校验失败

**Comment by SocialSisterYi** [comment]
确保Cookie中的`bili_jct`存在且与csrf一致

**Comment by Z-fly** [comment]
> 确保Cookie中的`bili_jct`存在且与csrf一致

已确认bili_jct存在的且与csrf一致
使用的是 https://gist.github.com/Z-fly/5debfe9aa96550c3be8aafd187e0ae70#file-jury-py
同个cookies，之前可以操作的，前不久不行了。
