### ISSUE TITLE
视频下载地址（Playurl）Web端API的鉴权方式貌似变了

### ISSUE THREAD

**Issue by HashLiver** [SocialSisterYi/bilibili-API-collect#194]
以前只需Cookie参数`SESSDATA`就行了，但现在就会返回code 412。
例如`curl -s "https://api.bilibili.com/x/player/playurl?avid=170001&cid=279786&qn=80&fnval=0&fourk=1" -b "SESSDATA=xxxxxx"`会返回：

```json
{
  "code": -412,
  "message": "请求被拦截",
  "ttl": 1,
  "data": null
}
```

尝试加上`api.bilibili.com`的Cookie参数`bfe_id`，问题就解决了：
`curl -s "https://api.bilibili.com/x/player/playurl?avid=170001&cid=279786&qn=80&fnval=0&fourk=1" -b "SESSDATA=xxxxxx;bfe_id=xxxxxx"`

不知道还有没有其它更好的办法。

**Comment by duzhaokun123** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/videostream_url.md#%E8%A7%86%E9%A2%91%E6%B5%81url

| 80 1080P 高清（登录）

很明显需要登录才能获取
换低分辨率或缺省

**Comment by HashLiver** [comment]
@duzhaokun123 看清楚主楼，SESSDATA就是登录用的Cookie。

**Comment by duzhaokun123** [comment]
`bfe_id`是什么, 哪来的

**Comment by HashLiver** [comment]
> `bfe_id`是什么, 哪来的

![bfe_id](https://user-images.githubusercontent.com/42889797/118632865-7149b280-b803-11eb-8713-5b9590ba38b1.png)

**Comment by HashLiver** [comment]
貌似今天又恢复正常了，我记得我也没对API频繁请求过（可能这个月都还没50次），B站这一套风控系统很迷。
