### ISSUE TITLE
查询用户关注明细order_type的可用参数错误

### ISSUE THREAD

**Issue by odysseus0** [SocialSisterYi/bilibili-API-collect#202]
order_type | str | 排序方式 | 非必要 | 按照关注顺序排列：留空 按照最常访问排列：attention
-- | -- | -- | -- | --

经测试，
- 留空时order_type会在两种方式中随机切换，并不会一直按照关注顺序排列。
  - 不会每一次请求都会切换，但是如果在一段时间内大量重复请求，会发现有两种不一样的排列顺序。
  - http://api.bilibili.com/x/relation/followings?vmid=9617619&ps=50&pn=1&order_type=
- `order_type=attention`会使request直接失败，不会返回任何数据。
  - http://api.bilibili.com/x/relation/followings?vmid=9617619&ps=50&pn=1&order_type=attention

**Comment by SocialSisterYi** [comment]
收到，谢谢勘误

**Comment by SocialSisterYi** [comment]
经过测试，这种bug是偶然情况，web端和app端js中的请求确实是这样写的
见[4.space.b56cc7b240ce794f463cff7a3229251624efc1ad.js](https://s1.hdslb.com/bfs/static/jinkela/space/4.space.b56cc7b240ce794f463cff7a3229251624efc1ad.js)格式化后的内容
![image](https://user-images.githubusercontent.com/45892418/130224788-92ffed61-ef48-4662-922d-2f820029856f.png)
