### ISSUE TITLE
直播人气是只要连上了信息流ws就算吗？

### ISSUE THREAD

**Issue by PdA1337** [SocialSisterYi/bilibili-API-collect#203]
rt

**Comment by stackinspector** [comment]
进场和tcp/ws信息流无关

**Comment by PdA1337** [comment]
> 进场和tcp/ws信息流无关

那是如何判断客户端离场的？

**Comment by duzhaokun123** [comment]
参考

https://github.com/czp3009/bilibili-api/blob/56f26e7106d03a9224cf12b8cfd056380ac6759e/src/main/kotlin/com/hiczp/bilibili/api/live/LiveAPI.kt#L23-L34

https://github.com/czp3009/bilibili-api/blob/56f26e7106d03a9224cf12b8cfd056380ac6759e/src/main/kotlin/com/hiczp/bilibili/api/live/LiveAPI.kt#L222-L232

**Comment by SocialSisterYi** [comment]
直播间人气值就是心跳包的回复值

**Comment by SocialSisterYi** [comment]
> > 进场和tcp/ws信息流无关
> 
> 那是如何判断客户端离场的？

进场有个独立的专门上报api

**Comment by PdA1337** [comment]
> 参考
> 
> https://github.com/czp3009/bilibili-api/blob/56f26e7106d03a9224cf12b8cfd056380ac6759e/src/main/kotlin/com/hiczp/bilibili/api/live/LiveAPI.kt#L23-L34
> 
> https://github.com/czp3009/bilibili-api/blob/56f26e7106d03a9224cf12b8cfd056380ac6759e/src/main/kotlin/com/hiczp/bilibili/api/live/LiveAPI.kt#L222-L232

感谢，请问有相关web端的相关资料吗？

**Comment by PdA1337** [comment]
> 直播间人气值就是心跳包的回复值

我的意思是B站在收到客户端ws后直播间人气会+1吗

**Comment by SocialSisterYi** [comment]
> > 直播间人气值就是心跳包的回复值
> 
> 我的意思是B站在收到客户端ws后直播间人气会+1吗

准确的说，不会

**Comment by PdA1337** [comment]
> > > 直播间人气值就是心跳包的回复值
> > 
> > 
> > 我的意思是B站在收到客户端ws后直播间人气会+1吗
> 
> 准确的说，不会

那么网页端的人气是如何计算的呢 我抓包好像没有看到其他的可疑包啊

**Comment by SocialSisterYi** [comment]
> > > > 直播间人气值就是心跳包的回复值
> > > 
> > > 
> > > 我的意思是B站在收到客户端ws后直播间人气会+1吗
> > 
> > 
> > 准确的说，不会
> 
> 那么网页端的人气是如何计算的呢 我抓包好像没有看到其他的可疑包啊

不要忽略最大的请求：直播间的网页
这个也带登录后的Cookie

**Comment by a1443304527** [comment]
也想知道网页端得人气是如何计算的，网页端虽然也有一个心跳包，但是好像不是通过这个来算的
