### ISSUE TITLE
疑似发现新版attribute属性

### ISSUE THREAD

**Issue by daofeng2015** [SocialSisterYi/bilibili-API-collect#206]
在文件 app\archive\v1\archive.proto 中发现 attribute_v2 属性.是否为新的限流标志呢?

**Comment by SocialSisterYi** [comment]
太晚了太晚了，我观察这个值已经大半年，任何情况下都恒为0

**Comment by ProgramRipper** [comment]
> 太晚了太晚了，我观察这个值已经大半年，任何情况下都恒为0


![image](https://user-images.githubusercontent.com/45716046/123198461-bab2af00-d4df-11eb-8802-aa567c8a2a0f.png)
易姐，可以看看这个。
视频是`av201532371`，应该是`https://api.bilibili.com/x/tag/detail?pn=1&ps=40&tag_id=11444507`的第一个视频，我之前发过给你。
