### ISSUE TITLE
解析直播websocket数据出现大量协议为3的数据帧，无法zlib解压，疑似换压缩方法

### ISSUE THREAD

**Issue by HynemanKan** [SocialSisterYi/bilibili-API-collect#210]
帧头如下：
00 00 01 2b 00 10 00 03 00 00 00 05 00 00 00 00
数据帧base64
AAABKwAQAAMAAAAFAAAAABsvAgAsCuxYBhKz0kGcOoHBZZhOJ3lyZaoRFMYApZ8rtawhhpykQLi21C/UL8mSDnVDBpvlMRo6HVRE9WXwnF4PdiBcvpOuVRQleL1Z2WZjK0j6BbrcedNX9KiuyGOCCPvK88E9AY5y7H+IaytuuePgsQTSYf4m2FXELGeGK+vRcTLOHkiYl2VkXIEp3xSoCAk3xISmPaktODVP7Ekx1NNNNcJz03W+IZiI/UHnF3SISg6AI8FWmuBECI8IKI6Yf2FjUrn5+EMnSUP2eD9mFegM+eBrLls1SYPbM/yazKQFO5AtN4qFKFG28CjiatnCItT4wZunpIfskL017WQrUAnbfHjSPTNdHh2N//+qLld3pTGiHGbCIsJh/xc=

**Comment by daofeng2015** [comment]
> 帧头如下：
> 00 00 01 2b 00 10 00 03 00 00 00 05 00 00 00 00
> 数据帧base64
> AAABKwAQAAMAAAAFAAAAABsvAgAsCuxYBhKz0kGcOoHBZZhOJ3lyZaoRFMYApZ8rtawhhpykQLi21C/UL8mSDnVDBpvlMRo6HVRE9WXwnF4PdiBcvpOuVRQleL1Z2WZjK0j6BbrcedNX9KiuyGOCCPvK88E9AY5y7H+IaytuuePgsQTSYf4m2FXELGeGK+vRcTLOHkiYl2VkXIEp3xSoCAk3xISmPaktODVP7Ekx1NNNNcJz03W+IZiI/UHnF3SISg6AI8FWmuBECI8IKI6Yf2FjUrn5+EMnSUP2eD9mFegM+eBrLls1SYPbM/yazKQFO5AtN4qFKFG28CjiatnCItT4wZunpIfskL017WQrUAnbfHjSPTNdHh2N//+qLld3pTGiHGbCIsJh/xc=

能问下是在那个地址或者房间出现为3的协议吗?

**Comment by daofeng2015** [comment]
> 帧头如下：
> 00 00 01 2b 00 10 00 03 00 00 00 05 00 00 00 00
> 数据帧base64
> AAABKwAQAAMAAAAFAAAAABsvAgAsCuxYBhKz0kGcOoHBZZhOJ3lyZaoRFMYApZ8rtawhhpykQLi21C/UL8mSDnVDBpvlMRo6HVRE9WXwnF4PdiBcvpOuVRQleL1Z2WZjK0j6BbrcedNX9KiuyGOCCPvK88E9AY5y7H+IaytuuePgsQTSYf4m2FXELGeGK+vRcTLOHkiYl2VkXIEp3xSoCAk3xISmPaktODVP7Ekx1NNNNcJz03W+IZiI/UHnF3SISg6AI8FWmuBECI8IKI6Yf2FjUrn5+EMnSUP2eD9mFegM+eBrLls1SYPbM/yazKQFO5AtN4qFKFG28CjiatnCItT4wZunpIfskL017WQrUAnbfHjSPTNdHh2N//+qLld3pTGiHGbCIsJh/xc=

我问了下群里的人 有人说是brotli压缩

**Comment by HynemanKan** [comment]
> > 帧头如下：
> > 00 00 01 2b 00 10 00 03 00 00 00 05 00 00 00 00
> > 数据帧base64
> > AAABKwAQAAMAAAAFAAAAABsvAgAsCuxYBhKz0kGcOoHBZZhOJ3lyZaoRFMYApZ8rtawhhpykQLi21C/UL8mSDnVDBpvlMRo6HVRE9WXwnF4PdiBcvpOuVRQleL1Z2WZjK0j6BbrcedNX9KiuyGOCCPvK88E9AY5y7H+IaytuuePgsQTSYf4m2FXELGeGK+vRcTLOHkiYl2VkXIEp3xSoCAk3xISmPaktODVP7Ekx1NNNNcJz03W+IZiI/UHnF3SISg6AI8FWmuBECI8IKI6Yf2FjUrn5+EMnSUP2eD9mFegM+eBrLls1SYPbM/yazKQFO5AtN4qFKFG28CjiatnCItT4wZunpIfskL017WQrUAnbfHjSPTNdHh2N//+qLld3pTGiHGbCIsJh/xc=
> 
> 能问下是在那个地址或者房间出现为3的协议吗?

我是随机选了一个房间，多进了几个都换了

**Comment by HynemanKan** [comment]
> > 帧头如下：
> > 00 00 01 2b 00 10 00 03 00 00 00 05 00 00 00 00
> > 数据帧base64
> > AAABKwAQAAMAAAAFAAAAABsvAgAsCuxYBhKz0kGcOoHBZZhOJ3lyZaoRFMYApZ8rtawhhpykQLi21C/UL8mSDnVDBpvlMRo6HVRE9WXwnF4PdiBcvpOuVRQleL1Z2WZjK0j6BbrcedNX9KiuyGOCCPvK88E9AY5y7H+IaytuuePgsQTSYf4m2FXELGeGK+vRcTLOHkiYl2VkXIEp3xSoCAk3xISmPaktODVP7Ekx1NNNNcJz03W+IZiI/UHnF3SISg6AI8FWmuBECI8IKI6Yf2FjUrn5+EMnSUP2eD9mFegM+eBrLls1SYPbM/yazKQFO5AtN4qFKFG28CjiatnCItT4wZunpIfskL017WQrUAnbfHjSPTNdHh2N//+qLld3pTGiHGbCIsJh/xc=
> 
> 我问了下群里的人 有人说是brotli压缩

试过了确实试brotli，解压后还回带一个文件头，头格式与外部的头一致
