### ISSUE TITLE
用户空间信息中sys_notice状态补充

### ISSUE THREAD

**Issue by CKylinMC** [SocialSisterYi/bilibili-API-collect#213]
[用户详细信息1 (用于空间)](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/info.md#%E7%94%A8%E6%88%B7%E8%AF%A6%E7%BB%86%E4%BF%A1%E6%81%AF1)

补充一个 `sys_notice` 的状态：争议账号
![image](https://user-images.githubusercontent.com/11648014/124869666-1ad34600-dff4-11eb-87a3-2da1b7d70711.png)

**Comment by SocialSisterYi** [comment]
谢谢提供，已经加上去了
