### ISSUE TITLE
【用户】->【基本信息】API部分下official相关内容补充

### ISSUE THREAD

**Issue by g497813927** [SocialSisterYi/bilibili-API-collect#219]
通过 https://s1.hdslb.com/bfs/static/jinkela/space/6.space.c93b4516819ba4466a477a6aeb39b418c54af16a.js 格式化后，得到了以下内容：
![image](https://user-images.githubusercontent.com/24208169/127106396-7f87141a-b84b-4d40-8827-f3dc04d94b04.png)
根据这一个内容可以大致判断目前对于`个人认证`类型中的`role`字段还应该包含`7`这一个值
与此同时，`7`这一个认证类型也有相关的一个UP主案例：
UID:`67141499`
<details>
<summary>API返回内容</summary>
<pre>
{
    "code": 0,
    "message": "0",
    "ttl": 1,
    "data": {
        "mid": 67141499,
        "name": "大漠叔叔",
        "sex": "男",
        "face": "http://i2.hdslb.com/bfs/face/6d5a0e4406b06f7560e02c827e236b53dc941d8e.jpg",
        "sign": " Youtube、微博同名，叔是正经叔！",
        "rank": 10000,
        "level": 6,
        "jointime": 0,
        "moral": 0,
        "silence": 0,
        "birthday": "11-21",
        "coins": 0,
        "fans_badge": true,
        "fans_medal": {
            "show": true,
            "wear": true,
            "medal": {
                "uid": 67141499,
                "target_id": 437316738,
                "medal_id": 196110,
                "level": 5,
                "medal_name": "枯燥",
                "medal_color": 6126494,
                "intimacy": 851,
                "next_intimacy": 1000,
                "day_limit": 1500,
                "medal_color_start": 6126494,
                "medal_color_end": 6126494,
                "medal_color_border": 6126494,
                "is_lighted": 1,
                "light_status": 1,
                "wearing_status": 1,
                "score": 2552
            }
        },
        "official": {
            "role": 7,
            "title": "Vlog领域优质UP主，大漠叔叔官方账号",
            "desc": "",
            "type": 0
        },
        "vip": {
            "type": 2,
            "status": 1,
            "due_date": 1629475200000,
            "vip_pay_type": 1,
            "theme_type": 0,
            "label": {
                "path": "",
                "text": "年度大会员",
                "label_theme": "annual_vip",
                "text_color": "#FFFFFF",
                "bg_style": 1,
                "bg_color": "#FB7299",
                "border_color": ""
            },
            "avatar_subscript": 1,
            "nickname_color": "#FB7299",
            "role": 3,
            "avatar_subscript_url": "http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"
        },
        "pendant": {
            "pid": 0,
            "name": "",
            "image": "",
            "expire": 0,
            "image_enhance": "",
            "image_enhance_frame": ""
        },
        "nameplate": {
            "nid": 1,
            "name": "黄金殿堂",
            "image": "http://i0.hdslb.com/bfs/face/82896ff40fcb4e7c7259cb98056975830cb55695.png",
            "image_small": "http://i0.hdslb.com/bfs/face/627e342851dfda6fe7380c2fa0cbd7fae2e61533.png",
            "level": "稀有勋章",
            "condition": "单个自制视频总播放数\u003e=100万"
        },
        "user_honour_info": {
            "mid": 0,
            "colour": null,
            "tags": null
        },
        "is_followed": false,
        "top_photo": "http://i0.hdslb.com/bfs/space/cb1c3ef50e22b6096fde67febe863494caefebad.png",
        "theme": {},
        "sys_notice": {},
        "live_room": {
            "roomStatus": 1,
            "liveStatus": 0,
            "url": "https://live.bilibili.com/21574414",
            "title": "中国西沙群岛",
            "cover": "http://i0.hdslb.com/bfs/live/user_cover/81e94ce8bb69c850c98e16e1277f185a09b16f7c.jpg",
            "online": 144981,
            "roomid": 21574414,
            "roundStatus": 0,
            "broadcast_type": 0
        }
    }
}
</pre>
</details>

**Comment by SocialSisterYi** [comment]
全部文档的`role`字段下，个人认证类型已经添加`7`这个type
