### ISSUE TITLE
protobuf弹幕的弹幕类型

### ISSUE THREAD

**Issue by leiurayer** [SocialSisterYi/bilibili-API-collect#221]
目前已知的有1-9，但是在https://www.bilibili.com/video/BV1ax411P7zH?p=11 中，有一条弹幕的mode=10，类型未知

{
id: 850221784
progress: 11000
mode: 10
fontsize: 25
color: 16777215
midHash: a26a98ca
content: 第一次有广告 我去
ctime: 1373897400
weight: 10
pool: 0
}

**Comment by SocialSisterYi** [comment]
这个type_id还需要研究，大概....
