### ISSUE TITLE
请问有APP端的登录接口吗

### ISSUE THREAD

**Issue by sou1maker** [SocialSisterYi/bilibili-API-collect#223]

**Comment by ProgramRipper** [comment]
[申请二维码URL及扫码密钥（TV端）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/QR.md#%E7%94%B3%E8%AF%B7%E4%BA%8C%E7%BB%B4%E7%A0%81url%E5%8F%8A%E6%89%AB%E7%A0%81%E5%AF%86%E9%92%A5tv%E7%AB%AF)

**Comment by sou1maker** [comment]
> [申请二维码URL及扫码密钥（TV端）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/QR.md#%E7%94%B3%E8%AF%B7%E4%BA%8C%E7%BB%B4%E7%A0%81url%E5%8F%8A%E6%89%AB%E7%A0%81%E5%AF%86%E9%92%A5tv%E7%AB%AF)

好的，但没有看到sign的生成方式呢

**Comment by sou1maker** [comment]
APP 端可以使用账号密码登录吗

**Comment by duzhaokun123** [comment]
参考 https://github.com/czp3009/bilibili-api

**Comment by sou1maker** [comment]
> 参考 ~https://github.com/czp3009/bilibili-api~ (过时了)
> 
> https://github.com/duzhaokun123/BilibiliHD2/blob/3567667fd17095e285dc89719d6cc67512f3ad4a/bilibili-api/src/main/kotlin/com/hiczp/bilibili/api/BilibiliClient.kt#L261-L302

非常感谢

**Comment by ProgramRipper** [comment]
> > [申请二维码URL及扫码密钥（TV端）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/QR.md#%E7%94%B3%E8%AF%B7%E4%BA%8C%E7%BB%B4%E7%A0%81url%E5%8F%8A%E6%89%AB%E7%A0%81%E5%AF%86%E9%92%A5tv%E7%AB%AF)
> 
> 好的，但没有看到sign的生成方式呢

[app方式手机客户端及tv端等](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/other/API_auth.md#app%E6%96%B9%E5%BC%8F%E6%89%8B%E6%9C%BA%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%8F%8Atv%E7%AB%AF%E7%AD%89)
烦请善用仓库内搜索的功能

**Comment by sou1maker** [comment]
> > > [申请二维码URL及扫码密钥（TV端）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/QR.md#%E7%94%B3%E8%AF%B7%E4%BA%8C%E7%BB%B4%E7%A0%81url%E5%8F%8A%E6%89%AB%E7%A0%81%E5%AF%86%E9%92%A5tv%E7%AB%AF)
> > 
> > 
> > 好的，但没有看到sign的生成方式呢
> 
> [app方式手机客户端及tv端等](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/other/API_auth.md#app%E6%96%B9%E5%BC%8F%E6%89%8B%E6%9C%BA%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%8F%8Atv%E7%AB%AF%E7%AD%89)
> 烦请善用仓库内搜索的功能

抱歉，只找了login项目下的。谢谢告知
