### ISSUE TITLE
[目录链接失效] 用户关系相关页面中目录的部分链接失效

### ISSUE THREAD

**Issue by CKylinMC** [SocialSisterYi/bilibili-API-collect#225]
[用户关系相关](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/relation.md) 页面中目录的部分链接失效

1. 操作用户关系 没有链接
    * ![image](https://user-images.githubusercontent.com/11648014/130197624-21d34939-2356-4fee-a09d-5f55da30493c.png)
2. 部分链接点击后无法跳转
    * 批量操作用户关系（仅关注&拉黑）
    * 查询用户与自己关系（仅查关注）
    * 查询用户与自己关系（互相）
    * 修改分组成员（添加/删除）

*//似乎失效的链接都包含了括号*

------

另外 一个疑问 在[修改分组成员](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/relation.md#%E4%BF%AE%E6%94%B9%E5%88%86%E7%BB%84%E6%88%90%E5%91%98%EF%BC%88%E6%B7%BB%E5%8A%A0/%E5%88%A0%E9%99%A4%EF%BC%89)中，标题是"添加/删除"，但是API地址是 `.../addUsers`，而且演示也是添加的，没有看到删除操作的参数，它是如何将成员从分组中删除的呢？

**Comment by SocialSisterYi** [comment]
锚点链接不能跳转应该是全角括号导致的问题

**Comment by SocialSisterYi** [comment]
在[修改分组成员](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/relation.md#%E4%BF%AE%E6%94%B9%E5%88%86%E7%BB%84%E6%88%90%E5%91%98%EF%BC%88%E6%B7%BB%E5%8A%A0/%E5%88%A0%E9%99%A4%EF%BC%89)这个api中 如需删除分组中的成员，请将`tagids`设为0，即移动至默认分组，而不是取关，也没有专门用于删除的api

**Comment by SocialSisterYi** [comment]
错误已经更正

**Comment by CKylinMC** [comment]
> 在[修改分组成员](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/relation.md#%E4%BF%AE%E6%94%B9%E5%88%86%E7%BB%84%E6%88%90%E5%91%98%EF%BC%88%E6%B7%BB%E5%8A%A0/%E5%88%A0%E9%99%A4%EF%BC%89)这个api中 如需删除分组中的成员，请将`tagids`设为0，即移动至默认分组，而不是取关，也没有专门用于删除的api

  好的 明白了，感谢回复
