### ISSUE TITLE
返回的code 有可能是412

### ISSUE THREAD

**Issue by Somiona** [SocialSisterYi/bilibili-API-collect#23]
![image](https://user-images.githubusercontent.com/20739885/87624088-db319100-c6f4-11ea-8eee-c8a0879a6d2f.png)

API是 http://api.bilibili.com/x/web-interface/view

没有跨域的问题，这里应该是请求次数过多就被ban掉了

**Comment by SocialSisterYi** [comment]
不一定是跨域问题，请求间隔过快且没登录会被短时间封ip

**Comment by Somiona** [comment]
问题确定了，是操作过于频繁

**Comment by newtorn** [comment]
> 不一定是跨域问题，请求间隔过快且没登录会被短时间封ip

建议在`bilibili_api.exceptions.NetworkException`中附加b站API接口，返回的msg，以便区分
