### ISSUE TITLE
那种直播间带进度条的，要如何获得从某进度开始的直播流？

### ISSUE THREAD

**Issue by gMan1990** [SocialSisterYi/bilibili-API-collect#232]
比如: https://live.bilibili.com/11218604

**Comment by SocialSisterYi** [comment]
这种应该是直播回放吧？不确定

**Comment by vooidzero** [comment]
B 站直播 web 端现在用的是HLS，切片为 1 秒，切片格式为 m4s（moof + mdat）。
m3u8 的 url 加上 tmshift 参数，比如 tmshift=60，返回的就是 60 秒前的切片信息.

比如 m3u8 的 url 为：`/index.m3u8?expires=1636786517`，GET 回复的内容为：
（url 和 m3u8 内容仅示意）
```
#EXTM3U
....
#EXTINF:1.00,68d1a|d1a7a14d
680.m4s
#EXTINF:1.00,73847|4beb5a0b
681.m4s
```

此时，如果请求的是 `/index.m3u8?expires=1636786517&tmshift=60`，那么得到是：
```
#EXTM3U
....
#EXTINF:1.00,7d34f|ef2c7790
620.m4s
#EXTINF:1.00,74931|58c7faa7
621.m4s
```

**Comment by gMan1990** [comment]
@vooidzero 为啥我加上`tmshift`没用，是不是只有某些直播间才有用？

**Comment by vooidzero** [comment]
> @vooidzero 为啥我加上`tmshift`没用，是不是只有某些直播间才有用？

抱歉，前面的回复草率了。

B 站 web 端直播流目前有三种形式：
- http_stream (flv)
- 切片格式为 ts 的 HLS
- 切片格式为 fmp4 (m4s) 的 HLS。

采样观察了下，有的直播间 3 种全支持，**有的只支持 flv 和 ts HLS**，web 端播放的优先级是 fmp4 HLS > flv > ts HLS.

**之前的回复说的是切片格式为 fmp4 的 HLS**，我测试了几个支持 fmp4 HLS 的直播间，tmshift 都是可以用的。
