### ISSUE TITLE
用其他工具直接从apk中获取到部分的proto,需要放上来研究下吗?

### ISSUE THREAD

**Issue by daofeng2015** [SocialSisterYi/bilibili-API-collect#233]
![image](https://user-images.githubusercontent.com/14891398/131260784-82fa51ce-4086-47f1-a4ef-d3478a7232d3.png)
目前看好像很多都还没采用.都是埋点

**Comment by duzhaokun123** [comment]
#189

**Comment by daofeng2015** [comment]
> #189

我这是从最新安装包逆向出来的，不是官方以前从安装包泄露出来的一部分

**Comment by SocialSisterYi** [comment]
> ![image](https://user-images.githubusercontent.com/14891398/131260784-82fa51ce-4086-47f1-a4ef-d3478a7232d3.png)
> 目前看好像很多都还没采用.都是埋点

并不是接口没使用和埋点，而是包含了很多冗余字段，使得前端的组件的可控性更高
