### ISSUE TITLE
网页端的人气是通过那个接口来进行心跳检测得？

### ISSUE THREAD

**Issue by a1443304527** [SocialSisterYi/bilibili-API-collect#237]

**Comment by daofeng2015** [comment]
> _No description provided._

那个人气是一个ws连接来确定的.返回数据基本明文

**Comment by a1443304527** [comment]
> > _No description provided._
> 
> 那个人气是一个ws连接来确定的.返回数据基本明文

我想可能是我表达得意思有问题，我想做的事：登录成功后，用户进直播间进行挂机操作，从而给直播间增加人气，现在问题是在于直播间挂机的心跳包暂时未找到

**Comment by SeaHOH** [comment]
这里没有你要的东西，你应该离开这里。

**Comment by daofeng2015** [comment]
> > > _No description provided._
> > 
> > 
> > 那个人气是一个ws连接来确定的.返回数据基本明文
> 
> 我想可能是我表达得意思有问题，我想做的事：登录成功后，用户进直播间进行挂机操作，从而给直播间增加人气，现在问题是在于直播间挂机的心跳包暂时未找到

我还以为你说的是视频下面的那个在线人数.直播的这个不知道

**Comment by a1443304527** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 那个人气是一个ws连接来确定的.返回数据基本明文
> > 
> > 
> > 我想可能是我表达得意思有问题，我想做的事：登录成功后，用户进直播间进行挂机操作，从而给直播间增加人气，现在问题是在于直播间挂机的心跳包暂时未找到
> 
> 我还以为你说的是视频下面的那个在线人数.直播的这个不知道

好的，谢谢
