### ISSUE TITLE
直播间信息流认证包中需要的key是哪个key

### ISSUE THREAD

**Issue by Hypocrisybbq** [SocialSisterYi/bilibili-API-collect#241]
直播间信息流认证包中需要的认证密钥key是哪个key
还有对应的url是啥

**Comment by ProgramRipper** [comment]
`https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo?id={房间真实id}`
![image](https://user-images.githubusercontent.com/45716046/132951536-ab379a8f-9ded-49b8-bc5b-3158dbbece19.png)
事实上不需要token也可以通过信息流认证

**Comment by Hypocrisybbq** [comment]
> `https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo?id={房间真实id}`
> ![image](https://user-images.githubusercontent.com/45716046/132951536-ab379a8f-9ded-49b8-bc5b-3158dbbece19.png)
> 事实上不需要token也可以通过信息流认证

谢谢~
