### ISSUE TITLE
【B币方式充电】响应字段 bp_num 变更为字符串类型

### ISSUE THREAD

**Issue by iyear** [SocialSisterYi/bilibili-API-collect#247]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/electric/Bcoin.md

由于太穷，无法测试具体数值😅

**Comment by catlair** [comment]
事实上这个东西无所谓，这样一个原始数据`bp_num=6&is_bp_remains_prior=false&up_mid=1&otype=up&oid=1&csrf=cfffffffffffffffff`
你告诉我 `1` 是字符串还是数字

**Comment by iyear** [comment]
> 事实上这个东西无所谓，这样一个原始数据`bp_num=6&is_bp_remains_prior=false&up_mid=1&otype=up&oid=1&csrf=cfffffffffffffffff`
> 你告诉我 `1` 是字符串还是数字
> 
> 没有产生变化吧
> ![image](https://user-images.githubusercontent.com/44313800/133920622-f8935820-39fc-42af-a15b-d9a7ac6c11df.png)

1. 提交字段没关系，最终都是转字符串提交
2. 响应的字段在js，py里没事，在静态语言里写struct要确定类型
3. 转变为字符串形式代表着非数字形式格式返回的可能性，应当添加在文档中

**Comment by catlair** [comment]
@iyear 你是对的

这个字段在网页中用的是字符串
