### ISSUE TITLE
关于 "视频基本信息" 中 [rotate]字段作用的猜测

### ISSUE THREAD

**Issue by thefatwhale** [SocialSisterYi/bilibili-API-collect#25]
av63009939视频返回的 rotate 是1 而不是大多数的 视频返回的 0
    www.bilibili.com/video/av63009939
["data"]["dimension"]
{'width': 640, 'height': 1280, 'rotate': 1}
右键视频看详细信息可以看到 写的是 1280 x 640(视频也确实是 横向的，不是纵向的）
猜测 如果rotate 为 1 时，width 和 height 值对调

(不知道issue是不是干这个用的)

**Comment by SocialSisterYi** [comment]
收到，已经改好了
