### ISSUE TITLE
一个获取不需要验证refer的视频地址api。

### ISSUE THREAD

**Issue by Quandong-Zhang** [SocialSisterYi/bilibili-API-collect#250]
如
https://api.bilibili.com/x/player/playurl?cid=2757236&avid=1797652&platform=html5&otype=json&qn=16&type=mp4&html5=1
从该api获得的视频地址refer可以为任意（空也可以），不一定为bilibili.com

**Comment by duzhaokun123** [comment]
这不就是app的api吗

**Comment by Quandong-Zhang** [comment]
注意，访问该api的refer有限制，但获取到视频的refer无限制。

**Comment by Quandong-Zhang** [comment]
> 这不就是app的api吗

应该不是，感觉是外站分享视频的api

**Comment by Quandong-Zhang** [comment]
> 这不就是app的api吗

比如
<iframe src="//player.bilibili.com/player.html?aid=932160271&bvid=BV1LM4y1K7Ms&cid=384624341&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>

**Comment by Quandong-Zhang** [comment]
//player.bilibili.com/player.html?aid=932160271&bvid=BV1LM4y1K7Ms&cid=384624341&page=1

**Comment by Quandong-Zhang** [comment]
https://player.bilibili.com/player.html?aid=932160271&bvid=BV1LM4y1K7Ms&cid=384624341&page=1

**Comment by Quandong-Zhang** [comment]
比如：
https://player.bilibili.com/player.html?aid=932160271&bvid=BV1LM4y1K7Ms&cid=384624341&page=1

**Comment by duzhaokun123** [comment]
抓了一下
这是移动端浏览器用的

**Comment by SocialSisterYi** [comment]
> 抓了一下
> 这是移动端浏览器用的
> 只给360p的
> 不如用app的api

专供的劣质清晰度流，笑死

**Comment by Quandong-Zhang** [comment]
> > 抓了一下
> > 这是移动端浏览器用的
> > 只给360p的
> > 不如用app的api
> 
> 专供的劣质清晰度流，笑死

好处就是refer无限制，可以直接搬到自己站上[doge]
