### ISSUE TITLE
【B币方式充电】响应字段 bp_num 变更为字符串类型

### ISSUE THREAD

**Issue by iyear** [SocialSisterYi/bilibili-API-collect#251]
在http表单中，没有字符串与数字之分，一切皆为k-v的字符串，就需要看怎么格式化它了

_Originally posted by @SocialSisterYi in https://github.com/SocialSisterYi/bilibili-API-collect/issues/247#issuecomment-926009627_

我说的是响应json里的bp_num，json分文本和数字

**Comment by SocialSisterYi** [comment]
好的，是我看错了😂😂
