### ISSUE TITLE
b 站手机端的 protobuf 协议好像挺奇怪的

### ISSUE THREAD

**Issue by yjqiang** [SocialSisterYi/bilibili-API-collect#253]
![3CA2FE80-AE60-4F45-A717-C93B903CFBA2](https://user-images.githubusercontent.com/8900942/134804397-b8597e40-aafe-4ce7-92b2-c8cfd1de89c8.jpeg)
把 protobuf 的数据，先 gzip 压缩，然后把压缩的数据前面又加了个 5 byte 的前缀，应该是校验的。请问这个前缀具体算法有么？
对应请求是 https://app.bilibili.com/bilibili.app.dynamic.v2.Dynamic/DynAll

**Comment by yjqiang** [comment]
解决了，校验位就是数据长度

**Comment by yjqiang** [comment]
但还有新问题，使用本仓库的 proto 文件，以及 https://www.npmjs.com/package/protobufjs ，好像先解析后编码，前后数据不一致

**Comment by yjqiang** [comment]
好像都干完了。。。解决了U•ェ•*U

**Comment by ProgramRipper** [comment]
> ![3CA2FE80-AE60-4F45-A717-C93B903CFBA2](https://user-images.githubusercontent.com/8900942/134804397-b8597e40-aafe-4ce7-92b2-c8cfd1de89c8.jpeg)
> 
> 把 protobuf 的数据，先 gzip 压缩，然后把压缩的数据前面又加了个 5 byte 的前缀，应该是校验的。请问这个前缀具体算法有么？
> 
> 对应请求是 https://app.bilibili.com/bilibili.app.dynamic.v2.Dynamic/DynAll
> 
> 

gzip压缩应该是http的压缩，前缀5byte应该是http2特性。支持http2的网络请求库都可以正常处理。
