### ISSUE TITLE
appkey | str | APP密钥 | APP方式必要    这个 哪里能获取 appkey

### ISSUE THREAD

**Issue by icetech233** [SocialSisterYi/bilibili-API-collect#256]
appkey | str | APP密钥 | APP方式必要

**Comment by KudouRan** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/a7a743dffdb0e22ef735a8639dd3c3ead82665e4/other/API_auth.md

**Comment by SocialSisterYi** [comment]
这个只能通过逆向工程获得，没有官方的申请渠道
