### ISSUE TITLE
视频流URL API 杜比视界流获取

### ISSUE THREAD

**Issue by Daniel2022** [SocialSisterYi/bilibili-API-collect#261]
fnval视频流格式标识：是否请求杜比视界 512
qn清晰度标识：杜比视界 126
杜比视界仅dash，格式仅h265

目前B站网页端请求fnval默认976

`fnval&128=128`或`fourk=1`均可允许请求“4K超清”清晰度，不必同时满足。

**Comment by wujiezero** [comment]
fnval&128=128 到底是啥意思，是fnval=128吗，能给个curl示例么

**Comment by SocialSisterYi** [comment]
> fnval&128=128 到底是啥意思，是fnval=128吗，能给个curl示例么

`fnval&128=128`指`fnval`字段的第 8 bit 为 1，也就意味着使能 4K 分辨率为真

**Comment by SocialSisterYi** [comment]
`fnval`默认`976`就是同时使能了 HDR、4K、杜比音效、杜比视界 这几个属性位，目前默认值已经改为`2000`了，增加了一个使能 8K分辨率 的属性

**Comment by FongMi** [comment]
請問有能請求 HDR、4K、8K 的 fnval 嗎
