### ISSUE TITLE
作者快女装qwq

### ISSUE THREAD

**Issue by kuresaru** [SocialSisterYi/bilibili-API-collect#27]

**Comment by gkgfu** [comment]
同求QwQ

**Comment by SocialSisterYi** [comment]
这个repo一万星了绝对女装

**Comment by zhang-anzhi** [comment]
强烈谴责无意义issue

**Comment by SocialSisterYi** [comment]
> 强烈谴责无意义issue

啊这

**Comment by SocialSisterYi** [comment]
虽然这个 repo 没有过 1w star 但是 owner 确实女装了（一年前的坑总要填的
https://github.com/komeiji-satori/Dress/tree/b49eb17b9c69198b56f893225db5dce62bf30a81/ShakaiAneE
https://www.bilibili.com/video/BV1EV411W7xo
