### ISSUE TITLE
对于获取其他用户关注列表

### ISSUE THREAD

**Issue by lb-chc** [SocialSisterYi/bilibili-API-collect#274]
对于获取其他用户关注列表
<img width="655" alt="屏幕快照 2021-11-11 上午11 19 13" src="https://user-images.githubusercontent.com/69136546/141231284-f0bc112b-13fd-4804-b91c-ad4b2f4aedcf.png">

按照[这里](https://www.zhihu.com/question/64737631)的说法,可以加order参数，“默认是desc是降序，如果改成asc返回结果会变成升序”, 先降序在升序，最多就能拿到500个了, 可以加上这条提示?

_Originally posted by @lb-chc in https://github.com/SocialSisterYi/bilibili-API-collect/issues/273#issuecomment-965954171_

**Comment by SocialSisterYi** [comment]
好的，感谢提供这个参数的用法
