### ISSUE TITLE
发送请求 Fatal: API error 错误

### ISSUE THREAD

**Issue by baozoulolw** [SocialSisterYi/bilibili-API-collect#278]
<img width="594" alt="QQ20211114-194812@2x" src="https://user-images.githubusercontent.com/31173826/141679532-2713b7d5-a1ff-4a38-abd2-feada1c1bbe4.png">

**Comment by baozoulolw** [comment]
带上了cookie
![image](https://user-images.githubusercontent.com/31173826/141681683-31a7ffbb-d1d1-405b-9bea-664262c5ba82.png)

**Comment by SocialSisterYi** [comment]
请检查你反向代理的配置，至少头部中`referer`和`UA`参数要存在，顺便提醒一下cookie中的`SESSDATA`和`bili_jct`暴漏会有盗号风险
