### ISSUE TITLE
b站新增8k清晰度，我搜集一些清晰度列表

### ISSUE THREAD

**Issue by blogwy** [SocialSisterYi/bilibili-API-collect#296]
const quality = {
  127: '8K超高清',
  126: '杜比视界',
  125: 'HDR真彩',
  120: '4K超清',
  116: '1080P60帧',
  112: '1080P+高码率',
  80: '1080P',
  74: '720P60帧',
  64: '720P',
  32: '480P清晰',
  16: '320P流畅'
}

**Comment by SocialSisterYi** [comment]
8K相关参数已经添加
