### ISSUE TITLE
请问一个关于清晰度的问题

### ISSUE THREAD

**Issue by TommyLe1** [SocialSisterYi/bilibili-API-collect#298]
对获取的URL进行在线播放的话最高只有720p清晰度，是我方法有问题还是有其他方面的限制啊？望大佬解惑！

**Comment by zjkwdy** [comment]
说的不明不白，哪个接口，哪个视频，请求的什么，返回了什么，

**Comment by TommyLe1** [comment]
有大佬帮我找到问题了，是cookies问题！
