### ISSUE TITLE
添加类似的库到README

### ISSUE THREAD

**Issue by poly000** [SocialSisterYi/bilibili-API-collect#3]
https://github.com/Vespa314/bilibili-api

https://github.com/fython/BilibiliAPIDocs

**Comment by zhongfly** [comment]
这几个api都好久没更新了，不见得还有效。目前我也没找到一个比较完整的api文档，都得翻相关的项目代码才能知道。

**Comment by jingyuexing** [comment]
我自己写了一个关于[API的库](https://github.com/jingyuexing/bilibiliAPI)
由于很多库都已经失效了，目前这个库算是最新的

**Comment by jingyuexing** [comment]
> 我自己写了一个关于[API的库](https://github.com/jingyuexing/bilibiliAPI)
> 由于很多库都已经失效了，目前这个库算是最新的

我说的是当前的库，不是我的库,我会用这个库去更新我的那个Bilibili-API的

**Comment by jingyuexing** [comment]
说一下，我那个项目也可以当作爬虫
