### ISSUE TITLE
整理收集隐私的API地址

### ISSUE THREAD

**Issue by cxw620** [SocialSisterYi/bilibili-API-collect#301]
有搜寻收集隐私、投放广告或辅助收集隐私、投放广告的API地址，尤其是HTTPDNS相关的API（导致广告拦截失效）
举例:http://ip（这个好像会变）/*（一串数字）/resolve?host=要解析的域名&*（其他的一些参数，有时候也没有）。
截至2022/1/4有效的接口：
[http://203.107.1.66/191607/resolve?host=grpc.biliapi.net](http://203.107.1.66/191607/resolve?host=grpc.biliapi.net)。
返回值:
`{"dns":[{"host":"grpc.biliapi.net","client_ip":"（我的ip）","ips":["111.161.22.4","111.161.22.10","111.161.22.7","111.161.22.1"],"type":1,"ttl":48,"origin_ttl":60}]}`
当然我也很乐意帮忙，不过得等寒假。

**Comment by SocialSisterYi** [comment]
这个是[HTTP-DNS](https://zhuanlan.zhihu.com/p/270596378)，和收集隐私没有丝毫的关系
