### ISSUE TITLE
请问大佬有那个手机B站新功能“听视频”的音频playUrl api吗

### ISSUE THREAD

**Issue by AndrewXiongGe** [SocialSisterYi/bilibili-API-collect#309]

**Comment by SocialSisterYi** [comment]
这个 api 使用 grpc 进行请求，并且仅有 app 端存在这个功能，近期会更对应 proto 结构体

**Comment by SocialSisterYi** [comment]
[听视频](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/grpc_api/bilibili/app/listener/v1/listener.proto)的 API 文档已经完工
