### ISSUE TITLE
是否考虑添加一个 退出登录的 api搜集

### ISSUE THREAD

**Issue by thefatwhale** [SocialSisterYi/bilibili-API-collect#31]
## 是否考虑添加 退出登录，避免登录cookies 泄漏导致不安全（up主的demo视频）或者再次登录导致点赞投币等出现提示错误

**Comment by SocialSisterYi** [comment]
确实有退出的接口正在研究，应该web和app都有，那个Demo视频上的cookie已经失效因为我发视频前已经改过密码
