### ISSUE TITLE
#302 中修改了申请极验验证码参数的请求和返回，导致key字段没了，影响到登录了

### ISSUE THREAD

**Issue by CuteReimu** [SocialSisterYi/bilibili-API-collect#324]
#302 中修改了申请极验验证码参数的请求和返回，导致key字段没了：

https://github.com/SocialSisterYi/bilibili-API-collect/commit/c25a8f4bf6351fa7b394b9934160502e1468945c?diff=unified#diff-b011b19b7f61d3d073bbb8db35ce5ea55a81cba19b5d1abba971cbd81b4dc776L42-L49

登录的时候需要key字段就获取不到了：

https://github.com/SocialSisterYi/bilibili-API-collect/blob/3dadadc97ef503dd71997f92d2a7fd227348e59a/login/login_action/password.md?plain=1#L144-L155

**Comment by CuteReimu** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/f2f1a52b5a2001d854cf204bc471510aae2a5344/login/login_action/readme.md?plain=1#L43

尝试了token字段填到key，会返回2400-登录密钥错误。其他找了一下，叫key的字段只有公钥了，但是感觉显然不太可能是这个。

**Comment by Colerar** [comment]
可参考我写的实现: [PassportApi.kt](https://github.com/SDLMoe/Yabapi/blob/kotlin-mt/yabapi-core/src/commonMain/kotlin/moe/sdl/yabapi/api/PassportApi.kt)

应该是最近API有变动, 仅根据这个 commit 补充的, 的确无法完成登录流程.

推荐优先实现扫码登录, 这个最简单.
