### ISSUE TITLE
大佬有没有有关免流方面的api

### ISSUE THREAD

**Issue by simo8102** [SocialSisterYi/bilibili-API-collect#337]
目前我只看到了这个

https://app.bilibili.com/x/wall/unicom/active/state?appkey=1d8b6e7d45233436&auto=true&build=6580300&c_locale=zh_CN&channel=yingyongbao&disable_rcmd=0&mobi_app=android&need_flow_auto=true&pip=x.x.x.x&platform=android&s_locale=zh_CN&statistics=xxxxxxxxxx&ts=1648169138&sign=xxxxxxx

**Comment by SocialSisterYi** [comment]
现在免流规则的api已经是grpc了，地址是`bilibili.app.wall.v1.Wall.RuleInfo`，定义可以去看文档
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/45892418/162668816-bb6ce8bb-b82f-4259-8b01-50170be162a3.png">
