### ISSUE TITLE
应援应援~

### ISSUE THREAD

**Issue by ycMia** [SocialSisterYi/bilibili-API-collect#34]
# up太强了太强了太强了!!!!

>话说我也超想这么写逆向的来着? 
>只不过放弃了2333

**Comment by SocialSisterYi** [comment]
也不难，就是捕捉到野生的接口，拿回来疯狂**调教**就行了QAQ

**Comment by zhang-anzhi** [comment]
强烈谴责无意义issue，你们这些人真的明白什么是github issue吗

**Comment by ycMia** [comment]
很抱歉打扰到了, 在这里表示道歉
