### ISSUE TITLE
建议在ranking/dynamic目录下增加热门视频（popular）的api

### ISSUE THREAD

**Issue by JiangOrangeSon** [SocialSisterYi/bilibili-API-collect#341]
（1）url：https://api.bilibili.com/x/web-interface/popular
（2）参数
ps：每页视频数，最大值为50
pn：页数
（3）返回json，结构基本上和排行榜差不多

**Comment by SocialSisterYi** [comment]
收到了，谢谢~

**Comment by Nemo2011** [comment]
已有

**Comment by Nemo2011** [comment]
{
    "info": {
        "hot": {
            "url": "http://api.bilibili.com/x/web-interface/popular", 
            "verify": false, 
            "comment": "小破站的热门视频排行"
        }, 
        "weakly_series": {
            "url": "http://api.bilibili.com/x/web-interface/popular/series/list", 
            "verify": false, 
            "comment": "小破站每周必看全部信息（简介）"
        }, 
        "weakly_details": {
            "url": "http://api.bilibili.com/x/web-interface/popular/series/one", 
            "verify": false, 
            "params": {
                "number": "int: 第几期"
            }, 
            "comment": "小破站每周必看一期的详细信息"
        }, 
        "popular": {
            "url": "http://api.bilibili.com/x/web-interface/popular/precious", 
            "verify": false, 
            "params": {
                "page_size": "int: 就设置 85 好了（每页的大小）", 
                "page": "int: 页码"
            }, 
            "comment": "获取入站必刷 85 个视频"
        }, 
        "ranking": {
            "url": "http://api.bilibili.com/x/web-interface/ranking/v2", 
            "verify": false, 
            "params": {
                "tid": "int: 频道的 tid", 
                "type": "string: all"
            }, 
            "comment": "获取各个分区的排行榜"
        }
    }
}

**Comment by Nemo2011** [comment]
```json
{
    "info": {
        "hot": {
            "url": "http://api.bilibili.com/x/web-interface/popular", 
            "verify": false, 
            "comment": "小破站的热门视频排行"
        }, 
        "weakly_series": {
            "url": "http://api.bilibili.com/x/web-interface/popular/series/list", 
            "verify": false, 
            "comment": "小破站每周必看全部信息（简介）"
        }, 
        "weakly_details": {
            "url": "http://api.bilibili.com/x/web-interface/popular/series/one", 
            "verify": false, 
            "params": {
                "number": "int: 第几期"
            }, 
            "comment": "小破站每周必看一期的详细信息"
        }, 
        "popular": {
            "url": "http://api.bilibili.com/x/web-interface/popular/precious", 
            "verify": false, 
            "params": {
                "page_size": "int: 就设置 85 好了（每页的大小）", 
                "page": "int: 页码"
            }, 
            "comment": "获取入站必刷 85 个视频"
        }, 
        "ranking": {
            "url": "http://api.bilibili.com/x/web-interface/ranking/v2", 
            "verify": false, 
            "params": {
                "tid": "int: 频道的 tid", 
                "type": "string: all"
            }, 
            "comment": "获取各个分区的排行榜"
        }
    }
}
```

**Comment by Nemo2011** [comment]
都是爬加载的 JavaScript 爬出来的
