### ISSUE TITLE
请教关于直播间封面的API

### ISSUE THREAD

**Issue by Kiritomo** [SocialSisterYi/bilibili-API-collect#35]
封面上传:https://api.bilibili.com/x/upload/web/image?csrf={}
参数:
![Snipaste 2020-08-01 13-05-08](https://user-images.githubusercontent.com/17985734/89094577-f2ac9180-d3f7-11ea-92db-4b863279c462.png)

返回值:
![Snipaste 2020-08-01 13-10-01](https://user-images.githubusercontent.com/17985734/89094616-559e2880-d3f8-11ea-8738-0235786fce23.png)

封面替换:https://api.live.bilibili.com/room/v1/Cover/replace
参数:
这里的csrf_token和csrf值正确且相同
![Snipaste 2020-08-01 13-12-47](https://user-images.githubusercontent.com/17985734/89094646-c2192780-d3f8-11ea-936b-71fe5cbac986.png)

返回值:
code: 0
data: []
message: ""
msg: ""

但是封面替换里的这个pic_id如何获取我就不知道了，封面接口调用并没看到返回pic_id，大佬可以研究研究一下

**Comment by ShigemoriHakura** [comment]
pic_id用/room/v1/Cover/get_list?room_id=房间号&type=all_cover拉所有的封面的id就可以
写那个pic_id就替换了哪个

**Comment by Kiritomo** [comment]
> pic_id用/room/v1/Cover/get_list?room_id=房间号&type=all_cover拉所有的封面的id就可以
> 写那个pic_id就替换了哪个

后来找到了，忘了关闭了，不过还是谢谢大大解答
