### ISSUE TITLE
请问一下，如何获取一条弹幕的点赞数，如何给弹幕点赞呢？

### ISSUE THREAD

**Issue by xyl23333** [SocialSisterYi/bilibili-API-collect#350]

**Comment by Kiss-your** [comment]
几天后我文档写好了就上传获取点赞列表

**Comment by MineCreeper86** [comment]
> 几天后我文档写好了就上传获取点赞列表

坑慢点挖（

**Comment by Kiss-your** [comment]
已经上传了，暂时看pr #387

**Comment by SocialSisterYi** [comment]
对应内容已经更新完毕 https://github.com/SocialSisterYi/bilibili-API-collect/commit/87d56b66e7ce375029bccf9efda5314964b0528d
