### ISSUE TITLE
弹幕条目protobuf增加了新属性

### ISSUE THREAD

**Issue by 7rikka** [SocialSisterYi/bilibili-API-collect#351]
目前发现
14: 13693280
15: 4
20: "0"
21: "0"

**Comment by SocialSisterYi** [comment]
这是哪个api的？只告诉我说id对应的值有变化，我也确定不了

**Comment by 7rikka** [comment]
https://api.bilibili.com/x/v2/dm/web/seg.so 获取视频的分段弹幕包

**Comment by SocialSisterYi** [comment]
> https://api.bilibili.com/x/v2/dm/web/seg.so 获取视频的分段弹幕包

这个API大家都知道，在这里不用说明了，另外我有时间在逆向一下最新版本安卓客户端的protobuf定义，弹幕API新增字段的意义就清楚了

**Comment by wly5556** [comment]
web端播放器的jsc-player.js里面有也有弹幕的完整protobuf定义（json格式），去那里面找也可以

**Comment by SocialSisterYi** [comment]
> web端播放器的jsc-player.js里面有也有弹幕的完整protobuf定义（json格式），去那里面找也可以

那里只有弹幕的定义啊，客户端里有最全的定义
