### ISSUE TITLE
如何获取指定用户创建的所有视频合集信息

### ISSUE THREAD

**Issue by lb-chc** [SocialSisterYi/bilibili-API-collect#367]
1.获取指定用户创建的所有视频合集信息 
[查询用户频道列表](http://api.bilibili.com/x/space/channel/list) 中的‘频道’与‘视频列表’、‘合集与列表’ 似乎不属于同一概念?因为目前频道是一项需要电磁力等级开启的功能,所以或许是独立的功能?
现在有获取合集内容的[API](http://api.bilibili.com/x/v3/fav/resource/infos),但是似乎没有获取用户合集id的api?
<img width="226" alt="屏幕快照 2022-05-06 上午10 27 05" src="https://user-images.githubusercontent.com/69136546/167056849-f22b5cb6-c1ad-41a8-87fa-670206c05443.png">

2.获取指定用户创建的所有文集信息 
我还没找到这个api......

3.获取指定用户收藏的所有视频信息
无法通过为API [获取指定用户创建的所有收藏夹信息](http://api.bilibili.com/x/v3/fav/folder/created/list-all) 添加参数 &type=21 获取这一信息
<img width="186" alt="屏幕快照 2022-05-06 上午10 26 56" src="https://user-images.githubusercontent.com/69136546/167056844-e9aed428-8c98-4cb5-b41c-b41281aa95c1.png">

**Comment by Nemo2011** [comment]
http://api.bilibili.com/x/polymer/space/seasons_series_list

**Comment by Nemo2011** [comment]
"mid":  uid
"page_num": 页数
"page_size": 每页大小

**Comment by lb-chc** [comment]
> 

太谢谢了

**Comment by Nemo2011** [comment]
给 up_mid 就行了，所有收藏夹都在。

**Comment by gyhyfj** [comment]
> 给 up_mid 就行了，所有收藏夹都在。

求大佬给一个获取视频合集里的数据的api...

**Comment by lb-chc** [comment]
> ```json
> https://api.bilibili.com/x/v3/fav/folder/created/list-all
> ```

啊，项目里有的部分我倒是找到了，只是

**Comment by lb-chc** [comment]
> 对了，收藏夹是不是还没有给 API。
> 
> ```json
> "list_list": {
>       "url": "https://api.bilibili.com/x/v3/fav/folder/created/list-all",
>       "method": "GET",
>       "verify": false,
>       "params": {
>         "up_mid": "int: 用户 UID",
>         "type": "int?: 资源类型，2 视频。",
>         "rid": "int?: 资源 ID"
>       },
>       "comment": "获取收藏夹列表。提供 type 和 rid 时会同时提供对该资源收藏情况。"
>     }
> ```
项目里有的部分我倒是找到了，关于收藏，其实我想找“查询用户收藏的视频合集”

**Comment by lb-chc** [comment]
> 对了，收藏夹是不是还没有给 API。
> 
> ```json
> "list_list": {
>       "url": "https://api.bilibili.com/x/v3/fav/folder/created/list-all",
>       "method": "GET",
>       "verify": false,
>       "params": {
>         "up_mid": "int: 用户 UID",
>         "type": "int?: 资源类型，2 视频。",
>         "rid": "int?: 资源 ID"
>       },
>       "comment": "获取收藏夹列表。提供 type 和 rid 时会同时提供对该资源收藏情况。"
>     }
> ```

项目里有的部分我倒是找到了，关于收藏，其实我想找“查询用户收藏的视频合集”API，这个功能好像没见到有地方提过
<img width="186" alt="167056844-e9aed428-8c98-4cb5-b41c-b41281aa95c1" src="https://user-images.githubusercontent.com/69136546/180455336-053c5cd8-6992-43eb-9afa-924a5dfdeb24.png">

&type=21是从其他需要这个参数的API中找到的，算是瞎尝试失败了

**Comment by lb-chc** [comment]
> http://api.bilibili.com/x/polymer/space/seasons_series_list 获取所有合集与列表，包括新版，现在用的。 仓库里的 URL 只能获取旧版，还有用户频道即为合集与列表，可以自行示例。 这里有两个概念：season->season_id（新版）和series->series_id（旧版）

还想问一下它和来自https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/space.md#%E6%9F%A5%E8%AF%A2%E7%94%A8%E6%88%B7%E9%A2%91%E9%81%93%E5%88%97%E8%A1%A8

的http://api.bilibili.com/x/space/channel/list是什么关系，现在还有频道之说吗？
