### ISSUE TITLE
[API请求]请求加入剧集播放地址

### ISSUE THREAD

**Issue by QYTC233** [SocialSisterYi/bilibili-API-collect#386]
请求补充这个api具体作用及用法 https://api.bilibili.com/pgc/player/web/playurl?ep_id=&qn=

**Comment by Quandong-Zhang** [comment]
https://api.bilibili.com/pgc/player/web/playurl?avid={aid}&cid={cid}&qn={qn_id}&fnver=0&fnval=4048&fourk=1&ep_id={epid}&session={your_ssid} 
如： https://api.bilibili.com/pgc/player/web/playurl?avid=2325306&cid=3629601&qn=32&fnver=0&fnval=4048&fourk=1&ep_id=85046&session=

其中'''session'''为鉴权使用，大会员专属剧集必须 
其余参数参照普通视频，含义相同 
有空我开个pr完善下文档

**Comment by Quandong-Zhang** [comment]
#402

**Comment by QYTC233** [comment]
明白了，感谢

**Comment by ackerx** [comment]
> [https://api.bilibili.com/pgc/player/web/playurl?avid={aid}&cid={cid}&qn={qn_id}&fnver=0&fnval=4048&fourk=1&ep_id={epid}&session={your_ssid}](https://api.bilibili.com/pgc/player/web/playurl?avid=%7Baid%7D&cid=%7Bcid%7D&qn=%7Bqn_id%7D&fnver=0&fnval=4048&fourk=1&ep_id=%7Bepid%7D&session=%7Byour_ssid%7D) 如： https://api.bilibili.com/pgc/player/web/playurl?avid=2325306&cid=3629601&qn=32&fnver=0&fnval=4048&fourk=1&ep_id=85046&session=
> 
> 其中 _session_ 为鉴权使用，大会员专属剧集必须 其余参数参照普通视频，含义相同 有空我开个pr完善下文档

请问session的值应如何取得？文档中说session是“从视频播放页的网页源码中获取”，可是在页面中没有找到。直接搜session确实能找到一处，但其值与监听到的api请求中的session值不同。

**Comment by Quandong-Zhang** [comment]
@QYTC233 @SocialSisterYi  这个issue应该算是解决了，麻烦谁close下
