### ISSUE TITLE
求一个视频合集的获取api .... 好多up都会创建视频合集并且在里面不断更新，但是怎么都试不出接口

### ISSUE THREAD

**Issue by gyhyfj** [SocialSisterYi/bilibili-API-collect#404]

**Comment by catlair** [comment]
或许试试手机抓？

**Comment by lb-chc** [comment]
> https://api.bilibili.com/x/polymer/space/seasons_series_list?mid=8047632&page_num=1&page_size=20

非常有用，这个似乎还没写在项目里，我可以把它Pull到项目里吗？

**Comment by kmsshdxf** [comment]
有对16位uid相关的comment吗
