### ISSUE TITLE
关于./x/article/viewinfo的返回

### ISSUE THREAD

**Issue by MineCreeper86** [SocialSisterYi/bilibili-API-collect#41]
最近使用GET方法对比了带Cookie和不带Cookie情况下的**_api_/x/article/viewinfo*，，发现**response.data.is_author**值在不带Cookie情况下**总是为false**。
带Cookie：
`{"code":0,"message":"0","ttl":1,"data":{"like":0,"attention":false,"favorite":false,"coin":0,"stats":{"view":807325,"favorite":8699,"like":21028,"dislike":1,"reply":8587,"share":352,"coin":1574,"dynamic":79},"title":"未知的光","banner_url":"https://i0.hdslb.com/bfs/article/b1e1029c08d8ad1bb06460d736839a7741dd7925.jpg","mid":91221505,"author_name":"gggwvg","is_author":true,"image_urls":["https://i0.hdslb.com/bfs/article/d2eedf1fd338bceca10099e2f7b33fa9017c859b.jpg"],"origin_image_urls":["https://i0.hdslb.com/bfs/article/b1e1029c08d8ad1bb06460d736839a7741dd7925.jpg"],"shareable":true,"show_later_watch":true,"show_small_window":true,"in_list":true,"pre":4155124,"next":0,"share_channels":[{"name":"QQ","picture":"https://i0.hdslb.com/bfs/album/114ccfb3a999df9c4d11f274c8c61a804c8f8803.png","share_channel":"QQ"},{"name":"QQ空间","picture":"https://i0.hdslb.com/bfs/album/30e9608bbce725bca45b5910866f60ab4d5e18b3.png","share_channel":"QZONE"},{"name":"微信","picture":"https://i0.hdslb.com/bfs/album/658af3c22431cd78bb7c50be3394f7c032eba12c.png","share_channel":"WEIXIN"},{"name":"朋友圈","picture":"https://i0.hdslb.com/bfs/album/c1ebcec8c5302f29f792d15f04e0d6dcef53ec27.png","share_channel":"WEIXIN_MONMENT"},{"name":"微博","picture":"https://i0.hdslb.com/bfs/album/3707fc23f7d3e24022712320284b0de9aa78c87d.png","share_channel":"SINA"}]}}`
不带Cookie：
`{"code":0,"message":"0","ttl":1,"data":{"like":0,"attention":false,"favorite":false,"coin":0,"stats":{"view":807319,"favorite":8699,"like":21028,"dislike":1,"reply":8587,"share":352,"coin":1574,"dynamic":79},"title":"未知的光","banner_url":"https://i0.hdslb.com/bfs/article/b1e1029c08d8ad1bb06460d736839a7741dd7925.jpg","mid":91221505,"author_name":"gggwvg","is_author":false,"image_urls":["https://i0.hdslb.com/bfs/article/d2eedf1fd338bceca10099e2f7b33fa9017c859b.jpg"],"origin_image_urls":["https://i0.hdslb.com/bfs/article/b1e1029c08d8ad1bb06460d736839a7741dd7925.jpg"],"shareable":true,"show_later_watch":true,"show_small_window":true,"in_list":true,"pre":4155124,"next":0,"share_channels":[{"name":"QQ","picture":"https://i0.hdslb.com/bfs/album/114ccfb3a999df9c4d11f274c8c61a804c8f8803.png","share_channel":"QQ"},{"name":"QQ空间","picture":"https://i0.hdslb.com/bfs/album/30e9608bbce725bca45b5910866f60ab4d5e18b3.png","share_channel":"QZONE"},{"name":"微信","picture":"https://i0.hdslb.com/bfs/album/658af3c22431cd78bb7c50be3394f7c032eba12c.png","share_channel":"WEIXIN"},{"name":"朋友圈","picture":"https://i0.hdslb.com/bfs/album/c1ebcec8c5302f29f792d15f04e0d6dcef53ec27.png","share_channel":"WEIXIN_MONMENT"},{"name":"微博","picture":"https://i0.hdslb.com/bfs/album/3707fc23f7d3e24022712320284b0de9aa78c87d.png","share_channel":"SINA"}]}}`

**Comment by SocialSisterYi** [comment]
这个确实是个没用的参数，理论上应该是当前用户是否是该文章的作者，但服务登录的账号固定为`true`否则为`false`
