### ISSUE TITLE
获取用户动态信息

### ISSUE THREAD

**Issue by woshishabii** [SocialSisterYi/bilibili-API-collect#413]
类似这样的API的详细说明https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?host_mid=8047632

**Comment by SessionHu** [comment]
已经收录
https://github.com/SocialSisterYi/bilibili-API-collect/blob/41d73f1a20d856ffc5468243fbf17e5a35dc1a92/docs/dynamic/space.md?plain=1#L3
