### ISSUE TITLE
[求助]使用Typescript进行avid、bvid互转的方法

### ISSUE THREAD

**Issue by xingkongqwq** [SocialSisterYi/bilibili-API-collect#417]
在我尝试用Typescript进行avid、bvid互转时，无论输入什么，`bv2av`方法总是返回`av177451812`，这是为什么?
这是我代码的错误吗？
[代码地址](https://netcut.cn/p/898e28d14a0f598b)

**Comment by woshishabii** [comment]
实施直接调用 API?

**Comment by catlair** [comment]
form https://github.com/Traveler-Brian/BV-to-AV/blob/master/BiliBili%20BV%20to%20AV.user.js

```js
var isBV = false;

var table = 'fZodR9XQDSUm21yCkr6zBqiveYah8bt4xsWpHnJE7jL5VG3guMTKNPAwcF';
var tr = {};
for (var i = 0; i < 58; i++) {
  tr[table[i]] = i;
}
var s = [11, 10, 3, 8, 4, 6];
var xor = 177451812;
var add = 8728348608;
var final = '';

function toAV(fromBV) {
  var r = 0;
  for (var i = 0; i < 6; i++) {
    r += tr[fromBV[s[i]]] * Math.pow(58, i);
  }

  return (r - add) ^ xor;
}

```

**Comment by SocialSisterYi** [comment]
> 部分代码改得更像 ts （js）了。关键是 `r += this.TR[bv[this.S[i]]] * 58 ** i;` 而不是 `r += this.TABEL[bv[this.S[i]]] * 58 ** i;`
> 
> ```ts
> export default class IDUTIL {
>   private TABEL = 'fZodR9XQDSUm21yCkr6zBqiveYah8bt4xsWpHnJE7jL5VG3guMTKNPAwcF';
>   private TR: Record<string, number> = {};
>   private S = [11, 10, 3, 8, 4, 6];
>   private XOR = 177451812;
>   private ADD = 8728348608;
>   constructor() {
>     this.init();
>   }
>   init() {
>     const len = this.TABEL.length;
>     for (let i = 0; i < len; i++) {
>       this.TR[this.TABEL[i]] = i;
>     }
>   }
>   av2bv(av: number) {
>     const x_ = (av ^ this.XOR) + this.ADD;
>     const r = ['B', 'V', '1', , , '4', , '1', , '7'];
>     for (let i = 0; i < 6; i++) {
>       r[this.S[i]] = this.TABEL[Math.floor(x_ / 58 ** i) % 58];
>     }
>     return r.join('');
>   }
>   bv2av(bv: string) {
>     let r = 0;
>     for (let i = 0; i < 6; i++) {
>       r += this.TR[bv[this.S[i]]] * 58 ** i;
>     }
>     return 'av' + String((r - this.ADD) ^ this.XOR);
>   }
> }
> 
> const util = new IDUTIL();
> 
> console.log(util.bv2av('BV1tS4y1J7vr'));
> console.log(util.av2bv(728375003));
> 
> console.log(util.bv2av('BV1gT4y1q7FP'));
> console.log(util.av2bv(939262727));
> ```

感谢提供，直接加入文档
