### ISSUE TITLE
兄弟们有没有不需要使用防盗链的接口

### ISSUE THREAD

**Issue by zimoyin** [SocialSisterYi/bilibili-API-collect#419]
有没有不需要设置referer就能下载视频的接口呢，最好清晰度大于360p的

**Comment by ElieenAndBella** [comment]
you-get（：

**Comment by Quandong-Zhang** [comment]
> 有没有不需要设置referer就能下载视频的接口呢，最好清晰度大于360p的

没有大于360P的 
之前我好像发现过一个，但清晰度贼阴间，就没加（好像刚好360P）
#250

**Comment by Quandong-Zhang** [comment]
> you-get（：

还有哥们，不知道不要乱说哦 
youget是个python pip ，命令行下载视频的 
他用的api都是正常要refer的.....

**Comment by ElieenAndBella** [comment]
> > you-get（：
> 
> 还有哥们，不知道不要乱说哦 youget是个python pip ，命令行下载视频的 他用的api都是正常要refer的.....

我知道啊，我的意思是他自己下载下来😂

**Comment by zimoyin** [comment]
> > 有没有不需要设置referer就能下载视频的接口呢，最好清晰度大于360p的
> 
> 没有大于360P的 之前我好像发现过一个，但清晰度贼阴间，就没加（好像刚好360P） #250

有个网站用的接口清晰度比较高：https://bilibili.iiilab.com/
但是我不知道他用的什么接口，所以才来问问QWQ

**Comment by Quandong-Zhang** [comment]
> > > 有没有不需要设置referer就能下载视频的接口呢，最好清晰度大于360p的
> > 
> > 
> > 没有大于360P的 之前我好像发现过一个，但清晰度贼阴间，就没加（好像刚好360P） #250
> 
> 有个网站用的接口清晰度比较高：https://bilibili.iiilab.com/ 但是我不知道他用的什么接口，所以才来问问QWQ

一言以蔽之：反代 
可以Google搜搜反代B站视频之类的，有一堆教程 
本质上就是把你的HTTP请求头上的referer改成bilibili.com，之后再转发到视频服务器上

**Comment by SocialSisterYi** [comment]
听说加上什么platform=h5就可以不验证referer，但是没有实测过，应该不准确

**Comment by zimoyin** [comment]
> 



> 听说加上什么platform=h5就可以不验证referer，但是没有实测过，应该不准确

确实不行

**Comment by Quandong-Zhang** [comment]
> 听说加上什么platform=h5就可以不验证referer，但是没有实测过，应该不准确

不一定
![image](https://user-images.githubusercontent.com/78526012/180591024-76296a04-e7cd-4b16-9cd2-9f65b14584e5.png)
</br>
这个就是不需要refer就能get1080视频的参数之一

**Comment by sainmu** [comment]
@Quandong-Zhang 

> > 听说加上什么platform=h5就可以不验证referer，但是没有实测过，应该不准确
> 
> 不一定 ![image](https://user-images.githubusercontent.com/78526012/180591024-76296a04-e7cd-4b16-9cd2-9f65b14584e5.png) 这个就是不需要refer就能get1080视频的参数之一

能告知下其他还有那些参数么？万分感谢！
