### ISSUE TITLE
文集信息相关

### ISSUE THREAD

**Issue by MineCreeper86** [SocialSisterYi/bilibili-API-collect#42]
https://api.bilibili.com/x/article/list/web/articles?id=_文集id_&jsonp=jsonp

**Comment by MineCreeper86** [comment]
我已经开始写关于这个的markdown了，具体在我的fork里

**Comment by SocialSisterYi** [comment]
写完了记得PR过来，谢谢啦qaq

**Comment by MineCreeper86** [comment]
这个issue可以关闭了
