### ISSUE TITLE
查询关系接口失效还是示例写错了

### ISSUE THREAD

**Issue by Qaplagzy** [SocialSisterYi/bilibili-API-collect#423]
你好 这个接口

<img width="300" alt="截屏2022-07-22 18 13 58" src="https://user-images.githubusercontent.com/44153730/180418122-198aea27-b2c8-4093-a8bb-4e53ed7d8ae1.png">

我看示例是写成了 ` http://http://xxxx" ` 用这种写法 会报错 ` curl: (6) Could not resolve host: http `

如果我写成  ` http://xxxxx" ` 就拿不到data  返回null 单个和批量都是如此
例如 
` {"code":0,"message":"0","ttl":1,"data":null}% `

请问是示例写法有问题还是接口过期了 谢谢

**Comment by catlair** [comment]
http://http://xxxx" 肯定是错的，测试了 https://api.bilibili.com/x/relation?fid=2 是没有问题的

**Comment by Qaplagzy** [comment]
你好 我重试了 结果和之前一样 我明明关注了 查询结果还是0 这个fid就是uid对吗

**Comment by catlair** [comment]
这个接口是查询你与别人的关系，fid就是uid。
如果要互查，文档中这个接口下一个就是啊，不过是把fid换成了mid
