### ISSUE TITLE
获取历史记录列表（视频、直播、专栏）

### ISSUE THREAD

**Issue by guzhidefeifeiyu** [SocialSisterYi/bilibili-API-collect#429]
http://api.bilibili.com/x/web-interface/history/cursor，
max，view_at 两个参数都有时参数才会生效。
business参数类型为string。
参数的内容表述不太清楚，我认为应该是以max，view_at为查询历史记录的起点，查询更早观看的ps条历史记录

**Comment by SocialSisterYi** [comment]
这个接口类似链表的索引而与翻页不同，是给历史记录列表IFS用的，`business` `max` `view_at`这几个参数都是列表尾部的数据
