### ISSUE TITLE
我发现那个发弹幕的API有改动

### ISSUE THREAD

**Issue by Mart20191012** [SocialSisterYi/bilibili-API-collect#43]
"rnd"为时间戳*1000000
Python实现为：round(time.time() * 1000000)

**Comment by Mart20191012** [comment]
这是我在写一个关于弹幕的程序的过程中发现的，应该没问题

**Comment by SocialSisterYi** [comment]
已收到，下次更新时修改

**Comment by SocialSisterYi** [comment]
已经改好了

**Comment by kebufu** [comment]
rnd不是random的缩写吗？

**Comment by SocialSisterYi** [comment]
> rnd不是random的缩写吗？

是啊，只要和上一次的值不同就不会限制冷却时间，用时间戳就是每次都不同

**Comment by kebufu** [comment]
> > rnd不是random的缩写吗？
> 
> 是啊，只要和上一次的值不同就不会限制冷却时间，用时间戳就是每次都不同

懂了
