### ISSUE TITLE
如何获取access key

### ISSUE THREAD

**Issue by XC-Qan** [SocialSisterYi/bilibili-API-collect#433]
翻了一大堆api愣是没找到app账号密码登录的api
顺便问一下kotlin/java怎么用指定的公钥加密内容
（其实就是#368没看明白

**Comment by catlair** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/QR.md#%E7%94%B3%E8%AF%B7%E4%BA%8C%E7%BB%B4%E7%A0%81url%E5%8F%8A%E6%89%AB%E7%A0%81%E5%AF%86%E9%92%A5tv%E7%AB%AF

**Comment by XC-Qan** [comment]
是，，什么意思呐
扫码登录已经会啦，就是想要获取access key，这样就能用app端的首页。Web端首页的视频筛选貌似有点苛刻，获取到的都是比较老的视频。app端的新一点。
但是感谢大佬的答案

**Comment by XC-Qan** [comment]
抱歉是我眼瞎没看见上面还有几行
