### ISSUE TITLE
如何获取up主ip归属地

### ISSUE THREAD

**Issue by wwchy** [SocialSisterYi/bilibili-API-collect#434]

**Comment by SCUTJcfeng** [comment]
app里面有，谁有空可以抓一下包就知道了

**Comment by SCUTJcfeng** [comment]
`https://app.bilibili.com/x/v2/space`
![image](https://user-images.githubusercontent.com/14869384/184118113-853de8e6-9b5d-4876-a316-7e738a80d262.png)
需要校验用户key信息

**Comment by gouku** [comment]
@SCUTJcfeng 请问这是什么抓包工具

**Comment by Creator2K** [comment]
@gouku  Stream

**Comment by SocialSisterYi** [comment]
安卓端也可以用小黄鸟抓

**Comment by dongdigua** [comment]
仔细说一下这个接口怎么使用呗, 然后加进文档里
(我完全不用客户端)

**Comment by chenffep** [comment]
手机没root应该不能用小黄鸟吧，现在各家手机厂商基本都锁bl了

**Comment by Nova-Noir** [comment]
> 安卓端也可以用小黄鸟抓

小黄鸟不会 ssl-pinning 拦截么？Android13，用 lsposed + TrustMeAlready 或者 JustTrustMe 这两个插件也还是只能获取到部分，对于 `api.bilibili.com/*` 的包啥都拿不到。

难道现在安卓只能直接改原 apk 文件来 bypass ssl pinning 吗？

**Comment by cxw620** [comment]
> > 安卓端也可以用小黄鸟抓
> 
> 小黄鸟不会 ssl-pinning 拦截么？Android13，用 lsposed + TrustMeAlready 或者 JustTrustMe 这两个插件也还是只能获取到部分，对于 `api.bilibili.com/*` 的包啥都拿不到。
> 
> 难道现在安卓只能直接改原 apk 文件来 bypass ssl pinning 吗？

android11一切正常, 可能是系统版本问题? 可以去lsposed的仓库那提个issue. 
P.S. 我在用Charles, 没试过小黄鸟. 设备是Android 11的Pixel 2 XL, 使用Magisk+LSPosed搭配TrustMeAlready, 优化对象把系统框架也勾上. 没试过小黄鸟.

**Comment by Nova-Noir** [comment]
> > > 安卓端也可以用小黄鸟抓
> > 
> > 小黄鸟不会 ssl-pinning 拦截么？Android13，用 lsposed + TrustMeAlready 或者 JustTrustMe 这两个插件也还是只能获取到部分，对于 `api.bilibili.com/*` 的包啥都拿不到。
> > 
> > 难道现在安卓只能直接改原 apk 文件来 bypass ssl pinning 吗？
> 
> android11一切正常, 可能是系统版本问题? 可以去lsposed的仓库那提个issue. 
> P.S. 我在用Charles, 没试过小黄鸟. 设备是Android 11的Pixel 2 XL, 使用Magisk+LSPosed搭配TrustMeAlready, 优化对象把系统框架也勾上. 没试过小黄鸟. 

成功了。可能是我两个模块都安装了的原因，又或者我更新之后没有重启的原因，
一开始勾选了系统框架仍然不能抓取。

尝试卸载了 JustTrustMe 只留下 TrustMeAlready 并且配置作用域包含系统框架后，重启系统，这次抓取成功了，谢谢！

**Comment by cxw620** [comment]
> > > > 安卓端也可以用小黄鸟抓
> > > 
> > > 
> > > 小黄鸟不会 ssl-pinning 拦截么？Android13，用 lsposed + TrustMeAlready 或者 JustTrustMe 这两个插件也还是只能获取到部分，对于 `api.bilibili.com/*` 的包啥都拿不到。
> > > 难道现在安卓只能直接改原 apk 文件来 bypass ssl pinning 吗？
> > 
> > 
> > android11一切正常, 可能是系统版本问题? 可以去lsposed的仓库那提个issue.
> > P.S. 我在用Charles, 没试过小黄鸟. 设备是Android 11的Pixel 2 XL, 使用Magisk+LSPosed搭配TrustMeAlready, 优化对象把系统框架也勾上. 没试过小黄鸟.
> 
> 成功了。可能是我两个模块都安装了的原因，又或者我更新之后没有重启的原因， 一开始勾选了系统框架仍然不能抓取。
> 
> 尝试卸载了 JustTrustMe 只留下 TrustMeAlready 并且配置作用域包含系统框架后，重启系统，这次抓取成功了，谢谢！

应该是没重启. 一开始我也没注意到这一点, 还一直以为是证书问题, 结果重启歪打正着.
结论: **LSPosed启用TrustMeAlready模块并优化应用后需要重启才生效**
