### ISSUE TITLE
视频搜索方式已失效

### ISSUE THREAD

**Issue by thevenomsnake** [SocialSisterYi/bilibili-API-collect#435]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/search/search_request.md

`curl -G 'http://api.bilibili.com/x/web-interface/search/type' \
--data-urlencode 'search_type=video' \
--data-urlencode 'keyword=少年' \
--data-urlencode 'order=totalrank' \
--data-urlencode 'duration=0' \
--data-urlencode 'tids=0' \
--data-urlencode 'page=1' \
-b 'SESSDATA=xxx'`

响应
{"code":-400,"message":"Key: 'SearchTypeArg.SearchType' Error:Field validation for 'SearchType' failed on the 'required' tag\nKey: 'SearchTypeArg.Keyword' Error:Field validation for 'Keyword' failed on the 'required' tag","ttl":1}

**Comment by wuziqian211** [comment]
将`\`去掉

**Comment by Sualiu** [comment]
首先呐，反斜杠 \ 用于分隔cURL中的选项，这个没有任何问题，整体看上去，除了复制粘贴的时候没有排版换行外，都没啥问题。

**但是**

--data-urlencode 命令，官方文档明确有写：

如果在**同一命令行上多次使用--data-urlencode**，则指定的数据片段将与分隔符 &-symbol 合并。因此，使用'-d name=daniel -d skill=lousy'会生成一个看起来像'name=daniel&skill=lousy'的帖子块。

他啊，必须得是同一命令行......否则只会读取首个 --data-urlencode命令，剩下的他都不要。

你这是命令出错了。

**Comment by Sualiu** [comment]
**笑死了.....不.....哭死我了。**

**你这就是格式出错了，不是其他问题，想了好久好久，也是挺无语的。**

**看好了，这是你发的命令行：**
`curl -G 'http://api.bilibili.com/x/web-interface/search/type' \ --data-urlencode 'search_type=video' \ --data-urlencode 'keyword=少年' \ --data-urlencode 'order=totalrank' \ --data-urlencode 'duration=0' \ --data-urlencode 'tids=0' \ --data-urlencode 'page=1' \ -b 'SESSDATA=xxx'`

**你应该是复制粘贴的时候没有排版，让我们排版：**
![image](https://user-images.githubusercontent.com/42514208/185107894-1c31e2e3-74fd-45d1-8f58-f398e4ab7d2b.png)
从这个 -- 前面开始空格，按回车
```
curl -G 'http://api.bilibili.com/x/web-interface/search/type' \ 
--data-urlencode 'search_type=video' \ 
--data-urlencode 'keyword=少年' \ 
--data-urlencode 'order=totalrank' \ 
--data-urlencode 'duration=0' \ 
--data-urlencode 'tids=0' \ 
--data-urlencode 'page=1' \ 
-b 'SESSDATA=xxx'
```
**看上去没有问题，但是，这个 \ 反斜杠后面还有一个空格.....而curl是单行命令，所以......知道了吧。**
![image](https://user-images.githubusercontent.com/42514208/185108869-cf84a0e7-91d9-4655-9ed5-d2d7ee377358.png)



下次注意点就行。

**Comment by thevenomsnake** [comment]
感谢指正
