### ISSUE TITLE
关于关注者api无法获取第1000个关注者之后的关注者

### ISSUE THREAD

**Issue by POPCORNBOOM** [SocialSisterYi/bilibili-API-collect#44]
*SESSDATA已添加至请求头
*SESSDATA拥有者的关注者总数148993

问题描述：在请求http://api.bilibili.com/x/relation/followers?vmid=487763254&pn=21和http://api.bilibili.com/x/relation/followers?vmid=487763254&pn=1001&ps=1时反馈{"code":0,"message":"0","ttl":1,"data":{"list":[],"re_version":0,"total":148993}}
第1001个关注者及以后关注者应该都没有信息。

![775RI W2A3YOR~N@{@Q47%B](https://user-images.githubusercontent.com/47022281/89730570-5d9e3e00-da72-11ea-813c-f33b53e53d29.png)
![1BKI8 06A6D69FPJ3 X(LU7](https://user-images.githubusercontent.com/47022281/89730574-6727a600-da72-11ea-8dc6-1d3f278bc5a2.png)

**Comment by POPCORNBOOM** [comment]
在写关于粉丝获取的程序时发现的

**Comment by duzhaokun123** [comment]
是up本人吗，
我看了一下
不是的话有限制，只能看前5页一页20个也就是1000个
是的话我不知道

**Comment by POPCORNBOOM** [comment]
> 是up本人吗，
> 我看了一下
> 不是的话有限制，只能看前5页一页20个也就是1000个
> 是的话我不知道

我不是那个uid的主人，不过我有主人的登入cookie（SESSDATA）
我可以获得20页内容（默认一页50个），不过后面的页数就不行了

还有，5x20不是100吗？？

**Comment by duzhaokun123** [comment]
算错了，当我没说好了
我在网站上只能看5页，后面说系统限制不让看

**Comment by SocialSisterYi** [comment]
非本人限制只能看前5页，本人限制只能看前50页，也就是如果粉丝多于1k后面的为不可见，是否本人使用cookie认证
可以看何同学那个粉丝墙的视频，他的信息来源不是直接抓取，而是问B站要的，B站的直接导出数据库

**Comment by POPCORNBOOM** [comment]
> 非本人限制只能看前5页，本人限制只能看前50页，也就是如果粉丝多于1k后面的为不可见，是否本人使用cookie认证
> 可以看何同学那个粉丝墙的视频，他的信息来源不是直接抓取，还是问B站要的，B站的直接转换数据库

明白了，谢谢
