### ISSUE TITLE
求教如何更新cookies信息

### ISSUE THREAD

**Issue by 7rikka** [SocialSisterYi/bilibili-API-collect#456]
最近阿b的网页端cookies有效期变短了，每次过期都要手动更新。自己正常使用浏览器浏览，登录状态是不会掉的。求教用接口怎么收到最新的cookies信息。

**Comment by catlair** [comment]
很简单，那你就不要在浏览器正常使用他就不会刷刷新了（获取cookie的时候用隐私窗口获取）🤣

如果你确实想要无聊的刷新，给你个提示 
![image](https://user-images.githubusercontent.com/44313800/185978226-e776de6e-febd-433c-844e-e2108bbfb935.png)

![image](https://user-images.githubusercontent.com/44313800/185977922-e4590cc5-08e4-4acf-83e9-8d7b30a58cfb.png)

![image](https://user-images.githubusercontent.com/44313800/185978095-62642022-768b-4443-a003-9d1c32443975.png)

![image](https://user-images.githubusercontent.com/44313800/185978309-4bb5d66f-5c0b-4c93-ac2c-df8e7f71bcf0.png)

**Comment by catlair** [comment]
很简单，那你就不要在浏览器正常使用他就不会刷新了（获取cookie的时候用隐私窗口获取）🤣

如果你确实想要无聊的刷新，给你个提示 

1. 登录获取到 cookie，通过 cookie 去请求 refresh_token 并保存到 localStorage ac_time_value
2. 访问b 站某些页面（www,space等），就会去请求 info 接口，获取到是否刷新和 timestamp
3. 如果需要刷新，将 timestamp 进行一系列 hash 最后作为 url 的路径去请求 refresh_csrf
4. 用 refresh_token refresh_csrf csrf 请求刷新接口，返回 set-cookie 和新的 refresh_token 
5. 请求刷新链接列表，获取 bigfun 等网站的 set-cookie （可忽略）
6. 调用确认 refresh_token  的接口，原 cookie 和 refresh_token  失效。

部分接口如下：

![image](https://user-images.githubusercontent.com/44313800/185978226-e776de6e-febd-433c-844e-e2108bbfb935.png)

![image](https://user-images.githubusercontent.com/44313800/185978095-62642022-768b-4443-a003-9d1c32443975.png)

![image](https://user-images.githubusercontent.com/44313800/185977922-e4590cc5-08e4-4acf-83e9-8d7b30a58cfb.png)

![image](https://user-images.githubusercontent.com/44313800/185981251-844d8f0c-01ae-429a-90dd-b688ee75258a.png)


（而且你把刷新弄出来浏览器登录状态就掉了）

**Comment by 7rikka** [comment]
> 很简单，那你就不要在浏览器正常使用他就不会刷新了（获取cookie的时候用隐私窗口获取）🤣
> 
> 如果你确实想要无聊的刷新，给你个提示
> 
> 1. 登录获取到 cookie，通过 cookie 去请求 refresh_token 并保存到 localStorage ac_time_value
> 2. 访问b 站某些页面（www,space等），就会去请求 info 接口，获取到是否刷新和 timestamp
> 3. 如果需要刷新，将 timestamp 进行一系列 hash 最后作为 url 的路径去请求 refresh_csrf
> 4. 用 refresh_token refresh_csrf csrf 请求刷新接口，返回 set-cookie 和新的 refresh_token
> 5. 请求刷新链接列表，获取 bigfun 等网站的 set-cookie （可忽略）
> 6. 调用确认 refresh_token  的接口，原 cookie 和 refresh_token  失效。
> 
> 部分接口如下：
> 
> ![image](https://user-images.githubusercontent.com/44313800/185978226-e776de6e-febd-433c-844e-e2108bbfb935.png)
> 
> ![image](https://user-images.githubusercontent.com/44313800/185978095-62642022-768b-4443-a003-9d1c32443975.png)
> 
> ![image](https://user-images.githubusercontent.com/44313800/185977922-e4590cc5-08e4-4acf-83e9-8d7b30a58cfb.png)
> 
> ![image](https://user-images.githubusercontent.com/44313800/185981251-844d8f0c-01ae-429a-90dd-b688ee75258a.png)
> 
> （而且你把刷新弄出来浏览器登录状态就掉了）

Nice 我先研究研究

**Comment by catlair** [comment]
补充最后两个的两个接口

![image](https://user-images.githubusercontent.com/44313800/186345395-fdb1751c-f0fb-4017-83a8-fa02f82c60bb.png)

![image](https://user-images.githubusercontent.com/44313800/186345505-2947985f-6cdd-419f-9e94-3769a7d1cd4a.png)

请求 refresh_csrf 所用 hash 的计算程序

https://s1.hdslb.com/bfs/static/jinkela/long/wasm/wasm_rsa_encrypt_bg.wasm

 https://s1.hdslb.com/bfs/static/jinkela/long/wasm/wasm_ras_umd.js

**Comment by catlair** [comment]
大佬是研究出来了？

**Comment by 7rikka** [comment]
> 大佬是研究出来了？

上次用无痕模式登录的cookie现在还能用，就不折腾这么多了

**Comment by ShiinaMono** [comment]
扫码登录用的post请求，没法获取cookie(uuid等，而jct和sessdata和token没影响)，请问有大佬有思路吗

**Comment by cxw620** [comment]
我写了个Python的, 用Pushplus推送二维码图片到手机, 保存二维码到相册扫码登录. 目前稳定一个月没让重新登陆, 也就懒得写刷新cookie的部分了. 纯新手, 欢迎批评指正
```python
def push():
    # pushplus推送模块
    pass

def plog():
    # 自己写的日志模块
    pass

def login(_needLogin: bool = False) -> dict:
    # 参考API文档: https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/QR.md
    if _needLogin:
        plog(f"登录Bilibili...")
        LOGIN_API_HOST = (
            "http://passport.bilibili.com/x/passport-login/web/qrcode/generate"
        )
        RESULT_API_HOST = (
            "http://passport.bilibili.com/x/passport-login/web/qrcode/poll"
        )
        _session_login = requests.Session()
        _session_login.headers.update({"user-agent": USER_AGENT})
        _qr_code_info = _session_login.get(LOGIN_API_HOST).json()
        if _qr_code_info["code"] == 0:
            # 有效期180s
            _login_time_limit_int = int(time.time()) + 160
            _url_of_qrcode_str = _qr_code_info["data"]["url"]
            _oauth_key_str = _qr_code_info["data"]["qrcode_key"]
            _qrcode_img_data = qrcode.make(data=_url_of_qrcode_str)
            with open("qrcode.png", "wb") as f:
                _qrcode_img_data.save(f)
            with open("qrcode.png", "rb") as f:
                _qrcode_base64_str = base64.b64encode(f.read()).decode(encoding="utf-8")
            _content = f"""<div><h4 style='font-size:bold'>Accesskey失效! Bilibili扫码登陆~</h4><img src="data:image/jpg;base64,{_qrcode_base64_str}"/></div>"""
            push(_content, "Bilibili扫码登陆")
            _finalCookieDict = {}
            _final_login_json_result = _session_login.get(
                RESULT_API_HOST + "?qrcode_key=" + _oauth_key_str
            ).json()
            while True:
                if int(time.time()) < _login_time_limit_int:
                    _final_login_json_result = _session_login.get(
                        RESULT_API_HOST + "?qrcode_key=" + _oauth_key_str
                    ).json()
                    _rsp_code = str(_final_login_json_result["data"]["code"])
                    if _rsp_code == "0":
                        plog("登陆成功!")
                        LOGIN_COOKIES_DICT = dict(_session_login.cookies.items())
                        _finalCookieDict = {
                            "DedeUserID": LOGIN_COOKIES_DICT["DedeUserID"],
                            "DedeUserID__ckMd5": LOGIN_COOKIES_DICT[
                                "DedeUserID__ckMd5"
                            ],
                            "SESSDATA": urllib.parse.unquote(
                                LOGIN_COOKIES_DICT["SESSDATA"]
                            ),
                        }
                        break
                    else:
                        plog(f"等待扫码确认中... {_rsp_code}")
                        time.sleep(10)
                else:
                    plog(
                        f"二维码过或其他问题, 服务器返回 -> {_final_login_json_result['data']['message']}, 程序退出"
                    )
                    exit(1)
            if _finalCookieDict:
                with open(f"{EXEC_PATH}/cookies.json", "w", encoding="utf-8") as f:
                    f.write(json.dumps(_finalCookieDict))
            return _finalCookieDict
        else:
            plog(f"获取二维码失败, 返回message: {_qr_code_info['message']}")
            exit(1)
    else:
        if os.path.exists(f"{EXEC_PATH}/cookies.json"):
            with open(f"{EXEC_PATH}/cookies.json", "r", encoding="utf-8") as f:
                _finalCookieDict = json.loads(f.read())
                return _finalCookieDict
        else:
            return ""
plog(f"获取AccessKey...")
_cookieDict = login()
if not _cookieDict:
    _cookieDict = login(True)
session_getAccessKey = requests.Session()
session_getAccessKey.headers.update({"user-agent": USER_AGENT})
session_getAccessKey.headers.update(_cookieDict)
_ = "api=http://link.acg.tv/forum.php" + "c2ed53a74eeefe3cf99fbd01d8c9c375"
_ = _.encode()
query = {
    "appkey": "27eb53fc9058f8c3",
    "api": "http://link.acg.tv/forum.php",
    "sign": hashlib.md5(_).hexdigest(),
}
REDIRECT_API_HOST = f"https://passport.bilibili.com/login/app/third?{urlencode(query)}"
try:
    SESSDATA = _cookieDict["SESSDATA"]
    DedeUserID = _cookieDict["DedeUserID"]
    resp_redirect = requests.get(
        REDIRECT_API_HOST,
        headers={
            "cookie": f"SESSDATA={SESSDATA};DedeUserID={DedeUserID}",
            "user-agent": USER_AGENT,
        },
    ).json()
    confirm_uri = resp_redirect["data"]["confirm_uri"]
    final_redirect_uri = requests.get(
        confirm_uri,
        headers={
            "cookie": f"SESSDATA={SESSDATA};DedeUserID={DedeUserID}",
            "user-agent": USER_AGENT,
        },
        allow_redirects=False,
    ).headers["Location"]
    global ACCESS_KEY
    ACCESS_KEY = urlparse(final_redirect_uri).query.split("&")[0].split("=")[-1]
    plog(f"获取AccessKey成功: {ACCESS_KEY}")
except Exception as e:
    plog(f"获取AccessKey失败: {e.args}")
    exit(1)
```

**Comment by catlair** [comment]
> 写了个Python的简单实现, 用pushplus推送二维码图片到手机, 保存二维码到相册扫码登录. 登陆后保存cookie文本到本地. 目前稳定一个月没让重新登陆, 也就懒得写刷新cookie的部分了. 改改还可以保存完整的cookie, 只不过我原来只需要SESSDATA和DedeUserID就只存了这两个. 纯新手, 欢迎批评指正.
> 
> ```python
> import time
> import json
> # requirement: pip install qrcode, pip install Image
> import qrcode
> import urllib.parse
> from urllib.parse import urlencode
> from urllib.parse import urlparse
> import requests
> 
> def push():
>     # pushplus推送模块
>     pass
> 
> def plog():
>     # 自己写的日志模块
>     pass
> 
> def login(_needLogin: bool = False) -> dict:
>     # 参考API文档: https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/login_action/QR.md
>     if _needLogin:
>         plog(f"登录Bilibili...")
>         LOGIN_API_HOST = (
>             "http://passport.bilibili.com/x/passport-login/web/qrcode/generate"
>         )
>         RESULT_API_HOST = (
>             "http://passport.bilibili.com/x/passport-login/web/qrcode/poll"
>         )
>         _session_login = requests.Session()
>         _session_login.headers.update({"user-agent": USER_AGENT})
>         _qr_code_info = _session_login.get(LOGIN_API_HOST).json()
>         if _qr_code_info["code"] == 0:
>             # 有效期180s
>             _login_time_limit_int = int(time.time()) + 160
>             _url_of_qrcode_str = _qr_code_info["data"]["url"]
>             _oauth_key_str = _qr_code_info["data"]["qrcode_key"]
>             _qrcode_img_data = qrcode.make(data=_url_of_qrcode_str)
>             with open("qrcode.png", "wb") as f:
>                 _qrcode_img_data.save(f)
>             with open("qrcode.png", "rb") as f:
>                 _qrcode_base64_str = base64.b64encode(f.read()).decode(encoding="utf-8")
>             _content = f"""<div><h4 style='font-size:bold'>Accesskey失效! Bilibili扫码登陆~</h4><img src="data:image/jpg;base64,{_qrcode_base64_str}"/></div>"""
>             push(_content, "Bilibili扫码登陆")
>             _finalCookieDict = {}
>             _final_login_json_result = _session_login.get(
>                 RESULT_API_HOST + "?qrcode_key=" + _oauth_key_str
>             ).json()
>             while True:
>                 if int(time.time()) < _login_time_limit_int:
>                     _final_login_json_result = _session_login.get(
>                         RESULT_API_HOST + "?qrcode_key=" + _oauth_key_str
>                     ).json()
>                     _rsp_code = str(_final_login_json_result["data"]["code"])
>                     if _rsp_code == "0":
>                         plog("登陆成功!")
>                         LOGIN_COOKIES_DICT = dict(_session_login.cookies.items())
>                         _finalCookieDict = {
>                             "DedeUserID": LOGIN_COOKIES_DICT["DedeUserID"],
>                             "DedeUserID__ckMd5": LOGIN_COOKIES_DICT[
>                                 "DedeUserID__ckMd5"
>                             ],
>                             "SESSDATA": urllib.parse.unquote(
>                                 LOGIN_COOKIES_DICT["SESSDATA"]
>                             ),
>                         }
>                         break
>                     else:
>                         plog(f"等待扫码确认中... {_rsp_code}")
>                         time.sleep(10)
>                 else:
>                     plog(
>                         f"二维码过或其他问题, 服务器返回 -> {_final_login_json_result['data']['message']}, 程序退出"
>                     )
>                     exit(1)
>             if _finalCookieDict:
>                 with open(f"{EXEC_PATH}/cookies.json", "w", encoding="utf-8") as f:
>                     f.write(json.dumps(_finalCookieDict))
>             return _finalCookieDict
>         else:
>             plog(f"获取二维码失败, 返回message: {_qr_code_info['message']}")
>             exit(1)
>     else:
>         if os.path.exists(f"{EXEC_PATH}/cookies.json"):
>             with open(f"{EXEC_PATH}/cookies.json", "r", encoding="utf-8") as f:
>                 _finalCookieDict = json.loads(f.read())
>                 return _finalCookieDict
>         else:
>             return ""
> plog(f"获取AccessKey...")
> _cookieDict = login()
> if not _cookieDict:
>     _cookieDict = login(True)
> session_getAccessKey = requests.Session()
> session_getAccessKey.headers.update({"user-agent": USER_AGENT})
> session_getAccessKey.headers.update(_cookieDict)
> _ = "api=http://link.acg.tv/forum.php" + "c2ed53a74eeefe3cf99fbd01d8c9c375"
> _ = _.encode()
> query = {
>     "appkey": "27eb53fc9058f8c3",
>     "api": "http://link.acg.tv/forum.php",
>     "sign": hashlib.md5(_).hexdigest(),
> }
> REDIRECT_API_HOST = f"https://passport.bilibili.com/login/app/third?{urlencode(query)}"
> try:
>     SESSDATA = _cookieDict["SESSDATA"]
>     DedeUserID = _cookieDict["DedeUserID"]
>     resp_redirect = requests.get(
>         REDIRECT_API_HOST,
>         headers={
>             "cookie": f"SESSDATA={SESSDATA};DedeUserID={DedeUserID}",
>             "user-agent": USER_AGENT,
>         },
>     ).json()
>     confirm_uri = resp_redirect["data"]["confirm_uri"]
>     final_redirect_uri = requests.get(
>         confirm_uri,
>         headers={
>             "cookie": f"SESSDATA={SESSDATA};DedeUserID={DedeUserID}",
>             "user-agent": USER_AGENT,
>         },
>         allow_redirects=False,
>     ).headers["Location"]
>     global ACCESS_KEY
>     ACCESS_KEY = urlparse(final_redirect_uri).query.split("&")[0].split("=")[-1]
>     plog(f"获取AccessKey成功: {ACCESS_KEY}")
> except Exception as e:
>     plog(f"获取AccessKey失败: {e.args}")
>     exit(1)
> ```

cookie不会主动去刷新，除非改密码或者风控。想法不错，但似乎与cookie刷新无关
