### ISSUE TITLE
TV版的app_id能用来请求普通的影视资源吗？

### ISSUE THREAD

**Issue by pboymt** [SocialSisterYi/bilibili-API-collect#46]
RT，我记得电视大会员好像是要单独开的？

**Comment by daofeng2015** [comment]
大会员取决你access_key吧.appkey和appsecret全平台通用.就是电视的api地址不一样而已吧

**Comment by SocialSisterYi** [comment]
判定是否为大会员使用的是access_key或cookie与你用什么appkey无关，但部分tv端接口需要使用专用appkey
