### ISSUE TITLE
针对今天b站搜索api失效的解决方案

### ISSUE THREAD

**Issue by XC-Qan** [SocialSisterYi/bilibili-API-collect#460]
省流：先GET一遍 https://bilibili.com 以获取cookies

今天写app的时候，啪的一下发现搜索功能不能用了，返回值如下：
```json
{
    "code": -412,
    "message": "请求被拦截",
    "ttl": 1,
    "data": null
}
```
一开始以为是登录失效的问题，后来发现web端在搜索的时候有一大堆cookies。
<img width="638" alt="image" src="https://user-images.githubusercontent.com/60663465/186456708-36f19b36-66c0-4135-8291-09adae2948aa.png">
后来发现把cookies都删掉再请求首页就会set一大堆所需的cookies。

建议易姐在search_request.md中加上

**Comment by zimoyin** [comment]
在我的实现里面有两个搜索搜索一个寄了（-412）一个没寄，一直不知道原因，我试试大佬的方法能不能救活他

**Comment by zimoyin** [comment]
> 在我的实现里面有两个搜索搜索一个寄了（-412）一个没寄，一直不知道原因，我试试大佬的方法能不能救活他

我寄了

**Comment by zimoyin** [comment]
其实是能用的，可能你代码有问题（来自一个同样问题的人，因为错把请求头当成了参数而传递的二货发言）

**Comment by XC-Qan** [comment]
postman也不行，参数一直没动过

**Comment by XC-Qan** [comment]
> 其实是能用的，可能你代码有问题（来自一个同样问题的人，因为错把请求头当成了参数而传递的二货发言）

不知是我，还有个大佬的搜索那天也寄了

**Comment by zimoyin** [comment]
> > 其实是能用的，可能你代码有问题（来自一个同样问题的人，因为错把请求头当成了参数而传递的二货发言）
> 
> 不知是我，还有个大佬的搜索那天也寄了

https://api.bilibili.com/x/web-interface/search/type?search_type=video&keyword=mc
你试试

**Comment by XC-Qan** [comment]
> > > 其实是能用的，可能你代码有问题（来自一个同样问题的人，因为错把请求头当成了参数而传递的二货发言）
> > 
> > 
> > 不知是我，还有个大佬的搜索那天也寄了
> 
> https://api.bilibili.com/x/web-interface/search/type?search_type=video&keyword=mc 你试试

没有那些cookies的情况下不行
估计是你之前已经有过那些cookies了
其实根据实验不需要那么多
<img width="92" alt="image" src="https://user-images.githubusercontent.com/60663465/187838146-7599939d-2e8a-4da6-a5dd-c4b80df11ff5.png">
有这俩应该就行了

**Comment by zimoyin** [comment]
> > > > 其实是能用的，可能你代码有问题（来自一个同样问题的人，因为错把请求头当成了参数而传递的二货发言）
> > > 
> > > 
> > > 不知是我，还有个大佬的搜索那天也寄了
> > 
> > 
> > https://api.bilibili.com/x/web-interface/search/type?search_type=video&keyword=mc 你试试
> 
> 没有那些cookies的情况下不行 估计是你之前已经有过那些cookies了 其实根据实验不需要那么多 <img alt="image" width="92" src="https://user-images.githubusercontent.com/60663465/187838146-7599939d-2e8a-4da6-a5dd-c4b80df11ff5.png"> 有这俩应该就行了

不清楚，但是我url在没有cookie下也能访问，可能玄学吧

**Comment by xinxinyihao** [comment]
> > > > > 其实是能用的，可能你代码有问题（来自一个同样问题的人，因为错把请求头当成了参数而传递的二货发言）
> > > > 
> > > > 
> > > > 不知是我，还有个大佬的搜索那天也寄了
> > > 
> > > 
> > > https://api.bilibili.com/x/web-interface/search/type?search_type=video&keyword=mc 你试试
> > 
> > 
> > 没有那些cookies的情况下不行 估计是你之前已经有过那些cookies了 其实根据实验不需要那么多 <img alt="image" width="92" src="https://user-images.githubusercontent.com/60663465/187838146-7599939d-2e8a-4da6-a5dd-c4b80df11ff5.png"> 有这俩应该就行了
> 
> 不清楚，但是我url在没有cookie下也能访问，可能玄学吧

我也遇到了这个问题，但是看这个api已经更新了。

你是在浏览器里面访问成功的么？一般浏览器会默认记住你访问b站的cookie的吧，你开个无痕浏览器窗口再直接访问试试，应该就不行了。

**Comment by zimoyin** [comment]
> > > > > > 其实是能用的，可能你代码有问题（来自一个同样问题的人，因为错把请求头当成了参数而传递的二货发言）
> > > > > 
> > > > > 
> > > > > 不知是我，还有个大佬的搜索那天也寄了
> > > > 
> > > > 
> > > > https://api.bilibili.com/x/web-interface/search/type?search_type=video&keyword=mc 你试试
> > > 
> > > 
> > > 没有那些cookies的情况下不行 估计是你之前已经有过那些cookies了 其实根据实验不需要那么多 <img alt="image" width="92" src="https://user-images.githubusercontent.com/60663465/187838146-7599939d-2e8a-4da6-a5dd-c4b80df11ff5.png"> 有这俩应该就行了
> > 
> > 
> > 不清楚，但是我url在没有cookie下也能访问，可能玄学吧
> 
> 我也遇到了这个问题，但是看这个api已经更新了。
> 
> 你是在浏览器里面访问成功的么？一般浏览器会默认记住你访问b站的cookie的吧，你开个无痕浏览器窗口再直接访问试试，应该就不行了。

![image](https://user-images.githubusercontent.com/49911488/188559423-3f1c3d3c-8a02-4fdd-9bbd-8fe42545b114.png)

不知道，一种在代码里使用这cookie倒是没问题，但是不加cookie确实很会 412
