### ISSUE TITLE
点踩有吗?

### ISSUE THREAD

**Issue by dongdigua** [SocialSisterYi/bilibili-API-collect#468]
![图片](https://user-images.githubusercontent.com/79030590/189475220-ab80bba3-eab3-4cfb-a083-1c33caaccc8b.png)
点踩api有吗, 我只用网页端  
点踩不会是根本没有用吧?  
~~(猜测: 网页不加怕发现, 客户端只起到发泄作用)~~

**Comment by SocialSisterYi** [comment]
web端从来就没有出过点踩功能，自然没有相应的api

**Comment by dongdigua** [comment]
客户端抓包呢？
