### ISSUE TITLE
互动视频相关

### ISSUE THREAD

**Issue by MineCreeper86** [SocialSisterYi/bilibili-API-collect#48]
https://api.bilibili.com/x/stein/edgeinfo_v2
**GET**方法，param包括：
bvid
edge_id
graph_version
platform
portal
screen
buvid
choices

**Comment by MineCreeper86** [comment]
bvid是视频的BV号
edge_id与互动视频内选择有关
graph_version我这里一直是155446
platform在web端为pc
portal和screen都是0
buvid和cookie中的buvid相同
choices不明确

**Comment by MineCreeper86** [comment]
搞懂了，感觉自己又行了

**Comment by MineCreeper86** [comment]
我先开始写文档

**Comment by SocialSisterYi** [comment]
那个buvid不知道是什么含义

**Comment by MineCreeper86** [comment]
> 那个buvid不知道是什么含义

这个不是必须的
buvid存储在cookie里，但具体机制未知，有和没有都差不多

**Comment by MineCreeper86** [comment]
文档撰写已经完成了，请查阅

**Comment by SocialSisterYi** [comment]
分支已合并，文档现在上线master，详见https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/interact_video.md
