### ISSUE TITLE
反馈一下

### ISSUE THREAD

**Issue by 1665169869** [SocialSisterYi/bilibili-API-collect#50]
收藏视频（双端）

prompt 有时候会返回true
我觉得应该是收藏就是true 取消收藏就是false 试了好几次
{"code":0,"message":"0","ttl":1,"data":{"prompt":true}}

**Comment by SocialSisterYi** [comment]
已收到，下次更新时修改

**Comment by SocialSisterYi** [comment]
已经修改，这个是判断成功收藏未关注用户的视频的，已关注的用户这个值永远是false，详见https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/like_coin_fav.md

**Comment by 1665169869** [comment]
> 已经修改，这个是判断成功收藏未关注用户的视频的，已关注的用户这个值永远是false，详见https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/like_coin_fav.md

好滴
