### ISSUE TITLE
[查询用户投稿视频明细] `/x/space/arc/search` 非法访问

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [SocialSisterYi/bilibili-API-collect#502]
示例出现非法访问，前段时间正常

https://api.bilibili.com/x/space/arc/search?ps=10&mid=6087825&pn=1

```bash
curl -G 'https://api.bilibili.com/x/space/arc/search' \
--data-urlencode 'mid=53456' \
--data-urlencode 'ps=2' \
--data-urlencode 'pn=1'
```

**Comment by catlair** [comment]
直接浏览器打开是没问题的。可能是缺少了必要的cookie信息(例如buvid。直接get b站首页就能获得了。

**Comment by Lmmmmmm-bb** [comment]
> 直接浏览器打开是没问题的。可能是缺少了必要的cookie信息(例如buvid。直接get b站首页就能获得了。

尝试过貌似正常了，不知道是什么情况

**Comment by zzh151223** [comment]
我找到原因了，或者作者的投稿视频需要添加user-agent

**Comment by fanza1** [comment]
我加了buvid和user-agent，用了cookie，还是不行

```
curl -G  'http://api.bilibili.com/x/space/arc/search' --data-urlencode 'mid=293793435' --data-urlencode 'buvid=buvid' --data-urlencode 'ps=50' --data-urlencode 'pn=1' -b 'SESSDATA=SESSDATA' --user-agent  'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0'
```

结果
```
{
    "code": -401,
    "message": "非法访问",
    "ttl": 1,
    "data": {
        "ga_data": {
            "decisions": [
                "verify_captcha_level2"
            ],
            "risk_level": 1,
            "grisk_id": "xxx",
            "decision_ctx": {
                "buvid": "",
                "ip": "xxx",
                "mid": "293793435",
                "scene": "anti_crawler",
                "ua": "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0",
                "v_voucher": "xxx"
            }
        }
    }
}
```

**Comment by catlair** [comment]
@fanza1 刚好收到邮件。buvid是cookie中的。

**Comment by zzh151223** [comment]
> 我加了buvid和user-agent，用了cookie，还是非法访问
> 
> 前天开始有问题的
> 
> ```
> curl -G  'http://api.bilibili.com/x/space/arc/search' --data-urlencode 'mid=293793435' --data-urlencode 'buvid=buvid' --data-urlencode 'ps=50' --data-urlencode 'pn=1' -b 'SESSDATA=SESSDATA' --user-agent  'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0'
> ```
> 
> 结果
> 
> ```
> {
>     "code": -401,
>     "message": "非法访问",
>     "ttl": 1,
>     "data": {
>         "ga_data": {
>             "decisions": [
>                 "verify_captcha_level2"
>             ],
>             "risk_level": 1,
>             "grisk_id": "xxx",
>             "decision_ctx": {
>                 "buvid": "",
>                 "ip": "xxx",
>                 "mid": "293793435",
>                 "scene": "anti_crawler",
>                 "ua": "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0",
>                 "v_voucher": "xxx"
>             }
>         }
>     }
> }
> ```

你再加个referer看看，我只用了sessdata   referer    User-Agent这3个去请求所有网页都没问题

**Comment by SocialSisterYi** [comment]
经过检测，发现真正决定风控的参数不是`buvid3`，而是UA，若UA中含有`python`或者`curl`等爬虫类标志，或空UA，那么就会-401
<img width="807" alt="image" src="https://user-images.githubusercontent.com/45892418/196926512-a704c59b-235e-4096-96a6-c6f41c0c74a9.png">

**Comment by catlair** [comment]
@fanza1 fuck，网页突然奔溃了。你的ua有问题

```bash
--user-agent  'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0'
```

应该是
```bash
--user-agent  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0'
```

**Comment by fanza1** [comment]
重新测试发现确实关键在于UA，谢谢各位大佬

**Comment by catlair** [comment]
发现随机 -401 可能有一个原因，设置了 Referer 并且不为 `https://www.bilibili.com/`。这样就可能偶发性的 -401，即使 UA 没有问题

**Comment by zeffon** [comment]
今天使用UA的方法似乎已经失效了

**Comment by RikaShiro** [comment]
在header添加user-agent和referer后 可以正常访问
