### ISSUE TITLE
如何获取搜索总页数

### ISSUE THREAD

**Issue by 12345-mcpython** [SocialSisterYi/bilibili-API-collect#503]
![image](https://user-images.githubusercontent.com/63326494/193208099-874564b8-6bb6-4fe8-8aa9-3605425828f4.png)

[http://api.bilibili.com/x/web-interface/search/type?keyword=mc&search_type=video](http://api.bilibili.com/x/web-interface/search/type?keyword=mc&search_type=video)

搜索api中并没有28这个搜索总页数，如何获取搜索总页数?

**Comment by SocialSisterYi** [comment]
如图所示
<img width="165" alt="image" src="https://user-images.githubusercontent.com/45892418/193398041-4693c26d-86d1-4909-aa3d-064471811a4a.png">
在`pagesize`字段里获取总页数，在`numPages`字段里获取每页的条目数

**Comment by 12345-mcpython** [comment]
@SocialSisterYi  这个50似乎只是一个定值，而那个28是一个动值
