### ISSUE TITLE
获取视频接口，填入登录Cookie（SESSDATA），获取不了高质量视频

### ISSUE THREAD

**Issue by AckyLin** [SocialSisterYi/bilibili-API-collect#51]
获取视频流URL（web端）
http://api.bilibili.com/x/player/playurl

请求接口时，Head添加 填SESSDATA，qn=64

返回的结果集一直为:  quality":32"

**Comment by krishukr** [comment]
什么视频，我也试试（滑稽

**Comment by AckyLin** [comment]
http://api.bilibili.com/x/player/playurlcid=10702890&bvid=BV1Bs411271v&qn=64

**Comment by duzhaokun123** [comment]
大概率是你的seekdata失效了，放错误的seekdata也不会返回错误

**Comment by SocialSisterYi** [comment]
首先确保视频存在指定的清晰度，然后你的SESSDATA要可用，还有是大会员才能获取1080p+和4k的视频，如获取4k除了qn=120还要加fourk=1

**Comment by AckyLin** [comment]
zheng

> 大概率是你的seekdata失效了，放错误的seekdata也不会返回错误

是不会返回错误，只是SESSDATA好像没起作用

**Comment by AckyLin** [comment]
已解决，没有把SESSDATA塞到Cookie中
