### ISSUE TITLE
动态图片上传疑似失效？

### ISSUE THREAD

**Issue by z0z0r4** [SocialSisterYi/bilibili-API-collect#513]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/dynamic/publish.md#%E4%B8%BA%E5%9B%BE%E7%89%87%E5%8A%A8%E6%80%81%EF%BC%88%E7%9B%B8%E7%B0%BF%EF%BC%89%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/195020829-890b7df5-3825-46a9-995c-f2639ed4f939.png)
Method Not Allowed

**Comment by SocialSisterYi** [comment]
确实失效了，因为API改了

**Comment by SocialSisterYi** [comment]
该文档已经修复
