### ISSUE TITLE
请问如何解决401

### ISSUE THREAD

**Issue by sunset1234321** [SocialSisterYi/bilibili-API-collect#518]
{'code': -401, 'message': '非法访问', 'ttl': 1,
 'data': {
    'ga_data': {'decisions': ['verify_captcha_level2'],
                'risk_level': 1,
                'grisk_id': 'xxxxxxxxxxxxxxxxxxx',
                'decision_ctx': {'buvid': '',
                                 'ip': 'xxxxxxxxx',
                                 'mid': '0',
                                 'scene': 'anti_crawler',
                                 'ua': 'python-requests/2.26.0',
                                 'v_voucher': 'xxxxxxxxxxxxxxxx'}}
 }

 }

**Comment by SocialSisterYi** [comment]
#502  UA中不要出现`python` `curl`等字样

**Comment by RikaShiro** [comment]
亲测 401. 用的node.js 没用python和curl
