### ISSUE TITLE
bilibili mcdn方面的API，有没有什么办法拿到？

### ISSUE THREAD

**Issue by machine-doll** [SocialSisterYi/bilibili-API-collect#519]
就是怎样在自己这边开一个bilibili mcdn，并且保活？  
之后通过这个mcdn的server，应该还是可以做不少事情的吧

**Comment by SocialSisterYi** [comment]
参考 https://www.blueskyxn.com/202106/4673.html 是可以的

**Comment by machine-doll** [comment]
> 参考 https://www.blueskyxn.com/202106/4673.html 是可以的

现在不行了，加了校验。必须得是上线的mcdn才能拿到域名解析
