### ISSUE TITLE
无法获取订阅&投稿状态数

### ISSUE THREAD

**Issue by krishukr** [SocialSisterYi/bilibili-API-collect#52]
以UP主[BComFly](https://space.bilibili.com/421333999)举例，uid421333999
即请求地址为http://api.bilibili.com/x/space/navnum?mid=421333999
返回：
`{
    "code": -412,
    "message": "请求被拦截",
    "ttl": 1,
    "data": null
}`

![](https://imgchr.com/i/d8nMvT)

[#23](https://github.com/SocialSisterYi/bilibili-API-collect/issues/23) 曾经提到过请求过快，但这里已经间隔了几天

是食用方法不对吗

[原文](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/status_number.md#%E8%AE%A2%E9%98%85%E6%8A%95%E7%A8%BF%E7%8A%B6%E6%80%81%E6%95%B0)

**Comment by SocialSisterYi** [comment]
验证了这个接口真的已经弃用，文档中折叠处理https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/status_number.md

**Comment by krishukr** [comment]
> 验证了这个接口真的已经弃用，文档中折叠处理https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/status_number.md

好的，辛苦了
