### ISSUE TITLE
[请教] APP 7.1.x 版本疑似使用 http3 获取视频播放链接

### ISSUE THREAD

**Issue by sgpublic** [SocialSisterYi/bilibili-API-collect#520]
我用 HttpCanary 抓包已经抓不到任何包含视频链接的 json 响应了，但是我抓到了一个 UDP 请求（HttpCanary 里面是乱码，部分字符有正常显示），里面包含了这样一段
```json
{"check_rid":"856657735_nb3-1-30232.m4s"}
```
接下来 APP 发送请求：
```
GET http://203.107.1.65/191607/resolve?host=upos-sz-mirrorcoso1.bilivideo.com&query=4,6
```
响应 json 包含视频播放的 CDN。
```json
{"dns":[{"host":"upos-sz-mirrorcoso1.bilivideo.com","client_ip":"125.71.134.116","ips":["124.225.23.118","113.249.87.131","180.105.72.161","180.105.72.160","180.105.72.158","124.225.23.116","180.105.72.159","113.249.87.130","124.225.23.117"],"type":1,"ttl":28,"origin_ttl":60},{"host":"upos-sz-mirrorcoso1.bilivideo.com","client_ip":"125.71.134.116","ips":["240e:978:2608:700:0:0:0:0","240e:930:c300:100:0:0:0:0","240e:983:415:101:0:0:0:7f","240e:978:2608:700:0:0:0:4"],"type":28,"ttl":7,"origin_ttl":60}]}
```
然后 APP 直接请求视频播放链接（就是 path 以 `.m4s` 结尾的链接），似乎阿b用上了 http3 直接发 UDP 通信？这样的话怎么抓接口呢？

**Comment by duzhaokun123** [comment]
app 应该改用 grpc 了吧
建议直接逆向

**Comment by sgpublic** [comment]
> app 应该改用 grpc 了吧 建议直接逆向

我仔细了解了一下，grpc 走的是 http2，也就是说就算数据不可读，也应该是 tcp 请求，但我只抓到了 udp，脑壳疼

**Comment by duzhaokun123** [comment]
> 但我只抓到了 udp，脑壳疼

也许你的 httpcanary 没装系统证书

**Comment by sgpublic** [comment]
> 也许你的 httpcanary 没装系统证书

肯定装了撒，固定证书我装了 JustTrustMe，我还抓了其他接口的，其他接口都是由正常的 RESTful 请求的，就这个视频接口很头疼

**Comment by sgpublic** [comment]
**更新**：我改用电脑 Fiddler 抓包抓到了 HTTP/2 请求，看样子确实可能是走了 grpc（如果我没理解错 rpc 是个什么东西的话）
```
POST https://app.bilibili.com/bilibili.pgc.gateway.player.v2.PlayURL/PlayView
```
响应如下：
```
���A
�cPflv��X *�
Iphdflv2
高清 1080P+08@Z1080P 高码率b1080Pj	高码率r�x��
�http://59.54.225.4:4480/upgcxcode/72/25/843952572/843952572-1-30102.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1666598907&gen=playurlv2&os=mcdn&oi=2101839476&trid=0000ee5daa184f0a4274a81a64d5e4c21d9fp&mid=71287338&platform=android&upsig=d0c2f4a5742c8d0ba63550677db50c61&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&mcdnid=9002418&bvc=vod&nettype=1&orderid=0,3&bw=104965&logo=A0000100�http://upos-sz-mirror08ct.bilivideo.com/upgcxcode/72/25/843952572/843952572-1-30102.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1666598907&gen=playurlv2&os=08ctbv&oi=2101839476&trid=ee5daa184f0a4274a81a64d5e4c21d9fp&mid=71287338&platform=android&upsig=9417af26d4f1fd3d8f6fc5a58a99670a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=1&orderid=1,3&bw=104965&logo=40000000�http://upos-sz-mirror08ct.bilivideo.com/upgcxcode/72/25/843952572/843952572-1-30102.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBv...
...
```

**Comment by SocialSisterYi** [comment]
> 我用 HttpCanary 抓包已经抓不到任何包含视频链接的 json 响应了，但是我抓到了一个 UDP 请求（HttpCanary 里面是乱码，部分字符有正常显示），里面包含了这样一段
> 
> ```json
> {"check_rid":"856657735_nb3-1-30232.m4s"}
> ```
> 
> 接下来 APP 发送请求：
> 
> ```
> GET http://203.107.1.65/191607/resolve?host=upos-sz-mirrorcoso1.bilivideo.com&query=4,6
> ```
> 
> 响应 json 包含视频播放的 CDN。
> 
> ```json
> {"dns":[{"host":"upos-sz-mirrorcoso1.bilivideo.com","client_ip":"125.71.134.116","ips":["124.225.23.118","113.249.87.131","180.105.72.161","180.105.72.160","180.105.72.158","124.225.23.116","180.105.72.159","113.249.87.130","124.225.23.117"],"type":1,"ttl":28,"origin_ttl":60},{"host":"upos-sz-mirrorcoso1.bilivideo.com","client_ip":"125.71.134.116","ips":["240e:978:2608:700:0:0:0:0","240e:930:c300:100:0:0:0:0","240e:983:415:101:0:0:0:7f","240e:978:2608:700:0:0:0:4"],"type":28,"ttl":7,"origin_ttl":60}]}
> ```
> 
> 然后 APP 直接请求视频播放链接（就是 path 以 `.m4s` 结尾的链接），似乎阿b用上了 http3 直接发 UDP 通信？这样的话怎么抓接口呢？

这个请求叫做**HTTP DNS**和视频取流的逻辑无关

**Comment by SocialSisterYi** [comment]
> **更新**：我改用电脑 Fiddler 抓包抓到了 HTTP/2 请求，看样子确实可能是走了 grpc（如果我没理解错 rpc 是个什么东西的话）
> 
> ```
> POST https://app.bilibili.com/bilibili.pgc.gateway.player.v2.PlayURL/PlayView
> ```
> 
> 响应如下：
> 
> ```
> ���A�
> �c�P��flv���X �*�
> I�p��hdflv2�
> 高清 1080P+0�8�@�Z�1080P 高码率b�1080Pj	高码率r�x������
> ��http://59.54.225.4:4480/upgcxcode/72/25/843952572/843952572-1-30102.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1666598907&gen=playurlv2&os=mcdn&oi=2101839476&trid=0000ee5daa184f0a4274a81a64d5e4c21d9fp&mid=71287338&platform=android&upsig=d0c2f4a5742c8d0ba63550677db50c61&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&mcdnid=9002418&bvc=vod&nettype=1&orderid=0,3&bw=104965&logo=A0000100���http://upos-sz-mirror08ct.bilivideo.com/upgcxcode/72/25/843952572/843952572-1-30102.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1666598907&gen=playurlv2&os=08ctbv&oi=2101839476&trid=ee5daa184f0a4274a81a64d5e4c21d9fp&mid=71287338&platform=android&upsig=9417af26d4f1fd3d8f6fc5a58a99670a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=1&orderid=1,3&bw=104965&logo=40000000���http://upos-sz-mirror08ct.bilivideo.com/upgcxcode/72/25/843952572/843952572-1-30102.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBv...
> ...
> ```

gRpc通讯使用protobuf数据格式为二进制，不应该解析成文本否则就是一堆乱码，相关的接口定义已经整理，请参考以下文档
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/grpc_api/bilibili/pgc/gateway/player/v2/playurl.proto

**Comment by sgpublic** [comment]
我超，原来这里面的东西是这个意思，才反应过来，大佬nb
