### ISSUE TITLE
web 端 cookie 刷新方式

### ISSUE THREAD

**Issue by catlair** [SocialSisterYi/bilibili-API-collect#524]
编辑到最前面：cookie 不会主动刷新的，只要他没有调用下面的刷新接口就不会刷新。也就是说，你只要不再打开浏览器，或者直接把 localStorage 的 ac_time_value 字段删除了。那么 cookie 在真的失效前（登录过期、账号风控等强制下线）都是不变化的。

---------------

本来想 pr 的但是有些地方发生了一定的变化，暂时上传之前保留内容。例如一些接口的传参方式居然由 body 变成了url query？？？

- [获取是否更新](#获取是否更新)
- [生成 correspond 路径](#生成-correspond-路径)
- [获取 refresh_csrf](#获取-refresh_csrf)
- [更新 Cookie](#更新-cookie)
- [确认更新](#确认更新)
- [SSO 刷新](#sso-刷新)

---

## 获取是否更新

> https://passport.bilibili.com/x/passport-login/web/cookie/info

_请求方式：GET_

鉴权方式：Cookie

**url 参数：**

| 参数名 | 类型 | 内容                      | 必要性 | 备注 |
| ------ | ---- | ------------------------- | ------ | ---- |
| csrf   | str  | CSRF Token（位于 cookie） | 非必要 |      |

**json 回复：**

根对象：

| 字段    | 类型 | 内容     | 备注                          |
| ------- | ---- | -------- | ----------------------------- |
| code    | num  | 返回值   | 0：成功<br />-101：账号未登录 |
| message | str  | 错误信息 | 默认为 0                      |
| ttl     | num  | 1        |                               |
| data    | obj  | 信息本体 |                               |

`data`对象：

| 字段      | 类型 | 内容                | 备注                  |
| --------- | ---- | ------------------- | --------------------- |
| refresh   | bool | 是否应该刷新 cookie |                       |
| timestamp | num  | 时间戳（毫秒）      | 用于获取 refresh_csrf |

## 生成 correspond 路径

算法来自：https://s1.hdslb.com/bfs/static/jinkela/long/wasm/wasm_rsa_encrypt_bg.wasm

wasm_rsa_encrypt_bg.wasm 导出了 `encrypt` 和 `decrypt` 两个函数。

暂时没有对 wasm 进行分析，网页的处理方式： https://s1.hdslb.com/bfs/static/jinkela/long/wasm/wasm_ras_umd.js

通过处理后得到 `wasmInit` 对象。使用上面请求得到的 `timestamp` 做为参数，生成 correspondPath。

然后拼接上 `https://www.bilibili.com/correspond/1/`

eg: `https://www.bilibili.com/correspond/1/a1531ecc654956b8ff40620b95a3f1bc96745725a4b331d09b38ed7a63b80e21c1871665cab0ec7dc74ef0d442edb91ba1bb78f28280ca1bb90d5eadab112aa9b44f82541621023359ed72f7d1e59317d8616fdf39c84ce1654fad8b3c987318818ee358e46561039170f0de7ab5e51596cafdd939d2dbda099a856538140797`

注意：获取到的 url 有时效性（与 timestamp 有关），大概 5s 内，过期后会返回 404 页面。

```js
await wasmInit.default();
const correspondPath = wasmInit.encrypt({
  data: convertToHex(`refresh_${timestamp}`),
  digest: 'SHA256',
});

const 目标URL = 'https://www.bilibili.com/correspond/1/' + correspondPath;

function convertToHex(str: string) {
  return str.split('').reduce((i, t) => i + t.charCodeAt(0).toString(16), '');
}
```

## 获取 refresh_csrf

> https://www.bilibili.com/correspond/1/:path

_请求方式：GET_

鉴权方式：Cookie

路径的获取方式参考 [生成 correspond 路径](#生成-correspond-路径)

**document 回复：**

返回的是一个页面，有效数据在页面的标签中。鉴权失败，路径不存在/已过期，返回 404 页面。

| 标签 id | 类型 | 内容         | 备注            |
| ------- | ---- | ------------ | --------------- |
| 1-name  | str  | refresh_csrf | 用于更新 Cookie |
| 1-value | str  | 空           |   从源码看是替代 refresh_token ，但并没有返回值            |

<details>
<summary>查看响应示例：</summary>

```html
<!DOCTYPE html>
<html lang="zh-Hans">
  <head> </head
  ><title>Correspond</title>
  <script
    type="text/javascript"
    src="//www.bilibili.com/gentleman/polyfill.js?features=Promise%2CObject.assign%2CString.prototype.includes%2CNumber.isNaN2%CglobalThis"
  ></script>
  <body>
    <div id="1-name">aa4f70d77d00c44a8e312387fd35b20d</div>
    <div id="1-value"></div>
    <div id="token-iframe-app"></div>
    <script type="text/javascript" src="1.token-iframe.js"></script>
    <script type="text/javascript" src="token-iframe.js"></script>
  </body>
</html>
```

</details>

## 更新 Cookie

发送请求的条件是 refresh_token 存在且不为空。

> https://passport.bilibili.com/x/passport-login/web/cookie/refresh

_请求方式：POST_

鉴权方式：Cookie & refresh_token （需要同时满足）

刷新成功后会设置以下 cookie 项：

`sid` `DedeUserID` `DedeUserID__ckMd5` `SESSDATA` `bili_jct`

**正文参数 (application/x-www-form-urlencoded)或 url 参数：**

| 参数名        | 类型 | 内容                               | 备注 |
| ------------- | ---- | ---------------------------------- | ---- |
| csrf          | str  | CSRF Token（位于 cookie）          |      |
| refresh_csrf  | str  | 通过上面步骤获取                   |      |
| source        | str  | `main_web`                         |      |
| refresh_token | str  | localStorage 的 ac_time_value 字段 |      |

**json 回复：**

根对象：

| 字段    | 类型 | 内容     | 备注                          |
| ------- | ---- | -------- | ----------------------------- |
| code    | num  | 返回值   | 0：成功<br />86095：refresh_csrf 错误或 refresh_token 与 cookie 不匹配 |
| message | str  | 错误信息 | 默认为 0                      |
| ttl     | num  | 1        |                               |
| data    | obj  | 信息本体 |                               |

`data`对象：

| 字段          | 类型 | 内容               | 备注                                      |
| ------------- | ---- | ------------------ | ----------------------------------------- |
| status        | num  | 0                  |                                           |
| message       | str  | 未知               |                                           |
| refresh_token | str  | 新的 refresh_token | 存储于 localStorage 的 ac_time_value 字段 |

## 确认更新

让 refresh_token 对应的 cookie 失效

> https://passport.bilibili.com/x/passport-login/web/confirm/refresh

_请求方式：POST_

鉴权方式：Cookie & refresh_token（需要同时满足）

**正文参数 (application/x-www-form-urlencoded)或 url 参数：**

| 参数名        | 类型 | 内容                      | 备注                                               |
| ------------- | ---- | ------------------------- | -------------------------------------------------- |
| csrf          | str  | CSRF Token（位于 cookie） | 从新的 cookie 中获取                               |
| refresh_token | str  | 旧的 refresh_token        | 并非上一步获取到的，而是之前从 localStorage 获取的 |

## SSO 刷新

> https://passport.bilibili.com/web/sso/list

**url 参数：**

| 参数名   | 类型 | 内容                      | 必要性 | 备注 |
| -------- | ---- | ------------------------- | ------ | ---- |
| biliCSRF | str  | CSRF Token（位于 cookie） |        |      |

**json 回复：**

根对象：

| 字段 | 类型 | 内容     | 备注                          |
| ---------- | ---- | -------- | ----------------------------- |
| code        | num  | 返回值   | 0：成功<br />-101：账号未登录 |
| data        | obj  | 信息本体 |                                      |
| message | str  |  空            |  与 data 不会同时存在  |

`data`对象：

| 字段 | 类型     | 内容                       | 备注                                  |
| ---- | -------- | -------------------------- | ------------------------------------- |
| sso  | str 列表 | 用于刷新 cookie 的链接列表 | 访问后返回 `set-cookie`用于设置对应域 |

```json
{
  "code": 0,
  "data": {
    "sso": [
      "https://passport.biligame.com/web/sso/set?ticket=9b859b32e7a5addd2307a4106c3a04c4",
      "https://passport.bigfun.cn/web/sso/set?ticket=9840371797aaee952307a4106c3a04c4",
      "https://passport.bigfunapp.cn/web/sso/set?ticket=1c1801a13336cfe12307a4106c3a04c4",
      "https://passport.bilibili.cn/web/sso/set?ticket=112c6a96e909cf0d1307a4106c3a04c4"
    ]
  }
}
```

**Comment by SocialSisterYi** [comment]
感谢提供

**Comment by catlair** [comment]
node 环境可用的 [wasm_ras_umd.js](https://s1.hdslb.com/bfs/static/jinkela/long/wasm/wasm_ras_umd.js)

```typescript
import * as fs from 'fs';
import path from 'path';
import { TextEncoder } from 'util';

let e: any;
const n: any[] = [];
function o(e: number) {
  return n[e];
}
let i = 0,
  a: Uint8Array;
function getA() {
  if (!a) {
    a = new Uint8Array(e.memory.buffer as ArrayBuffer);
  }
  return a;
}
const f = new TextEncoder();
function u(e: string, n: Uint8Array) {
  const a = f.encodeInto(e, n);
  return a;
}

function l(
  e: string,
  malloc: (arg0: number) => number,
  realloc: (arg0: number, arg1: number, arg2: number) => number,
) {
  if (!realloc) {
    const t = f.encode(e),
      r = malloc(t.length);
    i = t.length;
    return r;
  }
  let r = e.length,
    o = malloc(r);
  const a = getA();
  let l = 0;
  for (; l < r; l++) {
    const n = e.charCodeAt(l);
    if (n > 127) break;
    a[o + l] = n;
  }
  if (l !== r) {
    if (l !== 0) {
      e = e.slice(l);
      const temp_r = l + 3 * e.length;
      o = realloc(o, r, temp_r);
      r = temp_r;
    }
    const n = getA().subarray(o + l, o + r);
    l += u(e, n).written;
  }
  i = l;
  return o;
}
let s: Int32Array;
function getS() {
  if (!s || s.buffer !== e.memory.buffer) {
    s = new Int32Array(e.memory.buffer);
  }
  return s;
}
let b = n.length;
const d = new TextDecoder('utf-8');
function g(e: number, n: number) {
  return d.decode(getA().subarray(e, e + n));
}

function w(e: any) {
  b === n.length && n.push(n.length + 1);
  const t = b;
  b = n[t];
  n[t] = e;
  return t;
}

export function encrypt(params: { data: string; digest: string }) {
  try {
    const a = w(params);
    e.encrypt(8, a);
    return g(getS()[2], getS()[3]);
  } finally {
    // e.__wbindgen_free(t1, wasmInit);
  }
}

function emptyFunc() {
  return;
}

export async function defaultFunc() {
  const importObject = { wbg: {} } as { wbg: Record<string, any> };
  importObject.wbg.__wbindgen_json_serialize = function (n: number, t: number) {
    const a = l(JSON.stringify(o(t) || null), e.__wbindgen_malloc, e.__wbindgen_realloc);
    getS()[n / 4 + 1] = i;
    getS()[n / 4 + 0] = a;
  };
  importObject.wbg.__wbg_self_1b7a39e3a92c949c = emptyFunc;
  importObject.wbg.__wbg_log_da30ae7b677263c7 = emptyFunc;
  importObject.wbg.__wbindgen_object_drop_ref = emptyFunc;
  importObject.wbg.__wbg_new_59cb74e423758ede = emptyFunc;
  importObject.wbg.__wbg_stack_558ba5917b466edd = function (n: number, t: any) {
    const r = l(o(t).stack, e.__wbindgen_malloc, e.__wbindgen_realloc),
      a = i;
    getS()[n / 4 + 1] = a;
    getS()[n / 4 + 0] = r;
  };
  importObject.wbg.__wbg_error_4bb6c2a97407129a = emptyFunc;
  importObject.wbg.__wbg_randomFillSync_d5bd2d655fdf256a = emptyFunc;
  importObject.wbg.__wbg_getRandomValues_f5e14ab7ac8e995d = emptyFunc;
  importObject.wbg.__wbg_crypto_968f1772287e2df0 = emptyFunc;
  importObject.wbg.__wbindgen_is_undefined = emptyFunc;
  importObject.wbg.__wbg_getRandomValues_a3d34b4fee3c2869 = emptyFunc;
  importObject.wbg.__wbg_require_604837428532a733 = emptyFunc;
  const { instance } = await WebAssembly.instantiate(
    fs.readFileSync(path.resolve(__dirname, './wasm_rsa_encrypt_bg.wasm')),
    importObject,
  );
  e = instance.exports;
  return e;
}
```

**Comment by SocialSisterYi** [comment]
这个wasm的具体实现有人研究过吗，是加密还是hash还是编码呢？

**Comment by catlair** [comment]
加密后hash？decompile 了一下，一个函数几百行代码，看不明白。
![image](https://user-images.githubusercontent.com/44313800/199882262-5aa877de-1643-4874-98b6-fd992dd83fe0.png)

![image](https://user-images.githubusercontent.com/44313800/199882248-d31b8562-dab3-4f20-89fc-68e3a0512d0e.png)

**Comment by z0z0r4** [comment]
更新 Cookie 中的 source 从哪里获得呢？

**Comment by catlair** [comment]
> 更新 Cookie 中的 source 从哪里获得呢？

窗口类型固定值啊。你项目内搜一搜可以看到其他值，但是这里一般只有main才会到刷新

**Comment by Nemo2011** [comment]
> ``` javascript
> await wasmInit.default();
> const correspondPath = wasmInit.encrypt({
>   data: convertToHex(`refresh_${timestamp}`),
>   digest: 'SHA256',
> });
> 
> const 目标URL = 'https://www.bilibili.com/correspond/1/' + correspondPath;
> 
> function convertToHex(str: string) {
>   return str.split('').reduce((i, t) => i + t.charCodeAt(0).toString(16), '');
> }
> ```

这里的 `timestamp` 是指秒还是毫秒？

**Comment by catlair** [comment]
> > ```js
> > await wasmInit.default();
> > const correspondPath = wasmInit.encrypt({
> >   data: convertToHex(`refresh_${timestamp}`),
> >   digest: 'SHA256',
> > });
> > 
> > const 目标URL = 'https://www.bilibili.com/correspond/1/' + correspondPath;
> > 
> > function convertToHex(str: string) {
> >   return str.split('').reduce((i, t) => i + t.charCodeAt(0).toString(16), '');
> > }
> > ```
> 
> 这里的 `timestamp` 是指秒还是毫秒？

这是上下文介绍过的

![image](https://user-images.githubusercontent.com/44313800/213708288-7004b7d0-8f76-4e9e-800f-f1fa1b92147c.png)

**Comment by catlair** [comment]
wasm 使用 rust 写的，用到了 wasm-bindgen https://github.com/rustwasm/wasm-bindgen。这样打包除了生成 wasm 文件，还会生成一个 js 文件，[wasm_ras_umd.js](https://s1.hdslb.com/bfs/static/jinkela/long/wasm/wasm_ras_umd.js) 应该就是那个文件再压缩和 umd 化得到的（原js是esm的）。

**Comment by KudouRan** [comment]
虽然还没有大佬提供直接的方案，不过直接使用它的wasm也行。浏览器可以直接使用，无需处理。node 按照自己的情况更改，比如可能需要把 chrome 请求的代码删除，TextEncode 从 util 导入（低版本），url 补全 https 协议等。

这里是放在 github 的一个 node/浏览器 demo。

https://wasm-rsa.vercel.app/api/rsa?t=1123

python 等语言可以把 [wasm_ras.js](https://s1.hdslb.com/bfs/static/jinkela/long/wasm/wasm_ras.js) 种子代码转为 py 也可以直接利用 wasm

**Comment by 0f-0b** [comment]
逆向 Wasm 发现是 RSA-OAEP 加密，用 Web Crypto 重实现如下。

```js
const publicKey = await crypto.subtle.importKey(
  "jwk",
  {
    kty: "RSA",
    n: "y4HdjgJHBlbaBN04VERG4qNBIFHP6a3GozCl75AihQloSWCXC5HDNgyinEnhaQ_4-gaMud_GF50elYXLlCToR9se9Z8z433U3KjM-3Yx7ptKkmQNAMggQwAVKgq3zYAoidNEWuxpkY_mAitTSRLnsJW-NCTa0bqBFF6Wm1MxgfE",
    e: "AQAB",
  },
  { name: "RSA-OAEP", hash: "SHA-256" },
  true,
  ["encrypt"],
);

async function getCorrespondURL(timestamp) {
  const data = new TextEncoder().encode(`refresh_${timestamp}`);
  const encrypted = new Uint8Array(
    await crypto.subtle.encrypt({ name: "RSA-OAEP" }, publicKey, data),
  );
  return `https://www.bilibili.com/correspond/1/${
    encrypted.reduce((str, c) => str + c.toString(16).padStart(2, "0"), "")
  }`;
}

console.log(await getCorrespondURL(Date.now()));
```

**Comment by SocialSisterYi** [comment]
相关内容已经在此 commit 中完成 https://github.com/SocialSisterYi/bilibili-API-collect/commit/a46f140fde73530868ce9db5f613deed8d5c645e

详见 https://github.com/SocialSisterYi/bilibili-API-collect/blob/a46f140fde73530868ce9db5f613deed8d5c645e/docs/login/cookie_refresh.md

感谢你们提供的研究报告以及逆向工程（抱

**Comment by Ladtor** [comment]
按照教程接入之后，一直得到86095结果，有遇到相同问题的同学吗？

**Comment by Ladtor** [comment]
```python
import binascii
import re
import time

import requests
from Crypto.Cipher import PKCS1_OAEP
from Crypto.Hash import SHA256
from Crypto.PublicKey import RSA

key = RSA.importKey('''\
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDLgd2OAkcGVtoE3ThUREbio0Eg
Uc/prcajMKXvkCKFCWhJYJcLkcM2DKKcSeFpD/j6Boy538YXnR6VhcuUJOhH2x71
nzPjfdTcqMz7djHum0qSZA0AyCBDABUqCrfNgCiJ00Ra7GmRj+YCK1NJEuewlb40
JNrRuoEUXpabUzGB8QIDAQAB
-----END PUBLIC KEY-----''')


def getCorrespondPath():
    ts = round(time.time() * 1000)
    cipher = PKCS1_OAEP.new(key, SHA256)
    encrypted = cipher.encrypt(f'refresh_{ts}'.encode())
    return binascii.b2a_hex(encrypted).decode()


def get_refresh_csrf(correspond_path, cookie_dict):
    response = requests.get(url=f'https://www.bilibili.com/correspond/1/{correspond_path}', cookies=cookie_dict)
    if response.status_code != 200:
        raise Exception(f'correspondPath错误或过期 {response.status_code}')
    html = response.text
    pattern = r'<div\s+id="1-name">\s*(.*?)\s*</div>'
    match = re.search(pattern, html)
    if match:
        div_contents = match.group(1)
        return div_contents
    else:
        raise Exception(f'未获取到 refresh_csrf {html}')


def get_new_cookie(refresh_token, refresh_csrf, cookie_dict):
    data = {'csrf': cookie_dict['bili_jct'], 'refresh_csrf': refresh_csrf, 'source': 'main_web', 'refresh_token': refresh_token}
    response = requests.post('https://passport.bilibili.com/x/passport-login/web/cookie/refresh', data=data, headers={'Content-Type': 'application/x-www-form-urlencoded'},
                             cookies=cookie_dict)
    json = response.json()
    if json['code'] == 0:
        refresh_token = json['data']['refresh_token']
        cookies_dict = []
        for name, value in response.cookies.items():
            cookies_dict[name] = value
        return refresh_token, cookies_dict
    elif json['code'] == 86095:
        raise Exception(f'refresh_csrf 错误或 refresh_token 与 cookie 不匹配')
    else:
        raise Exception(f'刷新cookie失败 {json}')


def confirm_refresh(refresh_token_old, cookie_dict):
    data = {'csrf': cookie_dict['bili_jct'], 'refresh_token': refresh_token_old}
    response = requests.post('https://passport.bilibili.com/x/passport-login/web/confirm/refresh', data=data, headers={'Content-Type': 'application/x-www-form-urlencoded'},
                             cookies=cookie_dict)
    json = response.json()
    if json['code'] != 0:
        raise Exception(f'确认刷新cookie失败 {json}')


def check_login_user_info(cookie_dict):
    response = requests.get('https://api.bilibili.com/x/web-interface/nav', cookies=cookie_dict)
    json = response.json()
    if json['code'] != 0:
        raise Exception(f'新cookie检测异常 {json} {cookie_dict}')


# https://socialsisteryi.github.io/bilibili-API-collect/docs/login/cookie_refresh.html
# refresh_token: localStorage 中的ac_time_value
def refresh_cookie(refresh_token, cookie_dict):
    correspond_path = getCorrespondPath()
    refresh_csrf = get_refresh_csrf(correspond_path, cookie_dict)
    refresh_token_old = refresh_token
    new_refresh_token, new_cookie_dict = get_new_cookie(refresh_token_old, refresh_csrf, cookie_dict)
    confirm_refresh(refresh_token_old, new_cookie_dict)  # 这一步需要新的 Cookie 以及旧的 refresh_token
    check_login_user_info(new_cookie_dict)
    return new_refresh_token, new_cookie_dict
```

**Comment by catlair** [comment]
> 按照教程接入之后，一直得到86095结果，有遇到相同问题的同学吗？

我认为你应该新建一个 issue

**Comment by alphadoiy** [comment]
请问localStorage 中的ac_time_value怎么获取

**Comment by z0z0r4** [comment]
> 请问localStorage 中的ac_time_value怎么获取

https://nemo2011.github.io/bilibili-api/#/get-credential

**Comment by JueShiBaWangLong** [comment]
> 虽然还没有大佬提供直接的方案，不过直接使用它的wasm也行。浏览器可以直接使用，无需处理。node 按照自己的情况更改，比如可能需要把 chrome 请求的代码删除，TextEncode 从 util 导入（低版本），url 补全 https 协议等。
> 
> 这里是放在 github 的一个 node/浏览器 demo。
> 
> https://wasm-rsa.vercel.app/api/rsa?t=1123
> 
> python 等语言可以把 [wasm_ras.js](https://s1.hdslb.com/bfs/static/jinkela/long/wasm/wasm_ras.js) 胶水代码转为 py 也可以直接利用 wasm

大佬有没有Java版的代码
