### ISSUE TITLE
补充大会员中心大积分签到任务请求（限定大会员）

### ISSUE THREAD

**Issue by ClydeTime** [SocialSisterYi/bilibili-API-collect#525]
request:
url: https://api.bilibili.com/pgc/activity/score/task/sign
method: post
headers: {Cookie: xxx, Referer: xxx, User-Agent: xxx, Content-Length: xxx, Host: xxx, Accept: xxx, Buvid: xxx, native_api_from: xxx, ...}
其中headers中，哪些是必要字段未做验证。
response：
{"code":0,"message":"success"}
其他错误返回未做测试验证

**Comment by catlair** [comment]
我来补充一下

header 必选项为 Referer，Referer 需要为合法的 b 站链接 例如 `http://space.bilibili.com/1231`  `https://www.bilibili.com/`  `https://api.bilibili.com/` 

否者出现 -403  问权限不足

cookie 必须存在 SESSDATA，且 SESSDATA 必须进行 **URL 编码**，即 `,` 应该转为 `%2C`，`*` 转为 `%2A`

否者出现 -401 非法访问
