### ISSUE TITLE
好像哔哩哔哩的直播流hls404了

### ISSUE THREAD

**Issue by HGW-990223** [SocialSisterYi/bilibili-API-collect#526]
你好，直播流hls好像不能用了报404

**Comment by HGW-990223** [comment]
@SocialSisterYi 可以解决下吗

**Comment by HGW-990223** [comment]
![image](https://user-images.githubusercontent.com/68190282/199906746-d7287681-bc03-4f65-9e0d-f361cdb727d1.png)

**Comment by HGW-990223** [comment]
@SocialSisterYi  报错404
![image](https://user-images.githubusercontent.com/68190282/199906914-07a19873-e11e-44de-8a2a-b2461e02a303.png)

**Comment by SocialSisterYi** [comment]
看看是不是需要什么鉴权？

**Comment by HGW-990223** [comment]
@SocialSisterYi 鉴权是什么意思，就是很不稳定，有的直播间就可以，有的就不行

**Comment by SocialSisterYi** [comment]
那就有可能是画质不存在或者格式不存在导致的，我也不清楚，刚才试了一下flv和hls直播流都可以正常下载
