### ISSUE TITLE
全站音乐榜接口

### ISSUE THREAD

**Issue by mufeng233** [SocialSisterYi/bilibili-API-collect#531]
B站全站音乐榜原网页链接：[https://music.bilibili.com/pc/rank?list_id=1](https://music.bilibili.com/pc/rank?list_id=1)

B站全站音乐榜API：[https://api.bilibili.com/x/copyright-music-publicity/toplist/music_list?list_id=1](https://api.bilibili.com/x/copyright-music-publicity/toplist/music_list?list_id=21)

> 参数`list_id`为第几期，目前到11.4有21期

订阅全站音乐榜API：[https://api.bilibili.com/x/copyright-music-publicity/toplist/subscribe/update](https://api.bilibili.com/x/copyright-music-publicity/toplist/subscribe/update)
> 方法为`POST`

|参数|说明|
|---|---|
|list_id|第几期（好像随便一个就行）|
|csrf|CSRF Token|
|state|1为订阅2为取消|

**Comment by SocialSisterYi** [comment]
相关文档已经添加，感谢提供 https://github.com/SocialSisterYi/bilibili-API-collect/commit/48402b2fadee6bc62cc036ccf3a3a873c98f123e
