### ISSUE TITLE
接口获取的视频格式与清晰度有重大变动

### ISSUE THREAD

**Issue by nulla2011** [SocialSisterYi/bilibili-API-collect#535]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/cc6ab5f542f5c0360d0c8bb29c98341ea68f4d24/video/videostream_url.md?plain=1#L41-L57

据我的观察，b 站上个月把 fnval 中的 flv 选项从 0 改成了 17 ，现在用 0 也返回的是最高 1080p 非高码率的 mp4 。另外根据 esterTion 佬的测试，b 站从 11 月 1 日 12 左右之后的新视频已经没有 flv 格式了，使用 17 返回的是 360p 的 mp4 。

**Comment by Sualiu** [comment]
是的，同样有这个发现

**Comment by SocialSisterYi** [comment]
已更正文档错误
https://github.com/SocialSisterYi/bilibili-API-collect/commit/1c8591897502f5ae7ecc00ed89db921b60252c92
