### ISSUE TITLE
用户空间相关下视频copyright的可能性推测

### ISSUE THREAD

**Issue by ErickRen2021** [SocialSisterYi/bilibili-API-collect#536]
用户空间相关https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/user/space.md
json回复中data对象的list对象的vlist数组的copyright
发送get请求:http://api.bilibili.com/x/space/arc/search?mid=258457966&pn=1&ps=10 UP主：卧龙寺
其中视频copyright值均为2，对应视频许可信息：转载。
发送get请求:http:http://api.bilibili.com/x/space/arc/search?mid=25876945&pn=1&ps=10 UP主：极客湾Geekerwan
其中视频copyright值均为1，对应视频许可信息：原创，未经作者允许禁止转载。
发送mid=9209508的get请求可得知，即使未标未经作者允许禁止转载，但只要是原创，copyright都会返回1。

**Comment by SocialSisterYi** [comment]
相关内容已经更新 https://github.com/SocialSisterYi/bilibili-API-collect/commit/09c167af4512c40d26002a1d9b173b33da6fd9df
