### ISSUE TITLE
爬太快容易封api

### ISSUE THREAD

**Issue by 1665169869** [SocialSisterYi/bilibili-API-collect#54]
用cookie爬的话会被封api，不知道app的token会不会被封，有人试过嘛

**Comment by duzhaokun123** [comment]
试过无间隔的爬评论，没被封

**Comment by 1665169869** [comment]
> 试过无间隔的爬评论，没被封

我弄的批量收藏视频，设置了三秒延迟都被封了= =

**Comment by 1665169869** [comment]
好像是读取视频状态数太快就会被封几小时

**Comment by SocialSisterYi** [comment]
带上cookie，每次返回的sid和bfe_id也要更新

**Comment by 1665169869** [comment]
我去试试，感谢大佬

> 带上cookie，每次返回的sid和bfe_id也要更新

**Comment by 1665169869** [comment]
> 好像是读取视频状态数太快就会被封几小时

可能是，测试中ing，可能也不是

**Comment by 1665169869** [comment]
成功了，感谢SocialSisterYi大佬提供的解决方法

**Comment by 1665169869** [comment]
> 带上cookie，每次返回的sid和bfe_id也要更新

不行，还是被ban了 可能是我方法不对，我只带了SESSDATA和sid还有bfe_id

**Comment by 1665169869** [comment]
发现原因还是在获取视频状态数里，我这里没设置SESSDATA、sid、bfe_id 是直接默认获取的。
被判断机器人后会被封几小时IP，具体还没测试过是几小时，更换ip就显示正常

**Comment by SocialSisterYi** [comment]
sessdata非登录权限接口可以不用写

**Comment by MineCreeper86** [comment]
过频访问无论如何都会被封的，我吃过好几次亏，限制好像是10秒内200请求以内吧

**Comment by 1665169869** [comment]
> 过频访问无论如何都会被封的，我吃过好几次亏，限制好像是10秒内200请求以内吧

多谢方案，有空我试试。
我试过一次性无延迟爬取能爬三千次，如果慢慢爬应该能完成我需要的

**Comment by songrk415** [comment]
根据我对直播间状态和动态列表两个api的观察，B站是每十分钟检查一次api的爬取次数。如果超过允许的请求次数，会在第十分钟被ban，一次ban半个小时，之后恢复正常。个人猜测该规律适用于B站大部分api，只是每个api在十分钟之内允许的请求次数不同。

**Comment by 1665169869** [comment]
> 根据我对直播间状态和动态列表两个api的观察，B站是每十分钟检查一次api的爬取次数。如果超过允许的请求次数，会在第十分钟被ban，一次ban半个小时，之后恢复正常。个人猜测该规律适用于B站大部分api，只是每个api在十分钟之内允许的请求次数不同。

多谢大佬提醒，我有空的时候试试

**Comment by SocialSisterYi** [comment]
> 根据我对直播间状态和动态列表两个api的观察，B站是每十分钟检查一次api的爬取次数。如果超过允许的请求次数，会在第十分钟被ban，一次ban半个小时，之后恢复正常。个人猜测该规律适用于B站大部分api，只是每个api在十分钟之内允许的请求次数不同。

好像bfe_id也是10分钟刷新一次，添加这个到cookie里可以防止被ban

**Comment by zhang-anzhi** [comment]
如果用python来爬，借此处问一下bfe_id和sid如何获取，是每次使用api会返回吗？

**Comment by MineCreeper86** [comment]
> 如果用python来爬，借此处问一下bfe_id和sid如何获取，是每次使用api会返回吗？

bfe_id是十分钟一次，sid我不清楚

**Comment by zhang-anzhi** [comment]
> > 如果用python来爬，借此处问一下bfe_id和sid如何获取，是每次使用api会返回吗？
> 
> bfe_id是十分钟一次，sid我不清楚

**问一下bfe_id和sid如何获取**

**Comment by ProgramRipper** [comment]
@zhang-anzhi 如果你语气好点，大多数人会更加愿意回答你的问题。
python的requests库发送请求行为与浏览器基本一致，可以自动更新cookies。如果带了bfe_id和sid去请求的确是十分钟刷新，但我没有确认过不带sid和bfe_id发送请求会不会刷新。不过，据我观察浏览器未登录时（未登录时没有sid和bfe_id），不会获得sid和bfe_id。

**Comment by zhang-anzhi** [comment]
@ProgramRipper If you think this mood is not enough. I cant understant what is your need.
As i know, python `requests` lib will use default cookies, herders, etc. when use `requests.method()` to send request, unless give extra arguments like `cookies`, `herders`, etc. If you want auto save response cookies, need to use `Session` object.
When not login in, my test result is use `api.bilibili.com` api will return bef_id, more info please look here: #64

**Comment by ProgramRipper** [comment]
@zhang-anzhi If you think your mood is good enough, I have nothing to say.
I will test it after I back home.

**Comment by kebufu** [comment]
> @zhang-anzhi If you think your mood is good enough, I have nothing to say.
> I will test it after I back home.

I have nothing to say草

**Comment by HuangLuxuan** [comment]
补充一条未证实的，好像白天和半夜触发阈值不一样，半夜会低很多

**Comment by zhang-anzhi** [comment]
> 补充一条未证实的，好像白天和半夜触发阈值不一样，半夜会低很多

So could someone make a test program to test different request frequency during night and day. If the request during night is more hard to be banned, we could move the request to the night.

**Comment by SocialSisterYi** [comment]
经过长达一年的爬虫挂机测试，现在得出的结论是：
1. B站的api风控是一套复杂机制，针对ip而不针对账号
2. 风控的检测区间为10min，风控的持续时常为30min
3. 是否风控不仅和10min内的请求量相关，还与访问行为相关，已进行定性研究未进行定量研究（局域网内有正在使用B站app端或web端的设备时爬虫不易被风控）
4. 在同一ip下有时风控api会相互关联，如只访问A接口不风控，而访问B接口的量超过阈值后，A、B接口同时风控
5. app环境、`bfe_id`、Cookie、`access_key`、`buvid`会影响风控的判定，已进行定性研究未进行定量研究

**Comment by RikaShiro** [comment]
> > 补充一条未证实的，好像白天和半夜触发阈值不一样，半夜会低很多
> 
> So could someone make a test program to test different request frequency during night and day. If the request during night is more hard to be banned, we could move the request to the night.

还装起外宾来了 我笑死了

**Comment by pot-not-fish** [comment]
看不懂机制，今天在研究b站api的时候就手动访问了几次，然后就直接给我ban了，我脚本都还没跑呢

**Comment by landall** [comment]
> 补充一条未证实的，好像白天和半夜触发阈值不一样，半夜会低很多

这个很正常，因为爬虫一般在晚上工作。
而且晚上同一IP下同时访问的人也应该会变少（比如办公室、运营商公用出口这种IP）。
