### ISSUE TITLE
获取历史记录列表 参数名更改 business改为type

### ISSUE THREAD

**Issue by guzhidefeifeiyu** [SocialSisterYi/bilibili-API-collect#551]
目前只发现参数名变化

**Comment by SocialSisterYi** [comment]
没有改啊，不论是请求参数还是相应数据

![image](https://user-images.githubusercontent.com/45892418/207063219-6f818ce2-e1a6-49de-8929-23793f4f3a46.png)

![image](https://user-images.githubusercontent.com/45892418/207063348-c9fba3b4-e0e6-4fb7-9d39-a09c0bef39a1.png)

**Comment by SocialSisterYi** [comment]
> 我的我的，这个是页面最上方历史的参数 ![image](https://user-images.githubusercontent.com/47471842/207068080-e54d850f-1653-404f-99fc-43a6f59f72b4.png)

我也是看的这个，抓了这个页面下的数据包

**Comment by SocialSisterYi** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/commit/ffd414b23070d7d949ea616d28a45b1b6f90775f
