### ISSUE TITLE
奉上一对密钥

### ISSUE THREAD

**Issue by daofeng2015** [SocialSisterYi/bilibili-API-collect#57]
APPKEY aae92bc66f3edfab
APPSECRET af125a0d5279fd576c1b4418a3e8276d
pc端投稿工具

**Comment by daofeng2015** [comment]
刚抓到官方新出的必剪应用 
APPKEY 5dce947fe22167f9

**Comment by SocialSisterYi** [comment]
谢谢大佬，下次更新的时候加上

**Comment by SocialSisterYi** [comment]
已经补充进去了
