### ISSUE TITLE
请问如何仅获取视频的声音

### ISSUE THREAD

**Issue by RikaShiro** [SocialSisterYi/bilibili-API-collect#570]
可以正常登录/查找视频
希望可以根据bvid仅下载视频的音频 不需要任何画面
不太想先下载视频再转成mp3格式 操作很麻烦

**Comment by Myitian** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/1f9a684e1fc1a0f6cdb02cf6321fd4e3eaed8040/video/videostream_url.md?plain=1#L1060-L1160

dash方式获取视频流URL
返回内容音视频分离
可以用这个接口返回的音频URL（m4a容器格式）

取流的方式文档里有讲

当然如果是平时使用想省事儿的话，可以用脚本或是IDM抓取页面上的音视频

**Comment by RikaShiro** [comment]
阿里嘎多 我尝试一下

**Comment by RikaShiro** [comment]
成功了 多谢

**Comment by jkhAIjava** [comment]
@RikaShiro 你好，我看目前接口返回是m4s格式，能一步到位到mp3格式吗？
