### ISSUE TITLE
搜索接口是不是有新的了

### ISSUE THREAD

**Issue by kiddkyd2** [SocialSisterYi/bilibili-API-collect#574]
https://api.bilibili.com/x/web-interface/wbi/search/all/v2
https://api.bilibili.com/x/web-interface/wbi/search/type

这2个接口貌似不需要校验cookies，但是多了几个奇怪的参数

**Comment by cnsky2016** [comment]
需要cookie

**Comment by SessionHu** [comment]
[已经收录](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/search/search_request.md), close

**Comment by SocialSisterYi** [comment]
详见 [综合搜索（web端）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/search/search_request.md#%E7%BB%BC%E5%90%88%E6%90%9C%E7%B4%A2web%E7%AB%AF) 和 [分类搜索（web端）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/search/search_request.md#%E5%88%86%E7%B1%BB%E6%90%9C%E7%B4%A2web%E7%AB%AF) 注意提供 [wbi 签名](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md) 参数
