### ISSUE TITLE
修正

### ISSUE THREAD

**Issue by Aknices-QWQ** [SocialSisterYi/bilibili-API-collect#576]
查询用户投稿视频明细
pn 非必要 默认1
ps 非必要 默认30

**Comment by RikaShiro** [comment]
而且查询用户投稿明细 不查验sessdata。昨天使用格式错误的cookie依然有正确返回

**Comment by SocialSisterYi** [comment]
> 而且查询用户投稿明细 不查验sessdata。昨天使用格式错误的cookie依然有正确返回

这个 API 只检查 ck 中的`buvid3`字段存在，而不如判断 ck 中的登录 session 信息
