### ISSUE TITLE
分享一个app启动图的api

### ISSUE THREAD

**Issue by daofeng2015** [SocialSisterYi/bilibili-API-collect#58]
https://app.bilibili.com/x/v2/splash/brand/list?appkey=1d8b6e7d45233436&build=6071200&c_locale=zh_CN&ts=1598964145&sign=cb638b21caa71bec3ab59386c656ffad

sign一定需要,不然返回失败

**Comment by SocialSisterYi** [comment]
已经添加了开屏图片以及主题和颜色的api，请查收
