### ISSUE TITLE
关于获取电影视频流时返回的json文件中result对象“is_preview”键的值为1的讨论

### ISSUE THREAD

**Issue by MCJiu** [SocialSisterYi/bilibili-API-collect#583]
我在尝试使用Python的requests模块访问[获取电影流的API](http://api.bilibili.com/pgc/player/web/playurl)时，给出的URL参数如下：

```python
{
    "cid": 34568185, #电影《让子弹飞》
    "qn": 120,
    "fnval": 144,
    "fourk": 1,
}
```

在收到的json正文中，发现result对象的“is_preview”键的值为1，取流后发现只有480P分辨率的6分钟长的视频（我已通过cookie鉴权且有大会员）。随后尝试在URL参数中加入“is_preview": 0，但得到了同样的返回结果。

于是我猜测is_preview应指示获取到的流是否是预览流（6min）。另外，有没有大佬知道怎么获取电影的完整流？

**Comment by ruitard** [comment]
请问一下这个问题怎么解决的呢？

**Comment by cxw620** [comment]
> 请问一下这个问题怎么解决的呢？

Login in Bilibili and add valid cookie to your request header. For more details on building url please refer to relevant docs. Or you can F12 to see how your browser requests for movie video info.
