### ISSUE TITLE
视频发布时间戳不对 无法转化成有效时间

### ISSUE THREAD

**Issue by czzonet** [SocialSisterYi/bilibili-API-collect#59]
pubdate | num | 视频上传时间 | 时间戳
-- | -- | -- | --
ctime | num | 视频审核通过时间 | 时间戳

pubdate ：
1599032543

Date.now()？：
1599033163683

差了一个今年八月十五号的基数

不知哪里不对劲

**Comment by duzhaokun123** [comment]
那是秒级时间戳

**Comment by czzonet** [comment]
啊？这也行？！一般都是用毫秒，愣是没看明白U_U……

**Comment by duzhaokun123** [comment]
@SocialSisterYi 文档中应标明是秒级时间戳还是毫秒级时间戳
