### ISSUE TITLE
人机验证中附带的验证器貌似不能正常工作了

### ISSUE THREAD

**Issue by zimoyin** [SocialSisterYi/bilibili-API-collect#592]
验证器：https://kuresaru.github.io/geetest-validator/
试过好几次但是每次都无法进行
![image](https://user-images.githubusercontent.com/49911488/213367625-78916387-9834-4f55-ab0e-e327b41a285e.png)

**Comment by SocialSisterYi** [comment]
这个极验 DEMO 是第三方开源项目，不保证其正常功能，可以参考 [极验的官方文档](https://docs.geetest.com/sensebot/deploy/client/web) 自行搭建环境调试
