### ISSUE TITLE
如何查询指定用户的IP属地

### ISSUE THREAD

**Issue by JiaLeDe** [SocialSisterYi/bilibili-API-collect#597]
有这个api嘛？

**Comment by FishZe** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/clientinfo/ip.md
这个吗

**Comment by daofeng2015** [comment]
应该问的是up主的ip所属地

**Comment by SocialSisterYi** [comment]
调用客户端的用户空间 API `https://app.bilibili.com/x/v2/space`得到`$.data.card.space_tag_bottom[*].title`字段，即用户IP归属地，目前 web 端还不显示这一标识
