### ISSUE TITLE
好像发现个逻辑漏洞

### ISSUE THREAD

**Issue by 1665169869** [SocialSisterYi/bilibili-API-collect#60]
![image](https://user-images.githubusercontent.com/50762038/92333748-783bf500-f0ba-11ea-8f2e-7d503fc77db0.png)

二维码登录的web端流程&逻辑那里
如果if data == -5的话将会一直循环下去哎好像，甚至是从是否已经确认循环，实际变量内容还是以前的

**Comment by 1665169869** [comment]
python没goto语句没法放例程了，我去安装个goto库

**Comment by 1665169869** [comment]
可能我描述的不太清晰
大概就是：5.if data == -5 就会跳到3 3的判断数值还是和以前一样的话又是跳到4然后跳到5，最后再到3 如此循环

**Comment by 821938089** [comment]
...不就是要循环吗，不然怎么检查你有没有扫码登录?

**Comment by SocialSisterYi** [comment]
问题已经解决，把逻辑不清的文字描述换成了伪代码描述
