### ISSUE TITLE
获取主页ip属地API的分析

### ISSUE THREAD

**Issue by My-Responsitories** [SocialSisterYi/bilibili-API-collect#600]
> https://app.bilibili.com/x/v2/space
> https://app.biliapi.net/x/v2/space

*请求方式：GET*

认证方式：APP

- 接口本身不需要认证, 但获取IP属地需要认证

__url参数:__
参数名 | 类型 | 内容 | 必要性 | 备注
-- | -- | -- | -- | --
access_key | str | APP登录Token | 可选 | 获取IP属地必要
appkey | str | APP密钥 | 必要 | 需要与生成access_key时所用的appkey端一致
build | num | 版本 | 必要 | 接受任意num
mobi_app | str | 运行设备 | 可选 | 获取`$.data.card.space_tag`必要, 且为`android`
ps | num | `$.data.archive.item`个数 | 可选 | 默认10
ts | num | 秒级时间戳 | 必要 | 
sign | str | APP签名 | 必要 | 
vmid | num | 需要查询的mid | 必要 | 

__回复:__
`$.data.card.space_tag[0].title`或`$.data.card.space_tag_bottom[0].title`即为IP属地

其余内容太多了自己看

**Comment by jinyu2022** [comment]
为什么现在都没加进去

**Comment by imhmjz** [comment]
到现在都还没加

**Comment by z0z0r4** [comment]
因为没人 pr？

**Comment by imhmjz** [comment]
> 因为没人 pr？

可以问一下生成access_key的方法吗？照着https://github.com/SocialSisterYi/bilibili-API-collect/issues/861拿到的是账号未登录，找了一圈没看到其他相关
