### ISSUE TITLE
关系查询接口报错-400

### ISSUE THREAD

**Issue by sikishana** [SocialSisterYi/bilibili-API-collect#614]
relationAPI = 'https://api.bilibili.com/x/space/acc/relation'
    msg = requests.get(relationAPI,
                       headers={'cookie': cookie,
                                'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                                              'Chrome/110.0.0.0 Safari/537.36',
                                'sec-ch-ua-platform': 'Windows'},
                       data={'mid': 322055877})
代码如上
{'code': -400, 'message': "Key: 'Vmid' Error:Field validation for 'Vmid' failed on the 'min' tag", 'ttl': 1}

**Comment by 7rikka** [comment]
mid放在params里吧，你这个是get方法

**Comment by SocialSisterYi** [comment]
使用 requests 库进行 API 调用，就要明确你的参数位置，向函数中正确地传参
你这个是 GET 请求，所以必须使用`params`形参，而不是`data`
正确的代码应该是这样的：
```python
relationAPI = 'https://api.bilibili.com/x/space/acc/relation'
msg = requests.get(relationAPI,
    headers={
        'cookie': cookie,
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
        'sec-ch-ua-platform': 'Windows'
    },
    params={
        'mid': 322055877
    }
)
```
