### ISSUE TITLE
查询已设置关注不可见的用户关注API中attention参数失效

### ISSUE THREAD

**Issue by zty2019** [SocialSisterYi/bilibili-API-collect#621]
https://app.biliapi.net/x/v2/relation/followings对已设置关注不可见的用户，参数无论是否增加order=attention得到的返回值是一样的

**Comment by zty2019** [comment]
抱歉描述有误，order_type=attention参数失效，但问题是确实存在的。

**Comment by wuziqian211** [comment]
您好，我是这个部分内容的主要编写者，对于您的问题我已经创建了一个PR#626，感谢您发现这个问题

**Comment by SocialSisterYi** [comment]
请使用这个 API 查询关注的用户`https://api.bilibili.com/x/relation/following`，`older_type`可用
