### ISSUE TITLE
视频的播放地址获取到了，但是无法播放，显示403

### ISSUE THREAD

**Issue by WanYan1314** [SocialSisterYi/bilibili-API-collect#628]
![R0_1_C03)YCU AM`EVM$4NV](https://user-images.githubusercontent.com/118715871/221505124-049e7f2b-92e1-44df-b2e9-7c96ea706b28.png)

**Comment by Quandong-Zhang** [comment]
检查Headers里面的Referer

**Comment by SocialSisterYi** [comment]
请确保 Header 里`Referer`和`User-Agent`字段的正确性，并且保证申请流地址后在2小时内访问链接拉流
