### ISSUE TITLE
获取已隐藏关注列表用户关注API已失效

### ISSUE THREAD

**Issue by zty2019** [SocialSisterYi/bilibili-API-collect#637]
https://app.biliapi.net/x/v2/relation/followings 这个API对已设置关注不可见的用户失效，list返回null，请问是调用方式有所变化还是已经彻底失效呢？有没有其他可以替代的API？

**Comment by wuziqian211** [comment]
对于隐私关注列表已经彻底失效，暂时没有发现可替代的其他API（见 #636 ）

**Comment by wuziqian211** [comment]
fixed in #981
