### ISSUE TITLE
关于sid和bfe_id的讨论

### ISSUE THREAD

**Issue by AnzhiZhang** [SocialSisterYi/bilibili-API-collect#64]
据了解使用api带上bfe_id和sid会更**不**容易被封，以下是我了解到的一些信息，但仍有需要继续研究的地方，开个issue希望能共同完成这部分的研究
- 使用 `api.bilibili.com` 的api进行获取会返回bfe_id
- sid属于 `bilibili.com` 的cookie
- 这两个cookies大约10分钟刷新一次，同时B站会检查10分钟内的扒取次数，若超过上限封30分钟

**Comment by ProgramRipper** [comment]
测试方法：使用python两个`requests.session`（一个在cookies中**仅**设置SESSDATA，另一个没有），分别通过`get`方法，获得浏览`www.bilibili.com`和`api.bilibili.com`后的cookies。
结果：无论是否设置SESSDATA，`www.bilibili.com`均不会返回bfe_id和sid，即使过了10分钟（猜测应该设置bili_jct后才会返回sid）。如果没有设置SESSDATA，会有一个名为main_confirmation的cookie（作用不明）。
`api.bilibili.com`均会返回bfe_id（每次都会，即使没有设置bfe_id，即使bfe_id使用时间未超过10分钟），没有设置bfe_id时，会返回一个“新”的bfe_id（实验证明，不一定是新生成的，有可能会返回曾经用过的，怀疑有一个bfe_id池）。重复使用一个bfe_id超过10分钟后，会强制返回一个（新的？）bfe_id。

如下图，bfe_id存在复现现象。
![20201001175029](https://user-images.githubusercontent.com/45716046/94794607-b0f79180-040e-11eb-9e7a-df8eaa68dc2d.png)

**Comment by zhang-anzhi** [comment]
根据这个测试大概可以明白对于 `api.bilibili.com` 应当保存携带 `bfe_id`， 同时注意每10分钟会强制更新不能继续使用旧的

而sid仍未发现来源。

**Comment by zhang-anzhi** [comment]
我会长期观察我的账号sid用于确定是否会刷新。
