### ISSUE TITLE
如何爬取热评

### ISSUE THREAD

**Issue by jhzgjhzg** [SocialSisterYi/bilibili-API-collect#649]
评论的data中已经没有hots字段，有其他方式爬取热评吗

**Comment by SocialSisterYi** [comment]
这样做就需要把评论区列表的返回格式设置为按照热度排序，如使用 gRpc API 可以把 mode 字段设置为 [MAIN_LIST_HOT](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/grpc_api/bilibili/main/community/reply/v1/reply.proto#L626)，如果使用 RestAPI 可以把 [mode](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/comment/list.md#%E8%8E%B7%E5%8F%96%E8%AF%84%E8%AE%BA%E5%8C%BA%E6%98%8E%E7%BB%86_%E6%87%92%E5%8A%A0%E8%BD%BD) 字段设置为 3
