### ISSUE TITLE
如何不检查网页元素获取b站cookies

### ISSUE THREAD

**Issue by jhzgjhzg** [SocialSisterYi/bilibili-API-collect#675]
如题，是否有可能通过用户账号密码获取cookie

**Comment by SocialSisterYi** [comment]
可以尝试使用 Chrome 扩展 [CookieManager - Cookie Editor](https://chrome.google.com/webstore/detail/cookiemanager-cookie-edit/hdhngoamekjhmnpenphenpaiindoinpo)
