### ISSUE TITLE
请问有空能帮忙看看我java实现的有什么问题吗 好像一直签名出错导致403

### ISSUE THREAD

**Issue by q18892646300** [SocialSisterYi/bilibili-API-collect#683]
try {
            mapper = new ObjectMapper();
            //时间戳
            long wts = System.currentTimeMillis() / 1000;
            System.out.println(wts);
            // 获取nav接口数据
            JsonNode nav = mapper.readTree(HttpRequest.get("https://api.bilibili.com/x/web-interface/nav").body());

            // 提取img_key和sub_key
            String imgKey = nav.get("data").get("wbi_img").get("img_url").asText().replaceAll(".*/([^/]+)\\.png", "$1");
            String subKey = nav.get("data").get("wbi_img").get("sub_url").asText().replaceAll(".*/([^/]+)\\.png", "$1");

            // 拼接并打乱重排mixin_key
            String mixinKey = subKey + imgKey;
            String reMap = StringMapUtils.getMixinKey(mixinKey);
            String mixinKeySlice = reMap.substring(0, Math.min(reMap.length(), 30));
            // 排序和编码请求参数
            String mxKey = "mid=" + mid + "&platform=web&token=&web_location=1550101&wts=" + wts + mixinKeySlice;
            System.out.println(mxKey);
            String wrid=DigestUtils.md5Hex(mxKey);
            System.out.println(wrid);
            //判断开播状态
            JsonNode res = mapper.readTree(HttpRequest.get("https://api.bilibili.com/x/space/wbi/acc/info?mid=" + mid + "&token=&platform=web&web_location=1550101&w_rid=" + wrid + "&wts=" + wts)
                    .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36")
                    .header("Cookie", cookie)
                    .body());
            System.out.println(res);

这是重新排序的工具类:
            public class StringMapUtils {

    private static final int[] mixinKeyEncTab = {
            46, 47, 18, 2, 53, 8, 23, 32, 15, 50, 10, 31, 58, 3, 45, 35, 27, 43, 5, 49,
            33, 9, 42, 19, 29, 28, 14, 39, 12, 38, 41, 13, 37, 48, 7, 16, 24, 55, 40,
            61, 26, 17, 0, 1, 60, 51, 30, 4, 22, 25, 54, 21, 56, 59, 6, 63, 57, 62, 11,
            36, 20, 34, 44, 52
    };

    public static String getMixinKey(String orig) {
        StringBuilder sb = new StringBuilder();
        for (int index : mixinKeyEncTab) {
            sb.append(orig.charAt(index));
        }
        return sb.toString().substring(0, 32);
    }

}

**Comment by Radekyspec** [comment]
似乎是 `String mixinKey = subKey + imgKey;` 这里有问题

`imgKey` 和 `subKey` 的顺序反了

改成 `String mixinKey = imgKey + subKey;` 试一下

**Comment by q18892646300** [comment]
确实 改了之后就可以了 多谢大佬

**Comment by SocialSisterYi** [comment]
#684
