### ISSUE TITLE
番剧API的文档中貌似有内容错误

### ISSUE THREAD

**Issue by MFWT** [SocialSisterYi/bilibili-API-collect#71]
![image](https://user-images.githubusercontent.com/59013632/95023847-e079f880-06b1-11eb-888b-1975180b331e.png)

番剧API的文档（master/bangumi/info.md）中，关于wide_screen项的介绍是“投币数”，此处是否有错？
不敢贸然更正，因此发出一个issues询问一下。

十分感谢。

**Comment by SocialSisterYi** [comment]
谢谢提醒，番剧基本信息api尚未完工，上传这个半成品md文件纯属意外

**Comment by SocialSisterYi** [comment]
现已修复，但文件没有修改完，暂时不上线主页目录
