### ISSUE TITLE
最近发现部分视频点赞接口会出异常

### ISSUE THREAD

**Issue by kiddkyd2** [SocialSisterYi/bilibili-API-collect#714]
以ikun的这个视频来测试    →   [点击跳转](https://www.bilibili.com/video/BV1wo4y1P7gd)

点赞接口  https://api.bilibili.com/x/web-interface/archive/like

目前网页版多了几个参数eab_x，ramval，source，ga
一开始以为是这些参数影响的，后来发现，依然会报错（某些视频就没问题）

后来发现，如果更换csrf，SESSDATA，bili_jct几个值，用网页正常登录的值来覆盖，就能调用成功。
用我自己扫码接口登录成功后返回的值，就会异常： {"code":-403,"message":"账号异常,操作失败","ttl":1}

这不知道你们是不是这样？

**Comment by lovegaoshi** [comment]
我早就有这个问题，索性直接手动加cookies
多谢兄弟点拨:D

**Comment by SocialSisterYi** [comment]
重点关注一下 ck 中的`buvid3`字段，可以用控制变量或者二分法筛选一下具体影响风控状态的字段

**Comment by AlohaHenry** [comment]
csrf和bili_jct是不是一样的？为什么我的cookies里面没有csrf的cookie项

**Comment by lovegaoshi** [comment]
回楼上的朋友 csrf是bilijct
只需要sessdata和csrf，文档里记录的curl方法用正常的cookies还是有效的
拿biliup-rs的cookies.json
试了试，他的cookie是ok的。他是用的bilitv的二维码，又把accesstoken转成sessdata等。有没有好心的兄弟找个js版测试和分享，想当伸手党

**Comment by esoman888** [comment]
有些视频风控了 弹极验出来

**Comment by lovegaoshi** [comment]
我发现在我这里[web](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/login_action/QR.md#%E6%89%AB%E7%A0%81%E7%99%BB%E5%BD%95%E6%B5%81%E7%A8%8B%E4%BC%AA%E4%BB%A3%E7%A0%81)或[web legacy](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/login_action/QR.md#%E7%94%B3%E8%AF%B7%E4%BA%8C%E7%BB%B4%E7%A0%81web%E7%AB%AF-%E6%97%A7%E7%89%88)的二维码登录获得的cookie都没法点赞。[tv](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/login_action/QR.md#tv%E7%AB%AF%E6%89%AB%E7%A0%81%E7%99%BB%E5%BD%95)可以。

**Comment by 14Kay** [comment]
> > 我早就有这个问题，索性直接手动加cookies 多谢兄弟点拨:D
> 
> 我刚试了一下[Web端Cookie刷新](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/cookie_refresh.md?rgh-link-date=2023-06-28T03%3A57%3A35Z)。感觉又行了。。。再观察一下。。

so 结果怎么样 我也遇到这个问题了

**Comment by SocialSisterYi** [comment]
#840

**Comment by JueShiBaWangLong** [comment]
有没有更好的解决方法

**Comment by JueShiBaWangLong** [comment]
还没解决web问题，我都用TV了，不知道可以稳多久




983456783
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SocialSisterYi/bilibili-API-collect"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月8日(星期一) 上午8:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SocialSisterYi/bilibili-API-collect] 最近发现部分视频点赞接口会出异常 (Issue #714)





  
有没有更好的解决方法
  
我现在换成tv扫码接口了
