### ISSUE TITLE
请教最近爬查询用户投稿视频明细报错-799

### ISSUE THREAD

**Issue by zzhjiyin** [SocialSisterYi/bilibili-API-collect#715]
好像老的api([https://api.bilibili.com/x/space/arc/search~)已经完全用不了的，请问新的api应该怎么用呢，请问大佬们有示例参考一下格式吗？
我用以下格式似乎是不正确的
‘https://api.bilibili.com/x/space/wbi/arc/search/mid=53456&ps=5&pn=1&wts=1685073645&w_rid=2e49b69235fb3ea9340422ac9382cbc2’

**Comment by SocialSisterYi** [comment]
目前大量热门 API 均已换成 Wbi 验证类接口，相关使用方法可以参考 #631 

近期会逐步验证补全

**Comment by zzhjiyin** [comment]
> 

谢谢你，我先学习一下
