### ISSUE TITLE
反馈：上报观看进度 api不可用

### ISSUE THREAD

**Issue by cctyl** [SocialSisterYi/bilibili-API-collect#721]
为了模拟播放，尝试了[视频观看数据上报](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/video/report.md#%E4%B8%8A%E6%8A%A5%E8%A7%82%E7%9C%8B%E8%BF%9B%E5%BA%A6%E5%8F%8C%E7%AB%AF) 的两个api，发现均不可用。

下面分别说明下：
- 上报观看进度（双端） https://api.bilibili.com/x/v2/history/report 

这个接口是调不通，复制了文档的示例，修改成这样：
```
curl 'https://api.bilibili.com/x/v2/history/report' \
--data-urlencode 'aid=615058646' \
--data-urlencode 'cid=1172753033' \
--data-urlencode 'progress=34' \
--data-urlencode 'platform=android' \
--data-urlencode 'csrf=省略' \
-b 'SESSDATA=省略'
```
得到的响应始终是：
```
{"code":-400,"message":"请求错误","ttl":1}
```
最初只传递 aid cid 和 progress，后面为了排错，添加上platform 和 csrf，这个csrf，看issue中提到，是bili_jct ，就使用了这个

- 上报视频播放心跳（web端） https://api.bilibili.com/x/click-interface/web/heartbeat
这个接口调用正常，返回也正常。但是不生效，历史记录中并没有出现该视频的观看进度.

请求如下：
```
curl 'api.bilibili.com/x/click-interface/web/heartbeat' \
--data-urlencode 'aid=615058646' \
--data-urlencode 'bvid=BV11h4y1u7aU' \
--data-urlencode 'cid=1172753033' \
--data-urlencode 'played_time=60' \
--data-urlencode 'realtime=60' \
--data-urlencode 'type=3' \
--data-urlencode 'dt=2' \
--data-urlencode 'play_type=0' \
--data-urlencode 'csrf=省略' \
-b 'SESSDATA=省略'

```
响应为：
```
{"code":0,"message":"0","ttl":1}
```
但是经过测试，就是没有在历史记录中出现

**Comment by cctyl** [comment]
我是刚对接不行的。后面我也是直接网页抓取官方的接口，照抄官方的参数，这样就行，github上的不太行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 中午11:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/bilibili-API-collect] 反馈：上报观看进度 api不可用 (Issue #721)




 
你是突然不行的？还是刚对接发现不行？我用的是这个接口：https://api.bilibili.com/x/click-interface/web/heartbeat
 刚试了一下，没问题，官网能出现历史记录。
 我是按照官网的接口参数传递的，不是按照github的参数传递。

**Comment by aaa1115910** [comment]
我普通投稿视频只传 `aid` `cid` `played_time` `csrf` 这几个就能用
剧集类视频就要多传几个参数 `type` `sub_type` `epid` `sid`

**Comment by cctyl** [comment]
> 我用的这个接口 `https://api.bilibili.com/x/click-interface/web/heartbeat` 普通投稿视频只传 `aid` `cid` `played_time` `csrf` 这几个就能用 剧集类视频就要多传几个参数 `type` `sub_type` `epid` `sid`

我大概猜到了，第二个接口不行，是start_ts没传。不传在历史记录就不会显示，或者显示在不知道哪个地方。第一接口原因未知

**Comment by aaa1115910** [comment]
我刚刚试了一下你给的例子，都没有问题，app 里也能看到播放记录
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/34527143/18af31b4-27ce-4402-90b1-6d9807127271)
