### ISSUE TITLE
小白求问：proto解析获取历史日期弹幕错误

### ISSUE THREAD

**Issue by yigehaoren31** [SocialSisterYi/bilibili-API-collect#724]
Traceback (most recent call last):
  File "D:/PycharmProjects/pythonProject2/demo.py", line 179, in <module>
    get_history(bvid='BV1qm4y1e7pb',date='2023-06-28')
  File "D:/PycharmProjects/pythonProject2/demo.py", line 68, in get_history
    danmaku_seg.ParseFromString(data)
google.protobuf.message.DecodeError: Error parsing message

def get_history(bvid,date):
    '''
    获取视频历史弹幕
    输入：视频bvid,日期
    输出：视频某一日期开始的弹幕
    '''
    oid = get_cid(bvid)
    url = 'https://api.bilibili.com/x/v2/dm/web/history/seg.so'
    param = {
        'type' : 1,
        'oid' : oid,
        'date' : date
    }
    # 此接口需要登陆，因此需要cookies
    cookies = {
       ...
    }
    resp = requests.get(url, param, cookies=cookies)
    data = resp.content
    danmaku_seg = test_pb2.DmSegMobileReply()
    danmaku_seg.ParseFromString(data)

**Comment by SocialSisterYi** [comment]
经测试，未发现这个接口存在按照文档内容无法访问的错误

但仅通过你的描述不知道指无法获取指定日期的弹幕，还是无法获取返回每条弹幕的具体发送时间；从报错信息`google.protobuf.message.DecodeError: Error parsing message`来看，应该是接口`https://api.bilibili.com/x/v2/dm/web/history/seg.so`返回了不合法的 PBF 数据，故使用方法函数`ParseFromString()`解析 PBF 数据报错

造成这样的问题可能是接口`https://api.bilibili.com/x/v2/dm/web/history/seg.so`未登录，返回了以下 json 内容

```json
{"code":-101,"message":"账号未登录","ttl":1}
```

或由于调用你定义的函数`get_cid()`获取 cid 出错导致该接口请求错误，返回类似以下内容

```json
{"code":-400,"message":"strconv.ParseInt: parsing \"***\": invalid syntax","ttl":1}
```

但无论何种 json 数据都是纯文本，绝非合法的 PBF 二进制数据

参考代码：

```python
from dm_pb2 import DmSegMobileReply
import requests

resp = requests.get(
    url='https://api.bilibili.com/x/v2/dm/web/history/seg.so',
    params={
        'type' : 1,
        'oid' : 73550718,
        'date' : '2023-06-28'
    },
    headers={
        'Cookie': 'SESSDATA=***'
    }
)
message = DmSegMobileReply()
message.ParseFromString(resp.content)
print(message)
```

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/45892418/69c83636-cd37-45a3-a337-eaac8fc6916f)

**Comment by yigehaoren31** [comment]
您的邮件我已收到，我会尽快给你回复。

**Comment by yigehaoren31** [comment]
确实没有问题，原因是sessdata多打了个=，非常感谢

**Comment by SocialSisterYi** [comment]
> 确实没有问题，原因是sessdata多打了个=，非常感谢

你可以判断一下 Content-Type，来决定按 PBF 还是 json 解析

**Comment by yigehaoren31** [comment]
好的，感谢，已经可以获取历史弹幕了
