### ISSUE TITLE
一条bash命令查视频是否被限流(数据来源未确定准确性)

### ISSUE THREAD

**Issue by kuresaru** [SocialSisterYi/bilibili-API-collect#73]
根据情况替换命令中的bvid  正常输出ok 否则输出fuck

```shell
curl -fsSL https://api.bilibili.com/x/web-interface/view?bvid=BV1eb411k77b | sed -r 's/^.*"attribute":([0-9]+).*$/\1/g' | xargs echo 'obase=2;' | bc | sed -r 's/^.*(.).{6}$/\1/g' | grep -E "^1$" > /dev/null && echo fuck || echo ok
```

**Comment by SocialSisterYi** [comment]
有兄贵画面出现的视频全部是fuck

**Comment by shitianshiwa** [comment]
nodejs写的版本
```
//https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/info.md
//https://api.bilibili.com/x/web-interface/view?bvid=
//https://api.bilibili.com/x/web-interface/view?aid=
import {
    get,
    head
} from 'axios';
let attr = {
    0: "禁止排行",
    1: "禁止推送(该视频不会自动推送给被关注者)",
    2: "禁止网页输出",
    3: "禁止客户端列表",
    4: "搜索禁止",
    5: "海外禁止",
    6: "禁止推荐",
    7: "禁止转载",
    8: "高清视频(视频清晰度>=1080P)",
    9: "是PGC稿件(番剧及影视)",
    10: "允许承包",
    11: "是否番剧",
    12: "是否私单",
    13: "是否限制地区(大多数番剧)",
    14: "允许其他人添加tag",
    15: "未知1",
    16: "跳转(番剧及影视av/bv->ep跳转)",
    17: "是否影视",
    18: "付费",
    19: "推送动态",
    20: "家长模式",
    21: "UGC付费",
    22: "未知2",
    23: "是否失效"
};
const param={aid:"2",bvid:"BV1xx411c7mD"}
const {
                aid,
                bvid
            } = param;
function getVideoInfo(param) {
    return get(`https://api.bilibili.com/x/web-interface/view?${stringify(param)}`)
        .then(
            ({
                data: {
                    data: {
                        bvid,
                        aid,
                        attribute
                    },
                },
            }) => {
                let sum = 0;
                let s = "";
                let temp = attribute.toString(2); //正整数转成二进制字符串
                console.log("1:" + temp);
                let s2 = "";
                for (let i = temp.length - 1; i >= 0; i--) { //要反着取出才是从右到左
                    s2 += temp[i];
                    if (temp[i] == "1") {
                        if (s != "") {
                            s = s + " , " + attr[sum];
                        } else {
                            s = s + attr[sum];
                        }
                    }
                    if (sum < 23) { //目前知道24种状态0-23
                        sum++;
                    } else {
                        break;
                    }
                }
                console.log("1:" + s2);
            }
        )
        .catch(e => {
            logError(e);
        });
}
```

**Comment by duzhaokun123** [comment]
@shitianshiwa 
\```js
...
\```
加高亮

**Comment by kuresaru** [comment]
> nodejs写的版本
> 
> ```
> //https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/info.md
> //https://api.bilibili.com/x/web-interface/view?bvid=
> //https://api.bilibili.com/x/web-interface/view?aid=
> import {
>     get,
>     head
> } from 'axios';
> let attr = {
>     0: "禁止排行",
>     1: "禁止推送(该视频不会自动推送给被关注者)",
>     2: "禁止网页输出",
>     3: "禁止客户端列表",
>     4: "搜索禁止",
>     5: "海外禁止",
>     6: "禁止推荐",
>     7: "禁止转载",
>     8: "高清视频(视频清晰度>=1080P)",
>     9: "是PGC稿件(番剧及影视)",
>     10: "允许承包",
>     11: "是否番剧",
>     12: "是否私单",
>     13: "是否限制地区(大多数番剧)",
>     14: "允许其他人添加tag",
>     15: "未知1",
>     16: "跳转(番剧及影视av/bv->ep跳转)",
>     17: "是否影视",
>     18: "付费",
>     19: "推送动态",
>     20: "家长模式",
>     21: "UGC付费",
>     22: "未知2",
>     23: "是否失效"
> };
> const param={aid:"2",bvid:"BV1xx411c7mD"}
> const {
>                 aid,
>                 bvid
>             } = param;
> function getVideoInfo(param) {
>     return get(`https://api.bilibili.com/x/web-interface/view?${stringify(param)}`)
>         .then(
>             ({
>                 data: {
>                     data: {
>                         bvid,
>                         aid,
>                         attribute
>                     },
>                 },
>             }) => {
>                 let sum = 0;
>                 let s = "";
>                 let temp = attribute.toString(2); //正整数转成二进制字符串
>                 console.log("1:" + temp);
>                 let s2 = "";
>                 for (let i = temp.length - 1; i >= 0; i--) { //要反着取出才是从右到左
>                     s2 += temp[i];
>                     if (temp[i] == "1") {
>                         if (s != "") {
>                             s = s + " , " + attr[sum];
>                         } else {
>                             s = s + attr[sum];
>                         }
>                     }
>                     if (sum < 23) { //目前知道24种状态0-23
>                         sum++;
>                     } else {
>                         break;
>                     }
>                 }
>                 console.log("1:" + s2);
>             }
>         )
>         .catch(e => {
>             logError(e);
>         });
> }
> ```

bash上的字符串操作,这都用上编程语言了还不上个位运算?

**Comment by kuresaru** [comment]
> 有兄贵画面出现的视频全部是fuck

早知道我那个鬼畜就换点素材了...之前还有点其它内容给我退回来改了才过的

**Comment by shitianshiwa** [comment]
主要是想知道有没有结果错误，至于写法。。。。。举手投降

**Comment by shitianshiwa** [comment]
已凉

**Comment by SocialSisterYi** [comment]
> 已凉

R.I.P.   attribute    R.I.P.
