### ISSUE TITLE
IP属地查询

### ISSUE THREAD

**Issue by mckuhei** [SocialSisterYi/bilibili-API-collect#730]
https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr?ip=1.1.1.1

**Comment by SocialSisterYi** [comment]
这个 API 似乎可以查询任意 IP 地址的归属地

**Comment by MarkLily** [comment]
https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr
https://api.live.bilibili.com/client/v1/Ip/getInfoNew
这两个有啥区别？内部是否调的同一个接口，对外不同而已？

**Comment by Sualiu** [comment]
> https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr https://api.live.bilibili.com/client/v1/Ip/getInfoNew 这两个有啥区别？内部是否调的同一个接口，对外不同而已？

这俩都是哔哩哔哩直播的接口，第一个可以指定IP地址，第二个是根据请求IP确定属地。除此之外似乎没有区别。
