### ISSUE TITLE
B站疑似已更新视频观看时长相关 API

### ISSUE THREAD

**Issue by Colerar** [SocialSisterYi/bilibili-API-collect#734]
如 https://api.bilibili.com/archive_stat/stat?aid=170001

```json
{
  "code": 0,
  "message": "0",
  "ttl": 1,
  "data": {
    "aid": 170001,
    "view": 44141032,
    "danmaku": 911681,
    "reply": 179713,
    "favorite": 892768,
    "coin": 283430,
    "share": 633868,
    "now_rank": 0,
    "his_rank": 13,
    "like": 895088,
    "dislike": 0,
    "vt": 43084175,
    "vv": 44141032,
    "no_reprint": 0,
    "copyright": 2
  }
}
```

新增 `vt` 疑似为视频观看时长（**v**ideo **t**ime）

**Comment by 7rikka** [comment]
老视频的观看时长怎么算？总时长*播放量？

**Comment by aaa1115910** [comment]
> 老视频的观看时长怎么算？总时长*播放量？

b 站不可能没做相关数据统计，不然 UP 播放时长成就怎么计算出来的

**Comment by z0z0r4** [comment]
[https://api.bilibili.com/x/web-interface/archive/stat?aid=170001](https://api.bilibili.com/x/web- interface/archive/stat?aid=170001) B站是不更了吗...还是 `vt: null`、


应该再等等还是换成 [https://api.bilibili.com/x/web-interface/archive/stat?aid=170001](https://api.bilibili.com/x/web-interface/archive/stat?aid=170001) 呢？

**Comment by z0z0r4** [comment]
> 这个接口应该是被删除了 🤔

指的是 https://api.bilibili.com/archive_stat/stat?aid=170001 吗？

**Comment by SocialSisterYi** [comment]
> > 这个接口应该是被删除了 🤔
> 
> 指的是 https://api.bilibili.com/archive_stat/stat?aid=170001 吗？

这个接口现在 HTTP 403 了

**Comment by z0z0r4** [comment]
> > > 这个接口应该是被删除了 🤔
> > 
> > 
> > 指的是 https://api.bilibili.com/archive_stat/stat?aid=170001 吗？
> 
> 这个接口现在 HTTP 403 了

这么刺激...还有哪里可以搞到 `vt` 吗？

**Comment by 00randomize00** [comment]
可以访问这个接口https://api.bilibili.com/x/player/wbi/v2?aid=&cid=，last_play_time 就是时间了。只要加上视频的aid和cid, 然后访问时在Cookie里面带上SESSDATA就可以了

**Comment by arnoldhao** [comment]
> 可以访问这个接口[https://api.bilibili.com/x/player/wbi/v2?aid=&cid=，last_play_time](https://api.bilibili.com/x/player/wbi/v2?aid=&cid=%EF%BC%8Clast_play_time) 就是时间了。只要加上视频的aid和cid, 然后访问时在Cookie里面带上SESSDATA就可以了

last_play_time这个值是当前用户播放此视频的进度，上面被403的接口返回的vt是整个视频的播放时长，是为了替代视频播放次数的参数

**Comment by SessionHu** [comment]
vt 相关自取消播放时长外显以来恒为 0, close?
