### ISSUE TITLE
某部（港澳台）番剧的字幕文件消失了（返回`null`

### ISSUE THREAD

**Issue by RadioNoiseE** [SocialSisterYi/bilibili-API-collect#739]
## 描述
我试图荡一部番剧（[處刑少女的生存之道（僅限港澳台地區）](https://www.bilibili.com/bangumi/play/ss41487)）的字幕文件时，发现返回数据里没有字幕文件的地址。

## 方法
- 首先获取剧集信息：浏览器中访问[`https://api.bilibili.com/pgc/view/web/season?season_id=41487`](https://api.bilibili.com/pgc/view/web/season?season_id=41487)（懒得用`curl`了）
- 然后使用获取到的（第一集）的BVID获取视频详细信息：[`https://api.bilibili.com/x/web-interface/view?bvid=BV1Nq4y1e7AF`](https://api.bilibili.com/x/web-interface/view?bvid=BV1Nq4y1e7AF)

## 问题所在
返回数据中，字幕文件地址的键对应的值为空：`"subtitle":null`；而从播放器页面可知它是有繁体中文字幕的。
这种情况下该如何找到失踪的字幕文件呢？

**Comment by 00randomize00** [comment]
请问你需要的是这个接口吗? 
`https://api.bilibili.com/x/player/wbi/v2?aid=595261425&cid=564524943&ep_id=476918&season_id=41487`

以下是这个接口返回subtitle的数据
```
"subtitle": {
            "allow_submit": false,
            "lan": "",
            "lan_doc": "",
            "subtitles": [
                {
                    "id": 928306765832249344,
                    "lan": "zh-Hant",
                    "lan_doc": "中文（繁体）",
                    "is_lock": false,
                    "subtitle_url": "//aisubtitle.hdslb.com/bfs/subtitle/0b10693fd9b107c0cbe540190ea203c2493f7097.json?auth_key=1689166431-8226eb93d78749fcb566b8782274a64f-0-855a715873e2ccc7de88cf1f394b3bf9",
                    "type": 0,
                    "id_str": "928306765832249344",
                    "ai_type": 0,
                    "ai_status": 0
                }
            ]
        }
  ```

**Comment by RadioNoiseE** [comment]
啊是这个，感谢您！

**Comment by 00randomize00** [comment]
更正一下这个接口似乎只需要aid和cid, 其他的很像不需要。我忘记一个一个paramaters去测试了 😅

例子:
`https://api.bilibili.com/x/player/wbi/v2?aid=595261425&cid=564524943`
`https://api.bilibili.com/x/player/wbi/v2?aid=255459061&cid=570480929`

**Comment by Protostars** [comment]
`https://api.bilibili.com/pgc/view/web/season?season_id=41487` 这个接口目前无法访问港澳台地区番剧信息了，请问有新api吗
