### ISSUE TITLE
BV 号 av 号转换算法不适用于 av 号大于 29460791296 的情况

### ISSUE THREAD

**Issue by cxw620** [SocialSisterYi/bilibili-API-collect#740]
经过测试, 目前本 Repo 内的 BV, AV 号互转的算法应该实锤是不适用于 aid >= 29460791296 的情况的, 可以更新一下说明. 不过 aid 也没什么可能累积到这么多. 

验证如下: 

例 1: `https://api.bilibili.com/x/player/wbi/v2?aid=29460791295&cid=1&bvid=BV1uN4F1w7xp`
```json
{"code":-404,"message":"啥都木有","ttl":1}
```

例 2: `https://api.bilibili.com/x/player/wbi/v2?aid=29460791296&cid=1&bvid=BVyfo4f1p74X`
```json
{"code":-400,"message":"请求错误","ttl":1}
```

例 3: `https://api.bilibili.com/x/player/wbi/v2?aid=29460791296&cid=0&bvid=BVyfo4f1p74X`, cid最小是1
```json
{"code":-400,"message":"Key: 'PlayerV2Arg.Cid' Error:Field validation for 'Cid' failed on the 'min' tag","ttl":1}
```

例 4: `https://api.bilibili.com/x/player/wbi/v2?aid=29460791296&cid=1`, 没了bvid就不报错了, 估计有个转换判定. 
```json
{"code":-404,"message":"啥都木有","ttl":1}
```

例 5: `https://api.bilibili.com/x/player/wbi/v2?aid=9223372036854775808&cid=1` 明显是 int64, 不过 gRPC 内涉及 aid 的又是 int32, MAX 2147483647 < 29460791296
```json
{"code":-400,"message":"strconv.ParseInt: parsing \"9223372036854775808\": value out of range","ttl":1}
```

注: 
转换算法及示例代码(Rust)见 [bvid_desc.md](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/bvid_desc.md), 在线运行: [Rust Code Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=859e6b6871cbe27927de6afc56f3f75f)

**Comment by stackinspector** [comment]
已经给我的bvid crate加了`VAILD_AVID_MAX`及检测（）
我是故意不小心不要BV前缀的（）如果要BV前缀的话，av2bv的时候可以直接`[u8; 12]`，给前两位直接赋值，然后后面下标从2开始就可以了，这样减少一次复制，另外实际上对于固定长度字符串可以用arraystr，现在还没有用const generic的arraystr crate（那个arraystring用的typenum），我那个crate自己搓了一个（）
另外建议用Option或者Result来表示错误情况，不要养成用0和空字符串来表示错误的坏习惯（）

**Comment by cxw620** [comment]
> 已经给我的bvid crate加了`VAILD_AVID_MAX`及检测（） 我是故意不小心不要BV前缀的（）如果要BV前缀的话，av2bv的时候可以直接`[u8; 12]`，给前两位直接赋值，然后后面下标从2开始就可以了，这样减少一次复制，另外实际上对于固定长度字符串可以用arraystr，现在还没有用const generic的arraystr crate（那个arraystring用的typenum），我那个crate自己搓了一个（） 另外建议用Option或者Result来表示错误情况，不要养成用0和空字符串来表示错误的坏习惯（）

学到了()

**Comment by 0f-0b** [comment]
发现了两对分别报错和不报错的相邻 BV 号。这可能是 BV 号的上下界？

* `https://api.bilibili.com/x/player/wbi/v2?cid=1&bvid=BV1z66RuGi4n`

  ```json
  {"code":-400,"message":"请求错误","ttl":1}
  ```

  `https://api.bilibili.com/x/player/wbi/v2?cid=1&bvid=BV1z66RuGi4J`

  ```json
  {"code":-404,"message":"啥都木有","ttl":1}
  ```

* `https://api.bilibili.com/x/player/wbi/v2?cid=1&bvid=BV1JSSoei7Vg`

  ```json
  {"code":-404,"message":"啥都木有","ttl":1}
  ```

  `https://api.bilibili.com/x/player/wbi/v2?cid=1&bvid=BV1JSSoei7Vu`

  ```json
  {"code":-400,"message":"请求错误","ttl":1}
  ```

**Comment by cxw620** [comment]
> 发现了两对分别报错和不报错的相邻 BV 号。这可能是 BV 号的上下界？
> 
> * `https://api.bilibili.com/x/player/wbi/v2?cid=1&bvid=BV1z66RuGi4n`
>   ```json
>   {"code":-400,"message":"请求错误","ttl":1}
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   `https://api.bilibili.com/x/player/wbi/v2?cid=1&bvid=BV1z66RuGi4J`
>   ```json
>   {"code":-404,"message":"啥都木有","ttl":1}
>   ```
> * `https://api.bilibili.com/x/player/wbi/v2?cid=1&bvid=BV1JSSoei7Vg`
>   ```json
>   {"code":-404,"message":"啥都木有","ttl":1}
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   `https://api.bilibili.com/x/player/wbi/v2?cid=1&bvid=BV1JSSoei7Vu`
>   ```json
>   {"code":-400,"message":"请求错误","ttl":1}
>   ```

bvid BV1z66RuGi4n -> aid 258263486042588315
bvid BV1z66RuGi4J -> aid 258263486042588388
bvid BV1JSSoei7Vg -> aid 78886850937548507
bvid BV1JSSoei7Vu -> aid 78886850937548068
用已知的算法算 aid 超限了, 不能用已知的算法算, 所以我们不知道这些 bvid 对应的 cid()
所以你是怎么发现这两对 bvid 的

**Comment by 0f-0b** [comment]
> 所以你是怎么发现这两对 bvid 的

假设（并没有尝试验证过（））：

* 已知的算法中除了 `XORN`、`ADDN` 和 `MAP` 三个常数以外其他的细节都准确无误。
* 其他参数合法时，服务器返回 `-400` 报错当且仅当 `bvid` 转换到 av 号后最高 k 位非零。
* 实际的 `XORN` 最高 k 位为零。
* 实际的 `MAP` 是 `[9, 8, 1, 6, 2, 4, 3, 5, 7, 0]`。

然后在已知合法的 BV 号 `BV1xx411c7mD` = `av2` 和值最小的 BV 号 `BVffffffffff` 之间二分找到了第一对，在它和值最大的 BV 号 `BVFFFFFFFFFF` 之间二分找到了第二对。两对 BV 号的差是 2⁵¹，即 k = 13。

**Comment by catlair** [comment]
只有官方的开发才知道这些值他们到底是想给多大。你这计算值都已经超过ecmascript number的范围了😅

**Comment by 0f-0b** [comment]
进一步测试时偶然发现 `bvid` 参数中开头的 `BV1` 可以省略（如 `https://api.bilibili.com/x/player/wbi/v2?cid=1&bvid=xx411c7mD`），这可能意味着 BV 号只有最后 9 位包含信息。如果这样，值最大的 BV 号就会是 `BV1FFFFFFFFF`，恰好略小于 2⁵³。

可惜目前还没有 av 号足够大的视频，确实没有办法知道完整的转换算法。

**Comment by cxw620** [comment]
> BV 号实质上以 `BV1` 打头，并且 AV 最大值为 251，可以参考我的实现：
> 
> https://github.com/Colerar/abv/blob/main/src/lib.rs
> 
> 已同步发布至 crates.io，算法来自 B 站某 JS 文件，另外 GitHub 上实际也有某员工上传的 Go 版。
> 
> 最大值取 251 可能是因为这是 IEEE 754 浮点数所能承载的极限。

Mark ~

**Comment by xiaoyv404** [comment]
close by #857
