### ISSUE TITLE
新视频清晰度只能获取720p了

### ISSUE THREAD

**Issue by TommyLe1** [SocialSisterYi/bilibili-API-collect#744]
各位朋友有没有遇到同样的问题？ 画质只有720p，应该不是cookis问题，因为看老视频还可以获取1080p，但是一些最近更新的视频却只有720p

**Comment by aaa1115910** [comment]
你如何确定那些新视频在上传时不是传的 720P？

**Comment by TommyLe1** [comment]
> 你如何确定那些新视频在上传时不是传的 720P？

很多up主都变成720p了，按理说不可能这么巧，多个up同时都传720p清晰度的视频了

**Comment by lm317379829** [comment]
早就是这样了，mp4最高720P，想要更高用dash

**Comment by TommyLe1** [comment]
> 早就是这样了，mp4最高720P，想要更高用dash

为什么我用dash获取的视频流只会有640p以下的清晰度呢？ 视频信息中支持4k，而我的cookis也是最新的

**Comment by TommyLe1** [comment]
> 看看你的参数
> ?bvid=${bvid}&cid=${cid}&qn=127&fnval=4048&fnver=0&fourk=1&voice_balance=1

嗯，这下可以了，谢了。

**Comment by kaikaiblog** [comment]
> > 
> 
> 看看你的参数 ?bvid=${bvid}&cid=${cid}&qn=127&fnval=4048&fnver=0&fourk=1&voice_balance=1

非常感谢您的params 他让我成功获取到了1080p的视频，其中的fnval=4048文档中是没有提及，希望完善文档。

**Comment by YuHuanTin** [comment]
> > > 
> > 
> > 
> > 看看你的参数 ?bvid=${bvid}&cid=${cid}&qn=127&fnval=4048&fnver=0&fourk=1&voice_balance=1
> 
> 非常感谢您的params 他让我成功获取到了1080p的视频，其中的fnval=4048文档中是没有提及，希望完善文档。

4048 = 2048 | 1024 | 512 | 256 | 128 | 64 | 16

[请看这](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/video/videostream_url.md#fnval视频流格式标识)

16 | DASH 格式 | 与 MP4、FLV 格式互斥
64 | 是否需求 HDR 视频 | 需求 DASH 格式仅 H.265 编码需要qn=125大会员认证
128 | 是否需求 4K 分辨率 | 该值与fourk字段协同作用需要qn=120大会员认证
256 | 是否需求杜比音频 | 需求 DASH 格式大会员认证
512 | 是否需求杜比视界 | 需求 DASH 格式大会员认证
1024 | 是否需求 8K 分辨率 | 需求 DASH 格式需要qn=127大会员认证
2048 | 是否需求 AV1 编码 | 需求 DASH 格式
