### ISSUE TITLE
新版获取直播流的 api

### ISSUE THREAD

**Issue by nulla2011** [SocialSisterYi/bilibili-API-collect#746]
[旧版 api](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/live/live_stream.md) 没法获取现在直播正在广泛使用的格式（fMP4-HLS），我从 `room-player.min.js` 中发现了疑似新版的 api 地址的代码
```
a.ajax("//api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=" + e.roomId + "&protocol=0,1&format=0,1,2&codec=0,1&qn=" + e.qn + "&platform=" + (e.isMobile ? "html5" : "web") + "&ptype=8&dolby=5" + (e.isMobile ? "" : "&panorama=1")
```
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/5034243/c256908d-22c4-49ac-81c1-b2782b63a9e6)
直接访问就可以拿到 fmp4 格式的地址

**Comment by xiaoyv404** [comment]
Pr welcome

**Comment by nulla2011** [comment]
哦原来都写在 [info.md](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/live/info.md#%E8%8E%B7%E5%8F%96%E7%9B%B4%E6%92%AD%E9%97%B4%E4%BF%A1%E6%81%AF-1) 里面了，没看见（
