### ISSUE TITLE
卡在了websocket连接服务端

### ISSUE THREAD

**Issue by NanthanYYDS** [SocialSisterYi/bilibili-API-collect#749]
server rejected WebSocket connection: HTTP 403

**Comment by xiaoyv404** [comment]
请表述清楚

**Comment by NanthanYYDS** [comment]
我的疑惑是关于/docs/live
/message_stream.md中MQ数据格式和websocket通信的。
因为自学python不是很懂怎么搞报头（数据包为MQ（Message Queue，消息队列）使用Websocket或TCP连接作为通道，具体格式为头部数据+正文数据）。

`
import asyncio
import websockets
import json

async def main():
    async with websockets . connect("ws://broadcastlv.chat.bilibili.com:2244") as websocket:
        data = {"roomid":"870691"}
        websocket.send(json.dumps(data).encode("utf-8"))
    
asyncio.run(main())
`

这个代码报错：websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 403

请问一下我该如何修改才能让他与服务器成功连接呀。如果可以的话能不能推荐一下学习这方面的文章什么的 orz

**Comment by NanthanYYDS** [comment]
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)
改成wss之后报错是这个
网上搜到的教程行不通呜呜呜，自学太难了，大学会教这些吗

**Comment by NanthanYYDS** [comment]
谢谢大佬，我就是不知道这个头部数据怎么搞，orz

**Comment by NanthanYYDS** [comment]
> > 我的疑惑是关于/docs/live /message_stream.md中MQ数据格式和websocket通信的。 因为自学python不是很懂怎么搞报头（数据
> > 问题出在这句：websockets.connect("ws://broadcastlv.chat.bilibili.com:2244") 这个代码报错：websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 403
> > 请问一下我该如何修改才能让他与服务器成功连接呀。如果可以的话能不能推荐一下学习这方面的文章什么的 orz
> 
> url错了, 没有path, 需要加上`/sub`, 完整url为`wss://broadcastlv.chat.bilibili.com/sub` 另外你没有头部数据, 修改后如下:
> 
> ```python
> async def main():
>     async with websockets.connect("wss://broadcastlv.chat.bilibili.com/sub", user_agent_header='Mozilla/5.0') as websocket:
>         index = 1
>         data = json.dumps({"roomid":"870691"}, separators=(',', ':')).encode()
>         data_bytes = bytearray()
>         data_bytes += (0x0010 + len(data)).to_bytes(4, 'big')
>         data_bytes += b'\x00\x10'
>         data_bytes += (1).to_bytes(2, 'big')
>         data_bytes += (7).to_bytes(4, 'big')
>         data_bytes += index.to_bytes(4, 'big')
> 
>         data_bytes += data
> 
>         await websocket.send(data_bytes)
>         index += 1
>         print(await websocket.recv())
> ```

但是好像没有接收到啥耶，文档里面说发送认证包之后会收到回复，但是没有输出呢

**Comment by NanthanYYDS** [comment]
orz，我是**
