### ISSUE TITLE
爬取 refresh_csrf 请求 data 一直为乱码

### ISSUE THREAD

**Issue by NoahCodeGG** [SocialSisterYi/bilibili-API-collect#750]
项目环境为「next.js」
尝试配置「axios」中「responseType」为「text」或「arraybuffer」和关闭「decompress」，都不能获取到正常的 html 文本
请问有大佬遇到并解决的吗？求个思路

**Comment by catlair** [comment]
axios 直接 get 就能取到页面吧，自动判断类型的。

html 类型是 document

没能复现，也不知道乱码是啥

**Comment by NoahCodeGG** [comment]
> axios 直接 get 就能取到页面吧，自动判断类型的。
> 
> html 类型是 document
> 
> 没能复现，也不知道乱码是啥

抱歉，忘发图片了，这是刚用 fetch 获取的
<img width="1532" alt="image" src="https://github.com/SocialSisterYi/bilibili-API-collect/assets/51156988/371ff05e-38b4-4453-a6ca-f6b02eb02171">

**Comment by SessionHu** [comment]
Bilibili 主站 HTML 页面很多都是强制 GZip 压缩的, 无论请求头是否传入 Accept-Encoding, 这一点在使用 cURL 请求时很容易注意到.
解决方案为检查 MagicNumber, 若为 gzip 压缩进行解压获取数据即可.
Close?
