### ISSUE TITLE
查看视频状态数接口报错

### ISSUE THREAD

**Issue by 7rikka** [SocialSisterYi/bilibili-API-collect#753]
> https://api.bilibili.com/archive_stat/stat?aid=91572143

返回403 看着像弃用了

**Comment by SessionHu** [comment]
Please close as #1066 has been merged.
https://github.com/SocialSisterYi/bilibili-API-collect/blob/60a0c5d1a2f44fe61335da04571305fa7727a968/docs/video/status_number.md#L1-L9
