### ISSUE TITLE
发送短信验证码_web端：86103 请下载最新版本哔哩哔哩App完成注册或继续登录

### ISSUE THREAD

**Issue by Sualiu** [SocialSisterYi/bilibili-API-collect#756]
人机验证啥的都挺成功，到最后的发送验证码，接口返回异常 code：86103 请下载最新版本哔哩哔哩App完成注册或继续登录。

好像是个新增的提示？测试和cookie无关，header头也改了一堆，似乎关系不大。

由于geetest时间太短，也没什么头绪 ，半天没找到问题所在。

接口：https://passport.bilibili.com/x/passport-login/web/sms/send

使用php的guzzle库，版本7.7。

意外返回：
`Array ( [code] => 86103 [message] => 请下载最新版本哔哩哔哩App完成注册或继续登录 [ttl] => 1 [data] => )`

**Comment by Sualiu** [comment]
补全headers头部信息即可

**Comment by waerlp** [comment]
> 补全headers头部信息即可

想问一下现在还有出现吗，我也出现了但是补全了也没什么用

**Comment by Sualiu** [comment]
> > 补全headers头部信息即可
> 
> 想问一下现在还有出现吗，我也出现了但是补全了也没什么用

虽然很晚了，我也不想说。但你有可能没有注意到，请求接口的User-Agent和人机验证的User-Agent不一致就会报错。

**Comment by waerlp** [comment]
> 

不好意思打扰了，这个我测试了，但是有时候就能过有时候过不去，有什么好的解决办法吗

**Comment by Sualiu** [comment]
> > 
> 
> 不好意思打扰了，这个我测试了，但是有时候就能过有时候过不去，有什么好的解决办法吗

刚才测试了一下，发信啥的正常。至于偶尔的失败，倒是很久以前遇到过，但都是刷新人机验证重新再来几次就没事了。

具体分析的话，可能还要看具体代码逻辑？

**Comment by waerlp** [comment]
> > > 
> > 
> > 
> > 不好意思打扰了，这个我测试了，但是有时候就能过有时候过不去，有什么好的解决办法吗
> 
> 刚才测试了一下，发信啥的正常。至于偶尔的失败，倒是很久以前遇到过，但都是刷新人机验证重新再来几次就没事了。
> 
> 具体分析的话，可能还要看具体代码逻辑？失败是什么报错？情况是？

应该是没办法解决的了，最近片哥太多了，上了强风控，还是抱歉那么晚打扰了

**Comment by Sualiu** [comment]
> > > > 
> > > 
> > > 
> > > 不好意思打扰了，这个我测试了，但是有时候有时候有时候过不去，有什么好的解决办法吗？
> > 
> > 
> > 刚才测试了一下，发信啥的正常。至于偶尔的失败，倒是很久以前遇到过，但都是刷新人机重新验证再来几次就恢复了。
> > 具体分析的话，可能还要看具体代码逻辑？失败是什么报错？情况是？
> 
> 应该是没办法解决的了，最近片哥太多了，上了强风控，还是后悔那么晚打扰了

我这测试的倒是没怎么失败，海外服务器。可能是风控吧，可以具体找找问题，风控又不是玄学。

没啥事，大半夜的我不也没睡。

**Comment by Sualiu** [comment]
> > > > 
> > > 
> > > 
> > > 不好意思打扰了，这个我测试了，但是有时候有时候有时候过不去，有什么好的解决办法吗？
> > 
> > 
> > 刚才测试了一下，发信啥的正常。至于偶尔的失败，倒是很久以前遇到过，不过都是刷新人机重新验证一下再来几次就恢复了。
> > 具体分析的话，可能还要看具体代码逻辑？失败是什么报错？情况是？
> 
> 应该是没办法解决的了，最近片哥太多了，上了强风控，还是补充那么晚干扰了

感觉不大可能高频率出现错误。毕竟是扒的官网接口，用户不能登不上哔哩哔哩是吧_(:3 ⌒ﾞ)_

**Comment by waerlp** [comment]
> 

确实，别卷了快睡觉

**Comment by waerlp** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 不好意思打扰了，这个我测试了，但是有时候有时候有时候过不去，有什么好的解决办法吗？
> > > 
> > > 
> > > 刚才测试了一下，发信啥的正常。至于偶尔的失败，倒是很久以前遇到过，不过都是刷新人机重新验证一下再来几次就恢复了。
> > > 具体分析的话，可能还要看具体代码逻辑？失败是什么报错？情况是？
> > 
> > 
> > 应该是没办法解决的了，最近片哥太多了，上了强风控，还是补充那么晚干扰了
> 
> 感觉不大可能高频率出现错误。毕竟是扒的官网接口，用户不能登不上哔哩哔哩是吧_(:3 ⌒ﾞ)_

这个86103报错4月就出了，当时补个buvid3就可以解决，现在补ck是没法解决了，就是点选的问题

**Comment by waerlp** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 不好意思打扰了，这个我测试了，但是有时候有时候有时候过不去，有什么好的解决办法吗？
> > > 
> > > 
> > > 刚才测试了一下，发信啥的正常。至于偶尔的失败，倒是很久以前遇到过，不过都是刷新人机重新验证一下再来几次就恢复了。
> > > 具体分析的话，可能还要看具体代码逻辑？失败是什么报错？情况是？
> > 
> > 
> > 应该是没办法解决的了，最近片哥太多了，上了强风控，还是补充那么晚干扰了
> 
> 感觉不大可能高频率出现错误。毕竟是扒的官网接口，用户不能登不上哔哩哔哩是吧_(:3 ⌒ﾞ)_

已经解决

**Comment by xiaoheimaoo** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 不好意思打扰了，这个我测试了，但是有时候有时候有时候过不去，有什么好的解决办法吗？
> > > > 
> > > > 
> > > > 刚才测试了一下，发信啥的正常。至于偶尔的失败，倒是很久以前遇到过，不过都是刷新人机重新验证一下再来几次就恢复了。
> > > > 具体分析的话，可能还要看具体代码逻辑？失败是什么报错？情况是？
> > > 
> > > 
> > > 应该是没办法解决的了，最近片哥太多了，上了强风控，还是补充那么晚干扰了
> > 
> > 
> > 感觉不大可能高频率出现错误。毕竟是扒的官网接口，用户不能登不上哔哩哔哩是吧_(:3 ⌒ﾞ)_
> 
> 已经解决

怎么解决的，大佬

**Comment by nizhenyu2022** [comment]
> 

大佬能不能教下怎么解决的，谢谢。

**Comment by iiaowro** [comment]
@xiaoheimaoo @nizhenyu2022 需要补充请求头

**Comment by linshao520kim** [comment]
请问有解的方法吗？各种都试了始终返回86103

**Comment by linshao520kim** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 不好意思打扰了，这个我测试了，但是有时候有时候有时候过不去，有什么好的解决办法吗？
> > > > 
> > > > 
> > > > 刚才测试了一下，发信啥的正常。至于偶尔的失败，倒是很久以前遇到过，不过都是刷新人机重新验证一下接下来几次就恢复了。
> > > > 具体分析的话，可能还要看具体代码逻辑失败？报错是什么？情况是？
> > > 
> > > 
> > > 应该是没办法解决的了，最近片太多了，上了强风控，还是补充那么晚干预了
> > 
> > 
> > 不太感觉可能出现频率较高的错误。毕竟是扒的官网接口，用户不能登不上哔哩哔哩是吧_(:3 ⌒ﾞ)_
> 
> 已经解决

请问如何解决的

**Comment by waerlp** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 不好意思打扰了，这个我测试了，但是有时候有时候有时候过不去，有什么好的解决办法吗？
> > > > > 
> > > > > 
> > > > > 刚才测试了一下，发信啥的正常。至于偶尔的失败，倒是很久以前遇到过，不过都是刷新人机重新验证一下接下来几次就恢复了。
> > > > > 具体分析的话，可能还要看具体代码逻辑失败？报错是什么？情况是？
> > > > 
> > > > 
> > > > 应该是没办法解决的了，最近片太多了，上了强风控，还是补充那么晚干预了
> > > 
> > > 
> > > 不太感觉可能出现频率较高的错误。毕竟是扒的官网接口，用户不能登不上哔哩哔哩是吧_(:3 ⌒ﾞ)_
> > 
> > 
> > 已经解决
> 
> 请问如何解决的

洗洗睡吧，就算你过了这个还有2层风控等你呢

**Comment by xiao-rao** [comment]
经过一小波测试，发现可能跟buvid3这个参数有关，使用python requests库对https://www.bilibili.com/进行请求拿到set-cookie 
buvid3和b_nut的值，然后生成其他cookie参数  包括fp。请求下发短信 会返回86013   请下载最新版本哔哩哔哩App完成注册或继续登录的错误，然后直接复制浏览器上的buvid3 替换到模拟的cookie里 请求成功 测试多次页不会再出错。可能使用buvid3参数做了什么。还待继续研究
