### ISSUE TITLE
如何获取APP密钥和APP签名呢？

### ISSUE THREAD

**Issue by xhemj** [SocialSisterYi/bilibili-API-collect#78]
如何获取APP密钥和APP签名呢？
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/APP_widget/splash.md

**Comment by duzhaokun123** [comment]
[APP方式（手机客户端及TV端等）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/other/API_auth.md#app%E6%96%B9%E5%BC%8F%E6%89%8B%E6%9C%BA%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%8F%8Atv%E7%AB%AF%E7%AD%89)

**Comment by xhemj** [comment]
好的，谢谢
