### ISSUE TITLE
[疑似]B站播放时长显示字段更新

### ISSUE THREAD

**Issue by mhbalthasar** [SocialSisterYi/bilibili-API-collect#781]
https://api.bilibili.com/x/web-interface/ranking/v2
https://api.bilibili.com/x/web-interface/popular

对应播放时长字段：
vt_display

此外还有视频详情(https://api.bilibili.com/x/web-interface/view/detail)里的Realted字段里的稿子也给了vt_display

目前观察单位都是：万

**Comment by SessionHu** [comment]
目前所有接口 vt_display 恒为 `0`

**Comment by SocialSisterYi** [comment]
该字段已弃用，关了
