### ISSUE TITLE
限制 Github Action 在 forked 仓库中的使用

### ISSUE THREAD

**Issue by catlair** [SocialSisterYi/bilibili-API-collect#783]
每次 pr 都会收到来自 github action 的错误邮件，很烦，而且浪费资源。

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/44313800/f62febd9-f4e0-419f-9dba-a77ce8c1d5b1)

**Comment by xiaoyv404** [comment]
Close by #784
