### ISSUE TITLE
新风控报错 -401

### ISSUE THREAD

**Issue by z0z0r4** [SocialSisterYi/bilibili-API-collect#788]
```{'code': -401, 'message': '非法访问', 'ttl': 1, 'data': {'ga_data': {'decisions': ['verify_captcha_level2'], 'risk_level': 1, 'grisk_id': '55aa98739b8235bf64ad75d38164dc40', 'decision_ctx': {'buvid': '931081E9D-AE3E-9F5F-9109F-6E1521591018836102infoc', 'decision_type': '4', 'ip': '4.154.90.97', 'mid': '0', 'origin_scene': 'anti_crawler', 'scene': 'anti_crawler', 'ua': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37', 'v_checkIds': '931081E9D-AE3E-9F5F-9109F-6E1521591018836102infoc', 'v_seconds': '120', 'v_times': '100', 'v_voucher': 'voucher_2c8c3a77-c37a-44f8-8eb5-8e1858e2e5b6'}}}}```
原因未知，似乎绑定 buvid3

**Comment by choco9527** [comment]
我也出现了

**Comment by choco9527** [comment]
找到原因了，我是请求的ua被识别为爬虫了，设置ua就好
`const requestHeader = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
}`

**Comment by LTDSA** [comment]
> 找到原因了，我是请求的ua被识别为爬虫了，设置ua就好 `const requestHeader = { 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' }`

依旧不太行，怀疑和 SESSDATA 有关。很奇怪，我在电脑上获取的 Cookie 不行（Windows 和 Mac 都是），但 Android 上获取的就可以，把电脑上的 Cookie 替换掉之后马上就又可以了，但明明用的是同一个接口。

**Comment by z0z0r4** [comment]
很多因素吧... buvid3 也是原因之一

注意 risk level

**Comment by SessionHu** [comment]
请求的接口地址是哪个? 有些有 Wbi 签名的接口访问原地址也会出现类似错误.
