### ISSUE TITLE
关于https://api.bilibili.com/x/space/arc/search出现“请求过于频繁”的解决方法

### ISSUE THREAD

**Issue by BaiCha2007** [SocialSisterYi/bilibili-API-collect#789]
`https://api.bilibili.com/x/space/arc/search`
这个API接口是用来获取UP主的视频之类的信息
最近这个接口常见“{"code":-799,"message":"请求过于频繁，请稍后再试","ttl":1}”的错误
（其实也是可以用的）
--------------------------------
关于此错误
可以更换为更加稳定的API
“https://api.bilibili.com/x/space/wbi/arc/search”
对的，就是直接加入一个“/wbi”
就可以解决此问题
（这个接口我自己测试出来更加稳定）

**Comment by BaiCha2007** [comment]
对了，这个接口和旧的接口参数好像是一样的，可以直接用。
(本来就没有几个参数，小声)

**Comment by catlair** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/631#issuecomment-1563788098

不只是搜索

**Comment by BaiCha2007** [comment]
谢谢

> [#631 (comment)](https://github.com/SocialSisterYi/bilibili-API-collect/issues/631#issuecomment-1563788098)
> 
> 不只是搜索

谢谢，请问怎么关闭这个issue

**Comment by shugen002** [comment]
看到那个close issue的按钮了吗，点下去就可以了。

**Comment by BaiCha2007** [comment]
thx


> 看到那个close issue的按钮了吗，点下去就可以了。

thx
