### ISSUE TITLE
202分区请求错误

### ISSUE THREAD

**Issue by JunzhouLiu** [SocialSisterYi/bilibili-API-collect#79]
`http://api.bilibili.com/x/web-interface/ranking/region?rid=202&day=3`
```
{"code":-400,"message":"请求错误","ttl":1,"data":null}
```

**Comment by SocialSisterYi** [comment]
正常情况，“资讯”分区极其子分区不参与排行，所以请求id为202-206的排行数据会报错，网页和客户端也没有该分区的排名条目
