### ISSUE TITLE
用户空间详细信息 sys_notice 字段示例失效

### ISSUE THREAD

**Issue by stydxm** [SocialSisterYi/bilibili-API-collect#791]
[用户空间详细信息](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/user/info.md#%E7%94%A8%E6%88%B7%E7%A9%BA%E9%97%B4%E8%AF%A6%E7%BB%86%E4%BF%A1%E6%81%AF)中`sys_notice`示例 id 为5的示例用户[82385070](https://space.bilibili.com/82385070)个人主页已无该banner
![](https://github.com/SocialSisterYi/bilibili-API-collect/assets/62790279/e2679c17-70ff-4574-b7a6-96a6f414d814)
![](https://github.com/SocialSisterYi/bilibili-API-collect/assets/62790279/0858e302-cb25-4888-9e0f-7f24dfdcfff6)

**Comment by SessionHu** [comment]
Please close. See #1081.
