### ISSUE TITLE
游客获取 `buvid3`/`buvid4`

### ISSUE THREAD

**Issue by z0z0r4** [SocialSisterYi/bilibili-API-collect#795]
GET https://api.bilibili.com/x/frontend/finger/spi
```json
{
    "code": 0,
    "data": {
        "b_3": "7CD33A68-44A3-CD36-E673-9E2BA37DA0FE65095infoc",
        "b_4": "7CD783BE-C11C-0A7D-F97D-E7A97CA2A5EF65095-023082418-Pk1O31qDhl72PWBbOdWFow322IXICu3XsGWvXg7QG+Q02pcHIJbzyQ=="
    },
    "message": "ok"
}
```

**Comment by GOOD-AN** [comment]
正常第一次访问页面的话`buvid3`是返回头`set-cookie`内携带

**Comment by z0z0r4** [comment]
> 正常第一次访问页面的话`buvid3`是返回头`set-cookie`内携带

http 接口方便一点

**Comment by titxue** [comment]
接口的貌似不能用。

**Comment by z0z0r4** [comment]
> 接口的貌似不能用。

可以的我记得

**Comment by GOOD-AN** [comment]
> http 接口方便一点

确实，不过我记得头部的话，还有个参数`b_nut`，虽然目前没看到有什么意义，而且，测试了几个接口，`buvid3`和`buvid4`甚至乱写都可以，只要非空？

**Comment by z0z0r4** [comment]
> > http 接口方便一点
> 
> 确实，不过我记得头部的话，还有个参数`b_nut`，虽然目前没看到有什么意义，而且，测试了几个接口，`buvid3`和`buvid4`甚至乱写都可以，只要非空？

有的接口不能乱写，比如放映室，`b_nut` 没人分析不知道，在这问没用...

**Comment by GOOD-AN** [comment]
> 有的接口不能乱写，比如放映室，`b_nut` 没人分析不知道，在这问没用...

是的，只是有些接口

**Comment by GOOD-AN** [comment]
不好意思，将删除其余无关回复。

**Comment by kaosaa** [comment]
> > > http 接口方便一点
> > 
> > 
> > 确实，不过我记得头部的话，还有个参数`b_nut`，虽然目前没看到有什么意义，而且，测试了几个接口，`buvid3`和`buvid4`甚至乱写都可以，只要非空？
> 
> 有的接口不能乱写，比如放映室，`b_nut` 没人分析不知道，在这问没用...

Math.floor(Date.now() / 1e3).toString()

**Comment by ahut666** [comment]
> GET https://api.bilibili.com/x/frontend/finger/spi
> 
> ```json
> {
>     "code": 0,
>     "data": {
>         "b_3": "7CD33A68-44A3-CD36-E673-9E2BA37DA0FE65095infoc",
>         "b_4": "7CD783BE-C11C-0A7D-F97D-E7A97CA2A5EF65095-023082418-Pk1O31qDhl72PWBbOdWFow322IXICu3XsGWvXg7QG+Q02pcHIJbzyQ=="
>     },
>     "message": "ok"
> }
> ```

这个API没有了吧

**Comment by ahut666** [comment]
> GET https://api.bilibili.com/x/frontend/finger/spi
> 
> ```json
> {
>     "code": 0,
>     "data": {
>         "b_3": "7CD33A68-44A3-CD36-E673-9E2BA37DA0FE65095infoc",
>         "b_4": "7CD783BE-C11C-0A7D-F97D-E7A97CA2A5EF65095-023082418-Pk1O31qDhl72PWBbOdWFow322IXICu3XsGWvXg7QG+Q02pcHIJbzyQ=="
>     },
>     "message": "ok"
> }
> ```

这个接口好像没有了

**Comment by z0z0r4** [comment]
![图片](https://github.com/SocialSisterYi/bilibili-API-collect/assets/78744121/24d1d8f1-7c91-45f0-860a-9d0fd1fe0c10)


> > GET https://api.bilibili.com/x/frontend/finger/spi
> > ```json
> > {
> >     "code": 0,
> >     "data": {
> >         "b_3": "7CD33A68-44A3-CD36-E673-9E2BA37DA0FE65095infoc",
> >         "b_4": "7CD783BE-C11C-0A7D-F97D-E7A97CA2A5EF65095-023082418-Pk1O31qDhl72PWBbOdWFow322IXICu3XsGWvXg7QG+Q02pcHIJbzyQ=="
> >     },
> >     "message": "ok"
> > }
> > ```
> 
> 这个接口好像没有了

**Comment by kingwingfly** [comment]
我使用这种方式获取的buvid来调用视频点赞的API有点问题
```sh
$ curl "https://api.bilibili.com/x/web-interface/archive/like?bvid=xxx&like=1&csrf=xxx" \
-H "Cookie: SESSDATA=xxx; buvid3=60CFFD2A-5D28-97BC-A6FD-75838D5CD72330730infoc" \
-X POST

Object {
    "code": Number(-403),
    "message": String("账号异常,操作失败"),
    "ttl": Number(1),
}
```
使用浏览器里copy的没有问题。

只需要SESSDATA的其他API也没问题，csrf也没问题，就是buvid不太对。

**Comment by z0z0r4** [comment]
> EDIT：游客获取鸭，打扰了（doge）
> 
> 我使用这种方式获取的buvid来调用视频点赞的API有点问题
> 
> ```shell
> $ curl "https://api.bilibili.com/x/web-interface/archive/like?bvid=xxx&like=1&csrf=xxx" \
> -H "Cookie: SESSDATA=xxx; buvid3=60CFFD2A-5D28-97BC-A6FD-75838D5CD72330730infoc" \
> -X POST
> 
> Object {
>     "code": Number(-403),
>     "message": String("账号异常,操作失败"),
>     "ttl": Number(1),
> }
> ```
> 
> 使用浏览器里copy的没有问题。
> 
> 只需要SESSDATA的其他API也没问题，csrf也没问题，就是buvid不太对。

是不是游客无所谓的...已登录删 buvid 也是调 spi

**Comment by kingwingfly** [comment]
@z0z0r4 

我看 #933 的意思似乎是 buvid 还需要激活。
但是我激活了，也没成功用它完成点赞API的调用。可能是我犯了其他低级错误。

如果确实可以直接用请求到的buvid调用点赞API的话，麻烦帮我再确认一下(🙏ˊᗜˋ*)，我好继续排查。

如果有兴趣，也可以帮我康康 [code](https://github.com/kingwingfly/backup/blob/deff82dad42253da1ca68a800b5103b938da60ba/src/api/like.rs#L7)

**Comment by z0z0r4** [comment]
我看不懂rs，但看起来是这个流程，不确定 headers 之类的风控你没搞错

但是 spi 拿到的 buvid 对于点赞是不需要激活的，我这还没激活就可以用

```python
>>> from bilibili_api import video, Credential, sync
>>> c = Credential(sessdata="", bili_jct="")
>>> v = video.Video(bvid="BV1EK4y1z7St", credential=c)
>>> sync(v.like())
>>> sync(v.has_liked())
1
```

**Comment by z0z0r4** [comment]
> EDIT：游客获取鸭，打扰了（doge）
> 
> 我使用这种方式获取的buvid来调用视频点赞的API有点问题
> 
> ```shell
> $ curl "https://api.bilibili.com/x/web-interface/archive/like?bvid=xxx&like=1&csrf=xxx" \
> -H "Cookie: SESSDATA=xxx; buvid3=60CFFD2A-5D28-97BC-A6FD-75838D5CD72330730infoc" \
> -X POST
> 
> Object {
>     "code": Number(-403),
>     "message": String("账号异常,操作失败"),
>     "ttl": Number(1),
> }
> ```
> 
> 使用浏览器里copy的没有问题。
> 
> 只需要SESSDATA的其他API也没问题，csrf也没问题，就是buvid不太对。

虽然我不知道你那边有啥问题，但是我直接在 cmd 里面是可以 POST 上去的...

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/78744121/cb01e0b4-92fe-43bb-b6d4-7a38a8f83009)

**Comment by kingwingfly** [comment]
@z0z0r4 
确实。
我测试用的 BVID是 `BV1GQ4y177Dv`。
```
{
    "code": Number(-403),
    "message": String("账号异常,操作失败"),
    "ttl": Number(1),
}
```

换了 `BV1aT4y1h71M` 就可以了。
```
{
    "code": Number(65006),
    "message": String("已赞过"),
    "ttl": Number(1),
}
```

居然是Up主的账号异常。。。。。。。。太逆天了……
