### ISSUE TITLE
用户-关系-查询粉丝列表 接口更换?

### ISSUE THREAD

**Issue by Werewolf-Wu** [SocialSisterYi/bilibili-API-collect#798]
现在查询的接口似乎是https://api.bilibili.com/x/relation/followings
此外有了验证码，是我前面有次爬取过度导致的吗....

**Comment by Werewolf-Wu** [comment]
并发请求的时候会返回-352错误

**Comment by TyraelDLee** [comment]
给你推荐一个邪性API https://api.vc.bilibili.com/dynamic_mix/v1/dynamic_mix/at_list
这玩意似乎可以一次性返回你的整个列表，目前试过800多的列表可以一次性获取，具体上限不太清楚。

**Comment by wuziqian211** [comment]
fixed in #981
