### ISSUE TITLE
【网页版文档相关】vuepress 深色模式支持

### ISSUE THREAD

**Issue by 188102836** [SocialSisterYi/bilibili-API-collect#803]

**Comment by catlair** [comment]
vvuepress1 有官方的 dark 支持吗，好像没有

**Comment by 188102836** [comment]
> vvuepress1 有官方的 dark 支持吗，好像没有

可以自己写组件吧，vuepress 支持自定义组件

**Comment by 188102836** [comment]
v1 应该不会集成 ( https://github.com/vuejs/vuepress/issues/114#issuecomment-382216613 )，需要自己写，
可以参考 https://github.com/vuejs/vuepress/issues/1865

但 [v2](https://vuejs.press/zh/) 已经集成了，不过目前 v2 处于 beta 阶段

要从 v1 迁移的话，可以看[官方文档](https://vuejs.press/zh/guide/migration.html)

**Comment by catlair** [comment]
并不建议迁移至v2，v2属于脑热产物，现已烂尾

**Comment by catlair** [comment]
> 要从 v1 迁移的话，可以看[官方文档](https://vuejs.press/zh/guide/migration.html)

这是VuePress Theme Hope主题的文档，而非官方文档

**Comment by 188102836** [comment]
> 这是VuePress Theme Hope主题的文档，而非官方文档，不过这个主题有 dark

是的，粘贴错了，官方文档在这
https://v2.vuepress.vuejs.org/zh/guide/migration.html

**Comment by catlair** [comment]
迁移的问题不在框架本身，主要两点

1. 易姐是否同意
2. 目前文档存在大量错误引用，包括锚点，链接和图片，在v1这些会被忽略，但是v2不会，这才是最难迁移的

**Comment by xiaoyv404** [comment]
@SocialSisterYi 

> 迁移的问题不在框架本身，主要两点
> 
>     1. 易姐是否同意
> 
>     2. 目前文档存在大量错误引用，包括锚点，链接和图片，在v1这些会被忽略，但是v2不会，这才是最难迁移的

**Comment by catlair** [comment]
这里有个预览 https://catlair.github.io/bilibili-API-collect/

已完成：
- [x] 修复死链和错误链接
- [x] 修复错误的 `</br>` 标签
- [x] 修复多余或缺少的 `details` 标签
- [x] 迁移 Copyright footer
- [x] 删除不必要的 to top 插件

未完成：
- [ ] nav 行为一致
- [ ] 首页徽章样式一致
- [ ] 修正 link icon 链接

**Comment by SocialSisterYi** [comment]
> 迁移的问题不在框架本身，主要两点
> 
> 1. 易姐是否同意
> 2. 目前文档存在大量错误引用，包括锚点，链接和图片，在v1这些会被忽略，但是v2不会，这才是最难迁移的

目前不怎么希望迁移至 v2，主要还是考虑迁移工作量

但后面如使用 #604 中提到的 MarkLanguage 开新 branch（或重构），可以在它生成 md 后，尝试使用 v2 构建

**Comment by catlair** [comment]
> 目前不怎么希望迁移至 v2，主要还是考虑迁移工作量

在 #806 已经完成文档中错误内容的修复。

只需要迁移配置文件和自定义的 footer 即可 #807。

使用 v2 在 build 速度上有巨大提升

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/44313800/1e09f3fd-eae5-412a-b6f3-ff7c03b09577)

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/44313800/ef00d4c3-2247-46dc-9269-04dc488aa206)

**Comment by xiaoyv404** [comment]
Close by #807
