### ISSUE TITLE
直播间心跳包回复中人气值始终为1

### ISSUE THREAD

**Issue by GD-Slime** [SocialSisterYi/bilibili-API-collect#809]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/92b30f354ab21b97fe52357161fd04e2ca687c97/docs/live/message_stream.md?plain=1#L209
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/82302542/d9dab1f0-b960-4f44-bde7-1014b8596944)
按照文档中写的，我监测了几分钟网页端的心跳包回复。 但是即使是热门直播，返回的值中人气值也好像始终为1.
这个人气值是否被b站弃用了，还是我的姿势不太对？

**Comment by why0209** [comment]
已弃用

**Comment by GD-Slime** [comment]
> 已弃用

好的，那么现在人气值相关是用什么获取呢？

**Comment by why0209** [comment]
有个检测直播状态的API 暂时只能用那个获取了。

**Comment by GD-Slime** [comment]
> > > 已弃用
> > 
> > 好的，那么能否问一下现在人气值相关是用什么获取呢？
> 
> 这个online_count
> 
> {"cmd":"ONLINE_RANK_COUNT","data":{"count":1112,"online_count":1395}}

所以说这里的count是高能用户数量，online_count是在线用户数量吗？
