### ISSUE TITLE
可以添加视频相关的Protobuf

### ISSUE THREAD

**Issue by yujincheng08** [SocialSisterYi/bilibili-API-collect#81]
我这里扒了一点安卓端的protobuf（不全）。
IOS好像已经全都是protobuf+grpc了。

https://github.com/yujincheng08/BiliRoaming/blob/master/app/src/main/proto/me/iacn/biliroaming/Request.proto

**Comment by SocialSisterYi** [comment]
谢谢啦，有时间测试一下，整个进文档

**Comment by SocialSisterYi** [comment]
已添加
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/grpc_api/bilibili/app/view/v1.proto

**Comment by yujincheng08** [comment]
👍
