### ISSUE TITLE
获取IP地址以及运营商的多个接口，哪个更好？

### ISSUE THREAD

**Issue by MarkLily** [SocialSisterYi/bilibili-API-collect#812]
https://api.live.bilibili.com/client/v1/Ip/getInfoNew
https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr
https://api.bilibili.com/x/web-interface/zone
一共三个，第一个速度快点，0.09s，其余两个0.1s多一点。
这三个有啥区别？哪个更稳？

**Comment by Sualiu** [comment]
现在知道了，选择第一个或第二个。

**Comment by Sualiu** [comment]
第三个不能浏览器直接访问返回数据。


第一，第二个可以，而且我测试是支持IPv6的哇。

**Comment by SocialSisterYi** [comment]
实测三个API速度和功能没什么区别，并且似乎不能获取V6的地址，现在DNS都查不到B站下域名的V6地址了

**Comment by Sualiu** [comment]
不是支持IPv6 IP判断嘛？难道不是这个意思……

**Comment by SocialSisterYi** [comment]
> 不是支持IPv6地址判断嘛？难道不是这个意思……

前一阵V6似乎就用不成了，可能是我这里运营商造成的

**Comment by cxw620** [comment]
> > 不是支持IPv6地址判断嘛？难道不是这个意思……
> 
> 前一阵V6似乎就用不成了，可能是我这里运营商造成的

部分地区确实没了, 不过大部分地方没影响吧() -> https://www.boce.com/dns/a.w.bilicdn1.com

**Comment by guanzhujiaran** [comment]
> > 不是支持IPv6地址判断嘛？难道不是这个意思……
> 
> 前一阵V6似乎就用不成了，可能是我这里运营商造成的

我倒是一直在用ipv6访问b站，但是发送短信验证码时一直都是报错{"code":86103,"message":"请下载最新版本哔哩哔哩App完成注册或继续登录","ttl":1,"data":null}
