### ISSUE TITLE
视频url无法下载以及下载之后只有几个kb无法播放

### ISSUE THREAD

**Issue by zpc-dragon** [SocialSisterYi/bilibili-API-collect#822]
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/102280098/b5eb1aba-dd82-4b3c-ac4c-f13bfa5fb91e)
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/102280098/7b029464-a183-4a0e-9f26-02d799b14e80)
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/102280098/b6d428a9-1902-4a1b-a6d4-c49fa20908b9)

**Comment by aaa1115910** [comment]
缺少 referer

**Comment by zpc-dragon** [comment]
跟着视频做的，不是这个问题
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/102280098/d10702f3-8e07-4024-88e4-027eefcbdff0)
这是昨晚我的一些记录

**Comment by aaa1115910** [comment]
> 跟着视频做的，不是这个问题 ![image](https://user-images.githubusercontent.com/102280098/269477391-d10702f3-8e07-4024-88e4-027eefcbdff0.png) 这是昨晚我的一些记录

```
wget "https://xxxx" --referer="https://www.bilibili.com"
```

mcdn 不会检验 referer，非 mcdn 会检验 referer

**Comment by zpc-dragon** [comment]
> > 跟着视频做的，不是这个问题 ![image](https://user-images.githubusercontent.com/102280098/269477391-d10702f3-8e07-4024-88e4-027eefcbdff0.png) 这是昨晚我的一些记录
> 
> ```
> wget "https://xxxx" --referer="https://www.bilibili.com"
> ```
> 
> mcdn 不会检验 referer，非 mcdn 会检验 referer

格式是没有问题，上面只是我打的草稿

**Comment by zpc-dragon** [comment]
> > > 跟着视频做的，不是这个问题 ![image](https://user-images.githubusercontent.com/102280098/269477391-d10702f3-8e07-4024-88e4-027eefcbdff0.png) 这是昨晚我的一些记录
> > 
> > 
> > ```
> > wget "https://xxxx" --referer="https://www.bilibili.com"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > mcdn 不会检验 referer，非 mcdn 会检验 referer
> 
> 格式是没有问题，上面只是我打的草稿

还有一个问题时，明明我是大会员，然后qn选择的1080以上的清晰度，但是json中
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/102280098/97c552f4-fae3-4be6-8e56-7d8c8846e41f)
默认是下载不了的

**Comment by aaa1115910** [comment]
> > > > 跟着视频做的，不是这个问题 ![image](https://user-images.githubusercontent.com/102280098/269477391-d10702f3-8e07-4024-88e4-027eefcbdff0.png) 这是昨晚我的一些记录
> > > 
> > > 
> > > ```
> > > wget "https://xxxx" --referer="https://www.bilibili.com"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > mcdn 不会检验 referer，非 mcdn 会检验 referer
> > 
> > 
> > 格式是没有问题，上面只是我打的草稿
> 
> 还有一个问题时，明明我是大会员，然后qn选择的1080以上的清晰度，但是json中 ![image](https://user-images.githubusercontent.com/102280098/269478211-97c552f4-fae3-4be6-8e56-7d8c8846e41f.png) 默认是下载不了的

抱歉，看眼花了，直接截图看起来不是很直观。我觉得你应该把你请求的参数贴出来看看（

**Comment by zpc-dragon** [comment]
__

> > > > > 跟着视频做的，不是这个问题 ![image](https://user-images.githubusercontent.com/102280098/269477391-d10702f3-8e07-4024-88e4-027eefcbdff0.png) 这是昨晚我的一些记录
> > > > 
> > > > 
> > > > ```
> > > > wget "https://xxxx" --referer="https://www.bilibili.com"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > mcdn 不会检验 referer，非 mcdn 会检验 referer
> > > 
> > > 
> > > 格式是没有问题，上面只是我打的草稿
> > 
> > 
> > 还有一个问题时，明明我是大会员，然后qn选择的1080以上的清晰度，但是json中 ![image](https://user-images.githubusercontent.com/102280098/269478211-97c552f4-fae3-4be6-8e56-7d8c8846e41f.png) 默认是下载不了的
> 
> 抱歉，看眼花了，直接截图看起来不是很直观。我觉得你应该把你请求的参数贴出来看看（

curl -G https://api.bilibili.com/x/player/playurl --data-urlencode bvid=BV1Tu4y1R7Fo --data-urlencode cid=1234977915 --data-urlencode qn=112 -b SESSDATA=4c4bf1d7%2C1710766720%2C46e45*91

**Comment by aaa1115910** [comment]
@zpc-dragon 你忘记隐藏你的 SESSDATA 了。。。。
你请求参数没带 `fnval`
```
curl -G https://api.bilibili.com/x/player/playurl \
    --data-urlencode bvid=BV1Tu4y1R7Fo \
    --data-urlencode cid=1234977915 \
    --data-urlencode qn=112 \
    --data-urlencode fnval=4048 \
    -b SESSDATA=****
```

**Comment by zpc-dragon** [comment]
> @zpc-dragon 你忘记隐藏你的 SESSDATA 了。。。。 你请求参数没带 `fnval`
> 
> ```
> curl -G https://api.bilibili.com/x/player/playurl \
>     --data-urlencode bvid=BV1Tu4y1R7Fo \
>     --data-urlencode cid=1234977915 \
>     --data-urlencode qn=112 \
>     --data-urlencode fnval=4048 \
>     -b SESSDATA=****
> ```
我试试看，谢谢

**Comment by zpc-dragon** [comment]
已经找到问题原因所在，之前在Ubuntu系统使用gcc直接使用-o输出到目标文件，在使用wget下载的过程中想当然以为也可以
在网上查找资料发现wget大小写敏感！！！
-O test.zip 下载并以不同的文件名保存
-o 将log日志指定保存到文件（新建一个文件）
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/102280098/9843ae11-dfbe-43d0-bd8f-06b36c8d45b3)
现在已经解决了，感谢@aaa1115910支持
