### ISSUE TITLE
查询用户投稿视频明细 api 失效

### ISSUE THREAD

**Issue by liarchgh** [SocialSisterYi/bilibili-API-collect#823]
查询用户投稿视频明细 完全失效，一直返回`{"code":-799,"message":"请求过于频繁，请稍后再试"}`
尝试浏览器中直接访问`https://api.bilibili.com/x/space/arc/search`也一样

直接观察个人空间的网络请求后尝试使用以下api查询可以替换上边api进行使用：
```
https://api.bilibili.com/x/space/wbi/arc/search
```

**Comment by liarchgh** [comment]
看到又其他issue中也在使用此api了 #796

**Comment by HashLiver** [comment]
#631

**Comment by liarchgh** [comment]
> #631

我用了[Wbi签名](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md#wbi%E7%AD%BE%E5%90%8D)，但是原API（`https://api.bilibili.com/x/space/arc/search`）还是一样的`-799`返回结果

**Comment by catlair** [comment]
> > #631
> 
> 我用了[Wbi签名](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md#wbi%E7%AD%BE%E5%90%8D)，但是原API（`https://api.bilibili.com/x/space/arc/search`）还是一样的`-799`返回结果

你都知道 wbi 签名了，为啥还把他给老接口用。
