### ISSUE TITLE
查询每日奖励状态API偶尔会返回投币经验为0的数据

### ISSUE THREAD

**Issue by JunzhouLiu** [SocialSisterYi/bilibili-API-collect#83]
问题API地址：http://api.bilibili.com/x/member/web/exp/reward
我在开发[![BILIBILI-HELPER](https://github-readme-stats.vercel.app/api/pin/?username=JunzhouLiu&repo=BILIBILI-HELPER)](https://github.com/JunzhouLiu/BILIBILI-HELPER)的过程中遇到了这个问题，应该不是请求速率过快导致的（rate<5次/s），当天投币投5枚后，经验信息有时候会返回0。通过网页版登录个人中心查看也是0。建议文档中增加相关提示。

这里我找到了另外一个获得每日投币经验的API :https://www.bilibili.com/plus/account/exp.php 这个api的数据出奇的准确和及时。

```json
返回示例
{"code":0,"message":"0","number":50}
```

另外 提供一个直接查询硬币余额的api ：https://account.bilibili.com/site/getCoin

```json
返回示例
{"code":0,"status":true,"data":{"money":536.9}}
```

**Comment by SocialSisterYi** [comment]
收到，下次更新文档时添加相关内容

**Comment by JunzhouLiu** [comment]
> 收到，下次更新文档时添加相关内容

补充`https://account.bilibili.com/site/getCoin`的另一个返回示例，硬币为0时 

```
{"code":0,"status":true,"data":{"money":null}}
```

**Comment by SocialSisterYi** [comment]
已经修改完毕了，谢谢dalao发现错误以及提醒https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/login/member_center.md#%E6%9F%A5%E8%AF%A2%E6%AF%8F%E6%97%A5%E5%A5%96%E5%8A%B1%E7%8A%B6%E6%80%81
