### ISSUE TITLE
请问如何在获取直播间弹幕时附上cookie

### ISSUE THREAD

**Issue by 6486449j** [SocialSisterYi/bilibili-API-collect#830]
如题
正在用java写一个弹幕浮窗，请问是在哪个时候附上cookie，我尝试在获取key的时候附上，好像没什么效果，依旧是匿名登录
buvid应该用在哪个地方

**Comment by TyraelDLee** [comment]
带上cookie请求这个https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo，传回来的数据里有个token，把那个token放在第一个包里发过去。
