### ISSUE TITLE
wbi即时弹幕API中的必要参数"web_location"的来源是什么？

### ISSUE THREAD

**Issue by lb-chc** [SocialSisterYi/bilibili-API-collect#831]
本项目已有API：https://api.bilibili.com/x/v2/dm/wbi/web/seg.so

该在web端获得的请求示例如下：
https://api.bilibili.com/x/v2/dm/wbi/web/seg.so?type=1&oid=146044693&pid=85440373&segment_index=1&pull_mode=1&ps=0&pe=120000&web_location=1315873&w_rid=xxx&wts=xxx

其中，"web_location=1315873"是必要参数，如果省略，将导致和省略wbi一样的"{"code":-403,"message":"访问权限不足","ttl":1}"回复

该参数在不同IP、不同chrome隐私窗口、不同视频下的值一样，想知道它的出处

**Comment by catlair** [comment]
这玩意儿源码里面写死的

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/44313800/73701a1f-9b53-408c-bc75-f84564a76ecf)

**Comment by lb-chc** [comment]
> 这玩意儿源码里面写死的
> 
> ![image](https://user-images.githubusercontent.com/44313800/272149475-73701a1f-9b53-408c-bc75-f84564a76ecf.png)

谢谢

我还发现这不是API的必要参数，我忘了Wbi是对参数的整体签名了，应该改了参数以后签名没改，签名对不上才会出现"访问权限不足"的

pull_mode、ps、pe、web_location这几个参数只出现在弹幕请求的第一包链接中，从第二包开始它们就不再出现，出现就会获得"不存在页面"HTML返回值
