### ISSUE TITLE
终端信息查询接口失效

### ISSUE THREAD

**Issue by SessionHu** [SocialSisterYi/bilibili-API-collect#835]
- [终端信息查询](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/clientinfo/client_info.md#%E7%BB%88%E7%AB%AF%E4%BF%A1%E6%81%AF%E6%9F%A5%E8%AF%A2-1)页面中的接口测试发现无法使用. 会返回Bilibili的普通404页.

- 经过测试IP/Cookie/UA不影响结果. 以下是不同访问方式的截图.
  - curl
    ![curl](https://github.com/SocialSisterYi/bilibili-API-collect/assets/102411014/0e7d508d-928d-45ec-972e-1945a6f84803)
  - Edge
    ![edge](https://github.com/SocialSisterYi/bilibili-API-collect/assets/102411014/f898ac46-b9ae-4fe9-b5fc-fc38786253fc)

- 希望能在失效的页面进行标识, 防止再次遇到类似问题

- ~~虽然可以使用[这个](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/clientinfo/ip.md#%E9%80%9A%E8%BF%87ip%E7%A1%AE%E5%AE%9A%E4%BD%8D%E7%BD%AE)接口进行部分代替, 但有一些功能使用不方便.~~

**Comment by xiaoyv404** [comment]
pr welcome（

**Comment by SessionHu** [comment]
resolved at #853
