### ISSUE TITLE
评论区只能获取到第1页的评论，第2页获取不到

### ISSUE THREAD

**Issue by nzhangzhuo** [SocialSisterYi/bilibili-API-collect#837]
{'code': 0, 'message': '0', 'ttl': 1, 'data': {'cursor': {'is_begin': False, 'prev': 0, 'next': 0, 'is_end': False, 'mode': 0, 'mode_text': '', 'name': '', 'pagination_reply': None, 'session_id': ''}, 'replies': None, 'top': {'admin': None, 'upper': None, 'vote': None}, 'top_replies': None, 'up_selection': {'pending_count': 0, 'ignore_count': 0}, 'effects': {'preloading': ''}, 'assist': 0, 'blacklist': 0, 'vote': 0, 'config': {'showtopic': 0, 'show_up_flag': False, 'read_only': False}, 'upper': {'mid': 0}, 'control': {'input_disable': False, 'root_input_text': '', 'child_input_text': '', 'giveup_input_text': '', 'screenshot_icon_state': 0, 'upload_picture_icon_state': 0, 'answer_guide_text': '', 'answer_guide_icon_url': '', 'answer_guide_ios_url': '', 'answer_guide_android_url': '', 'bg_text': '', 'empty_page': None, 'show_type': 0, 'show_text': '', 'web_selection': False, 'disable_jump_emote': False, 'enable_charged': False, 'enable_cm_biz_helper': False}, 'note': 0, 'callbacks': None, 'esports_grade_card': None}}

第2页往后获取replies都是None

**Comment by snowman** [comment]
请问如何解决?

**Comment by z0z0r4** [comment]
登录

**Comment by snowman** [comment]
好像 是 `buvid3` 过期了, 重新从浏览器复制了一下 `cookies` 可用
