### ISSUE TITLE
bvID 编码位置顺序

### ISSUE THREAD

**Issue by SeaHOH** [SocialSisterYi/bilibili-API-collect#84]
请问 `11, 10, 3, 8, 4, 6, 2, 9, 5, 7` 和 `11, 10, 3, 8, 4, 6, 7, 9, 5, 2` 怎么确定是前者的，难道已经有 29460791296 以上的 avID 出现？

**Comment by duzhaokun123** [comment]
似乎 29460791296 以上都不是合法的 aid

**Comment by SeaHOH** [comment]
你单个试肯定没法，数量太庞大。
我问的是怎么确定。如果已经有大于这个数的 ID 出现，可以用算法验证，反之，是否是哪里相关代码泄漏？

**Comment by duzhaokun123** [comment]
> 你单个试肯定没法，数量太庞大。
> 我问的是怎么确定。如果已经有大于这个数的 ID 出现，可以用算法验证，反之，是否是哪里相关代码泄漏？

原来是我测试时用 java , 数是用 long 存的导致的判断错误, 用 python 算回去的时候是相同的

**Comment by SocialSisterYi** [comment]
> 请问 `11, 10, 3, 8, 4, 6, 2, 9, 5, 7` 和 `11, 10, 3, 8, 4, 6, 7, 9, 5, 2` 怎么确定是前者的，难道已经有 29460791296 以上的 avID 出现？

这个顺序编码表是在看了很多大佬的帖子以及各种代码后得出的，结果神一般一致，但没办法与B站后台做一致性验证，为了保证文档的严谨性还是先这么写吧

**Comment by duzhaokun123** [comment]
@SocialSisterYi 那就不该叫[援引](https://baike.baidu.com/item/%E6%8F%B4%E5%BC%95/2454012)了

另外 python 的单行注释是`#`不是`//`

**Comment by SeaHOH** [comment]
> 原来我用的和这里提供的不是一个算法, 我用的 https://www.zhihu.com/question/381784377/answer/1099438784

是同一个，只不过原版限定 29460791296 以下，后面没法确定。

@SocialSisterYi 建议先用原版，确定后再改代码。

**Comment by SocialSisterYi** [comment]
算法及C、Python示例程序已修改，并添加相关备注
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/other/bvID.md
