### ISSUE TITLE
b站好像自带ai总结了

### ISSUE THREAD

**Issue by guohuiyuan** [SocialSisterYi/bilibili-API-collect#841]
https://api.bilibili.com/x/web-interface/view/conclusion/get?bvid=BV1ju4y1s7kn&cid=1296086601&up_mid=4641697&web_location=333.788&w_rid=1607c6c5a4a35a1297e31992220900ae&wts=1697033079

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/54976075/cf6a5e17-dc0c-4186-a447-5898938aaf03)

**Comment by z0z0r4** [comment]
在哪里触发的？

**Comment by z0z0r4** [comment]
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/78744121/c36f413d-9498-4052-a522-caefdb436670)

我这边没看到

**Comment by guohuiyuan** [comment]
> bvid=BV1ju4y1s7kn

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/54976075/a0a9d411-4b33-4f28-bf4d-4a56bb2cde68)
在右下角

**Comment by z0z0r4** [comment]
能看看 url 里面有没有特殊参数来触发吗？还是根据用户的？

**Comment by guozhigq** [comment]
在无痕模式未登录也出现入口了，然后我另外调了一下接口，可以调通
```
String | bvid
int | cid
int | up_mid
String | w_rid
int | wts
```
其中w_rid、wts是通过bvid、cid、up_mid等等计算出来的

**Comment by z0z0r4** [comment]
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/78744121/887b88b6-89dd-4603-b427-384d81a277dc)

为什么就我这没，有参？

**Comment by MarcusYYDS** [comment]
这玩意还在内测(,希望大佬早日加上,加上了踢我,感谢

**Comment by z0z0r4** [comment]
挺重要的，我写个 md 待会 pr

**Comment by MarcusYYDS** [comment]
> 挺重要的，我写个 md 待会 pr

佬在写吗,没写让我贡献下😍

**Comment by z0z0r4** [comment]
> > 挺重要的，我写个 md 待会 pr
> 
> 佬在写吗,没写让我贡献下😍

我刚好澡，随你，我在写音视频上传部分

**Comment by guohuiyuan** [comment]
#865 增加了
