### ISSUE TITLE
有没有api可以获得用户space中所有的视频

### ISSUE THREAD

**Issue by victorxys** [SocialSisterYi/bilibili-API-collect#845]
目前看到的api都是获取特定列表、合集的视频，请问有没有api可以按uuid或其他用户id来获取space中的所有视频？
谢谢！

**Comment by SocialSisterYi** [comment]
请查阅文档中这部分内容

https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/user/space.md#%E6%9F%A5%E8%AF%A2%E7%94%A8%E6%88%B7%E6%8A%95%E7%A8%BF%E8%A7%86%E9%A2%91%E6%98%8E%E7%BB%86

**Comment by victorxys** [comment]
这里只是“用户投稿“视频吧？而不是Up主发布的全部视频？

**Comment by SocialSisterYi** [comment]
“用户投稿”就是“UP主全部视频”

> 这里只是“用户投稿“视频吧？而不是Up主发布的全部视频？

**Comment by victorxys** [comment]
哦哦，好的明白了，非常感谢，我再研究一下，谢谢！

**Comment by victorxys** [comment]
还要在麻烦您一下，我使用python的demo生成相应的参数
{'bar': '514', 'baz': '1919810', 'foo': '114', 'wts': '1698221857', 'w_rid': 'cc01e80017df7754ac9297c01f0b63f0'}
bar=514&baz=1919810&foo=114&wts=1698221857&w_rid=cc01e80017df7754ac9297c01f0b63f0
并使用postman get 以下链接
https://api.bilibili.com/x/space/wbi/arc/search?mid=53456&bar=514&baz=1919810&foo=114&wts=1698221857&w_rid=cc01e80017df7754ac9297c01f0b63f0

但返回结果是
```
{
    "code": -401,
    "message": "非法访问",
    "ttl": 1,
    "data": {
        "ga_data": {
            "decisions": [
                "verify_captcha_level2"
            ],
            "risk_level": 1,
            "grisk_id": "6eeaaa0cedc8764b52591f94e26538cf",
            "decision_ctx": {
                "buvid": "",
                "decision_type": "4",
                "ip": "104.199.132.30",
                "mid": "0",
                "origin_scene": "anti_crawler",
                "scene": "crawler_main_space_wbi_acc_search",
                "ua": "PostmanRuntime/7.34.0",
                "v_voucher": "voucher_39482fd4-073f-431c-9c9f-ed37ae85b69d"
            }
        }
    }
}
``` 
请问是我的使用方法有问题吗？

**Comment by SocialSisterYi** [comment]
清不要使用 Postman 自带的 UA，或者在 HTTP 头部的`User-Agent`中将它用正常的浏览器或客户的UA替换

**Comment by victorxys** [comment]
好的，我加上UA试一下，谢谢

**Comment by SocialSisterYi** [comment]
发送相应请求表单的参数，再使用签名算法对其签名，而不是发送我签名算法中的demo数据

**Comment by victorxys** [comment]
哦哦，我漏掉了个参数，针对“投稿视频明细”这个接口，我加上了mid
```
# 为给定的参数生成签名
signed_params = encWbi(
    params={
        'mid': '53456'
    },
    img_key=img_key,
    sub_key=sub_key
)
``` 
现在不显示400错误了，而是401
```
{
	'code': -401,
	'message': '非法访问',
	'ttl': 1,
	'data': {
		'ga_data': {
			'decisions': ['verify_captcha_level2'],
			'risk_level': 1,
			'grisk_id': '55a7f48b042fd4c4394bdc5ee36538d8',
			'decision_ctx': {
				'buvid': '',
				'decision_type': '4',
				'ip': '35.221.182.49',
				'mid': '0',
				'origin_scene': 'anti_crawler',
				'scene': 'crawler_main_space_wbi_acc_search',
				'ua': 'python-requests/2.28.2',
				'v_voucher': 'voucher_09989cf3-8955-487a-97c0-bb3cad0f9914'
			}
		}
	}
}
```

**Comment by SocialSisterYi** [comment]
修改请求中的`user-agent`并在请求的 cookie 中加入合适的`buvid3`字段

**Comment by victorxys** [comment]
问题解决！我写了header但是忘记在request中加这个参数了，十分感谢！十分感谢！
