### ISSUE TITLE
发现部分账号调用登录会返回错误码86853

### ISSUE THREAD

**Issue by ywmoyue** [SocialSisterYi/bilibili-API-collect#848]
调用TV版二维码登录接口，使用IPadOS的appKey
以及调用App的短信登录接口，使用Android的appKey都会出现

返回数据：
```
{"code":86853,"message":"版本过低，请升级到最新版本","ttl":1}"
```

**Comment by ywmoyue** [comment]
直接扫码Ipad端客户端是可以正常登录的，可能登录流程和现在文档记录的有差异，我这边再抓包看看

**Comment by cxw620** [comment]
这不是字面意思说版本过低吗, 除非 ios 的那个 appkey 彻底失效了

**Comment by ywmoyue** [comment]
> 这不是字面意思说版本过低吗, 除非 ios 的那个 appkey 彻底失效了

我这边3个账号只有1个账号登录会返回这个错误码，另外两个正常

**Comment by cxw620** [comment]
> > 这不是字面意思说版本过低吗, 除非 ios 的那个 appkey 彻底失效了
> 
> 我这边3个账号只有1个账号登录会返回这个错误码，另外两个正常

给出代码样例看看

**Comment by ywmoyue** [comment]
抱歉，我重新写了demo后发现是我的代码有问题，传参mobiapp传了android，我关闭这个issue吧
非常感谢您的建议
