### ISSUE TITLE
移动端&web端的cookies不通用？

### ISSUE THREAD

**Issue by SpaceXC** [SocialSisterYi/bilibili-API-collect#850]
之前 #393 的方法不是挂了嘛
现在改用TV端的二维码登录
但是获取到access key以及cookies之后
所有web端通过cookies认证的api都返回-101:账号未登录
查看之后发现这样登录获取的SESSDATA比web端的短很多

因为我的app里面是web端的app端的api混用
想问下现在有没有什么方法可以一次登录之后
同时获得access key以及适用于web端的cookies？

**Comment by aaa1115910** [comment]
短信登录 平板扫码登录

**Comment by SpaceXC** [comment]
我就是用的平板扫码登录
实际上api和tv端是一个

**Comment by aaa1115910** [comment]
> 我就是用的平板扫码登录 实际上api和tv端是一个

访问的服务器域名不同，且appkey不同，因此返回的cookies是不是等效的我不知道，但我用平板扫码登录获取的cookies用起来没出问题

**Comment by SpaceXC** [comment]
可以说一下用的哪个api及appkey嘛
<img width="733" alt="image" src="https://github.com/SocialSisterYi/bilibili-API-collect/assets/60663465/d1236dbc-6e3f-4c3b-9ce7-e0baad700798">
<img width="594" alt="image" src="https://github.com/SocialSisterYi/bilibili-API-collect/assets/60663465/c6284f30-6f7f-4814-b062-c0e4fb315add">
上面是我的

**Comment by aaa1115910** [comment]
> 可以说一下用的哪个api及appkey嘛 <img alt="image" width="733" src="https://user-images.githubusercontent.com/60663465/280459798-d1236dbc-6e3f-4c3b-9ce7-e0baad700798.png"> <img alt="image" width="594" src="https://user-images.githubusercontent.com/60663465/280459808-c6284f30-6f7f-4814-b062-c0e4fb315add.png"> 上面是我的

我也用的相同接口，appkey 也相同，刚刚试了扫码登录后也正常能用
https://github.com/aaa1115910/bv/blob/4960d7ac21fab61363ddea7d2f66576188786958/bili-api/src/main/kotlin/dev/aaa1115910/biliapi/http/BiliPassportHttpApi.kt#L82-L95

**Comment by SpaceXC** [comment]
那就奇怪了
localId一样吗

**Comment by SpaceXC** [comment]
还是动态生成的

**Comment by cxw620** [comment]
我的评价是建议自己抓包分析, 反编译客户端拿算法... 下面的仅供参考.

目前已知 HD 版也会用到这个接口 https://github.com/SocialSisterYi/bilibili-API-collect/blob/2d86a3cc7c9598f1e05f13acfd5780f64ace7bd9/docs/login/login_action/QR.md?plain=1#L492-L494

参考请求 param
```
appkey: dfca71928277209b
build: 1442100
channel: master
device: phone
mobi_app: android_hd
platform: android
```

具体请求参数如下
UA: Mozilla/5.0 BiliDroid/1.44.2 (bbcallen@gmail.com)

POST Form 各参数分析
|key|示例|备注|
|:-:|:-:|:-:|
|appkey|dfca71928277209b||
|auth_code|***|来自`/x/passport-tv-login/qrcode/auth_code`|
|bili_local_id|***|参考[设备指纹 fp (fp_local, fp_remote)](https://github.com/SocialSisterYi/bilibili-API-collect/blob/2d86a3cc7c9598f1e05f13acfd5780f64ace7bd9/docs/misc/device_identity.md#%E8%AE%BE%E5%A4%87%E6%8C%87%E7%BA%B9-fp-fp_local-fp_remote)|
|build|1442100|版本号|
|buvid|***|XU-Prefix BUVID, 参考[设备唯一标识 BUVID](https://github.com/SocialSisterYi/bilibili-API-collect/blob/2d86a3cc7c9598f1e05f13acfd5780f64ace7bd9/docs/misc/device_identity.md#%E8%AE%BE%E5%A4%87%E5%94%AF%E4%B8%80%E6%A0%87%E8%AF%86-buvid)|
|c_locale|zh-Hans_CN
|channel|master
|code||留空|
|device|phone
|device_id|***|参考[设备指纹 fp (fp_local, fp_remote)](https://github.com/SocialSisterYi/bilibili-API-collect/blob/2d86a3cc7c9598f1e05f13acfd5780f64ace7bd9/docs/misc/device_identity.md#%E8%AE%BE%E5%A4%87%E6%8C%87%E7%BA%B9-fp-fp_local-fp_remote)|
|device_name|HUAWEIWGR-W09|设备 model|
|device_platform|Android12HUAWEIWGR-W09|?|
|device_tourist_id|***|请求 `/x/passport-user/guest/reg` 获取|
|disable_rcmd|0
|dt|***|签名? 算法未知|
|extend||留空|  
|local_id|***|XU-Prefix BUVID, 参考[设备唯一标识 BUVID](https://github.com/SocialSisterYi/bilibili-API-collect/blob/2d86a3cc7c9598f1e05f13acfd5780f64ace7bd9/docs/misc/device_identity.md#%E8%AE%BE%E5%A4%87%E5%94%AF%E4%B8%80%E6%A0%87%E8%AF%86-buvid)|
|login_session_id|***|算法未知|
|mobi_app|android_hd
|platform|android
|s_locale|zh-Hans_CN
|spm_id|from_spmid
|statistics|{"appId":5,"platform":3,"version":"1.44.2","abtest":""}
|ts|1698601768
|sign|***|APP 端 API 通行的签名算法

**Comment by SpaceXC** [comment]
感谢，试下

**Comment by cxw620** [comment]
dt 应该是个 AES 加密的玩意, 包含设备信息, 看起来是风控用的, 算法就不发了, 个人用应该缺个参数也能用.

**Comment by SpaceXC** [comment]
> device

想问下你获取到的SESSDATA长啥样，多少位

**Comment by SpaceXC** [comment]
补充下，貌似之前用web端的二维码获取到的SESSDATA也在这几天无法使用了
之前获取到的SESSDATA也是短版的
应该和 #742 有关
试了下上面几个大佬的方案，返回的SESSDATA也是短的，猜测只能给app端的接口使用，或者这个接口还没有升级到长版SESSDATA
我的问题描述和 #767 应该是一样的，但是我已经把返回的那些cookies放到请求头中了
postman中使用web端的长版SESSDATA返回正常，修改成TV端返回的cookies就报-101

**Comment by cxw620** [comment]
APP 拿到的是给 webview 用的吧, 不通用很正常. ~~混用 APP 和 Web 的 API 是坏文明~~

**Comment by SpaceXC** [comment]
其实我主要还是用web端的来着
只有一两个是app的
主要是觉得他们返回的东西多一些
实在不行就趁着这个机会重构一下子吧
