### ISSUE TITLE
现在还有什么方法能拿到正常使用的access_token

### ISSUE THREAD

**Issue by DandyChan** [SocialSisterYi/bilibili-API-collect#867]
之前的https://github.com/SocialSisterYi/bilibili-API-collect/issues/393 不能用了，又众所周知直接使用TV端扫码的方法会663鉴权失败，那现在还有什么扫码登陆的方式可以用呢

**Comment by catlair** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/861

**Comment by xiaoyv404** [comment]
Duplicate #861
