### ISSUE TITLE
我的大部分api都返回 -412状态码，大家有没有遇到这个问题？

### ISSUE THREAD

**Issue by TommyLe1** [SocialSisterYi/bilibili-API-collect#872]
比如访问直播视频URL的api "https://api.live.bilibili.com/room/v1/Room/playUrl" 返回的信息是：{'code': -412, 'message': 'request was banned', 'ttl': 1}，应该不是参数设置错误，因为代码是前一阵子忽然用不了的，大部分都是报错-412 有没有大佬遇到同样的情况？指导一下。

**Comment by guanzhujiaran** [comment]
这是爬虫速度太快风控了吧，试试换个ip，或者上代理池

**Comment by Disky** [comment]
23号晚上到现在-412，换IP无效

**Comment by 7rikka** [comment]
我也遇到了

**Comment by whitney333** [comment]
剛剛試了一下request "https://api.bilibili.com/x/web-interface/view?bvid={bvid}", 同樣也是返回{'code': -412, 'message': 'request was banned', 'ttl': 1}, 但是用Jupyter Notebook request卻成功了! 請大佬指教

**Comment by Natrium0521** [comment]
加header

**Comment by cxw620** [comment]
说实在的, 提 issue 求助又不给示例代码, 旁观者迷啊

还是得弄个 issue template

**Comment by TommyLe1** [comment]
> 加header

确实加上header和cookies报错消失了

**Comment by sikishana** [comment]
有大佬试获取评论的接口了吗，我用多个账号测试，有的412有的缺没有，即使加上cookie也是一样的

**Comment by 2-3-5-7** [comment]
@sikishana 我用的 `/x/v2/reply/reply` 这个接口，发现换 IP 也不行，但家宽 IP 没问题，可能是 hosting ip 容易风控？

**Comment by catlair** [comment]
> 有大佬试获取评论的接口了吗，我用多个账号测试，有的412有的缺没有，即使加上cookie也是一样的

获取评论用的是新接口吗？需要wbi

**Comment by sikishana** [comment]
> > 有大佬试获取评论的接口了吗，我用多个账号测试，有的412有的缺没有，即使加上cookie也是一样的
> 
> 获取评论用的是新接口吗？需要wbi
用的https://api.bilibili.com/x/v2/reply，同环境下切换账号cookie调用，有的号返回412，有的正常

**Comment by sikishana** [comment]
[catlair](https://github.com/catlair) 用的[https://api.bilibili.com/x/v2/reply，同环境下切换账号cookie调用，有的号返回412，有的正常](https://api.bilibili.com/x/v2/reply%EF%BC%8C%E5%90%8C%E7%8E%AF%E5%A2%83%E4%B8%8B%E5%88%87%E6%8D%A2%E8%B4%A6%E5%8F%B7cookie%E8%B0%83%E7%94%A8%EF%BC%8C%E6%9C%89%E7%9A%84%E5%8F%B7%E8%BF%94%E5%9B%9E412%EF%BC%8C%E6%9C%89%E7%9A%84%E6%AD%A3%E5%B8%B8)
