### ISSUE TITLE
search api 无返回内容

### ISSUE THREAD

**Issue by Erythritee** [SocialSisterYi/bilibili-API-collect#895]
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/71497207/f659b89d-b2bb-4f06-a48d-661c5781c40c)
为什么我请求的时候，有时候返回正常，有时候只返回一个v_voucher啊
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/71497207/e8d0cd64-27b0-4427-9425-440e1eba15f0)

**Comment by cxw620** [comment]
see PR https://github.com/SocialSisterYi/bilibili-API-collect/pull/892
