### ISSUE TITLE
”获取历史弹幕protobuf接口“的porto定义文件失效

### ISSUE THREAD

**Issue by lb-chc** [SocialSisterYi/bilibili-API-collect#907]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/danmaku/history.md

如上页面中的如下链接失效，这个文件的正确版本还在吗？

https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/grpc_api/bilibili/community/service/dm/v1.proto

**Comment by cxw620** [comment]
移动到 https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/grpc_api/bilibili/community/service/dm/v1/dm.proto 了吧

**Comment by SocialSisterYi** [comment]
该 gRPC 弹幕接口文档并未失效，请及时 pull 跟进项目 HEAD，参阅 https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/grpc_api/bilibili/community/service/dm/v1/dm.proto
