### ISSUE TITLE
api.bilibili.com 查询他人关注接口限制更新

### ISSUE THREAD

**Issue by xxxxxliil** [SocialSisterYi/bilibili-API-collect#909]
1. 实际上限 100 人，文档中说明的上限前五页需要的前提条件是每页 20 人（也就是 `ps=20`）
2. `order=` 不再能控制排列顺序（by: [walle的回答 - 知乎](https://www.zhihu.com/question/64737631/answer/1952548366)）

**Comment by wuziqian211** [comment]
fixed in #981
