### ISSUE TITLE
用户关系查询接口修改，需要wbi签名校验

### ISSUE THREAD

**Issue by zly2006** [SocialSisterYi/bilibili-API-collect#910]
`x/space/wbi/acc/relation`接口已被修改，没有wbi签名会返回-403

**Comment by SocialSisterYi** [comment]
该接口为查询自己与对方关系，并非修改关系，修改关系的接口为`https://api.bilibili.com/x/relation/modify`

**Comment by zly2006** [comment]
不，我遇到了，这个接口也需要wbi签名。您测试一下就知道了

**Comment by SocialSisterYi** [comment]
> 不，我遇到了，这个接口也需要wbi签名。您测试一下就知道了

指的是`https://api.bilibili.com/x/space/wbi/acc/relation`还是`https://api.bilibili.com/x/relation/modify`？

**Comment by zly2006** [comment]
<https://api.bilibili.com/x/space/wbi/acc/relation?mid=1>

**Comment by zly2006** [comment]
根据我的b站回复机器人日志，是今天中午12点左右改的

**Comment by SocialSisterYi** [comment]
> https://api.bilibili.com/x/space/wbi/acc/relation?mid=1

那就应该是`用户关系查询接口`，而不是`双方关系接口修改`原标题可能产生歧义

**Comment by cxw620** [comment]
带 wbi 的都会使用 wbi 签名, 特别是爬虫喜欢的接口, 只是 B 站方面风控改造进度问题.

**Comment by SocialSisterYi** [comment]
在 [用户关系](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/user/relation.md#%E6%9F%A5%E8%AF%A2%E7%94%A8%E6%88%B7%E4%B8%8E%E8%87%AA%E5%B7%B1%E5%85%B3%E7%B3%BB%E4%BA%92%E7%9B%B8%E5%85%B3%E7%B3%BB) 中已对该 API 的鉴权方式以及请求参数说明，测试与描述一致，并无新增与修改特性
