### ISSUE TITLE
带有dm_img_list的接口无法正常进行Wbi签名

### ISSUE THREAD

**Issue by Lightning-Lion** [SocialSisterYi/bilibili-API-collect#912]
B站在近期于`/x/space/wbi/arc/search`接口加入了`dm_img_list`参数，它是一个数组类型的参数，在现有的Wbi签名方法中（我使用的是文档中的Python实现），对于数组类型的数据，它无法正确实施签名。
- 实验过程
以这个请求为例
`https://api.bilibili.com/x/space/wbi/arc/search?mid=285244630&ps=30&tid=0&special_type=&pn=1&keyword=&order=pubdate&platform=web&web_location=1550101&order_avoided=true&dm_img_list=[%7B%22x%22:3085,%22y%22:1568,%22z%22:0,%22timestamp%22:20,%22type%22:0%7D,%7B%22x%22:3093,%22y%22:1574,%22z%22:14,%22timestamp%22:104,%22type%22:0%7D,%7B%22x%22:3206,%22y%22:1681,%22z%22:145,%22timestamp%22:269,%22type%22:0%7D,%7B%22x%22:3240,%22y%22:1687,%22z%22:171,%22timestamp%22:369,%22type%22:0%7D,%7B%22x%22:3171,%22y%22:1628,%22z%22:95,%22timestamp%22:535,%22type%22:0%7D,%7B%22x%22:3108,%22y%22:1568,%22z%22:23,%22timestamp%22:654,%22type%22:0%7D,%7B%22x%22:3505,%22y%22:2105,%22z%22:0,%22timestamp%22:755,%22type%22:0%7D,%7B%22x%22:3937,%22y%22:3597,%22z%22:702,%22timestamp%22:2109,%22type%22:0%7D,%7B%22x%22:3418,%22y%22:2030,%22z%22:728,%22timestamp%22:2210,%22type%22:0%7D,%7B%22x%22:2568,%22y%22:901,%22z%22:255,%22timestamp%22:2312,%22type%22:0%7D,%7B%22x%22:3170,%22y%22:1239,%22z%22:1074,%22timestamp%22:2414,%22type%22:0%7D,%7B%22x%22:1908,%22y%22:-507,%22z%22:45,%22timestamp%22:2520,%22type%22:0%7D,%7B%22x%22:2002,%22y%22:-587,%22z%22:293,%22timestamp%22:2621,%22type%22:0%7D,%7B%22x%22:2717,%22y%22:73,%22z%22:1104,%22timestamp%22:2722,%22type%22:0%7D,%7B%22x%22:2687,%22y%22:56,%22z%22:1150,%22timestamp%22:2823,%22type%22:0%7D,%7B%22x%22:1830,%22y%22:-797,%22z%22:327,%22timestamp%22:2928,%22type%22:0%7D]&dm_img_str=V2ViR0wgMS4wIChPcGVuR0wgRVMgMi4wIENocm9taXVtKQ&dm_cover_img_str=QU5HTEUgKEFwcGxlLCBBTkdMRSBNZXRhbCBSZW5kZXJlcjogQXBwbGUgTTIgUHJvLCBVbnNwZWNpZmllZCBWZXJzaW9uKUdvb2dsZSBJbmMuIChBcHBsZS&w_rid=488d7265331b56a02ea3f78192a37489&wts=1703133633`
当我带着数组签名，发现报错。
<img width="871" alt="image" src="https://github.com/SocialSisterYi/bilibili-API-collect/assets/85005672/29f691f1-51d8-4ada-8da9-38d8c38fe27c">
当我清空数组签名，请求成功。
<img width="863" alt="image" src="https://github.com/SocialSisterYi/bilibili-API-collect/assets/85005672/2a080bb4-770f-416b-b681-2b8aa4fb1790">

我使用的是[文档中的Python实现](https://github.com/SocialSisterYi/bilibili-API-collect/blob/968b3e246f146ef560c05468e200cb5c1f0daaac/docs/misc/sign/wbi.md#python)，有人能复现这种情况吗？

**Comment by cxw620** [comment]
自己确认encode出来的内容是不是一样的，还有imgkey和subkey是不是用的js文件内嵌的

**Comment by Lightning-Lion** [comment]
> 自己确认encode出来的内容是不是一样的，还有imgkey和subkey是不是用的js文件内嵌的

收到，已经修改问题描述。
