### ISSUE TITLE
关于bilibili 网页端 http协议版本变化对接口影响

### ISSUE THREAD

**Issue by cctyl** [SocialSisterYi/bilibili-API-collect#926]
今天发现历史观看数据接口一直提示 {"code":-101,"message":"账号未登录","ttl":1}.。 检查了一下，cookie 和网页端一直，header也调整到与网页端一致，但是依然出现这个问题。

直到我发现，浏览器请求列表中，http版本变成了 HTTP/2.
如下图所示：
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/34262992/0c38df35-383e-4cd8-abe3-43e98dfd267f)

有些甚至是HTTP/3:
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/34262992/39ddec52-52f8-4343-924f-caaea297af7d)

在我发出issue的时候，还没有证明，是不是HTTP版本变化，导致请求失败。另外我也比较震惊，HTTP/3 居然已经开始普及，且浏览器也已经开始支持。。。

我不知道是我记错了，bilibili一直就是HTTP/2 还是说最近才普及，我又打开了知乎，发现知乎也是大部分HTTP/2，又尝试了一些小网站，发现小网站的版本依旧是HTTP/1.1

**Comment by cctyl** [comment]
> 用chrome插件ModHeader - Modify HTTP headers可以修改请求头，改回去试试

我测试了下，这个接口访问不了与HTTP版本没有关系。但是以后会不会有影响不太清楚

**Comment by cxw620** [comment]
虽然但是, HTTP 协议和接口鉴权有关系吗... HTTP2 都用了多少年了

**Comment by cctyl** [comment]
> 虽然但是, HTTP 协议和接口鉴权有关系吗... HTTP2 都用了多少年了

这样吗，我映象中一直停留在HTTP1.1时代，看了我的请求库也是只有1.1😂。 HTTP 协议和接口鉴权 应该是没关系，不符合应该会直接调不通（看到过网上博客提到因为版本号不同导致调不同300系列错误），发完这个issue之后我就排除了鉴权问题

**Comment by cxw620** [comment]
> > 虽然但是, HTTP 协议和接口鉴权有关系吗... HTTP2 都用了多少年了
> 
> 这样吗，我映象中一直停留在HTTP1.1时代，看了我的请求库也是只有1.1😂。 HTTP 协议和接口鉴权 应该是没关系，不符合应该会直接调不通（看到过网上博客提到因为版本号不同导致调不同300系列错误），发完这个issue之后我就排除了鉴权问题

So this issue can be closed now.
