### ISSUE TITLE
Web端Cookie刷新，“确认更新”API所需的CSRF Token的来源有矛盾

### ISSUE THREAD

**Issue by lb-chc** [SocialSisterYi/bilibili-API-collect#929]
对于“刷新Cookie”API（https://passport.bilibili.com/x/passport-login/web/cookie/refresh）

它的输出如下
>刷新成功后会设置以下 Cookie 项：
>sid、DedeUserID、DedeUserID__ckMd5、SESSDATA、bili_jct

这是http 响应（设置cookie所需的信息应该是在这里面？），里面并没有一个新提供出来的“CSRF Token”
```
HTTP/2 200
date: Fri, 19 May 2023 07:34:11 GMT
content-type: application/json; charset=utf-8
content-length: 116
bili-status-code: 0
bili-trace-id: 17f4251365646726
set-cookie: SESSDATA=***; Path=/; Domain=bilibili.com; Expires=Wed, 15 Nov 2023 07:34:10 GMT; HttpOnly; Secure
set-cookie: bili_jct=***; Path=/; Domain=bilibili.com; Expires=Wed, 15 Nov 2023 07:34:10 GMT
set-cookie: DedeUserID=***; Path=/; Domain=bilibili.com; Expires=Wed, 15 Nov 2023 07:34:10 GMT
set-cookie: DedeUserID__ckMd5=***; Path=/; Domain=bilibili.com; Expires=Wed, 15 Nov 2023 07:34:10 GMT
set-cookie: sid=***; Path=/; Domain=bilibili.com; Expires=Wed, 15 Nov 2023 07:34:10 GMT
x-bili-trace-id: 3f6f6174aaa087b517f4251365646726
expires: Fri, 19 May 2023 07:34:10 GMT
cache-control: no-cache
x-cache-webcdn: BYPASS from blzone03

{"code":0,"message":"0","ttl":1,"data":{"status":0,"message":"","refresh_token":"ae1bd1149b56af9743ffe7bbbeff3e51"}}
```

新的cookie是从这里获取的。

---
对于“确认更新”API（https://passport.bilibili.com/x/passport-login/web/confirm/refresh）
它的输入如下
| 参数名        | 类型 | 内容                      | 必要性 | 备注                                                         |
| ------------- | ---- | ------------------------- | ------ | ------------------------------------------------------------ |
| csrf          | str  | CSRF Token（位于 cookie） | 必要   | 从新的 cookie 中获取                                         |
| refresh_token | str  | 旧的持久化刷新口令        | 必要   | 在刷新前 localStorage 中的`ac_time_value`获取，**并非刷新后返回的值** |

---

在说明中，“刷新Cookie”API并未在新的Cookie中设置CSRF Token，这似乎是个逻辑矛盾。

因为这个操作失败会导致重新登陆，对其重复实验的难度较高，所以想得到更确切的说明

**Comment by aaa1115910** [comment]
`bili_jct` 就是 `csrf token`
