### ISSUE TITLE
[补充]关于视频分区情况的更新

### ISSUE THREAD

**Issue by zstd-lzmp** [SocialSisterYi/bilibili-API-collect#931]
舞蹈区新增二级分区手势·网红舞，tid=255，我看文档里没有，提个issue

**Comment by Flamemad** [comment]
拿不准的话，可以看看这个
https://www.bilibili.com/read/cv22152471/

**Comment by niu541412** [comment]
分区信息都在主页代码载入的js文件里的。
[/s1.hdslb.com/bfs/static/laputa-home/client/assets/index.fe6dabee.js](/s1.hdslb.com/bfs/static/laputa-home/client/assets/index.fe6dabee.js)
在si[channellist]这个变量里。
这个序列号fe6dabee会定期更新。si的这个名字也不是固定的。

**Comment by z0z0r4** [comment]
> 最近几天我发现汽车区同样有一个文档中没有出现的二级分区，汽车知识科普，tid=258，即使在文档修正中也没有看到修正，所以我补充一下

直接对照下上面的 json 比较好

**Comment by Flamemad** [comment]
> > 最近几天我发现汽车区同样有一个文档中没有出现的二级分区，汽车知识科普，tid=258，即使在文档修正中也没有看到修正，所以我补充一下
> 
> 直接对照下上面的 json 比较好

我去看了，json里面没有tid=258，但是事实上，这个汽车区的二级分区确实存在
我甚至找了一个视频，https://api.bilibili.com/x/web-interface/view?bvid=BV1kN4y117gd

**Comment by Flamemad** [comment]
> > 最近几天我发现汽车区同样有一个文档中没有出现的二级分区，汽车知识科普，tid=258，即使在文档修正中也没有看到修正，所以我补充一下
> 
> 直接对照下上面的 json 比较好

我去上面的json看了，里面确实没有我提到的二级分区，但是，这个二级分区确实是存在的。
比如BV1kN4y117gd，这个视频就是属于汽车->汽车知识科普
我甚至请求了关于视频信息的接口，https://api.bilibili.com/x/web-interface/view?bvid=BV1kN4y117gd
返回值的tid=258，tname=汽车知识科普，这也说明了这是一个汽车区的二级分区
