### ISSUE TITLE
悄悄关注接口失效

### ISSUE THREAD

**Issue by boxie123** [SocialSisterYi/bilibili-API-collect#937]
[操作用户关系](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/user/relation.md#%E6%93%8D%E4%BD%9C%E7%94%A8%E6%88%B7%E5%85%B3%E7%B3%BB)，现在`act=3`时会返回```{code: -400, message: "请求错误", ttl: 1}```

**Comment by boxie123** [comment]
> 话说这个接口是哪个页面的

之前在关注按钮后面的下拉栏里，一个月前按钮删掉了但是接口还能用，昨天发现接口也寄了

**Comment by z0z0r4** [comment]
> > 话说这个接口是哪个页面的
> 
> 之前在关注按钮后面的下拉栏里，一个月前按钮删掉了但是接口还能用，昨天发现接口也寄了

蜀黍这是不打算提供了？还是仅供移动端

**Comment by cxw620** [comment]
这个功能应该是删了吧?

**Comment by boxie123** [comment]
> 蜀黍这是不打算提供了？还是仅供移动端

应该是不提供了，移动端一直都没有

**Comment by z0z0r4** [comment]
https://api.bilibili.com/x/relation/whispers 还能用

**Comment by boxie123** [comment]
> https://api.bilibili.com/x/relation/whispers 还能用

是的，已经悄悄关注过的不影响，但是不能再加新的了

**Comment by wuziqian211** [comment]
fixed in #981
