### ISSUE TITLE
直播间弹幕认证秘钥怎么获取的

### ISSUE THREAD

**Issue by NanoNM** [SocialSisterYi/bilibili-API-collect#94]
直播间弹幕认证秘钥怎么获取的啊 哭哭

**Comment by ProgramRipper** [comment]
`https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo?id={房间id}`
![image](https://user-images.githubusercontent.com/45716046/99162571-20fd7500-273a-11eb-9baa-bee39324d730.png)
也许你想要这个？

**Comment by NanoNM** [comment]
谢谢已经解决了 谢谢
