### ISSUE TITLE
求一个高级弹幕参数含义

### ISSUE THREAD

**Issue by SpaceXC** [SocialSisterYi/bilibili-API-collect#941]
想自己搓一个弹幕绘制，普通弹幕已经搞定了，想绘制一下高级弹幕，但是看不懂返回的参数（晕
而且貌似返回的参数数量还有差异

例：
`[0.328,0.362,"1-1",3,"有什么兴趣爱好吗？",0,0,0.328,0.362,500,0,0,"SimHei",1]`
`[0,0,"1-1",10,"御坂美琴 我愿与你从行至水穷到坐看云起 从浅浅相遇到深深欢喜",0,0,0,520,2200,0,true,"微软雅黑",1]`
`[0.1,0.01,"1-1",9,"                                      Mf5QE@MZGd3czzTgBK@G1V0vWd                                              ",0,0,0.1,0.85,500,0,true,"黑体",1]`

如果有大佬研究过这方面的东西的话，真心希望能告知一下。如果有现成的文档，也求一个（w

**Comment by cxw620** [comment]
逆向下弹幕相关的js?

**Comment by z0z0r4** [comment]
> 想自己搓一个弹幕绘制，普通弹幕已经搞定了，想绘制一下高级弹幕，但是看不懂返回的参数（晕 而且貌似返回的参数数量还有差异
> 
> 例： `[0.328,0.362,"1-1",3,"有什么兴趣爱好吗？",0,0,0.328,0.362,500,0,0,"SimHei",1]` `[0,0,"1-1",10,"御坂美琴 我愿与你从行至水穷到坐看云起 从浅浅相遇到深深欢喜",0,0,0,520,2200,0,true,"微软雅黑",1]` `[0.1,0.01,"1-1",9," Mf5QE@MZGd3czzTgBK@G1V0vWd ",0,0,0.1,0.85,500,0,true,"黑体",1]`
> 
> 如果有大佬研究过这方面的东西的话，真心希望能告知一下。如果有现成的文档，也求一个（w

这是从哪里拿到的数据？proto、xml？

**Comment by SpaceXC** [comment]
> > 想自己搓一个弹幕绘制，普通弹幕已经搞定了，想绘制一下高级弹幕，但是看不懂返回的参数（晕 而且貌似返回的参数数量还有差异
> > 例： `[0.328,0.362,"1-1",3,"有什么兴趣爱好吗？",0,0,0.328,0.362,500,0,0,"SimHei",1]` `[0,0,"1-1",10,"御坂美琴 我愿与你从行至水穷到坐看云起 从浅浅相遇到深深欢喜",0,0,0,520,2200,0,true,"微软雅黑",1]` `[0.1,0.01,"1-1",9," Mf5QE@MZGd3czzTgBK@G1V0vWd ",0,0,0.1,0.85,500,0,true,"黑体",1]`
> > 如果有大佬研究过这方面的东西的话，真心希望能告知一下。如果有现成的文档，也求一个（w
> 
> 这是从哪里拿到的数据？proto、xml？

proto和xml好像都有的

**Comment by SpaceXC** [comment]
> 逆向下弹幕相关的js?

还是在DanmakuFlameMaster里面找到了，感谢

**Comment by niu541412** [comment]
好像你是在问高级弹幕的字符串的定义问题？
这有我以前写的一个专栏，可以帮助你，https://www.bilibili.com/read/cv15030542/

**Comment by SpaceXC** [comment]
> 好像你是在问高级弹幕的字符串的定义问题？
> 
> 这有我以前写的一个专栏，可以帮助你，https://www.bilibili.com/read/cv15030542/

感谢分享，已经从DannakuFlameMaster里面扒出来了，你也可以看一下源码哦，后面有些参数是不固定返回的
