### ISSUE TITLE
web端密码登录校验规则是改变了吗

### ISSUE THREAD

**Issue by Jiagu1218** [SocialSisterYi/bilibili-API-collect#944]
如题web端密码登录校验规则是改变了吗？
按照文档登录token用的是获取极验证获取到的token,但是调用接口显示-662调用超时，自己用网页调试看官网获取极验证的token和登录接口使用的token并不一致，challenge也不一致
还有是否有客户端密码登录的接口说明

**Comment by Sudsier** [comment]
目前并未检测到有问题，本人正在使用密码登录接口。请确认输入的值是否正确和匹配，别把challenge和token写反之类的。还有就是温馨提示一下，登录时后端一定要记得带上UA，referer，b_nut，buvid3，buvid4，否则就会返回风险提示

**Comment by shouxindehai** [comment]
请问二位解决了吗 或者有样例代码吗 我也遇到如上问题并没有解决

**Comment by lzyvegetable** [comment]
-662调用超时是因为加密参数里面的hash是有时限的，它后端收到解密一查发现hash过期就返回这个。

**Comment by lzyvegetable** [comment]
收到hash之后发请求快一点就不会这样了

**Comment by huazinet** [comment]
> 目前并未检测到有问题，本人正在使用密码登录接口。请确认输入的值是否正确和匹配，别把challenge和token写反之类的。还有就是温馨提示一下，登录时后端一定要记得带上UA，referer，b_nut，buvid3，buvid4，否则就会返回风险提示

请问大佬，极验你是用手动过的验证吗，有自动的吗，感谢

**Comment by Sudsier** [comment]
> > 目前并未检测到有问题，本人正在使用密码登录接口。请确认输入的值是否正确和匹配，别把challenge和token写反之类的。还有就是温馨提示一下，登录时后端一定要记得带上UA，referer，b_nut，buvid3，buvid4，否则就会返回风险提示
> 
> 请问大佬，极验你是用手动过的验证吗，有自动的吗，感谢

按照BAC的逻辑手动登录的，用的php

**Comment by huazinet** [comment]
> > > 目前并未检测到有问题，本人正在使用密码登录接口。请确认输入的值是否正确和匹配，别把challenge和token写反之类的。还有就是温馨提示一下，登录时后端一定要记得带上UA，referer，b_nut，buvid3，buvid4，否则就会返回风险提示
> > 
> > 
> > 请问大佬，极验你是用手动过的验证吗，有自动的吗，感谢
> 
> 按照BAC的逻辑手动登录的，用的php

有自动的方案吗大佬

**Comment by z0z0r4** [comment]
哪有自动化的极验...别想了，自己去整个模拟吧（x

**Comment by SessionHu** [comment]
经测试文档 Web 端密码登录算法及接口仍然有效, 对于验证的速度有一定要求, 建议先做验证码然后再获取 hash 登录, 否则 hash 过期 (有效期只有几秒) 返回 -662. close?
