### ISSUE TITLE
昨天上传了一个视频，但是在老uwp客户端的bv号显示不对，而且这个bug延续至今

### ISSUE THREAD

**Issue by 12345xinkai** [SocialSisterYi/bilibili-API-collect#958]
当我上传了很多视频，其中只有一个视频能正确显示bv号：aqo55的Super Mario 74 Ten Years After v3.74 - Course 12: Cliff of Time (Savestateless)，https://www.bilibili.com/video/BV1bx4y1Z7Ej
When I uploaded many videos, one only showed bvid correctly

以下是bv号偏移
bvid offsets below
juzcook的Mario Finds a Ghost Town // OMH (Part #16): 正确：https://www.bilibili.com/video/BV1Lp421f7Wz ，错误：https://www.bilibili.com/video/BV1DT4C1G7Jh
shisyow的Another Generic 74EE Edit: Course 2 - Corona Virusvine (Savestateless)，正确：https://www.bilibili.com/video/BV1dK421y7Mc ，错误：https://www.bilibili.com/video/BV1hS4k1f7AX
N450 SMW Central的Häschen [hɛʃn̩] #1 - Mission: Get Yosh，正确：https://www.bilibili.com/video/BV1WF4m1u7NK ，错误：https://www.bilibili.com/video/BV1fC4C1p7FZ
aqo55的Super Mario 74 Ten Years After v3.74 - Course 13: Sea Salt Peaks (Savestateless)，正确：https://www.bilibili.com/video/BV1MA4m1L7h7 ，错误：https://www.bilibili.com/video/BV1C24C1b74u
katze789的Box World [savestateless]，正确：https://www.bilibili.com/video/BV15y421a7fr ，错误：https://www.bilibili.com/video/BV1St4C117RY
Ozzie的STUPID XMAS BALLZ: MorningStorm64's Lost Souls (Savestateless)，正确：https://www.bilibili.com/video/BV1oJ4m1t7NQ ，错误：https://www.bilibili.com/video/BV1aA4y1k7cC
等等
![QQ截图20240130091852](https://github.com/SocialSisterYi/bilibili-API-collect/assets/121651626/940d459e-0ae8-46a8-9d6e-178239d7adbb)

**Comment by cxw620** [comment]
Not related with this repo? What's more, UWP version of Bilibili is already EOL.
