### ISSUE TITLE
Proto文件有格式错误

### ISSUE THREAD

**Issue by zly2006** [SocialSisterYi/bilibili-API-collect#962]
Error: Field number 1 has already been used in "bilibili.app.view.v1.GetUserReq" by field "aid".

Path: bilibili-API-collect/grpc_api/bilibili/app/view/v1/view.proto

```
//
message GetUserReq {
    //
    int64 aid = 1;
    //
    int64 up_mid = 1;
}
```

**Comment by cxw620** [comment]
这块的 proto 有很大变动(7.67), 相关接口还没有正式投入使用吧还是原来就弄错了? 正常来说上线的接口出于兼容性不会改的.

```proto
//
message GetUserReq {
    //
    repeated int64 mids = 1;
    //
    int64 aid = 2;
    // 
    int64 up_mid = 3;
    //
    bool only_fans = 4;
}

//
message GetUserReply {
    // 
    repeated User like_list = 1;
    // 
    string title = 2;
}
```

**Comment by stmtc233** [comment]
> 这块的 proto 有很大变动(7.67), 相关接口还没有正式投入使用吧还是原来就弄错了? 正常来说上线的接口出于兼容性不会改的.
> 
> ```proto
> //
> message GetUserReq {
>     //
>     repeated int64 mids = 1;
>     //
>     int64 aid = 2;
>     // 
>     int64 up_mid = 3;
>     //
>     bool only_fans = 4;
> }
> 
> //
> message GetUserReply {
>     // 
>     repeated User like_list = 1;
>     // 
>     string title = 2;
> }
> ```
> 
> PR Welcome

你这个是正确的 我之前copy好像copy错了 直接pr吧
