### ISSUE TITLE
关于birthday字段的含义

### ISSUE THREAD

**Issue by My-Account-1** [SocialSisterYi/bilibili-API-collect#967]
https://api.vc.bilibili.com/account/v1/user/cards?uids=68
在请求这个api后，其中birthday字段返回值为-62135625943
请问它的含义是什么...

**Comment by My-Account-1** [comment]
如图
![Uploading 搜狗截图20240212194518.png…]()

**Comment by My-Account-1** [comment]
如图
<img width="959" alt="搜狗截图20240212194518" src="https://github.com/SocialSisterYi/bilibili-API-collect/assets/149792698/f2b49ddf-aa5b-48ba-b35d-ebe77c1370ec">

**Comment by cxw620** [comment]
时间戳(秒), 这个是应该是没设置生日的默认值(1900-01-01 00:00:00)

**Comment by z0z0r4** [comment]
https://gitea.com/xorm/xorm/issues/2339 可能有关，这是 Go 的 ORM 库

**Comment by cxw620** [comment]
> https://gitea.com/xorm/xorm/issues/2339 可能有关，这是 Go 的 ORM 库

这就是供应链攻击么(bushi)

**Comment by SessionHu** [comment]
现在 birthday 字段返回空了, close?
