### ISSUE TITLE
buvid_fp  这个是怎么来的

### ISSUE THREAD

**Issue by xiaofeisi** [SocialSisterYi/bilibili-API-collect#969]
buvid_fp  这个是怎么来的  自动生成还是从包里面返回的

**Comment by cxw620** [comment]
Search for docs or reverse engineer the offcial APK. Seems that I've mentioned it in docs.

This issue can be closed as completed.

**Comment by lb-chc** [comment]
> buvid_fp 这个是怎么来的 自动生成还是从包里面返回的

https://github.com/SocialSisterYi/bilibili-API-collect/issues/933

**Comment by xiaofeisi** [comment]
> > buvid_fp这是怎么来的自动生成还是从包里面返回的
> 
> [第933章](https://github.com/SocialSisterYi/bilibili-API-collect/issues/933)

看不懂这个  有没有 js  或者python代码的

**Comment by z0z0r4** [comment]
> > > buvid_fp这是怎么来的自动生成还是从包里面返回的
> > 
> > 
> > [第933章](https://github.com/SocialSisterYi/bilibili-API-collect/issues/933)
> 
> 看不懂这个 有没有 js 或者python代码的

配个眼镜？https://github.com/SocialSisterYi/bilibili-API-collect/issues/933#issuecomment-1931506993
