### ISSUE TITLE
关于用户关系部分文档错误的校正

### ISSUE THREAD

**Issue by artisticUtilizationOfVoid** [SocialSisterYi/bilibili-API-collect#975]
### 查询用户粉丝明细
[查询用户粉丝明细](https://api.bilibili.com/x/relation/followers)
<img width="464" alt="Snipaste_2024-02-23_10-36-57" src="https://github.com/SocialSisterYi/bilibili-API-collect/assets/149796693/cd4f4382-cbf7-4f36-9448-c451d48d52ab">
其他用户可以查看到1000名
<img width="361" alt="Snipaste_2024-02-23_10-38-08" src="https://github.com/SocialSisterYi/bilibili-API-collect/assets/149796693/14414968-076e-434e-9e18-5c813940e56a">
### 查询用户关注明细
[查询用户关注明细](https://api.bilibili.com/x/relation/followings)
关于  登录可看当前用户全部，其他用户仅可查看前5页 的错误描述
我就不贴图了 ps默认50的情况下就能查看2页也就是100条数据

**Comment by slxxx12** [comment]
隐藏关注怎么看不了了

**Comment by z0z0r4** [comment]
因为隐藏关注已经下线了

**Comment by wuziqian211** [comment]
fixed in #981
