### ISSUE TITLE
Cookies 刷新意外 correspondPath 过期或错误

### ISSUE THREAD

**Issue by z0z0r4** [SocialSisterYi/bilibili-API-collect#976]
见 https://github.com/Nemo2011/bilibili-api/issues/687

之前一直都可以的，现在出问题了

**Comment by z0z0r4** [comment]
有谁遇到过的吗？

示例
`pip install bilibili-api-python`

```python
from bilibili_api import Credential, sync
sync(Credential(sessdata="", bili_jct="", ac_time_value="").refresh())
```

~~这太大坨了，我实在抠不出来~~

**Comment by z0z0r4** [comment]
我现在也复现不出了...暂时搁置

**Comment by Misaka-L** [comment]
如果你生成的 correnspondPath 里的 `refresh_${timestampe}` 里时间戳刚刚好是现在的，生成完就发...
有可能会发生你的时间比服务器时间早的情况，可以考虑把生成的时间戳提前一分钟

如果这节省了你一天（或者其他值）的时间，请加个 reaction 告诉其他人这个方法有效....

**Comment by SessionHu** [comment]
问题解决了, 这的issues忘关了?
