### ISSUE TITLE
 https://api.bilibili.com/x/space/upstat这个api请求回来的data为{}，但是在网页上调试时data里是有数据的。这是为啥

### ISSUE THREAD

**Issue by leiting2333** [SocialSisterYi/bilibili-API-collect#980]
我一开始是通过bilibili-api库来调用这个api发现返回的是{}，我以为是接口失效，然后我自己写了一下，成功请求返回数据，但是字典中的data依然为{}
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/80498048/9205e95c-ef6f-4b1e-94d9-d63478879f80)
![Uploading image.png…]()

**Comment by z0z0r4** [comment]
那你应该去那边提 issue

**Comment by Radekyspec** [comment]
upstat需要添加cookie才会返回有效数据，否则data为空
