### ISSUE TITLE
获取用户头像和昵称API

### ISSUE THREAD

**Issue by AmberHan** [SocialSisterYi/bilibili-API-collect#982]

**Comment by z0z0r4** [comment]
返回值里面有...

**Comment by AmberHan** [comment]
> 返回值里面有...

https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/message/private_msg.md
没有吧，我刚刚查看了下B站私信返回的是这个接口  但是没有私信人的昵称和头像Url

**Comment by z0z0r4** [comment]
当我没说，这私信内容咋这么缺记录...

**Comment by wuziqian211** [comment]
B站网页版是通过 https://api.vc.bilibili.com/account/v1/user/cards 这个接口来获取用户头像和昵称的，相关说明可以参见 [多用户详细信息](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/user/info.md#获取多用户详细信息)

另外我最近准备更新一下私信接口的相关说明
