### ISSUE TITLE
[Update] b站up主新后台诊断API

### ISSUE THREAD

**Issue by zly2006** [SocialSisterYi/bilibili-API-collect#987]
todo: 猜出来字段的意思
url: https://member.bilibili.com/x/web/data/archive_diagnose/compare?size=10&t=_
参数: t=时间戳（optional），size=最近n个视频，可以改到非常大的数字，不清楚有无最大值

**Comment by zly2006** [comment]
就点击率（tm）来说：
```json5
                "tm_rate": 369, // 点击率
                "tm_rate_med": 282, // med=median （猜测）
                "tm_fan_simi_rate_med": 249, // simi=?
                "tm_viewer_simi_rate_med": 249,
                "tm_fan_rate": 385,
                "tm_viewer_rate": 300,
                "tm_pass_rate": 5870, // pass=超过n%同类稿件
                "tm_fan_pass_rate": 5271, 
                "tm_viewer_pass_rate": 5477,
```

**Comment by zly2006** [comment]
play_trans_fan_rate=播转粉比
crash=3秒跳出
active_fans_rate=粉丝观看率（有n%的粉丝观看了这个视频）

**Comment by zly2006** [comment]
simi似乎可能是similar的缩写

**Comment by IcyWatermango** [comment]
Github可以直接这样评论吗？老哥觉得不合适的话可以删掉这条。
        "duration": 4995, 视频时长
        "play": 786, 视频播放量

        "full_play_ratio": 5792, 完播率
        "play_viewer_rate": 8334, 游客播放占比
        "active_fans_rate": 358,  粉丝观看率
        "active_fans_med": 232, 粉丝观看率中位数

        "tm_rate": 598, 点击率
        "tm_rate_med": 374, 点击率中位数
        "tm_fan_simi_rate_med": 331, 相似体量UP粉丝点击率中位数
        "tm_viewer_simi_rate_med": 331, 相似体量UP游客点击率中位数
        "tm_fan_rate": 633, 粉丝点击率
        "tm_viewer_rate": 596, 游客点击率
        "tm_pass_rate": 6671, 点击率超过同类
        "tm_fan_pass_rate": 5836,  粉丝点击率超过同类
        "tm_viewer_pass_rate": 6906, 游客点击率超过同类

        "interact_rate": 1330, 互动率
        "interact_rate_med": 413, 互动率中位数
        "interact_fan_simi_rate_med": 877, 相似体量UP粉丝互动率中位数
        "interact_viewer_simi_rate_med": 258, 相似体量UP游客互动率中位数
        "interact_fan_rate": 1750, 粉丝互动率
        "interact_viewer_rate": 1246, 游客互动率

        "avg_play_time": 0, 平均播放时长？
        "total_new_attention_cnt": 
        "play_trans_fan_rate": 50, 播转粉率
        "play_trans_fan_rate_med": 0, 播转粉中位数
