### ISSUE TITLE
将废弃 `UID` 转向使用  `open_id` 的支持问题

### ISSUE THREAD

**Issue by z0z0r4** [SocialSisterYi/bilibili-API-collect#989]
具体见 https://github.com/Nemo2011/bilibili-api/issues/728

https://www.bilibili.com/opus/911220549299994641

**Comment by z0z0r4** [comment]
以下摘自公告

1、对直播间长连心跳进行严格鉴权：

将在下周一2024年3月25日，心跳严格鉴权将会生效。届时未正常维持心跳的长连将会无法收到消息推送。

心跳说明请查看直播创作者服务中心文档-开放能力-API列表中的项目心跳说明


2、UID字段的下线处理：

先前通知内容中的open_id字段已于2024年3月11日上线，UID字段定于2024年4月15日[将UID值统一设置为0]。 作者：哔哩哔哩开放平台 https://www.bilibili.com/read/cv33326830/?spm_id_from=333.999.0.0&jump_opus=1 出处：bilibili

**Comment by z0z0r4** [comment]
我这边接到好几个直播相关的 issue 了，不知道各位有没有已经分析过了的

**Comment by shugen002** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/README.md?plain=1#L31-L33

**Comment by z0z0r4** [comment]
> https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/README.md?plain=1#L31-L33
> 
> ```
> 本文档探讨的对象是主站业务接口，[官方开放平台](https://openhome.bilibili.com/doc) 和 [直播开放平台](https://open-live.bilibili.com/document/) 均不属于本项目范畴，请移步
> ```

这个改动只限于开放平台吗？

**Comment by shugen002** [comment]
要是改外面这里，怕不是要全站重写？
