### ISSUE TITLE
进行评论时 csrf变到url上了 提交后返回这个是什么意思呢 有遇到过的吗

### ISSUE THREAD

**Issue by moyu-jie** [SocialSisterYi/bilibili-API-collect#996]
{"code":-400,"message":"Key: 'AddReplyReq.ReplyCommonReq.Type' Error:Field validation for 'Type' failed on the 'required' tag","ttl":1}

**Comment by wuziqian211** [comment]
请求评论接口请使用POST方式，并且要将参数添加到正文中

[接口相关说明](../blob/master/docs/comment/action.md)

**Comment by SocialSisterYi** [comment]
请根据 **必选参数** 添加`type`字段，与`csrf`无关
